### ISSUE TITLE
unmarshall predictors due to invalid character 

### ISSUE THREAD

**Issue by majorinche** [kserve/kserve#1135]
kubeflow version: kfctl_k8s_istio.v1.1.0
istio versino:1.3.1 (installed along with kubeflow)
kubernetes version: 1.17.9 (installed in bare metal)

kfserving failed at: 
This step is in Failed state with this message: Error from server: error when creating "/tmp/manifest.yaml": admission webhook "inferenceservice.kfserving-webhook-server.validator" denied the request: Unable to unmarshall predictors json string due to invalid character '.' after object key:value pair

the manifest used as following:
apiVersion: serving.kubeflow.org/v1alpha2 kind: InferenceService metadata: name: mnist-4cc7916d-e045-4dc4-a61b-f412dd0da354 spec: default: predictor: tensorflow: storageUri: pvc://train-data/ 

and i try use example directly from: https://github.com/kubeflow/kfserving/blob/master/docs/samples/pvc/mnist-pvc.yaml
it report the same error

[root@d0404 kubeflow]# cat mnist-pvc.yaml 
apiVersion: "serving.kubeflow.org/v1alpha2"
kind: "InferenceService"
metadata:
  name: "mnist-sample"
spec:
  default:
    predictor:
      tensorflow:
        storageUri: "pvc://train-data"

[root@d0404 kubeflow]# kubectl apply -f mnist-pvc.yaml -n chejinguo
Error from server: error when creating "mnist-pvc.yaml": admission webhook "inferenceservice.kfserving-webhook-server.validator" denied the request: Unable to unmarshall predictors json string due to invalid character '.' after object key:value pair

**Comment by yuzisun** [comment]
Closing the staled issue
