### ISSUE TITLE
The predictor imagePullPolicy was "Always" in default, and I can not set it to "IfNotPresent"

### ISSUE THREAD

**Issue by jiujiang** [kserve/kserve#1173]
/kind bug

**What steps did you take and what happened:**
[A clear and concise description of what the bug is.]

**What did you expect to happen:**

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

**Environment:**

- Istio Version:
- Knative Version:
- KFServing Version:
- Kubeflow version:
- Kfdef:[k8s_istio/istio_dex/gcp_basic_auth/gcp_iap/aws/aws_cognito/ibm]
- Minikube version:
- Kubernetes version: (use `kubectl version`):
- OS (e.g. from `/etc/os-release`):
@ewilderj @mhausenblas @pineking @idvoretskyi

**Comment by yuzisun** [comment]
@jiujiang can you elaborate which image specifically?

**Comment by yuzisun** [comment]
you should be able to set `imagePullPolicy` field now with v1beta1 API.
