### ISSUE TITLE
Scikit-learn version for sklearnserver

### ISSUE THREAD

**Issue by MLnick** [kserve/kserve#1214]
https://github.com/kubeflow/kfserving/blob/96c6a8f56ca834b85b39a8e592711654f01784ca/python/sklearnserver/setup.py#L36

Is there a reason for the current sklearn version being so old for the `sklearnserver`? `0.20.3` was released March 2019.

**Comment by yuzisun** [comment]
@MLnick check the matrix [here](https://github.com/kubeflow/kfserving/pull/1211/files?short_path=f4d70a1#diff-f4d70a1b9907cbb949d07e68ece6cab47b79f62ac7293e4bc9aa31a9d6f9d47c), we are moving towards using MLServer(sklearn 0.23.1) to serve sklearn model in KFS 0.5. Meanwhile you can always [build the sklearnserver image](https://github.com/kubeflow/kfserving/tree/master/docs/samples/sklearn#run-sklearn-inferenceservice-with-your-own-image) with the version you want and update default image in the configmap.

**Comment by MLnick** [comment]
@yuzisun thanks - yes for now I've built my own image. Good to know there's a path to more recent versions of the frameworks.

For the configmap update - I did it via `kubectl edit` but I wonder if the docs for that in your link could be expanded (e.g. perhaps either use `kubectl edit` or `patch`?)

**Comment by yuzisun** [comment]
As of 0.8.0 skleanserver is upgraded with 1.0 version
