### ISSUE TITLE
Recommended Kfserving Dependency Versioning

### ISSUE THREAD

**Issue by mszacillo** [kserve/kserve#1274]
/kind bug

**What steps did you take and what happened:**
I was experiencing issues deploying my inference service after running the make deploy-dev with self signed certs enabled. To reproduce, these are the steps I took:
1. Unset all proxies and set my KO repo
2. Created kind cluster using kind create cluster --image=kindest/node:v1.17.11@sha256:7175872357bc85847ec4b1aba46ed1d12fa054c83ac7a8a11f5c268957fd5765
3. Manually installed knative and istio on my cluster by following https://knative.dev/docs/install/any-kubernetes-cluster/
4. Set KFSERVING_ENABLE_SELF_SIGNED_CA to true
5. Ran make deploy-dev
6. When deploying an inference service, I would get an error message by looking at the controller-manager pod stating:
`2020/12/31 18:34:55 http: TLS handshake error from 10.244.0.1:1305: remote error: tls: bad certificate`

This occurred when I was running kfserving on a kind cluster with K8s v1.17.11, Knative v0.19.1, and Istio v1.8.1. I was able to resolve this issue by downgrading my Knative version to v0.12.1, and my istio version to v1.7.2.

**Anything else you would like to add:**
Do we have a list of recommended dependency versions to run kfserving? Currently the main README states that kfserving is compatible with Istio: v1.3.1+ and Knative Serving: v0.14.3+, but I ran into cert problems when using the most recent versions of knative and istio. 

**Environment:**

- Istio Version: v1.8.1
- Knative Version: v0.19.1
- Kubernetes version: v1.17.11

**Comment by yuzisun** [comment]
see https://kserve.github.io/website/0.10/admin/serverless/serverless/
