### ISSUE TITLE
Deploying Kf-serving on AKS Cluster.

### ISSUE THREAD

**Issue by prakashsingh21** [kserve/kserve#1325]
I am facing the issue with KF 1.2 on AKS using [this](https://raw.githubusercontent.com/kubeflow/manifests/v1.2-branch/kfdef/kfctl_azure.v1.2.0.yaml) manifest. 
1. queue-proxy gives error connection refused. 
2. Main kf-serving container has no error. 
3. Calling inference endpoint gives 404 error. Any workaround/doc for this issue? If yes please share with me.

**Comment by sivanantha321** [comment]
closing this issue as it is stale. Please feel free to create a new issue if it is still persists.

/close
