### ISSUE TITLE
Is there any way of passing the env/proxy details to the init-container mainly storage-initializer?

### ISSUE THREAD

**Issue by chinmay22897** [kserve/kserve#1348]
/kind bug

**What steps did you take and what happened:**
[A clear and concise description of what the bug is.]
I am creating a inferenceservice sklearn-iris from examples using kfserving standalone deployment on my cluster, everything is setup, I am even able to create my own custom images and run the kfserving but when running by setting the predictor as one of the main libraries (sklearn,tensorflow,pytorch) the storage-initializer (which I have no control over from basic yaml file) is trying to download the model from the path in storage uri (here, `"gs://kfserving-samples/models/sklearn/iris"`) but since I am behind the proxy it is not able to connect to external routes which is the expected behaviour.
**What did you expect to happen:**
The running kfserving instance where I can use the pre-defined predictor methods.

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]
I have installed the kfserving using the /hack/quick_install.sh script from github master branch on minikube.
I even tried to edit the deployment yaml using `kubectl edit deploy` and adding the env details but I couldn't find the init-containers details there.
**Environment:**

- Istio Version: v1.6.2
- Knative Version: v0.18.0
- KFServing Version: v0.5.0-rc2
- Kubeflow version: -
- Kfdef:[k8s_istio/istio_dex/gcp_basic_auth/gcp_iap/aws/aws_cognito/ibm] -
- Minikube version: v1.15.1
- Kubernetes version: (use `kubectl version`):
```
Client Version: version.Info{Major:"1", Minor:"15", GitVersion:"v1.15.0", GitCommit:"e8462b5b5dc2584fdcd18e6bcfe9f1e4d970a529", GitTreeState:"clean", BuildDate:"2019-06-19T16:40:16Z", GoVersion:"go1.12.5", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"17", GitVersion:"v1.17.11", GitCommit:"ea5f00d93211b7c80247bf607cfa422ad6fb5347", GitTreeState:"clean", BuildDate:"2020-08-13T15:11:47Z", GoVersion:"go1.13.15", Compiler:"gc", Platform:"linux/amd64"}
```
- OS (e.g. from `/etc/os-release`): 
```
NAME="Oracle Linux Server"
VERSION="7.6"
ID="ol"
VARIANT="Server"
VARIANT_ID="server"
VERSION_ID="7.6"
PRETTY_NAME="Oracle Linux Server 7.6"
ANSI_COLOR="0;31"
CPE_NAME="cpe:/o:oracle:linux:7:6:server"
HOME_URL="https://linux.oracle.com/"
BUG_REPORT_URL="https://bugzilla.oracle.com/"

ORACLE_BUGZILLA_PRODUCT="Oracle Linux 7"
ORACLE_BUGZILLA_PRODUCT_VERSION=7.6
ORACLE_SUPPORT_PRODUCT="Oracle Linux"
ORACLE_SUPPORT_PRODUCT_VERSION=7.6
```

**Comment by gabrielecastellano** [comment]
I think I am facing the same error. The deployment of the sklearn-iris example fails with "RevisionFailed", and I get this message in the inferenceservice description:

`Revision "sklearn-iris-predictor-default-djllv" failed with message: Unable to fetch image "gcr.io/kfserving/sklearnserver:v0.5.0": failed to resolve image to digest: Get "https://gcr.io/v2/": dial tcp 108.177.126.82:443: i/o timeout.`

However, I can pull images through docker (I configured the proxy variables in the docker service) and the deployment of all the kfserving components worked fine.

Is there any news on this?

**Comment by gabrielecastellano** [comment]
I confirm the error is exactly the same. This is the log of my storage-initializer container:

```
[I 210408 10:26:29 initializer-entrypoint:13] Initializing, args: src_uri [gs://kfserving-samples/models/sklearn/iris] dest_path[ [/mnt/models]
[I 210408 10:26:29 storage:43] Copying contents of gs://kfserving-samples/models/sklearn/iris to local
[W 210408 10:26:32 _metadata:104] Compute Engine Metadata server unavailable onattempt 1 of 3. Reason: timed out
[W 210408 10:26:32 _metadata:104] Compute Engine Metadata server unavailable onattempt 2 of 3. Reason: [Errno 113] No route to host
[W 210408 10:26:35 _metadata:104] Compute Engine Metadata server unavailable onattempt 3 of 3. Reason: timed out
[W 210408 10:26:35 _default:250] Authentication failed using Compute Engine authentication due to unavailable metadata server.
```

I have tried injecting the env variables for the proxy through `kubectl edit` but such container is not listed in the deployment yaml. It seems it is generated from the metadata annotation `internal.serving.kubeflow.org/storage-initializer-sourceuri: gs://kfserving-samples/models/sklearn/iris`.

The following is the status of the storage-initializer container:

```
$ sudo kubectl -n kfserving-test get pod sklearn-iris-predictor-default-b49ws-deployment-c7dbf794b-kjw45 -o json | jq .status.initContainerStatuses
[
  {
    "containerID": "docker://1bb0e718823da1d19e64ba0a8ddd68d358cb0a05f44961cc2b444b967345dd82",
    "image": "gcr.io/kfserving/storage-initializer:v0.5.0",
    "imageID": "docker-pullable://gcr.io/kfserving/storage-initializer@sha256:1d396c0c50892f5562a1c24d925691ec786e5d48e08200f3f9bb17bb48da40ae",
    "lastState": {
      "terminated": {
        "containerID": "docker://e1ca4e71002bf24654da8c49c482e0c70be61a40f943da7d2958ace8d6580de4",
        "exitCode": 1,
        "finishedAt": "2021-04-08T10:38:36Z",
        "message": "load(src_uri, dest_path)\n  File \"/usr/local/lib/python3.7/site-packages/kfserving/storage.py\", line 58, in 
download\n    Storage._download_gcs(uri, out_dir)\n  File \"/usr/local/lib/python3.7/site-packages/kfserving/storage.py\", line
116, in _download_gcs\n    for blob in blobs:\n  File \"/usr/local/lib/python3.7/site-packages/google/api_core/page_iterator.py\", 
line 212, in _items_iter\n    for page in self._page_iter(increment=False):\n  File \"/usr/local/lib/python3.7/site-
packages/google/api_core/page_iterator.py\", line 243, in _page_iter\n    page = self._next_page()\n  File 
\"/usr/local/lib/python3.7/site-packages/google/api_core/page_iterator.py\", line 369, in _next_page\n    response = 
self._get_next_page_response()\n  File \"/usr/local/lib/python3.7/site-packages/google/api_core/page_iterator.py\", line 419, in 
_get_next_page_response\n    method=self._HTTP_METHOD, path=self.path, query_params=params\n  File 
\"/usr/local/lib/python3.7/site-packages/google/cloud/storage/_http.py\", line 78, in api_request\n    return call()\n  File 
\"/usr/local/lib/python3.7/site-packages/google/api_core/retry.py\", line 286, in retry_wrapped_func\n    on_error=on_error,\n  
File \"/usr/local/lib/python3.7/site-packages/google/api_core/retry.py\", line 206, in retry_target\n    last_exc,\n  File \"<string>\", 
line 3, in raise_from\ngoogle.api_core.exceptions.RetryError: Deadline of 120.0s exceeded while calling 
functools.partial(functools.partial(<bound method JSONConnection.api_request of <google.cloud.storage._http.Connection 
object at 0x7fe638137d50>>, timeout=60, method='GET', path='/b/kfserving-samples/o', query_params={'projection': 'noAcl', 
'prefix': 'models/sklearn/iris/'})), last exception: HTTPSConnectionPool(host='storage.googleapis.com', port=443): Max retries 
exceeded with url: /storage/v1/b/kfserving-samples/o?
projection=noAcl&prefix=models%2Fsklearn%2Firis%2F&prettyPrint=false (Caused by 
ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x7fe6380d8d10>, 'Connection to storage.googleapis.com 
timed out. (connect timeout=60)'))\n",
        "reason": "Error",
        "startedAt": "2021-04-08T10:26:28Z"
      }
    },
    "name": "storage-initializer",
    "ready": false,
    "restartCount": 3,
    "state": {
      "running": {
        "startedAt": "2021-04-08T10:38:37Z"
      }
    }
  }
]
```

**Comment by tejashpe** [comment]
Any luck with the issue ? Was anyone successful in working around with proxy ?

**Comment by sivanantha321** [comment]
Kserve 0.11.1 just introduced [`ClusterStroageContainer`](https://github.com/kserve/kserve/pull/3060) which will allow you to modify storage-initalizer spec. You should be able to inject env variables into storage-initalizer. Here is an example StorageContainer

```yaml
apiVersion: serving.kserve.io/v1alpha1
kind: ClusterStorageContainer
metadata:
  name: example-storage-initializer
spec:
  container:
    image: kserve/storage-initializer:v0.12.0-rc0
    name: storage-initializer
    env: 
      - name: "test-env"
        value: "dummy"
    resources:
      limits:
        cpu: '1'
        memory: 1Gi
      requests:
        cpu: 100m
        memory: 100Mi
  supportedUriFormats:
    - prefix: gs://
    - prefix: s3://
    - prefix: hdfs://
    - prefix: webhdfs://
    - regex: https://(.+?).blob.core.windows.net/(.+)
    - regex: https://(.+?).file.core.windows.net/(.+)
    - regex: https?://(.+)/(.+)
```
As you can see, the env variable is injected into the storage-initializer.
![Screenshot from 2024-01-12 11-54-03](https://github.com/kserve/kserve/assets/90966311/96fbb326-d595-4f6c-a2da-0c3f27c9d54e)

**Comment by philipp1992** [comment]
have added http_proxy, https_proxy, HTTP_PROXY and HTTPS_PROXY using the env section in the storagecontainer, can see the env being set in the kubernetes Pod, but still not using the proxy.

urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='storage.googleapis.com', port=443): Max retries exceeded with url: /storage/v1/b/kfserving-examples/o?projection=noAcl&prefix=models%2Fsklearn%2F1.0%2Fmodel%2F&prettyPrint=false (Caused by ProxyError('Cannot connect to proxy.', NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fdf54c8cd00>: Failed to establish a new connection: [Errno 111] Connection refused')))
