### ISSUE TITLE
not able to deploy custom ECR images into kfserving using its tags

### ISSUE THREAD

**Issue by tiru1930** [kserve/kserve#1355]
When i do the deployment with yaml  if the image has tags, kfserving is not able deploy the model. 
if the ECR image has tags then i was not deploying where has if we provide image URI@digest it was working.

**Environment:**

- Istio Version:
- Knative Version:
- KFServing Version:
- Kubeflow version:
- Kfdef:[k8s_istio/istio_dex/gcp_basic_auth/gcp_iap/aws/aws_cognito/ibm]  aws
- Minikube version:
- Kubernetes version: (use `kubectl version`):  Client Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.3", GitCommit:"1e11e4a2108024935ecfcb2912226cedeafd99df", GitTreeState:"clean", BuildDate:"2020-10-14T12:50:19Z", GoVersion:"go1.15.2", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"15+", GitVersion:"v1.15.12-eks-31566f", GitCommit:"31566f851673e809d4d667b7235ed87587d37722", GitTreeState:"clean", BuildDate:"2020-10-20T23:25:14Z", GoVersion:"go1.12.17", Compiler:"gc", Platform:"linux/amd64"}
- OS (e.g. from `/etc/os-release`): Linux

**Comment by sivanantha321** [comment]
closing this issue as it is stale. If the issue persists, feel free to create a new issue.

/close
