### ISSUE TITLE
Reason for still using "default" in revision name?

### ISSUE THREAD

**Issue by Peilun-Li** [kserve/kserve#1397]
In kfserving v0.4 we have primary route with name `{isvc_name}-predictor-default` and canary route with name `{isvc_name}-predictor-canary`, which makes sense to distinguish them.

However in v0.5, from what I see [here](https://github.com/kubeflow/kfserving/tree/master/docs/samples/v1beta1/torchserve/canary#check-the-traffic-split-between-the-two-revisions), we are actually using DNS label as `latest-{isvc_name}-predictor-default` indicating canary, and `prev-{isvc_name}-predictor-default` indicating primary. Do we really still need the suffix `-default` here given it seems redundant (we are using `default` for both primary and canary)?

The reason for asking this is I'm a bit worried since DNS label has a maximum character limitation of 63, including such redundant information will reduce the effective `isvc_name` we can use, especially in the case that e.g., we are using knative domain template as `{{.Name}}-{{.Namespace}}.{{.Domain}}` for HTTPS wildcard certificates, with the new v0.5 the DNS label would be something like `latest-{isvc_name}-{namespace}-predictor-default`, only leaving 37 characters for `isvc_name` and `namespace`, and with a long `namespace` there's essentially not much space left for `isvc_name`.

Haven't tested yet (need some time to upgrade to v0.5) and maybe I'm missing something like maybe the URL in `ksvc` is not actually used for routing? Or is there any way we can customize our installation to reduce the DNS label length (such as update the suffix `-predictor-default` to `-pred-df`)? Thanks for any help/advice!

**Comment by yuzisun** [comment]
@Peilun-Li yes looks like we have the same setup and already running into the dns limit issue :). The reason we kept the name is to maintain the backwards compatibility for existing services.  we are thinking along the same line to provide a configuration to customize the names.

**Comment by Peilun-Li** [comment]
@yuzisun Great thanks! Looking forward to that feature.

**Comment by Peilun-Li** [comment]
Hey @yuzisun has that feature be supported (to customize those constant prefixes/suffixes) or is there a timeline? Thanks!

**Comment by Peilun-Li** [comment]
Hey @yuzisun just checking any updates or plan/workaround on this? Thanks!
