### ISSUE TITLE
Disabling the Istio Ingress gateway will result in calls to the knative local gateway to timeout.

### ISSUE THREAD

**Issue by PatrickGhosn** [kserve/kserve#1460]
/kind bug

**What steps did you take and what happened:**
We used the below istio-minimal-operator.yaml install with the ingress gateway disabled.
```
apiVersion: install.istio.io/v1alpha1
kind: IstioOperator
spec:
  values:
    global:
      proxy:
        autoInject: disabled
      useMCP: false
      # The third-party-jwt is not enabled on all k8s.
      # See: https://istio.io/docs/ops/best-practices/security/#configure-third-party-service-account-tokens
      jwtPolicy: first-party-jwt

  addonComponents:
    pilot:
      enabled: true

  components:
    ingressGateways:
      - name: istio-ingressgateway
        enabled: false
```
We also configured knative to use the `svc.cluster.local` domain. 

When we run a call from inside the cluster, the call fails and times out.
```
[ root@curl-tester:/ ]$  curl http://test-model-092-predictor-default.default.svc.cluster.local/v2/models/mesh-cnn/versions/v0.1.0/infer -X POST -v --header 'Host: test-model-092-predictor-default.default.svc.cl
uster.local'
* Failed to connect to test-model-092-predictor-default.default.svc.cluster.local port 80: Connection refused
curl: (7) Failed to connect to test-model-092-predictor-default.default.svc.cluster.local port 80: Connection refused
[ root@curl-tester:/ ]$  curl http://test-model-092-predictor-default.default.svc.cluster.local/v2/models/mesh-cnn/versions/v0.1.0/infer -X POST -v
* Failed to connect to test-model-092-predictor-default.default.svc.cluster.local port 80: Connection refused
curl: (7) Failed to connect to test-model-092-predictor-default.default.svc.cluster.local port 80: Connection refused
```

**What did you expect to happen:**
For calls to the model using the local domain to work.

**Anything else you would like to add:**
Using an ingress with a private IP works fine. When the Ingres is up and running, the calls to the knative local gateway work fine.
```
curl http://test-model-052-predictor-default.default.svc.cluster.local/v2/models/mesh-cnn/versions/v0.1.0/infer -X POST
{"detail":[{"loc":["body"]]}
```

**Environment:**

- Istio Version: 1.9
- Knative Version: v0.20
- KFServing Version: v0.5.1
- Kubeflow version: none (standalone kfserving)
- Kubernetes version: v1.18.12-gke.1210"

**Comment by yuzisun** [comment]
@PatrickGhosn Are you running in Mesh mode with istio sidecar injected to the inference service?

**Comment by moorthy156** [comment]
@PatrickGhosn I am also getting the same issue, can you let me know how did you resolve this. We want to expose it only within the cluster and want to disable external ingress
