### ISSUE TITLE
Cluster-local InferenceService should not require ingressGateway

### ISSUE THREAD

**Issue by butzist** [kserve/kserve#1468]
/kind bug

**What steps did you take and what happened:**

When creating an `InferenceService` with label `networking.knative.dev/visibility: cluster-local`, kfserving still requires ingressGateway and ingressService to be configured.

**What did you expect to happen:**

Only localGateway and localGatewayService should be required. Optimallym those should also be optional, if all traffic is expected to come from inside the service mesh.

**Anything else you would like to add:**

Controller logs:
```
{"level":"error","ts":1616055345.5101945,"logger":"controller-runtime.manager.controller.inferenceservice","msg":"Reconciler error","reconciler group":"serving.kubeflow.org","reconciler kind":"InferenceService","name":"pred-8c8cn79ducv1l42gz69p8fvzc","namespace":"dhl","error":"fails to create IngressConfig: Invalid ingress config, ingressGateway and ingressService are required.","errorVerbose":"Invalid ingress config, ingressGateway and ingressService are required.\nfails to create IngressConfig\ngithub.com/kubeflow/kfserving/pkg/controller/v1beta1/inferenceservice.(*InferenceServiceReconciler).Reconcile\n\t/go/src/github.com/kubeflow/kfserving/pkg/controller/v1beta1/inferenceservice/controller.go:141\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).reconcileHandler\n\t/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.7.0/pkg/internal/controller/controller.go:263\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem\n\t/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.7.0/pkg/internal/controller/controller.go:235\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func1.1\n\t/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.7.0/pkg/internal/controller/controller.go:198\nk8s.io/apimachinery/pkg/util/wait.JitterUntilWithContext.func1\n\t/go/pkg/mod/k8s.io/apimachinery@v0.19.2/pkg/util/wait/wait.go:185\nk8s.io/apimachinery/pkg/util/wait.BackoffUntil.func1\n\t/go/pkg/mod/k8s.io/apimachinery@v0.19.2/pkg/util/wait/wait.go:155\nk8s.io/apimachinery/pkg/util/wait.BackoffUntil\n\t/go/pkg/mod/k8s.io/apimachinery@v0.19.2/pkg/util/wait/wait.go:156\nk8s.io/apimachinery/pkg/util/wait.JitterUntil\n\t/go/pkg/mod/k8s.io/apimachinery@v0.19.2/pkg/util/wait/wait.go:133\nk8s.io/apimachinery/pkg/util/wait.JitterUntilWithContext\n\t/go/pkg/mod/k8s.io/apimachinery@v0.19.2/pkg/util/wait/wait.go:185\nk8s.io/apimachinery/pkg/util/wait.UntilWithContext\n\t/go/pkg/mod/k8s.io/apimachinery@v0.19.2/pkg/util/wait/wait.go:99\nruntime.goexit\n\t/usr/local/go/src/runtime/asm_amd64.s:1373","stacktrace":"github.com/go-logr/zapr.(*zapLogger).Error\n\t/go/pkg/mod/github.com/go-logr/zapr@v0.2.0/zapr.go:132\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).reconcileHandler\n\t/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.7.0/pkg/internal/controller/controller.go:267\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem\n\t/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.7.0/pkg/internal/controller/controller.go:235\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func1.1\n\t/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.7.0/pkg/internal/controller/controller.go:198\nk8s.io/apimachinery/pkg/util/wait.JitterUntilWithContext.func1\n\t/go/pkg/mod/k8s.io/apimachinery@v0.19.2/pkg/util/wait/wait.go:185\nk8s.io/apimachinery/pkg/util/wait.BackoffUntil.func1\n\t/go/pkg/mod/k8s.io/apimachinery@v0.19.2/pkg/util/wait/wait.go:155\nk8s.io/apimachinery/pkg/util/wait.BackoffUntil\n\t/go/pkg/mod/k8s.io/apimachinery@v0.19.2/pkg/util/wait/wait.go:156\nk8s.io/apimachinery/pkg/util/wait.JitterUntil\n\t/go/pkg/mod/k8s.io/apimachinery@v0.19.2/pkg/util/wait/wait.go:133\nk8s.io/apimachinery/pkg/util/wait.JitterUntilWithContext\n\t/go/pkg/mod/k8s.io/apimachinery@v0.19.2/pkg/util/wait/wait.go:185\nk8s.io/apimachinery/pkg/util/wait.UntilWithContext\n\t/go/pkg/mod/k8s.io/apimachinery@v0.19.2/pkg/util/wait/wait.go:99"}
```

**Environment:**

Istio Version: 1.9.1
Knative Version: 0.21.0
KFServing Version: 0.5.1
Kubeflow version: -
Minikube version: 1.18.1
Kubernetes version: 1.20.2
OS (e.g. from /etc/os-release): Ubuntu 20.10

**Comment by yuzisun** [comment]
@butzist The configuration is global, there could be cases that some services which need to be exposed while some run in cluster.

**Comment by butzist** [comment]
@yuzisun I configured KNative to create only cluster-local services and not use any ingress (via config-domain + config-istio). I would like to be able to configure KFServing similarly - or would it make sense that KFServing would use an ingress gateway while KNative does not?

**Comment by yuzisun** [comment]
@butzist I have been looking into [networking istio code](https://github.com/knative-sandbox/net-istio/blob/main/pkg/reconciler/ingress/config/istio.go#L142), I do not see how knative does not use ingress gateway. The only difference is that knative is defaulting it in code while we set the default in configmap.

**Comment by butzist** [comment]
@yuzisun You're right. The knative net-istio config only claims that the local gateway can be replaced with mesh.

```
    # To use only Istio service mesh and no cluster-local-gateway, replace
    # all local-gateway.* entries by the following entry.
    local-gateway.mesh: "mesh"
```

Considering that, having to provide a non-existing ingress gateway is a minor issue. What is more relevant for me is the ability to configure kfserving for only cluster-local inference services. I think the `networking.knative.dev/visibility=cluster-local` annotation is still needed on the inferenceservice even though knative has only configured domain `svc.cluster.local`. Which is the [documented](https://knative.dev/docs/serving/services/private-services/) the way for globally forcing only cluster-local services in knative.

**Comment by andyi2it** [comment]
/close

Closing this as this is completed in #2380
