### ISSUE TITLE
Latest ready inference service is showing the none working update

### ISSUE THREAD

**Issue by PatrickGhosn** [kserve/kserve#1474]
/kind bug

**What steps did you take and what happened:**
-Update a working existing model with a new inference revision (patch)
-The new inference revision crashes with an error such as `ReconcileIngressFailed`
-The inference service is incorrectly updated with having the nonworking revision as the latest Ready revision.

**What did you expect to happen:**
The latest Ready revision to be the one used per this graph:
https://github.com/kubeflow/kfserving/tree/master/docs/samples/v1beta1/rollout

https://github.com/kubeflow/kfserving/raw/master/docs/samples/v1beta1/rollout/canary.png

> NAME                               URL                                                           LATESTCREATED                            LATESTREADY                              READY   REASON
> test-model-088-predictor-default   http://test-model-088-predictor-default.default.example.com   test-model-088-predictor-default-00002   test-model-088-predictor-default-00002   True
> test-model-092-predictor-default   http://test-model-092-predictor-default.default.example.com   test-model-092-predictor-default-00004   test-model-092-predictor-default-00004   False   ReconcileIngressFailed

**Anything else you would like to add:**
A excerpt from the knative logs;

> {"severity":"ERROR","timestamp":"2021-03-19T11:51:37.607858036Z","logger":"istiocontroller.istio-ingress-controller.knative.dev-net-istio-pkg-reconciler-ingress.Reconciler","caller":"controller/controller.go:538","message":"Reconcile error","commit":"9f0302e","knative.dev/controller":"istio-ingress-controller","error":"failed to update VirtualService: Internal error occurred: failed calling webhook \"validation.istio.io\": Post https://istiod.istio-system.svc:443/validate?timeout=4s: context deadline exceeded","logging.googleapis.com/labels":{},"logging.googleapis.com/sourceLocation":{"file":"knative.dev/pkg@v0.0.0-20210107022335-51c72e24c179/controller/controller.go","line":"538","function":"knative.dev/pkg/controller.(*Impl).handleErr"},"stacktrace":"knative.dev/pkg/controller.(*Impl).handleErr\n\tknative.dev/pkg@v0.0.0-20210107022335-51c72e24c179/controller/controller.go:538\nknative.dev/pkg/controller.(*Impl).processNextWorkItem\n\tknative.dev/pkg@v0.0.0-20210107022335-51c72e24c179/controller/controller.go:524\nknative.dev/pkg/controller.(*Impl).RunContext.func3\n\tknative.dev/pkg@v0.0.0-20210107022335-51c72e24c179/controller/controller.go:461"}

**Environment:**

- Istio Version: 1.9
- Knative Version: v0.20.1
- KFServing Version: v0.5.1
- Kubeflow version: none
- Kubernetes version: (use `kubectl version`): v1.17.17-gke.1100

**Comment by yuzisun** [comment]
@PatrickGhosn What's the status of the inference service, the revision status is separate from the routing status. It seems like that the knative controller is not able to call the istiod webhook?

**Comment by PatrickGhosn** [comment]
@yuzisun yes. I simulated a crash from the firewall by blocking the main node in a private gke cluster. I was trying to test out what would happen if a deployment update failed. 

After some testing, the good news is that calls to the inference service was routing to the running revision correctly.

So it looks like only the issue is that the `LatestReady` was showing the none ready version when the `Ready` was false. Functionally this shouldn't affect anything. But I will verify more in a couple of days when I have some time.

**Comment by yuzisun** [comment]
@PatrickGhosn The revision status is correct, in this case if you check `kubectl get revisions` the revision status should be reported as true but `kubectl get routes` should show the status as false, knative service status aggregates the revision status and routing status so it shows false there.
