### ISSUE TITLE
Prometheus metrics for inferenceservice - which endpoints?

### ISSUE THREAD

**Issue by LeBaronDean** [kserve/kserve#1535]
Reading through the documentation here: https://github.com/kubeflow/kfserving/tree/master/docs/samples/metrics-and-monitoring, I've successfully set up prometheus metrics for some services. However, it is not clear from he documentation or the outputs what endpoint something like revision_app_request_latencies_count is recording.

For example in my server code I have a /ping and a /invoke...both calls to these endpoints go through the queue-proxy. I'd like to see more documentation around the metrics. What metrics are available, are they configurable within the proxy, how do I know what endpoint it's reporting, etc.

**Comment by sivanantha321** [comment]
The updated observability docs are now available in [kserve website](https://kserve.github.io/website/latest/modelserving/observability/prometheus_metrics/) and in [kserve repo](https://github.com/kserve/kserve/tree/master/qpext).
