### ISSUE TITLE
Correct the DEVELOPER_GUIDE on patching the mutating webhook config

### ISSUE THREAD

**Issue by unclerayray** [kserve/kserve#1545]
/kind feature

**Describe the solution you'd like**
Update [the developer guide](https://github.com/kubeflow/kfserving/blob/master/docs/DEVELOPER_GUIDE.md#troubleshooting) and correct the patching instruction because it only goes around the issue. The real root cause is with the GCP firewall rule. It's by default denying the traffic from the GKE master CIDR so the webhook controller is not working properly. You need to enable it explicitly at the **target** port 9876 of the kvserving webhook service in kubeflow namespace. See why it's [9876 rather than 443 here](https://github.com/kubernetes/kubernetes/issues/79739#issuecomment-509813068).

My journey on this
1. I installed kubeflow at my cluster on GKE with k8s version 1.15
2. I tried to create a notebook server under my own namespace and found the pod could not be created. Same issue was described at #568 
3. I went along with the patching suggested in the DEVELOPER_GUIDE and it worked.
4. I later on upgraded my GKE cluster to k8s 1.17 and ran into problem with some workload pods could not be successfully created
5. raised it to google because I saw there's some disconnection with the api-server and I suspect the k8s master(managed by google) was not working properly
6. google pointed out there was a firewall deny that causing the katib webhook to stop working
7. Referecing explaination is [on this comment](https://github.com/elastic/cloud-on-k8s/issues/1437#issuecomment-516836262). 
8. TL,DR -- GKE has a special setting when they install the K8S master. As a result, the webhook controller at the GKE k8s master side trys to reach the webhook service at the cluster node pool at the **target** node, not the 443 node defined in the mutatingwebhookconfiguration. Google by default denies all ingress and usually only allows 443 from master CIDR if you are following the official document. The traffic is blocked by the firewall rule so the webhook controller could not work properly and caused the issue. Funny thing about it is this katib webhook issue does not stop pods from being created in 1.15. It behavious differently on 1.17
9. I fixed the problem by updating the firewall rule to allow traffic to 8443
10. I then related to this kfserving webhook and I had a test by allowing the port at 9876
11. I was able to created a notebook server(in step 2) **without** the patching

Hope the DEVELOPER_GUIDE can be updated to avoid confusion.

**Comment by sivanantha321** [comment]
Closing this issue as it is too old
