### ISSUE TITLE
Failed to start multiple workers.

### ISSUE THREAD

**Issue by talk2jaydip** [kserve/kserve#1559]
[I 210425 09:55:37 kfserver:98] Will fork 2 workers
[I 210425 09:55:37 process:123] Starting 2 processes
[W 210425 09:55:42 process:153] child 0 (pid 8391) killed by signal 11, restarting

Tornado version 6. Tried with nest_asynio but no luck.
<code>

if __name__ == "__main__":
    kf_model = MyModel("api-my-model")
    kf_model.load()
    server = kfserving.KFServer(workers=2)
    server.start([kf_model])

**Comment by talk2jaydip** [comment]
``

**Comment by yuzisun** [comment]
This seems like an issue in the custom model, please provide more details.

**Comment by sivanantha321** [comment]
Kserve is migrated from tornado server to uvicorn server. The server should run successfully with multiple workers now.
