### ISSUE TITLE
Postprocessing Output is not forwarded to Logger

### ISSUE THREAD

**Issue by felix-exel** [kserve/kserve#1561]
/kind bug

**What steps did you take and what happened:**
[A clear and concise description of what the bug is.]

When overwriting the postprocess function from kfserving.KFModel class with something like
```
def postprocess(self, request: Dict) -> Dict:
    request['id'] = 1
    return request
```
the added key will return to the client but will not be forwarded to the logger.

**What did you expect to happen:**

I expect that the postprocessed dictionary will be send to the logger as well.

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

**Environment:**

- Istio Version: 1.6.2
- Knative Version: 0.18.0
- KFServing Version: 0.5.0
- Kubeflow version: - (KFServing Standalone)
- Minikube version: 1.15.1
- Kubernetes version: (use `kubectl version`): 1.17.11
- OS (e.g. from `/etc/os-release`): Windows 10

**Comment by yuzisun** [comment]
Verified this with the latest release, this should work as expected
