### ISSUE TITLE
Support unpacking of model as tar/zip file for s3

### ISSUE THREAD

**Issue by gilbeckers** [kserve/kserve#1569]
/kind feature

**Describe the solution you'd like**
We are trying to marry  "KF Pipelines + KF Artifacts + KF Serving" in a nice use-case where we train a (sklearn) model using KFP, store it as an output artifact to the artifact store of pipelines (minio) and then deploy that model directly from the artifact store using KFServing. The problem we are facing is that the output artifacts are by default stored as `.tgz` , so even a `.joblib` blob model object is still wrapped into `.tgz`  at creation time of the artifact in minio. On the other end, the default KF serving application server expects a `.joblib` file, not a `.tgz`. 
We're using the `s3` protocol to load the model file from minio to the kfserving pod. 

We already discussed with @yuzisun in the Kubeflow slack, and he pointed out that unpacking of a model (in the storage-initializer container) is currently only supported for http: 
[see this example](https://github.com/kubeflow/kfserving/tree/master/docs/samples/storage/uri#specify-and-create-the-inferenceservice-1)
[see the code](https://github.com/kubeflow/kfserving/blob/47362081224d1b9855648c7fcbd50a3d8037e1cc/python/kfserving/kfserving/storage.py#L233)

I'm opening this issue to first of all start a discussing on how to go about this. 
I can already add that, if it's decided to add support to s3 for the extraction of a model file, we at Credo are happy to help :slightly_smiling_face:

**Comment by rado-parrak** [comment]
Copying part of the discussion from Slack:

@yuzisun would you let us know pls if OK with you to integrate the fix of the issue 1569 (see above in the thread) once we PR the fix?

@yuzisun: sounds good, How do you plan fix this?

Well, high-level speaking we would add the same functionality for unpacking the .tar.gz as currently implemented in _download_from_uri() (source) to _download_s3() as well. Sounds ok?

**Comment by juangon** [comment]
Hi! Are there any update on this? Thanks!

**Comment by zamonia500** [comment]
I need this functionality too!
Any update here?
