### ISSUE TITLE
Extract zip/tar/tgz files for gcs

### ISSUE THREAD

**Issue by Aaronchoo** [kserve/kserve#1577]
/kind feature

**Describe the solution you'd like**
[A clear and concise description of what you want to happen.]
Similar to [HTTP/HTTPS](https://github.com/kubeflow/kfserving/blob/4fd401e348174f954fee7596dc3d54f197f4aa8c/pkg/agent/storage/https.go#L145), we should support extraction of zip/tar/tgz files when downloading from gcs. We currently assume the file being downloaded will be in the model file.

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]
Could move the extraction logic to utils and share the logic between https/http, s3, and gcs.

**Comment by juangon** [comment]
Duplicate of https://github.com/kubeflow/kfserving/issues/1569?

**Comment by Aaronchoo** [comment]
> Duplicate of #1569?

Oh its partially a duplicate. It would be useful if we add this for `gcs` as well.

**Comment by andyi2it** [comment]
Fixed as part of adding tgz/zip support for all storages #1836
