### ISSUE TITLE
PVC Support

### ISSUE THREAD

**Issue by Aaronchoo** [kserve/kserve#1578]
/kind feature

**Describe the solution you'd like**
[A clear and concise description of what you want to happen.]
Could launch a job when deploying trained models to download the file. All pods can download from pvc when done.

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]
https://github.com/kubeflow/kfserving/blob/4fd401e348174f954fee7596dc3d54f197f4aa8c/pkg/agent/storage/provider.go#L28

**Comment by klmkrishna** [comment]
Hi @Aaronchoo, may I know when this PVC support feature is available in Multi Model Serving?

**Comment by nanduri1998** [comment]
@klmkrishna PR #1899 has the implementation. You can check this PR. It has to be merged.

**Comment by sivanantha321** [comment]
PVC is already supported in kserve.
