### ISSUE TITLE
isvc default resource requests/limits should be optional/configurable via ConfigMap

### ISSUE THREAD

**Issue by adamkgray** [kserve/kserve#1593]
/kind feature

**Describe the solution you'd like**

In `pkg/apis/serving/v1beta1/inference_service_defaults.go` the default InferenceService resource requests and limits are hard coded to be 1 cpu and 2Gi memory. These are reasonable defaults. However, the entire existence of these defaults should be disablable. Moreover, administrators should be able to quickly adjust defaults globally via the `inferenceservice-config` ConfigMap.

**Anything else you would like to add:**

It would be interesting to take the config a little further even, and expose different defaults for predictors, explainers and transformers. This sort of global preset adjustment could reduce config duplication on the user end and therefor reduce bugs.

**Comment by tzstoyanov** [comment]
I'm looking for a good first issue to get familiar with kfserving, may I get this one ?

**Comment by yuzisun** [comment]
> I'm looking for a good first issue to get familiar with kfserving, may I get this one ?

yes! feel free to assign to yourself, thanks !

**Comment by tzstoyanov** [comment]
thanks! I was on a vacation last week, going to start working on that this week.

**Comment by yuzisun** [comment]
the upcoming 0.8 release introduces the `ClusterServingRuntime` so you can overwrite with your custom resource requirement at the serving runtime level.
