### ISSUE TITLE
Kfserving + OpenShift serverless + OpenShift Service Mesh is not working

### ISSUE THREAD

**Issue by Jooho** [kserve/kserve#1620]
/kind bug

**What steps did you take and what happened:**
Basically I tried to follow this [doc](https://github.com/kubeflow/kfserving/blob/master/docs/OPENSHIFT_GUIDE.md#install-using-openshift-service-mesh) to use kfserving on OpenShift. However, I used OpenShift Operators for knative(OpenShift Serverless) and Istio(OpenShift Service Mesh) instead of upstream products.

After installing necessary components and the example "sklearn" in doc, I tested the isvc URL but it was not working properly.

**What did you expect to happen:**
The example "Sklearn" should work on OpenShift. 

**Anything else you would like to add:**
I noticed that the OpenShift Serverless use kourier but the doc uses net-istio as a knative network layer.

**Environment:**

- Istio Version: "1.6.14"
- Knative Version: v0.20.0
- KFServing Version: 0.5.1
- Kubeflow version:
- Kfdef:[k8s_istio/istio_dex/gcp_basic_auth/gcp_iap/aws/aws_cognito/ibm]
- Minikube version:
- Kubernetes version: (use `kubectl version`):  v1.20.0+c8905da
- OS (e.g. from `/etc/os-release`):
- OpenShift: 4.7.9

**Comment by juangon** [comment]
@Jooho  take a look at these instrucions: https://www.openshift.com/blog/operationalizing-kubeflow-in-openshift

**Comment by Jooho** [comment]
@juangon Before I create this issue, I already discuss it with the author of the blog. We think there are missing configurations with the combination.

**Comment by yuzisun** [comment]
See latest openshift guide https://github.com/kserve/kserve/blob/master/docs/OPENSHIFT_GUIDE.md
