### ISSUE TITLE
Storage initializer doesn't work when using subdirectories paths in S3 storage

### ISSUE THREAD

**Issue by juangon** [kserve/kserve#1625]
/kind bug

**What steps did you take and what happened:**

When storing files (used Minio in my case) in a path, storage creates the remote path in the storage initializer  container, causing models with single files to be added in some subdirectories path. This causes issues with sklearn models for example, as it expects model.joblib to be on root of /mnt/models, not on any subdirectory

**What did you expect to happen:**

When creating subdirectories in minio/S3 and point to that file in kfserving, not create all the structure if possible, just download file and put on root /mnt/models directory.

**Anything else you would like to add:**

**Environment:**

- Istio Version:
- Knative Version:
- KFServing Version: 0.5.2
- Kubeflow version: 1.3.0
- Kfdef:
- Minikube version:
- Kubernetes version: (use `kubectl version`):
- OS (e.g. from `/etc/os-release`):

**Comment by yuzisun** [comment]
fixed in https://github.com/kserve/kserve/pull/1883
