### ISSUE TITLE
MLFlow Model deployment in KFServing

### ISSUE THREAD

**Issue by linuraj** [kserve/kserve#1626]
Hello all,

What is the best way for deploying MLFlow models in KFServing?

Appreciate your help!

Thanks

**Comment by linuraj** [comment]
Hello @adriangonz 

Can you please share your recommendation here?

Thanks

**Comment by adriangonz** [comment]
Hey @linuraj, we're currently working on adding support for MLflow to MLServer. You can track the current progress in this GitHub project:

https://github.com/SeldonIO/MLServer/projects/1

Once this is finished, given that MLServer is already serving SKLearn and XGBoost models in KFServing, it should be straightforward to add a new framework to the KFServing spec for MLflow.

**Comment by linuraj** [comment]
Thank you @adriangonz

**Comment by yuzisun** [comment]
This is supported via MLServer #2034
