### ISSUE TITLE
Path in quick_install.sh need changed

### ISSUE THREAD

**Issue by jzonthemtn** [kserve/kserve#1628]
/kind bug

**What steps did you take and what happened:**
When running the `quick_install.sh` the install path at the end of the script is pointing to the wrong directory. It needs to be pointing to a directory up one level.

**What did you expect to happen:**
The `kfserving.yaml` file to be found.

**Anything else you would like to add:**
Pull request will follow.

**Environment:**

- Istio Version:
- Knative Version:
- KFServing Version:
- Kubeflow version:
- Kfdef:[k8s_istio/istio_dex/gcp_basic_auth/gcp_iap/aws/aws_cognito/ibm]
- Minikube version:
- Kubernetes version: (use `kubectl version`):
- OS (e.g. from `/etc/os-release`):

**Comment by yuzisun** [comment]
@jzonthemtn  `quick_install.sh` is expected to run under the root kfserving directory.

**Comment by yuzisun** [comment]
Fixed now using full url.
