### ISSUE TITLE
s3 https unable to get local issuer certificate

### ISSUE THREAD

**Issue by juanvasquezreyes** [kserve/kserve#1630]
I'm using kfserving and want to integrate with my minio instance that is running in a different cluster https://myminio-test.com

is there a way to provide my ca certificate so the connection to my minio is secure?

I already tried S3_VERIFY_SSL 0 and 1 and didnt work 

this is my secret
```
apiVersion: v1
kind: Secret
metadata:
  name: mysecret
  annotations:
     serving.kubeflow.org/s3-endpoint: myminio-test.com  
     serving.kubeflow.org/s3-usehttps: "1"
     serving.kubeflow.org/s3-verifyssl: "0"
     serving.kubeflow.org/s3-useanoncredential: "false" 
type: Opaque
stringData: # use `stringData` for raw credential string or `data` for base64 encoded string
  AWS_ACCESS_KEY_ID: test
  AWS_SECRET_ACCESS_KEY: <access-key>
```

and this is the error I'm getting
```
During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/storage-initializer/scripts/initializer-entrypoint", line 14, in <module>
    kfserving.Storage.download(src_uri, dest_path)
  File "/usr/local/lib/python3.7/site-packages/kfserving/storage.py", line 62, in download
    Storage._download_s3(uri, out_dir)
  File "/usr/local/lib/python3.7/site-packages/kfserving/storage.py", line 89, in _download_s3
    for obj in objects:
  File "/usr/local/lib/python3.7/site-packages/minio/api.py", line 2297, in _list_objects
    query=query,
  File "/usr/local/lib/python3.7/site-packages/minio/api.py", line 2209, in _url_open
    preload_content=preload_content)
  File "/usr/local/lib/python3.7/site-packages/urllib3/poolmanager.py", line 375, in urlopen
    response = conn.urlopen(method, u.request_uri, **kw)
  File "/usr/local/lib/python3.7/site-packages/urllib3/connectionpool.py", line 796, in urlopen
    **response_kw
  File "/usr/local/lib/python3.7/site-packages/urllib3/connectionpool.py", line 796, in urlopen
    **response_kw
  File "/usr/local/lib/python3.7/site-packages/urllib3/connectionpool.py", line 796, in urlopen
    **response_kw
  [Previous line repeated 2 more times]
  File "/usr/local/lib/python3.7/site-packages/urllib3/connectionpool.py", line 756, in urlopen
    method, url, error=e, _pool=self, _stacktrace=sys.exc_info()[2]
  File "/usr/local/lib/python3.7/site-packages/urllib3/util/retry.py", line 573, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='myminio-test.com', port=443): Max retries exceeded with url: /test/?delimiter=&max-keys=1000&prefix=sklearn (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1091)')))

```

**Comment by juanvasquezreyes** [comment]
@adriangonz Hello Adrian, sorry to pull you into this, I was wondering if you have any idea why I'm getting this error when using an external minio endpoint

I tested using S3_VERIFY_SSL=0 and doesnt work, is there a way to provide my CA certificate so its secure?

**Comment by adriangonz** [comment]
Hey @juanvasquezreyes, have you tried setting the `serving.kubeflow.org/s3-usehttps` annotation to `0` to disable SSL? I believe KFServing will only look at those and not at the `S3_VERIFY_SSL` flag.

**Comment by juanvasquezreyes** [comment]
> Hey @juanvasquezreyes, have you tried setting the `serving.kubeflow.org/s3-usehttps` annotation to `0` to disable SSL? I believe KFServing will only look at those and not at the `S3_VERIFY_SSL` flag.

yes I have, but my endpoint is over https, so I have to use s3-usehttps with 1, my endpoint for example is https://myexternal-minio.com and is external from where kfserving is running

I believe kfserving is using S3_VERIFY_SSL just to create the credentials, but not when making the call, I see that S3_VERIFY_SSL is only used at the following files

```
root@storage-initializer-75479959b7-t26lt:/usr/local/lib/python3.7# grep -rni . -e "S3_VERIFY_SSL"
./site-packages/kfserving/api/creds_utils.py:57:                       s3_endpoint=None, s3_region=None, s3_use_https=None, s3_verify_ssl=None):  # pylint: disable=unused-argument
./site-packages/kfserving/api/creds_utils.py:70:        s3_verify_ssl(str): S3 settings variable S3_VERIFY_SSL.
./site-packages/kfserving/api/creds_utils.py:99:        's3_verify_ssl': constants.KFSERVING_GROUP + "/s3-verifyssl",
```


but not where the error is thrown which is at **urllib**
```
During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/storage-initializer/scripts/initializer-entrypoint", line 14, in <module>
    kfserving.Storage.download(src_uri, dest_path)
  File "/usr/local/lib/python3.7/site-packages/kfserving/storage.py", line 62, in download
    Storage._download_s3(uri, out_dir)
  File "/usr/local/lib/python3.7/site-packages/kfserving/storage.py", line 89, in _download_s3
    for obj in objects:
  File "/usr/local/lib/python3.7/site-packages/minio/api.py", line 2297, in _list_objects
    query=query,
  File "/usr/local/lib/python3.7/site-packages/minio/api.py", line 2209, in _url_open
    preload_content=preload_content)
  File "/usr/local/lib/python3.7/site-packages/urllib3/poolmanager.py", line 375, in urlopen
    response = conn.urlopen(method, u.request_uri, **kw)
  File "/usr/local/lib/python3.7/site-packages/urllib3/connectionpool.py", line 796, in urlopen
    **response_kw
  File "/usr/local/lib/python3.7/site-packages/urllib3/connectionpool.py", line 796, in urlopen
    **response_kw
  File "/usr/local/lib/python3.7/site-packages/urllib3/connectionpool.py", line 796, in urlopen
    **response_kw
  [Previous line repeated 2 more times]
  File "/usr/local/lib/python3.7/site-packages/urllib3/connectionpool.py", line 756, in urlopen
    method, url, error=e, _pool=self, _stacktrace=sys.exc_info()[2]
  File "/usr/local/lib/python3.7/site-packages/urllib3/util/retry.py", line 573, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='myminio-test.com', port=443): Max retries exceeded with url: /test/?delimiter=&max-keys=1000&prefix=sklearn (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1091)')))
```

in order to fix this, I have to either provide my ca certificate or kfserving needs to make the url call skipping certificate validation at urllib

**Comment by adriangonz** [comment]
Hey @juanvasquezreyes, I was just having a look at this. I think you're right, it seems that `s3-verifyssl` is not currently being used. 

Do you know if it's possible to skip the SSL verification on the storage initialiser @yuzisun? I guess this should also be double checked on the agent, right?

**Comment by juanvasquezreyes** [comment]
> Hey @juanvasquezreyes, I was just having a look at this. I think you're right, it seems that `s3-verifyssl` is not currently being used.
> 
> Do you know if it's possible to skip the SSL verification on the storage initialiser @yuzisun? I guess this should also be double checked on the agent, right?

I was able to make it work, but in order to do that I had to manually load my ca certificate and set the following environment variable SSL_CERT_FILE based on the following file

/usr/local/lib/python3.7/site-packages/minio/api.py
line: 177

so s3-verifyssl, should skip certificate validation at minio/api.py when using urllib library

**Comment by yuzisun** [comment]
@juanvasquezreyes in KFServing 0.6 we have switched to use boto library instead of minio, can you check if this is still an issue?

**Comment by JakeNeyer** [comment]
@yuzisun I'm having similar problems attempting to use minio with an https:// URL using self-signed certificates. My understanding is that you cannot set verify-ssl at the [boto configuration level using the environment variables](https://boto3.amazonaws.com/v1/documentation/api/latest/guide/configuration.html#using-environment-variables). That would have to be set on the resource level [here](https://github.com/kserve/kserve/blob/3507c4611c8c92e86de64fee00b77e6ccf3e333a/python/kserve/kserve/storage.py#L105) (https://boto3.amazonaws.com/v1/documentation/api/latest/_modules/boto3/session.html#Session.resource)

**Comment by umka1332** [comment]
You can set S3_AWS_BUNDLE to an empty string "".
This results as S3_VERIFY_SSL 0.

**Comment by yuzisun** [comment]
consolidate to https://github.com/kserve/kserve/issues/3171
