### ISSUE TITLE
After one of my inference pod failed, no messages were received until I restarted the activator pod.

### ISSUE THREAD

**Issue by daganida88** [kserve/kserve#1639]
/kind bug

I started sending a lot of messages to my inference service that contains two GPU replicas.
I had some OOM issues inside the ingress controller and inside my pod, they were both restarted because of OOM issues.
After I increased the memory the pods never crashed again.
What is weird is that once a new inference pod was up and running, it did not receive traffic for some time.
After I restarted my activator I saw on the spot that I started receiving traffic again to my idle pod.
I also saw errors in the activator.
Once I restarted the pod the errors stopped. 

**What did you expect to happen:**
I expected that once a new pod is running I will not have to restart the activator (I'm not sure what is happening behind the scenes) and the traffic will reach my pod.

**Anything else you would like to add:**
Running on KFServing + Triton model server on EKS.

Please help :)

**Comment by yuzisun** [comment]
@daganida88 which knative version you are on ?

**Comment by daganida88** [comment]
@yuzisun ?

**Comment by daganida88** [comment]
?

**Comment by sivanantha321** [comment]
Closing this issue as it is stale. Feel free to create a new issue if encounter the same problem in latest kserve version.

/close

**Comment by zzuchen** [comment]
> Hi, I am using version: v0.22.1 Also, I restarted the activator at 10:20 ![image](https://user-images.githubusercontent.com/22128504/120975884-6aff8400-c77a-11eb-9120-2a57b8bb19fd.png) I also saw the following errorsm and warnning in the activator: Failed to send ping message to ws://autoscaler.knative-serving.svc.cluster.local:8080 read tcp 172.19.177.227:51556->10.100.250.229:8080: i/o timeout Connecting to ws://autoscaler.knative-serving.svc.cluster.local:8080 Healthcheck failed: connection has not yet been established Need to reprobe pods who became non-ready Set capacity to 2147483647 (backends: 1, index: 0/1) (And I have 2 backends, not 1)... Failed probing pods : error roundtripping http://172.19.155.94:8013/healthz: context deadline exceeded after I restarted the activator all the warnings and errors disappeared.

Hello，We have met the same problem. Has this issue been resolved？
