### ISSUE TITLE
Multi-model serving transformers support

### ISSUE THREAD

**Issue by beyersito** [kserve/kserve#1654]
/kind feature

**Describe the solution you'd like**
As far as I understand, currently transformers are specfied on the multi-model server and not on each TrainedModel, meaning that the same pre/post-processing would be applied to every model. Our use case for MMS is hosting several different models in the same GPU to make efficient use, however if my understanding is correct, the current implementation does not allow this. Is this something on your roadmap? Or is MMS only for hosting the same model with different weights?

**Anything else you would like to add:**

**Comment by yuzisun** [comment]
@beberg We are working on inference graph which would allow multiple transformers calling out to the same MMS predictor, but for now you can also work around by creating multiple custom predictors which calls out to the same MMS predictor.

custom-predictor-transformer-model1 ------> mms-predictor
custom-predictor-transformer-model2 ------> mms-predictor

**Comment by vaporpin** [comment]
@yuzisun, not sure if i understand correctly. Is it that there is no solution currently to append multiple transformers to a single predictor, for example sklearn model? 
And the current solution is to deploy transformers as predictors?

**Comment by beberg** [comment]
That mention was probably for @beyersito

**Comment by njhill** [comment]
@beyersito this work has now been done for modelmesh based MMS, see https://github.com/kserve/modelmesh-serving/issues/127 and https://github.com/kserve/kserve/pull/2136.
