### ISSUE TITLE
Serving service from github examples created with kubectl, but can not nor infere nor find the service, looks like it did not exist.

### ISSUE THREAD

**Issue by adamjablonowski** [kserve/kserve#1662]
/kind bug

**What steps did you take and what happened:**
I have installed minikube cluster and kfserving on a linux desktop.
Then I have followed two tutorials
1. https://github.com/kubeflow/kfserving/tree/master/docs/samples/v1beta1/custom/torchserve
2. https://github.com/kubeflow/kfserving/tree/master/docs/samples/v1alpha2/custom/kfserving-custom-model
In the second tutorial I have needed to move "name: custom" from "custom:" section to "container:" section in the yaml file.

**What did you expect to happen:**
Serving service working and responding to serving requests. Pods of the service in kubernetes.

**Anything else you would like to add:**
I have same bug in both tutorials. Bellow commands are from the first tutorial. When I prepare docker images with models and run
`$kubectl apply -f torchserve-custom.yaml`
command.
I see output like
`inferenceservice.serving.kubeflow.org/torchserve-custom created`
But I can not run a prediction, because service I get 404 not found.
When I run
`$kubectl get pods --all-namespaces`
I do not see any new pods.
But I can delete service with `kubectl delete -f torchserve-custom`.
When I followed other tutorials like https://github.com/kubeflow/kfserving/tree/master/docs/samples/v1beta1/torchserve every thing worked fine and I could run predictions.

Why can`t I run a prediction?
Why any new pods are created?
How to setup serving in kfserving using docker image, if the above tutorials did not worked?

**Environment:**

Newest stable versions from June 2021.
- Istio Version:
- Knative Version:
- KFServing Version:
- Kubeflow version:
- Kfdef:[k8s_istio/istio_dex/gcp_basic_auth/gcp_iap/aws/aws_cognito/ibm]
- Minikube version:
- Kubernetes version: (use `kubectl version`):
- OS (e.g. from `/etc/os-release`):

**Comment by yuzisun** [comment]
@adamjablonowski Please help give the detailed output of the service with `kubectl get isvc torchserve-custom -oyaml` and you can also run `kubectl get events` to debug the issue.

**Comment by adamjablonowski** [comment]
Thanks, It turned out that my local docker registry wasn't visible from kubernetes. kubectl get events shows TYPE Warning REASON InternalError and MESSAGE "Unable to fetch image torchserve-custom:latest": failed to resolve image to digest: Get "http://localhost:500/v2/": dial tcp 127.0.0.1:5000: connect: connection refused".

**Comment by adamjablonowski** [comment]
Do you know what is the best way to share access to own docker registry?

**Comment by yuzisun** [comment]
@adamjablonowski Please check https://knative.dev/docs/serving/deploying/private-registry/ to see if this helps.

**Comment by andyi2it** [comment]
/close
Closing this, since the problem was identified on the the environment setup and not in KServe.
