### ISSUE TITLE
Add docs for the Models web app

### ISSUE THREAD

**Issue by kimwnasptd** [kserve/kserve#1664]
/kind feature

**Describe the solution you'd like**
Right now the only docs we have for the web app are located in the app's [README](https://github.com/kubeflow/kfserving/blob/master/web-app/README.md) file.

I think it would be helpful for end users if we would also include documentation about the app in the official [kubeflow.org](https://www.kubeflow.org/docs/components/kfserving/) docs.

One first iteration I had in mind was to have docs like:
```
Components
    KFServing
        KFServing
        Models UI
```

We can go through what items to place under the `Models UI` docs component, but I would like to first hear your thoughts about if this is something you would like to see. If yes then I can also create an issue in the kubeflow/website repo and further discuss there the structure of the docs.

WDYT @yuzisun @animeshsingh @pvaneck

**Comment by yuzisun** [comment]
Thanks @kimwnasptd ! I think this is good.
