### ISSUE TITLE
Transformer not working with Tensorflow tensors in column format

### ISSUE THREAD

**Issue by Vafilor** [kserve/kserve#1667]
/kind bug

**What steps did you take and what happened:**

Following this guide: https://github.com/kubeflow/kfserving/tree/master/docs/samples/v1beta1/transformer/torchserve_image_transformer

I created a transformer converting base64 to data with tensors in column format to be sent to a predictor running tensorflow  serving 2.5.1.

Here's a part of the final data I send - the result of `preprocess` of `ImageTransformer(kfserving.KFModel)`
```json
{
   "inputs": {
      "input_image": [
         [
              ...data
         ]
    }
}
```

But I get an error because `inputs` is not a list. I believe it is from this line here https://github.com/kubeflow/kfserving/blob/master/python/kfserving/kfserving/handlers/http.py#L45

However, tensorflow serving does not allow it being a list, but expects a dict/map (as far as I understand) https://www.tensorflow.org/tfx/serving/api_rest#specifying_input_tensors_in_column_format

**What did you expect to happen:**

Not to get an error that inputs has to be a list.

**Anything else you would like to add:**

The request succeeds when I remove the validation check. 

I'm pretty new to this, so I might be misunderstanding something. But I think the data should be allowed to be a dict for tensorflow serving.

**Comment by yuzisun** [comment]
@Vafilor According to inference [v2 protocol](https://github.com/kubeflow/kfserving/blob/master/docs/predict-api/v2/required_api.md#inference-request-json-object) the `inputs` is a list but looks like this clashes with the tensorflow v1 protocol where `inputs` is a dict.

**Comment by plankthom** [comment]
I'd propose to validate according to the protocol implied by the endpoint.  I.m.o the http handlers initializers and the `KFModel.__call__` need to receive the protocol version so that each specific server can further validate or map the two protocol versions.
