### ISSUE TITLE
Cloud events responses need to be configurable for custom predictors and transformers

### ISSUE THREAD

**Issue by maganaluis** [kserve/kserve#1671]
/kind feature

**Describe the solution you'd like**
[A clear and concise description of what you want to happen.]

Cloud events responses need to be configurable for custom predictors and transformers. Currently it returns the same Ce-Type and Ce-Source, which means that the transformer/predictor will get those events again except this time without the proper payload, at any case they need to be configurable so the proper consumer can pick them up. 

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

I already have an example how this should be done but I am unsure how to allow for configuration view the custom spec. Should this be env variables? 

https://github.com/pwc-labs/kfserving/blob/ce-time-fix/python/kfserving/kfserving/handlers/http.py#L85

Also note that: RFC 3339 is not compatible with ISO. I corrected this as well. 

```python
self.set_header('ce-time', datetime.utcnow().replace(tzinfo=pytz.utc).trftime('%Y-%m-%dT%H:%M:%SZ'))
````

**Comment by yuzisun** [comment]
@maganaluis ye think env variable is fine, if not present we can set the default type/source as you suggested

**Comment by markwinter** [comment]
Related https://github.com/kserve/kserve/issues/1923

This will be fixed with my upcoming PR
