### ISSUE TITLE
s3 file download is failed when explainer deploying

### ISSUE THREAD

**Issue by jhs0318** [kserve/kserve#1691]
/kind bug

Hello, 
serviceAccountName does not apply when deploying the explainer in s3. 
predict deploying is ok.
Please check it.

-- yaml
apiVersion: "serving.kubeflow.org/v1beta1"
kind: "InferenceService"
metadata:
  name: "imagenet"
  namespace: auto-create-26
spec:
  predictor:
    serviceAccountName: s3-sa
    tensorflow:
      storageUri: "s3://jhs-bucket/seldon-models/tfserving/imagenet/model"
  explainer:
    serviceAccountName: s3-sa
    alibi:
      type: AnchorImages
      storageUri: "s3://jhs-bucket/seldon-models/tfserving/imagenet/explainer"
      config:
        batch_size: "25"
        stop_on_first: "True"

**What steps did you take and what happened:**
[A clear and concise description of what the bug is.]
` Init Containers:                                                                                                                   
   storage-initializer:                                                                                                             
     Container ID:  docker://14ed1ed27c766827b17652a7fc674cebae39cf1f05ef8ecb9cb718a9fc2982ae                                       
     Image:         gcr.io/kfserving/storage-initializer:v0.5.1                                                                     
     Image ID:      docker-pullable://gcr.io/kfserving/storage-initializer@sha256:b40188826494a24e7ee506799999f8c89811320a96bc143a5 
 fa50eb8d903f29d                                                                                                                    
     Port:          <none>                                                                                                          
     Host Port:     <none>                                                                                                          
     Args:                                                                                                                          
       s3://jhs-bucket/seldon-models/tfserving/imagenet/explainer                                                                   
       /mnt/models                                                                                                                  
     State:       Waiting                                                                                                           
       Reason:    CrashLoopBackOff                                                                                                  
     Last State:  Terminated                                                                                                        
       Reason:    Error                                                                                                             
       Message:   [I 210625 06:35:31 initializer-entrypoint:13] Initializing, args: src_uri [s3://jhs-bucket/seldon-models/tfservin 
 g/imagenet/explainer] dest_path[ [/mnt/models]                                                                                     
 [I 210625 06:35:31 storage:45] Copying contents of s3://jhs-bucket/seldon-models/tfserving/imagenet/explainer to local             
 Traceback (most recent call last):                                                                                                 
   File "/storage-initializer/scripts/initializer-entrypoint", line 14, in <module>                                                 
     kfserving.Storage.download(src_uri, dest_path)                                                                                 
   File "/usr/local/lib/python3.7/site-packages/kfserving/storage.py", line 62, in download                                         
     Storage._download_s3(uri, out_dir)                                                                                             
   File "/usr/local/lib/python3.7/site-packages/kfserving/storage.py", line 89, in _download_s3                                     
     for obj in objects:                                                                                                            
   File "/usr/local/lib/python3.7/site-packages/minio/api.py", line 2297, in _list_objects                                          
     query=query,                                                                                                                   
   File "/usr/local/lib/python3.7/site-packages/minio/api.py", line 2229, in _url_open                                              
     object_name).get_exception()                                                                                                   
 minio.error.NoSuchBucket: NoSuchBucket: message: The specified bucket does not exist.                                              
                                                                                                                                    
       Exit Code:    1                                                                                                              
       Started:      Fri, 25 Jun 2021 15:35:30 +0900                                                                                
       Finished:     Fri, 25 Jun 2021 15:35:31 +0900                                                                                
     Ready:          False                                                                                                          
     Restart Count:  2                                                                                                              
     Limits:                                                                                                                        
       cpu:     1                                                                                                                   
       memory:  1Gi                                                                                                                 
     Requests:                                                                                                                      
       cpu:        100m                                                                                                             
       memory:     100Mi                                                                                                            
     Environment:  <none>                                                                                                           
     Mounts:                                                                                                                        
       /mnt/models from kfserving-provision-location (rw)                                                                           
       /var/run/secrets/kubernetes.io/serviceaccount from default-token-j8bcx (ro)     `

**What did you expect to happen:**
`     Environment:
      AWS_ACCESS_KEY_ID:      <set to the key 'AWS_ACCESS_KEY_ID' in secret 's3-secret'>      Optional: false
      AWS_SECRET_ACCESS_KEY:  <set to the key 'AWS_SECRET_ACCESS_KEY' in secret 's3-secret'>  Optional: false
      S3_USE_HTTPS:           0
      S3_ENDPOINT:            34.69.6.239:80
      AWS_ENDPOINT_URL:       http://34.69.6.239:80
`

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

**Environment:**

- Istio Version:
- Knative Version:
- KFServing Version: 0.6.0-rc0 or 0.5.1
- Kubeflow version:
- Kfdef:[k8s_istio/istio_dex/gcp_basic_auth/gcp_iap/aws/aws_cognito/ibm]
- Minikube version:
- Kubernetes version: (use `kubectl version`):
- OS (e.g. from `/etc/os-release`):

**Comment by yuzisun** [comment]
@jhs0318 Can you check the explainer container to see if AWS S3 environment variables are injected there?

**Comment by kpulipati** [comment]
I am not using GCS but using a HTTPS endpoint, but facing a similar issue where the predictor is able to download and explainer fails to download with the same service account from same location. I opened a separate bug for it:

https://github.com/kubeflow/kfserving/issues/1778

**Comment by yuzisun** [comment]
fixed in https://github.com/kserve/kserve/pull/1868
