### ISSUE TITLE
[DOC] KFModel.load(): How to override? Inconsistent return type in examples

### ISSUE THREAD

**Issue by xuhdev** [kserve/kserve#1694]
/kind bug

**What steps did you take and what happened:** `KFServing.load` returns bool (`self.ready`):

https://github.com/kubeflow/kfserving/blob/b684b2ec26f8ddabdde36f9f462f5d8ac8458632/python/kfserving/kfserving/kfmodel.py#L84

However, examples in the repo are inconsistent on this. For example, https://github.com/kubeflow/kfserving/blob/b684b2ec26f8ddabdde36f9f462f5d8ac8458632/docs/samples/explanation/aif/germancredit/server/model.py#L15-L26 doesn't return anything but https://github.com/kubeflow/kfserving/blob/b684b2ec26f8ddabdde36f9f462f5d8ac8458632/docs/samples/explanation/aix/mnist/rfserver/rfserver/model.py#L43-L50 returns bool.

**What did you expect to happen:** Consistent examples.

If the return type doesn't matter, can we perhaps document it and give `KFServing.load` an `Any` return type annotation?

**Comment by sivanantha321** [comment]
Closing this issue as it is no longer valid.
