### ISSUE TITLE
How custom kfserving uses the pytorch model stored in pvc.

### ISSUE THREAD

**Issue by SeibertronSS** [kserve/kserve#1722]
Hello everyone,
I recently learned how to [customize kfserving](https://github.com/kubeflow/kfserving/blob/master/docs/samples/v1beta1/custom/custom_model/README.md). But I find that demo leverages `torchvision` to download a pytorch model in container. How to use the pytorch model stored in pvc?

**Comment by haijohn** [comment]
you can set `STORAGE_URI` environment variable in container
```
      env:
        - name: STORAGE_URI
          value: "pvc://path/to/pvc" # The storage mounts to /mnt/models
```

**Comment by SeibertronSS** [comment]
> you can set `STORAGE_URI` environment variable in container
> 
> ```
>       env:
>         - name: STORAGE_URI
>           value: "pvc://path/to/pvc" # The storage mounts to /mnt/models
> ```
Thank you very much for your reply.
I mount pvc by using the method of `V1beta1TorchServeSpec`. But I can't use `V1Volume`. Details can be viewed in #1733

**Comment by haijohn** [comment]
if you want to use custom kfserving by python sdk, you can specify env like follows:
```
    custom_contaier = V1Container(
        ...,
        env=[
            V1EnvVar("STORAGE_URI", storageUri),
        ]
    )
    spec = V1beta1InferenceServiceSpec(
        predictor=V1beta1PredictorSpec(
            containers=[
                custom_contaier
            ],
            ...
        )
    )

```
if you want use `V1beta1TorchServeSpec`, just specify `storage_uri` in the argument

**Comment by SeibertronSS** [comment]
> if you want to use custom kfserving by python sdk, you can specify env like follows:
> 
> ```
>     custom_contaier = V1Container(
>         ...,
>         env=[
>             V1EnvVar("STORAGE_URI", storageUri),
>         ]
>     )
>     spec = V1beta1InferenceServiceSpec(
>         predictor=V1beta1PredictorSpec(
>             containers=[
>                 custom_contaier
>             ],
>             ...
>         )
>     )
> ```
> 
> if you want use `V1beta1TorchServeSpec`, just specify `storage_uri` in the argument

Thank you very much for your suggestion. I will experiment as soon as possible.
