### ISSUE TITLE
Pod doesn't restore after node reboot

### ISSUE THREAD

**Issue by ben-omji** [kserve/kserve#1742]
/kind bug

**What steps did you take and what happened:**
[A clear and concise description of what the bug is.]

1. Create isvc with minreplica=1
2. Reboot the node including the isvc pod
3. The pod doesn't restore to Running state

**What did you expect to happen:**

The pod restore to Running state

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

![image](https://user-images.githubusercontent.com/47874806/127415917-f77d4afa-db9e-40ca-be23-07679bc1b21f.png)

**Environment:**

kubeflow manifest v1.3.0

- Kfdef:[k8s_istio]

- Kubernetes version: (use `kubectl version`): v1.19.9
- OS (e.g. from `/etc/os-release`): Ubuntu 20.04

**Comment by sivanantha321** [comment]
@ben-omji It seems like this issue is related to #2354. This is resolved by the PR #2794 .
