### ISSUE TITLE
x509: certificate is not valid for any names, but wanted to match   kfserving-webhook-server-service.kfserving-system.svc

### ISSUE THREAD

**Issue by NirmalAnandKuzhandaivel** [kserve/kserve#1749]
```
failed to create resource: Internal error occurred: failed calling
              webhook
              "inferenceservice.kfserving-webhook-server.v1beta1.defaulter":
              Post
              "https://kfserving-webhook-server-service.kfserving-system.svc:443/mutate-serving-kubeflow-org-v1beta1-inferenceservice?timeout=30s":
              x509: certificate is not valid for any names, but wanted to match
              kfserving-webhook-server-service.kfserving-system.svc
```

**What steps did you take and what happened:**
Tried redeploying knative-serving

**What did you expect to happen:**
Tried to deploy this model to kfserving
https://github.com/kubeflow/kfserving/tree/master/docs/samples/v1beta1/tensorflow

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

**Environment:**

- Knative Version: v0.24.0
- KFServing Version: v0.6.0

**Comment by Phelan164** [comment]
@NirmalAnandKuzhandaivel any update for this issue, I got other issue with webhook-server-service.kfserving-system.svc when redeploy knative also
`Internal error occurred: failed calling webhook "inferenceservice.kfserving-webhook-server.v1beta1.defaulter": Post "https://kfserving-webhook-server-service.kfserving-system.svc:443/mutate-serving-kubeflow-org-v1beta1-inferenceservice?timeout=30s": context deadline exceeded`

**Comment by yurkoff-mv** [comment]
Hello!
I have the same problem.
