### ISSUE TITLE
Health API not working with Triton Inference Server

### ISSUE THREAD

**Issue by bansal01yash** [kserve/kserve#1760]
/kind bug

**What steps did you take and what happened:**
[A clear and concise description of what the bug is.]
I'm using Triton Inference Server for model deployment and have built a frontend to access it. I make a health request to check if the model exists that I currently want to use. This health request returns 
"*   Trying 127.0.0.1:8000...
* TCP_NODELAY set
* Connected to localhost (127.0.0.1) port 8000 (#0)
> GET /v2/models/inception_graphdef/versions/1/ready HTTP/1.1
> Host: localhost:8000
> User-Agent: curl/7.68.0
> Accept: */*
> 
* Mark bundle as not supporting multiuse
< HTTP/1.1 200 OK
< Content-Length: 0
< Content-Type: text/plain
< 
* Connection #0 to host localhost left intact
"

when used through command line  as "curl -v localhost:8000/v2/models/inception_graphdef/versions/1/ready"

**What did you expect to happen:**

The problem is that on my frontend it gets stuck at this get request, so I tested it on postman. It didn't return anything on postman either. I am on Linux and this request gives appropriate output on Windows in postman and in my application.

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

**Environment:**

- Istio Version:
- Knative Version:
- KFServing Version:
- Kubeflow version:
- Kfdef:[k8s_istio/istio_dex/gcp_basic_auth/gcp_iap/aws/aws_cognito/ibm]
- Minikube version:
- Kubernetes version: (use `kubectl version`):
- OS (e.g. from `/etc/os-release`):

**Comment by yuzisun** [comment]
@bansal01yash this is unlikely triton issue, I see the output gives 200 response I am not clear what the problem is.

**Comment by andyi2it** [comment]
/close
Closing this as it has become stale and the issue could not be replicated.
