### ISSUE TITLE
Install through Hack method

### ISSUE THREAD

**Issue by asok-mirror** [kserve/kserve#1762]
/kind bug

Facing issue during the installation of isitio. Please help here. 

**What steps did you take and what happened:**
![image](https://user-images.githubusercontent.com/1701130/129105000-a5de9ad0-115c-4a1b-87a3-0eaa90098119.png)

Background: 

I am using wsl in windows with 8gb space and 4 cores. 

![image](https://user-images.githubusercontent.com/1701130/129104829-141d90e0-0578-4c4a-94b0-a826723fad2d.png)

**What did you expect to happen:**

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

**Environment:**
as per the config given in the quick install 
running ubuntu through wsl2

**Comment by yuzisun** [comment]
@asok-mirror Please check the istio ingress gateway pod logs, looks like the gateway pod is not in ready state.

**Comment by asok-mirror** [comment]
Not sure, what's going on. When I install them individually it seems to work. but through the quick install script, it didn't :(  Will investigate later on this. 

update : 

    After trying to explore KFServe for two weeks without much progress, I ended up using the Prometheus FAST API client to collect the metrics and integrated them with the custom metrics dashboard on grafana.

**Comment by yuzisun** [comment]
@asok-mirror this seems to be the Istio/Kubernetes [version compatibility](https://kserve.github.io/website/0.7/admin/serverless/) issue, should be fixed in the quick install now.
