### ISSUE TITLE
TrainedModel not able to download models from GCS

### ISSUE THREAD

**Issue by swapkh91** [kserve/kserve#1812]
I have tried the MMS [example](https://github.com/kserve/kserve/tree/master/docs/samples/multimodelserving/triton) for triton and it was working

Now I'm trying to load my own models as `TrainedModel` CR, just like in example but the models are not being downloaded from GCS due to access issue. 

Logs:
```
{"level":"info","ts":1632402209.4004538,"logger":"fallback-logger","caller":"agent/watcher.go:89","msg":"Start to watch model config event"}
{"level":"info","ts":1632402209.4005527,"logger":"fallback-logger","caller":"agent/watcher.go:127","msg":"Watching /mnt/data/models.json"}
{"level":"info","ts":1632402360.0603712,"logger":"fallback-logger","caller":"agent/watcher.go:103","msg":"Processing event \"/mnt/configs/..data\": CREATE"}
{"level":"info","ts":1632402360.0607443,"logger":"fallback-logger","caller":"agent/watcher.go:173","msg":"adding model densenetonnx"}
{"level":"info","ts":1632402360.0608056,"logger":"fallback-logger","caller":"agent/puller.go:136","msg":"Worker is started for densenetonnx"}
{"level":"info","ts":1632402360.0608337,"logger":"fallback-logger","caller":"agent/puller.go:144","msg":"Downloading model from gs://kfserving-custom-models/model_repo/densenetonnx"}
{"level":"info","ts":1632402360.060902,"logger":"fallback-logger","caller":"agent/downloader.go:48","msg":"Downloading gs://kfserving-custom-models/model_repo/densenetonnx to model dir /mnt/models"}
{"level":"error","ts":1632402360.5230613,"logger":"fallback-logger","caller":"agent/puller.go:149","msg":"Failed to download model densenetonnx with err failed to download model: failed to download model: unable to download object/s because: an error occurred while iterating: googleapi: Error 401: Anonymous caller does not have storage.objects.list access to the Google Cloud Storage bucket., required","stacktrace":"github.com/kubeflow/kfserving/pkg/agent.(*Puller).modelProcessor\n\t/go/src/github.com/kubeflow/kfserving/pkg/agent/puller.go:149"}
{"level":"info","ts":1632402360.523168,"logger":"fallback-logger","caller":"agent/puller.go:129","msg":"completion event for model densenetonnx, in flight ops 0"}
```

If I create a normal `InferenceService` with `predictor` as `triton` and `storageUri` same as above, then it works fine. 

The example worked because those buckets are public.

Also, the TM shows as READY
```
kubectl get tm densenetonnx -n kfserving-test

NAME           URL                                                                         READY   AGE
densenetonnx   http://triton-mms.kfserving-test.example.com/v2/models/densenetonnx/infer   True    5m33s
```

```
kubectl get tm densenetonnx -n kfserving-test -oyaml

apiVersion: serving.kubeflow.org/v1alpha1
kind: TrainedModel
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"serving.kubeflow.org/v1alpha1","kind":"TrainedModel","metadata":{"annotations":{},"name":"densenetonnx","namespace":"kfserving-test"},"spec":{"inferenceService":"triton-mms","model":{"framework":"onnx","memory":"1Gi","storageUri":"gs://kfserving-custom-models/model_repo/densenetonnx"}}}
  creationTimestamp: "2021-09-23T14:45:42Z"
  finalizers:
  - trainedmodel.finalizer
  generation: 1
  labels:
    inferenceservice: triton-mms
    serving.kubeflow.org/trainedmodel-allocated: triton-mms
  name: densenetonnx
  namespace: kfserving-test
  resourceVersion: "103920"
  uid: 25b6d287-9367-4137-9211-62f8c4f8ff2d
spec:
  inferenceService: triton-mms
  model:
    framework: onnx
    memory: 1Gi
    storageUri: gs://kfserving-custom-models/model_repo
status:
  address:
    url: http://triton-mms.kfserving-test.svc.cluster.local/v2/models/densenetonnx/infer
  conditions:
  - lastTransitionTime: "2021-09-23T14:45:43Z"
    status: "True"
    type: FrameworkSupported
  - lastTransitionTime: "2021-09-23T14:45:43Z"
    status: "True"
    type: InferenceServiceReady
  - lastTransitionTime: "2021-09-23T14:45:43Z"
    status: "True"
    type: IsMMSPredictor
  - lastTransitionTime: "2021-09-23T14:45:43Z"
    status: "True"
    type: MemoryResourceAvailable
  - lastTransitionTime: "2021-09-23T14:45:43Z"
    status: "True"
    type: Ready
  url: http://triton-mms.kfserving-test.example.com/v2/models/densenetonnx/infer
```

**Comment by swartz-k** [comment]
```Error 401: Anonymous caller does not have storage.objects.list access to the Google Cloud Storage bucket., required","stacktrace":"github.com/kubeflow/kfserving/pkg/agent.(*Puller).modelProcessor\n\t/go/src/github.com/kubeflow/kfserving/pkg/agent/puller.go:149"}```

looks like  Anonymous cannot access`gs://kfserving-custom-models/model_repo`

**Comment by swapkh91** [comment]
@yuzisun any idea about this?

**Comment by oguzhanoyan** [comment]
It's because you should define your auth service account key in secret, then annotate it in inferenceservice.  I followed these steps and managed to access private GCS; 

1. Rename downloaded auth key as follow; gcloud-application-credentials.json
2. Create secret kubectl create secret generic my-secret --from-file=gcloud-application-credentials.json
3. Edit inferenceservice-config configmap in kubeflow namespace and add some of the fields into credentials tab
3.1. add "storageSpecSecretName": "my-secret"
3.2. add "storageSecretNameAnnotation": "serving.kserve.io/storageSecretName"
4. Edit isvc and add annotation: serving.kserve.io/storageSecretName: my-secret

Now you should able to fetch models from private GCS.

**Comment by yc2984** [comment]
> It's because you should define your auth service account key in secret, then annotate it in inferenceservice. I followed these steps and managed to access private GCS;
> 
> 1. Rename downloaded auth key as follow; gcloud-application-credentials.json
> 2. Create secret kubectl create secret generic my-secret --from-file=gcloud-application-credentials.json
> 3. Edit inferenceservice-config configmap in kubeflow namespace and add some of the fields into credentials tab
>    3.1. add "storageSpecSecretName": "my-secret"
>    3.2. add "storageSecretNameAnnotation": "serving.kserve.io/storageSecretName"
> 4. Edit isvc and add annotation: serving.kserve.io/storageSecretName: my-secret
> 
> Now you should able to fetch models from private GCS.

Do you know why the key needs to be called gcloud-application-credentials.json? Otherwise it wouldn't work. 

Maybe it's because this the configMap, there is this line:
`"gcsCredentialFileName": "gcloud-application-credentials.json" `

```
 credentials:                                                                                                                          │
│ ----                                                                                                                                  │
│ {                                                                                                                                     │
│    "storageSpecSecretName": "storage-config",                                                                                         │
│    "storageSecretNameAnnotation": "serving.kserve.io/secretName",                                                                     │
│    "gcs": {                                                                                                                           │
│        "gcsCredentialFileName": "gcloud-application-credentials.json"                                                                 │
│    },                                                                                                                                 │
│    "s3": {                                                                                                                            │
│        "s3AccessKeyIDName": "AWS_ACCESS_KEY_ID",                                                                                      │
│        "s3SecretAccessKeyName": "AWS_SECRET_ACCESS_KEY",                                                                              │
│        "s3Endpoint": "",                                                                                                              │
│        "s3UseHttps": "",                                                                                                              │
│        "s3Region": "",                                                                                                                │
│        "s3VerifySSL": "",                                                                                                             │
│        "s3UseVirtualBucket": "",                                                                                                      │
│        "s3UseAnonymousCredential": "",                                                                                                │
│        "s3CABundle": ""                                                                                                               │
│    }                                                                                                                                  │
│ }   
```

**Comment by sivanantha321** [comment]
> > It's because you should define your auth service account key in secret, then annotate it in inferenceservice. I followed these steps and managed to access private GCS;
> > 
> > 1. Rename downloaded auth key as follow; gcloud-application-credentials.json
> > 2. Create secret kubectl create secret generic my-secret --from-file=gcloud-application-credentials.json
> > 3. Edit inferenceservice-config configmap in kubeflow namespace and add some of the fields into credentials tab
> >    3.1. add "storageSpecSecretName": "my-secret"
> >    3.2. add "storageSecretNameAnnotation": "serving.kserve.io/storageSecretName"
> > 4. Edit isvc and add annotation: serving.kserve.io/storageSecretName: my-secret
> > 
> > Now you should able to fetch models from private GCS.
> 
> Do you know why the key needs to be called gcloud-application-credentials.json? Otherwise it wouldn't work.
> 
> Maybe it's because this the configMap, there is this line: `"gcsCredentialFileName": "gcloud-application-credentials.json" `
> 
> ```
>  credentials:                                                                                                                          │
> │ ----                                                                                                                                  │
> │ {                                                                                                                                     │
> │    "storageSpecSecretName": "storage-config",                                                                                         │
> │    "storageSecretNameAnnotation": "serving.kserve.io/secretName",                                                                     │
> │    "gcs": {                                                                                                                           │
> │        "gcsCredentialFileName": "gcloud-application-credentials.json"                                                                 │
> │    },                                                                                                                                 │
> │    "s3": {                                                                                                                            │
> │        "s3AccessKeyIDName": "AWS_ACCESS_KEY_ID",                                                                                      │
> │        "s3SecretAccessKeyName": "AWS_SECRET_ACCESS_KEY",                                                                              │
> │        "s3Endpoint": "",                                                                                                              │
> │        "s3UseHttps": "",                                                                                                              │
> │        "s3Region": "",                                                                                                                │
> │        "s3VerifySSL": "",                                                                                                             │
> │        "s3UseVirtualBucket": "",                                                                                                      │
> │        "s3UseAnonymousCredential": "",                                                                                                │
> │        "s3CABundle": ""                                                                                                               │
> │    }                                                                                                                                  │
> │ }   
> ```

Yes, You can change the gcs credential name by editing the `inferenceservice-config` configmap.
