### ISSUE TITLE
Kubeflow pipeline integration for KServe

### ISSUE THREAD

**Issue by yuzisun** [kserve/kserve#1829]
/kind feature

**Describe the solution you'd like**
Create a new `KServe` component for Kubeflow Pipeline with newly released `kserve` SDK similar to [`KFServing` component](https://github.com/kubeflow/pipelines/blob/dec03067ca1f89f1ca23c7397830d60201448fa6/components/kubeflow/kfserving/README.md)

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

**Comment by Tomcli** [comment]
There's a WIP PR on it https://github.com/kubeflow/pipelines/pull/6716

**Comment by markwinter** [comment]
I made a PR to add a KServe component https://github.com/kubeflow/pipelines/pull/6881

It doesn't change existing KFServing stuff which is still used in current Kubeflow release.

Instead I just made a separate new component.

**Comment by markwinter** [comment]
https://github.com/kubeflow/pipelines/pull/6881#issuecomment-982297924

Any preference for this?

**Comment by Tomcli** [comment]
@markwinter Currently, we are not running any CI for this component. You can put KServe as the organization and keep the version the same as KServe. 

Organization: KServe
Organization Description: KServe is a highly scalable and standards based Model Inference Platform on Kubernetes for Trusted AI
Version information: 0.7.0
Test status: Manual Tests.
Owners information: Animesh Singh (animeshsingh) - IBM, singhan@us.ibm.com

For the CI tests, not sure can we add a cronjob Github action in KServe to pull the code from kubeflow/pipelines.

**Comment by markwinter** [comment]
The component has been merged now

**Comment by yuzisun** [comment]
Thanks @markwinter !!
