### ISSUE TITLE
Tensorflow serving can not find base path

### ISSUE THREAD

**Issue by wenyangchou** [kserve/kserve#1835]
/kind bug

**What steps did you take and what happened:**
[A clear and concise description of what the bug is.]
`apiVersion: "serving.kubeflow.org/v1alpha2"
kind: "InferenceService"
metadata:
  name: "flower-sample"
spec:
  default:
    predictor:
      tensorflow:
        storageUri: "gs://kfserving-samples/models/tensorflow/flowers"
`

**What did you expect to happen:**
the pod ready 3/3

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]
the pod ready status 2/3
Log the pod's container
`kc logs flower-sample-predictor-default-zwxch-deployment-957df6c85-ct98h -c kfserving-container`

the log is shown below
`2021-09-27 07:49:49.922163: E tensorflow_serving/sources/storage_path/file_system_storage_path_source.cc:362] FileSystemStoragePathSource encountered a filesystem access error: Could not find base path /mnt/models for servable flower-sample`

**Environment:**

- Istio Version:
- Knative Version:
- KFServing Version:
- Kubeflow version:
- Kfdef:[k8s_istio/istio_dex/gcp_basic_auth/gcp_iap/aws/aws_cognito/ibm]
- Minikube version:
- Kubernetes version: (use `kubectl version`):
- OS (e.g. from `/etc/os-release`):

**Comment by yuzisun** [comment]
@wenyangchou which namespace you deployed your model to?

**Comment by wenyangchou** [comment]
> @wenyangchou which namespace you deployed your model to?

my default namespace is kubeflow . I have tried sklearn , it works while tensorflow  does not work properly

**Comment by yuzisun** [comment]
@wenyangchou we do not support deploying in kubeflow namespace , see the warning in the [main readme](https://github.com/kserve/kserve/tree/release-0.6#kfserving-with-kubeflow-installation)
