### ISSUE TITLE
no matches for kind "InferenceService" in version "serving.kserve.io/v1beta1"

### ISSUE THREAD

**Issue by saisowjanyab** [kserve/kserve#1843]
/kind bug

**What steps did you take and what happened:**
[A clear and concise description of what the bug is.]
I installed kfserving on aws eks using the installation guide and also verified the installation. When i try deploying my ML model as an inference service, it shows an error that there are no matches for kind "InferenceService" in version "serving.kserve.io/v1beta1". But the documentation for the apiVersion serving.kserve.io/v1beta1 lists InferenceService in the resources . Please refer to https://github.com/kserve/website/blob/main/docs/reference/api.md

**What did you expect to happen:**
The inference service get deployed returning a URL as service host

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]
It worked well when the apiVersion was "serving.kubeflow.org/v1beta1".

**Environment:**

- Istio Version:
- Knative Version:
- KFServing Version:
- Kubeflow version:
- Kfdef:[k8s_istio/istio_dex/gcp_basic_auth/gcp_iap/aws/aws_cognito/ibm]
- Minikube version:
- Kubernetes version: (use `kubectl version`):
- OS (e.g. from `/etc/os-release`):

**Comment by yuzisun** [comment]
@saisowjanyab The API group has been changed to `serving.kserve.io` in the upcoming release and the website is built for kserve. For old kfserving doc please help refer to the [previous release doc](https://github.com/kserve/kserve/tree/release-0.6/docs/samples)
