### ISSUE TITLE
MMS agent fails to start in raw deployment mode due to dependency on Knative queue-proxy env vars

### ISSUE THREAD

**Issue by cmaddalozzo** [kserve/kserve#1857]
/kind bug

**What steps did you take and what happened:**

Ensure default deployment mode is set to `RawDeployment` in the inferenceservice-config config map.

Create a multi-model inference service:
```
kubectl apply -f docs/samples/multimodelserving/triton/multi_model_triton.yaml 
```
The agent fails to start due to missing environment variables.

Agent logs:
```
required key CONTAINER_CONCURRENCY missing value
```

**What did you expect to happen:**

The agent should start up without errors.

**Anything else you would like to add:**

The environment variables are added by the agent injector [here](https://github.com/kserve/kserve/blob/638fff64d833e3c5b378b16eda12d5e131417541/pkg/webhook/admission/pod/agent_injector.go#L224).

**Environment:**

- Istio Version: N/A
- Knative Version: N/A
- KFServing Version: [master](https://github.com/kserve/kserve/tree/829db48f25baffba9c26771716e68629302af7c5)
- Kubeflow version: N/A
- Kfdef: N/A
- Minikube version: v1.23.2
- Kubernetes version: v1.20.11
- OS: macOS 11.5.2

**Comment by Iamlovingit** [comment]
Hi @cmaddalozzo, can you paste kfserve's log about `triton-mms`
