### ISSUE TITLE
kfserving inference service state shows Ready=True when pods are in CrashLoopBackoff state

### ISSUE THREAD

**Issue by suhaskashyapr** [kserve/kserve#1859]
/kind bug

**What steps did you take and what happened:**
[A clear and concise description of what the bug is.]

Inference service resource was created as the deployment was created successfully with 1 pod as shown below:
k get pods -A | grep d5ce6b94087b41
`xxx-namespace-xxx     d5ce6b94087b41-predictor-default-vcwhr-deployment-xxxx   3/3     Running              0          11h`

k get deploy -A | grep d5ce6b94087b41
`xxx-namespace-xxx    d5ce6b94087b41-predictor-default-vcwhr-deployment     1/1     1            1           20d`

k get isvc -A | grep d5ce6b94087b41
`xxx-namespace-xxx          d5ce6b94087b41     http://d5ce6b94087b41-xxx-namespace-xxx-xxx.com       True           100                              d5ce6b94087b41-predictor-default-vcwhr    20d`

Due to some scenario, the deployment got restarted. But this time, as there was some problem with the model download storage-initialisation phase, pod got stuck with CrashLoopBackoff state.

Below is the current state of the resources:
k get pods -A | grep d5ce6b94087b41
`xxx-namespace-xxx        d5ce6b94087b41-predictor-default-vcwhr-deployment-oooo    0/3    Init:CrashLoopBackOff   356        40m46s`

k get deploy -A | grep d5ce6b94087b41
`xxx-namespace-xxx          d5ce6b94087b41-predictor-default-vcwhr-deployment     0/1     1            0           20d`

k get isvc -A | grep d5ce6b94087b41
`xxx-namespace-xxx          d5ce6b94087b41     http://d5ce6b94087b41-xxx-namespace-xxx-xxx.com       True           100                              d5ce6b94087b41-predictor-default-vcwhr    20d`

storage-initialiser error:
`Traceback (most recent call last):
  File "./scripts/initializer-entrypoint", line 14, in <module>
    kfserving.Storage.download(src_uri, dest_path)
  File "/usr/lib/python3.6/site-packages/kfserving/storage.py", line 62, in download
    Storage._download_s3(uri, out_dir)
  File "/usr/lib/python3.6/site-packages/kfserving/storage.py", line 101, in _download_s3
    The path or model %s does not exist." % (uri))
RuntimeError: Failed to fetch model. The path or model s3://bucket-name/test_data/gender does not exist.`

**What did you expect to happen:**
The inference service should reflect the similar status i.e, it should be Ready=False as there are no pods in Running state to serve the requests.

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]
Could reproduce the scenario.
Step1: Create a deployment with a model available in the object store s3. Deployment/Pod/InferenceService are in Running and Ready=True state.
Step2: Delete the model from the object store that is referenced by the deployment.
Step3: Kill the pod and the new pod gets stuck with CrashLoopBackoff state. InferenceService is still in Ready=True state.

No logs were observed in kfserving-controller during the deployment restart and the new pod was trying to come up. Is this an expected behaviour as the Ready=True state is misleading though the deployment/pods are not in Running state?

**Environment:**

- Istio Version: v1.9.7
- Knative Version: v0.18.0
- KFServing Version: v0.5.1
- KFserving-storage-initializer: v0.5.1

- Kubernetes version: (use `kubectl version`):
`Client Version: version.Info{Major:"1", Minor:"20", GitVersion:"v1.20.2", GitCommit:"faecb196815e248d3ecfb03c680a4507229c2a56", GitTreeState:"clean", BuildDate:"2021-01-13T13:28:09Z", GoVersion:"go1.15.5", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"20", GitVersion:"v1.20.9", GitCommit:"7a576bc3935a6b555e33346fd73ad77c925e9e4a", GitTreeState:"clean", BuildDate:"2021-07-15T20:56:38Z", GoVersion:"go1.15.14", Compiler:"gc", Platform:"linux/amd64"}`

**Comment by ssamora** [comment]
I'm still seeing this behavior in the latest KServe version.
Using KServe 0.12.0 and Knative 1.13.1. 
Pod enters CrashLoopBackoff and InferenceService does not reflect any of it. 
Any news on this bug?
