### ISSUE TITLE
Fix serving.kubeflow.org annotations in docs/samples

### ISSUE THREAD

**Issue by bartgras** [kserve/kserve#1869]
I've noticed that some `docs/samples` still use in `metadata.annotations` the `serving.kubeflow.org` instead of `serving.kserve.org`. See this [example](https://github.com/kserve/kserve/blob/master/docs/samples/kafka/s3_secret.yaml).
To save debugging time for others migrating from KFserving, I could create PR that fixes that.

**Comment by yuzisun** [comment]
@bartgras The documentation is moved to website repo here https://github.com/kserve/website/blob/main/docs/modelserving/kafka/s3-secret.yaml, but feel free to send a PR to fix in kserve repo as well.
