### ISSUE TITLE
`HTTPHandler` converts non ASCII characters to unicode escape sequences

### ISSUE THREAD

**Issue by Mehrad0711** [kserve/kserve#1871]
I'm using KFserving to setup a translation API.
I noticed [this method](https://github.com/tornadoweb/tornado/blob/1db5b45918da8303d2c6958ee03dbbd5dc2709e9/tornado/escape.py#L67) method is called from tornado (when using PredictHandler) before writing outputs in the buffer. Since "ensure_ascii=False" flag is not used when dumping, non-ascii characters are converted to unicode escape sequences instead of remaining intact. 
Was wondering if this could be fixed?
A possible solution is overwriting RequestHandler's [write method](https://github.com/tornadoweb/tornado/blob/790715ae0f0a30b9ee830bfee75bb7fa4c4ec2f6/tornado/web.py#L812) in its child class [here](https://github.com/kserve/kserve/blob/638fff64d833e3c5b378b16eda12d5e131417541/python/kserve/kserve/handlers/http.py#L28).

**Comment by sivanantha321** [comment]
This issue is no longer valid. KServe no longer uses tornado as the app server.
