### ISSUE TITLE
Custom KF server sample Readme link broken

### ISSUE THREAD

**Issue by rehanrishi21** [kserve/kserve#1875]
/kind bug

**What steps did you take and what happened:**
[A clear and concise description of what the bug is.]
Go to: https://github.com/kserve/kserve/tree/master/docs/samples
Click on Custom model server redirects to: https://github.com/kserve/kserve/blob/master/docs/samples/v1alpha2/custom/kfserving-custom-model
Result: Page not found

**Comment by yuzisun** [comment]
fixed the link to https://github.com/kserve/kserve/tree/master/docs/samples/v1beta1/custom/custom_model now.
