### ISSUE TITLE
New revision created at every redeployment of InferenceService

### ISSUE THREAD

**Issue by pratikgujjar** [kserve/kserve#1885]
/kind question
**What steps did you take and what happened:**
Deployed a custom isvc on a kubernetes cluster. Every re-deployment creates a new revision of the isvc. 

**What did you expect to happen:**
Update the existing isvc or delete the previous revision while retaining the latest.

**Anything else you would like to add:**
Also tried configuring the knative-serving garbage collector `config-gc` to remove the unused revisions. They still exist. 

```
{
	"max-non-active-revisions": "disabled",
	"min-non-active-revisions": "0",
	"retain-since-create-time": "disabled",
	"retain-since-last-active-time": "disabled"
}
```

**Environment:**

- Istio Version: 1.9.0
- Knative Version:v0.22.0
- KFServing Version:v0.7.0.0
- Kubeflow version:
- Kfdef:[k8s_istio/istio_dex/gcp_basic_auth/gcp_iap/aws/aws_cognito/ibm]
- Minikube version:
- Kubernetes version: (use `kubectl version`): v1.19.3
- OS (e.g. from `/etc/os-release`):

**Comment by markwinter** [comment]
We use the following in `config-gc` and it works correctly. Inactive revisions get cleaned up immediately when no longer used. 

```YAML
max-non-active-revisions: "0"
min-non-active-revisions: "0"
retain-since-create-time: disabled
retain-since-last-active-time: disabled
```

To trigger removal right away after updating the configmap, you can just create a new revision and the gc will kick in at that point.

Did you make sure it's not set in the `_example` block in the configmap by accident?

**Comment by pratikgujjar** [comment]
Thanks @markwinter. The change for `max-non-active-revisions: "disabled"` to `max-non-active-revisions: "0"` did the trick.
