### ISSUE TITLE
Update AIF explainer example with the latest knative API. 

### ISSUE THREAD

**Issue by Tomcli** [kserve/kserve#1886]
/kind bug

**What steps did you take and what happened:**
Since KServe is updated with a later version of knative. Knative service v1alpha1 is not longer supported, so we need to update the AIF example to use the latest knative API.

**What did you expect to happen:**

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

**Environment:**

- Istio Version:
- Knative Version:
- KFServing Version:
- Kubeflow version:
- Kfdef:[k8s_istio/istio_dex/gcp_basic_auth/gcp_iap/aws/aws_cognito/ibm]
- Minikube version:
- Kubernetes version: (use `kubectl version`):
- OS (e.g. from `/etc/os-release`):

**Comment by yuzisun** [comment]
@Tomcli Let's move the doc issue to the website repo.
