### ISSUE TITLE
How to disable torchserve MODEL_LOG

### ISSUE THREAD

**Issue by yurkoff-mv** [kserve/kserve#1889]
Hello,
Сan i turn off the log `MODEL_LOG - The Response of KFServing ...` in Inference Service?
It's that it can be very long, and this slows down the model inference.

**Comment by yuzisun** [comment]
@yurkoff-mv Where do you see this coming from?

**Comment by yurkoff-mv** [comment]
> @yurkoff-mv Where do you see this coming from?
`kubectl logs -n default {POD} -c kfserving-container`

I'm trying to to understend why the output of KFServing is noticeably slower than from a simple TorchServe (although I use GRPC there).
In general, there is really a lack of GRPC when using Torsnserve in the Inferenc Service.

**Comment by yuzisun** [comment]
@yurkoff-mv gRPC support is added in https://github.com/kserve/kserve/pull/1870, the log is actually from torchserve side. https://github.com/pytorch/serve/blob/f0da8d2714628cb5de0c6eaa3ac0448a6b226640/ts/torch_handler/request_envelope/kfserving.py#L52. @jagadeeshi2i Can we turn the logging level to debug?

**Comment by jagadeeshi2i** [comment]
@yurkoff-mv you could enable async logging https://github.com/pytorch/serve/blob/master/docs/logging.md#enable-asynchronous-logging

**Comment by yurkoff-mv** [comment]
Thank you very much for your advice. I will try this.

**Comment by jagadeeshi2i** [comment]
https://github.com/pytorch/serve/pull/1396

**Comment by yuzisun** [comment]
This has been fixed in kfs-torchserve 0.5.3 and released with kserve 0.8
