### ISSUE TITLE
404 error : model name does not exist

### ISSUE THREAD

**Issue by vaporpin** [kserve/kserve#1895]
/kind bug
Followed the instructions here https://kserve.github.io/website/get_started/first_isvc/ and the Inference Service worked. Then I deleted this inference service. 

However when I created my own model and serialised it, model.joblib, I
got a 404 error that model name does not exist. Please advise.

< HTTP/1.1 404 Not Found
< content-length: 139
< content-type: text/html; charset=UTF-8
< date: Thu, 04 Nov 2021 12:27:53 GMT
< server: istio-envoy
< x-envoy-upstream-service-time: 24

<html><title>404: Model with name sklearn-iris does not exist.</title><body>404: Model with name sklearn-iris does not exist.</body></html>* Closing connection 0

**What steps did you take and what happened:**
from sklearn import svm
from sklearn import datasets
from joblib import dump
iris = datasets.load_iris()
X, y = iris.data, iris.target
clf = svm.SVC(gamma='scale')
clf.fit(X, y)
dump(clf, 'model.joblib')

I created the above joblib model and uploaded to gcs at path gs://testpubllish0411221/mnt/models

Next, create an InferenceService : 
apiVersion: "serving.kserve.io/v1beta1"
kind: "InferenceService"
metadata:
  name: "sklearn-iris"
spec:
  predictor:
    sklearn:
      storageUri: "gs://testpubllish0411221/mnt/models"

Check that inference service is ready :
NAME           URL                                           READY   PREV   LATEST   PREVROLLEDOUTREVISION   LATESTREADYREVISION                    AGE
sklearn-iris   http://sklearn-iris.kserve-test.example.com   True           100                              sklearn-iris-predictor-default-00001   5m24s

Get Prediction:
curl -v -H "Host: ${SERVICE_HOSTNAME}" http://${INGRESS_HOST}:${INGRESS_PORT}/v1/models/sklearn-iris:predict -d @./iris-input.json

Got 404 error : 
< HTTP/1.1 404 Not Found
< content-length: 139
< content-type: text/html; charset=UTF-8
< date: Thu, 04 Nov 2021 12:27:53 GMT
< server: istio-envoy
< x-envoy-upstream-service-time: 24

<html><title>404: Model with name sklearn-iris does not exist.</title><body>404: Model with name sklearn-iris does not exist.</body></html>* Closing connection 0

**Comment by tidunguyen** [comment]
Why is this closed? I still encounter this issue. Is there any workaround?

**Comment by abhisheksinghblr** [comment]
how was it fixed ? any clue ? Thanks in advance
