### ISSUE TITLE
RawDeployment using latest from master complains about knative missing

### ISSUE THREAD

**Issue by edi-bice-by** [kserve/kserve#1907]
/kind bug

Deployed from master commit 45c3c2cf187b5255eb918fa365606f20d0e906d2

MD1-1029014MBP:kserve edibice$ ./hack/quick_install.sh -r
...
Downloading istio-1.10.3 from https://github.com/istio/istio/releases/download/1.10.3/istio-1.10.3-osx.tar.gz ...
Istio 1.10.3 Download Complete!
Istio has been successfully downloaded into the istio-1.10.3 folder on your system.

...

Need more information? Visit https://istio.io/latest/docs/setup/install/ 
namespace/istio-system created
✔ Istio core installed                                                                                   
✔ Istiod installed                                                                                       
✔ Egress gateways installed                                                                              
✔ Ingress gateways installed                                                                             
✔ Installation complete  

**What did you expect to happen:**

Tried to create the sample moviesentiment inference service

MD1-1029014MBP:moviesentiment edibice$ kubectl create -f moviesentiment.yaml
Error from server (InternalError): error when creating "moviesentiment.yaml": Internal error occurred: failed calling webhook "inferenceservice.kserve-webhook-server.defaulter": Post "https://kserve-webhook-server-service.kserve.svc:443/mutate-serving-kserve-io-v1beta1-inferenceservice?timeout=10s": dial tcp 10.96.109.255:443: connect: connection refused

**Anything else you would like to add:**

MD1-1029014MBP:gcp-iap edibice$ kubectl logs kserve-controller-manager-0 -n kserve -c manager
{"level":"info","ts":1636646678.1996138,"logger":"entrypoint","msg":"Setting up client for manager"}
...
{"level":"error","ts":1636646682.2695243,"logger":"controller-runtime.source","msg":"if kind is a CRD, it should be installed before calling Start","kind":"Service.serving.knative.dev","error":"no matches for kind \"Service\" in version \"serving.knative.dev/v1\"","stacktrace":"github.com/go-logr/zapr.(*zapLogger).Error\n\t/go/pkg/mod/github.com/go-logr/zapr@v0.2.0/zapr.go:132\nsigs.k8s.io/controller-runtime/pkg/source.(*Kind).Start\n\t/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.7.0/pkg/source/source.go:117\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func1\n\t/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.7.0/pkg/internal/controller/controller.go:159\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start\n\t/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.7.0/pkg/internal/controller/controller.go:205\nsigs.k8s.io/controller-runtime/pkg/manager.(*controllerManager).startRunnable.func1\n\t/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.7.0/pkg/manager/internal.go:691"}
{"level":"info","ts":1636649817.1688964,"logger":"controller-runtime.webhook","msg":"shutting down webhook server"}
{"level":"error","ts":1636649817.1694896,"logger":"entrypoint","msg":"unable to run the manager","error":"no matches for kind \"Service\" in version \"serving.knative.dev/v1\"","stacktrace":"github.com/go-logr/zapr.(*zapLogger).Error\n\t/go/pkg/mod/github.com/go-logr/zapr@v0.2.0/zapr.go:132\nmain.main\n\t/go/src/github.com/kserve/kserve/cmd/manager/main.go:183\nruntime.main\n\t/usr/local/go/src/runtime/proc.go:203"}

**Comment by edi-bice-by** [comment]
Added annotation to isvc after spotting in the PR though same end result

```bash-5.1$ cat moviesentiment_raw.yaml
apiVersion: "serving.kserve.io/v1beta1"
kind: "InferenceService"
metadata:
  name: "moviesentiment"
  annotations:
    "serving.kserve.io/deploymentMode": "RawDeployment"
spec:
  predictor:
    minReplicas: 1
    sklearn:
      storageUri: "gs://seldon-models/sklearn/moviesentiment"
      resources:
        requests:
          cpu: 0.1
          memory: 1Gi                        
        limits:
          cpu: 1
          memory: 1Gi                        
  explainer:
    minReplicas: 1
    alibi:
      type: AnchorText
      resources:
        requests:
          cpu: 0.1
          memory: 6Gi            
        limits:
          memory: 6Gi```

**Comment by yuzisun** [comment]
@edi-bice-by I think you need to turn on the `RawDeployment` mode in the inference service configmap.

**Comment by edi-bice-by** [comment]
It seemed either/or from my understanding, sort of, globally or at the individual service. If one wanted globally for all future isvc one would change default in the configmap otherwise change in the isvc. 

I've been trying to edit the configmap using following but changes are not applied

kubectl edit configmap inferenceservice-config -n kserve

**Comment by edi-bice-by** [comment]
Okay, I now realize I was trying to add the deploy stanza but apparently there was one already there. Changed it from Serverless to RawDeployment had no effect either on new attempts to apply the moviesentiment isvc (both with and without the annotation).

**Comment by edi-bice-by** [comment]
I was about to delete kserve-controller-manager (in order to see if after restart it picked up the inferenceservice-config configmap changes) and noticed in its logs that it seems to have picked it up already. Was then able to apply the moviesentiment yaml (original not annotated with rawdeployment) successfully.
