### ISSUE TITLE
Even though path does not exist in s3, the storage initialiser container does not crush loop

### ISSUE THREAD

**Issue by daganida88** [kserve/kserve#1914]
/kind bug

**What steps did you take and what happened:**
[A clear and concise description of what the bug is.]
I am running two inference services using triton server, one on GCP and one on AWS.
My container is crushlooping because the path I provided in the model repository does not exist.
When I did the same steps in AWS, the storage initializer did not crush, and copied 0 models to the repository.
The triton container was up running serving 0 models.

**What did you expect to happen:**
The container to crush in case the model repository path I provided in S3 does not exist.
**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]
kfserving 0.6

**Environment:**

- Istio Version:
- Knative Version:
- KFServing Version:
- Kubeflow version:
- Kfdef:[k8s_istio/istio_dex/gcp_basic_auth/gcp_iap/aws/aws_cognito/ibm]
- Minikube version:
- Kubernetes version: (use `kubectl version`):
- OS (e.g. from `/etc/os-release`):

**Comment by tc360950** [comment]
@daganida88 This issue has been solved in version 0.7

**Comment by yuzisun** [comment]
Fixed in commit https://github.com/kserve/kserve/commit/3507c4611c8c92e86de64fee00b77e6ccf3e333a
