### ISSUE TITLE
Kuberflow running pipeline failed

### ISSUE THREAD

**Issue by skseo941229** [kserve/kserve#1921]
/kind bug
![image](https://user-images.githubusercontent.com/92812391/142697595-bf481625-455b-4708-88ee-3317d9d979c9.png)
![image](https://user-images.githubusercontent.com/92812391/142697641-a5b821b9-0743-4a5e-9883-e17e7e5e393b.png)

**What steps did you take and what happened:**
[A clear and concise description of what the bug is.]

I am following https://codelabs.developers.google.com/codelabs/cloud-kubeflow-minikf-kale#3 this tutorial on GCP minikf but I got above error.
I tried several time but it always gives this error.

**Comment by yuzisun** [comment]
@skseo941229 this is not a KServe issue right? Can you move to the pipeline repo?

**Comment by yuzisun** [comment]
@skseo941229 please help move the issue to the kubeflow pipeline repo
