### ISSUE TITLE
KServe CloudEvents infinite-loop using Knative Eventing Broker

### ISSUE THREAD

**Issue by shahar3012** [kserve/kserve#1923]
/kind bug

**What steps did you take and what happened:**
We're using Knative eventing `Broker` and `Trigger` with a filter for triggering the `PredictHandler` handler in a custom model server using KServe python library.
Currently, KServe python library sends the response CloudEvent with the same attributes from the original CloudEvent and there is no option to filter the response CloudEvent to avoid the **infinite-loop** of CloudEvents being sent to KServe from the `Broker`.

**What did you expect to happen:**
We expect to at least change the response CloudEvent `source` field to KServe instance name or some env variable.

**Anything else you would like to add:**
Line of problematic code: https://github.com/kserve/kserve/blob/464308defb7245110a3dbf255629d7f418bb9947/python/kserve/kserve/handlers/http.py#L99

**Environment:**

- Istio Version: 1.11.4
- Knative Version: 1.0
- KFServing Version: 0.7
- Kubeflow version: N/A
- Kfdef: N/A
- Minikube version: N/A
- Kubernetes version: (use `kubectl version`): 1.21.2
- OS (e.g. from `/etc/os-release`): Amazon Linux 2

**Comment by markwinter** [comment]
I've been using Knative Eventing and CloudEvents recently so I will take a look at this.

Could you give me an example of your `Trigger`? Are you filtering based on event type attribute?

And am I understanding correctly, your system looks something like this:

System A produces a CloudEvent (Event A) -> Broker -> Trigger -> KServe Model Server

And the response from KServe Model Server goes into the Broker as well?
And because KServe Model Server uses same attributes as original CloudEvent Event A, it is sent again by the Trigger

Is System A that produces the original event also a KServe Model Server?

If I understand correctly, then as you said just setting the source field would probably be enough.

**Comment by shahar3012** [comment]
> I've been using Knative Eventing and CloudEvents recently so I will take a look at this.
> 
> Could you give me an example of your `Trigger`? Are you filtering based on event type attribute?
> 
> And am I understanding correctly, your system looks something like this:
> 
> System A produces a CloudEvent (Event A) -> Broker -> Trigger -> KServe Model Server
> 
> And the response from KServe Model Server goes into the Broker as well? And because KServe Model Server uses the same attributes as original CloudEvent Event A, it is sent again by the Trigger
> 
> Is System A that produces the original event also a KServe Model Server?
> 
> If I understand correctly, then as you said just setting the source field would probably be enough.

1. Yes, I'm filtering based on the event type attribute. I would like to use the source attribute as well to differentiate between request and response, but as I've mentioned it's not implemented that way right now.
2. You're right, the response goes to the Broker as part of the request-response option of Knative eventing (without a trigger for the response).
3. However, currently we're making a request directly to KServe Model Server in order to avoid the problem, and just using a Trigger for `org.kubeflow.serving.inference.response` for another service that recieves the model response.

I didn't mention it, but our process takes a couple of minutes to complete, so it's vital to be able to run KServe inferencing in an async way.

4. System A is not a KServe Model Server.

If we could send the request to the Broker, use a Trigger with a destination of a KServe Model Server and then get the response back or keep using another Trigger with the logger model response it would be more ideal.

**Comment by markwinter** [comment]
@shahar3012 
Okay thanks.
It should be included in the next KServe release hopefully

**Comment by markwinter** [comment]
@shahar3012 
Would something like this work for you?
https://github.com/markwinter/kserve/commit/c4884fa4fe74f415f34f25b8fef214d7511db2d8

**Comment by shahar3012** [comment]
@markwinter I think we should merge the override attributes (`type` and `source`) with the original CloudEvents attributes.

**Comment by markwinter** [comment]
@shahar3012 

I'm not sure about that. I think we should be creating a brand new event here (the event type is different after all), and a new event should have a different ID (every event should have a unique ID according to CloudEvent spec) and an updated timestamp.

**Comment by shahar3012** [comment]
@markwinter I agree. 
I wanted to support CloudEvents extensions if they've been used in the original CloudEvent. Do you think we should ignore them?
Sometimes it's useful to have additional information sent in the request to also appear in the response event.

I suggest we set the `source` attribute value to the KFModel name.

**Comment by markwinter** [comment]
@shahar3012 
Including the KFModel name in the `source` seems like a good idea.
I'll also make `type` `source` configurable with env vars.
And probably an env var to merge attributes if desired (except id, timestamp, source, type)

I'll make some changes, fix the tests and create a PR soon.

**Comment by markwinter** [comment]
@shahar3012 
I made a PR here https://github.com/kserve/kserve/pull/1934
