### ISSUE TITLE
s3-verifyssl not work as kserve use boto?if not, then how can i inject my ca-bundle to storage-initializer

### ISSUE THREAD

**Issue by motocoder-cn** [kserve/kserve#1935]
/kind bug

**What steps did you take and what happened:**
minio with self signed cert
try use `s3-verifyssl=0`, but not work,
see some issues explain this, may because kserve change from minio to boto `S3_VERIFY_SSL` env not work anymore

then i found `s3-cabundle` with env `AWS_CA_BUNDLE` that work for boto [https://boto3.amazonaws.com/v1/documentation/api/latest/guide/configuration.html](url)

but how do i inject my ca-bundle to storage-initializer?

**What did you expect to happen:**
skip cert verify or inject ca-bundle to storage-initializer to verify cert

**Comment by motocoder-cn** [comment]
one way is to rebuild storage-initializer docker image? any other way to inject ca-bundle in runtime not in build?

**Comment by yuzisun** [comment]
@ZhengJuCn I think [this PR](https://github.com/kserve/kserve/pull/1780/files) fixes this, it is available in KServe 0.7 release

**Comment by motocoder-cn** [comment]
> @ZhengJuCn I think [this PR](https://github.com/kserve/kserve/pull/1780/files) fixes this, it is available in KServe 0.7 release

no，this only add ca-bundle but how to inject ca-bundle to container in runtime？

**Comment by yuzisun** [comment]
Looks like we are calling S3.Resouce high level API instead of s3.client which provides a way to skip ssl verification.

**Comment by umka1332** [comment]
@motocoder-cn `s3-cabundle: ""` should disable ssl check

**Comment by yuzisun** [comment]
consolidate to https://github.com/kserve/kserve/issues/3171
