### ISSUE TITLE
triton python_backend_stub can't be executed in kfserving-container, coz it has hardcoded read-only access

### ISSUE THREAD

**Issue by Alexejklim** [kserve/kserve#1938]
/kind bug

I use triton inference server with model in s3. But there is the problem to launch it coz of access rights.

```
bash: ... triton_python_backend_stub: Permission denied
bash: ... triton_python_backend_stub: cannot execute: Permission denied
```

Chmod doesn't help.
`chmod: changing permissions of '.../triton_python_backend_stub': Read-only file system`

Assume problem could be solved by adding possibility change access to kfserving-container.
https://github.com/kserve/kserve/blob/release-0.6/pkg/webhook/admission/pod/storage_initializer_injector.go#L198

This issue is also mentioned in the comments here.
https://github.com/triton-inference-server/python_backend/blob/r21.09/src/python.cc#L1133

- KFServing Version: v0.6.0-rc0
- tritonserver:21.09-py3

**Comment by sivanantha321** [comment]
The volume permission can be configured by providing annotation in the isvc. 
- https://github.com/kserve/kserve/pull/3885
