### ISSUE TITLE
Renaming: KFServer KFModelRepository KFModel ?

### ISSUE THREAD

**Issue by markwinter** [kserve/kserve#1947]
Currently in the Python SDK there are still some names relating to the old KFServing name:

`KFServer`
`KFModelRepository`
`KFModel`

Should these be renamed?

If so my suggestion is to remove the prefixes entirely as they're already part of the `KServe` package already.

So just `Server` `ModelRepository` `Model` would be sufficient I think.

Updating the names would also require:
- Updating the python model servers e.g. lgbserver, sklearnserver etc.
- Updating the documentation examples

**Comment by yuzisun** [comment]
Sounds good to me, how about Server -> ModelServer ?

**Comment by markwinter** [comment]
@yuzisun Yer that will be better I think

/assign

**Comment by markwinter** [comment]
Will update docs after christmas weekend
