### ISSUE TITLE
Istio 1.9.0 (as set by quick_install script) does not work with kubernetes cluster 1.21

### ISSUE THREAD

**Issue by molejnik-mergebit** [kserve/kserve#1952]
/kind bug

I have a Kubernetes cluster version 1.21 on GKE (Goole Kubernetes Engine). I'm using kfserving release 0.6.1 with quick install script. I'm getting the very same error as described here: https://issueexplorer.com/issue/kserve/kserve/1858

Prior to the cluster 1.21 it was working fine, now it does not. I suppose this is due to cluster 1.21 does not work with Istio 1.9.0 as specified in quick_install script (https://istio.io/latest/docs/releases/supported-releases/#support-status-of-istio-releases).

Is it possible to adjust quick_install script so kfserving works on cluster version 1.21 ?

**Environment:**

- Istio Version: 1.9.0
- Knative Version: 0.22.0
- KFServing Version: 0.6.1
- Kubernetes version: (use `kubectl version`): 1.21, GKE (Google Kubernetes Engine)

**Comment by yuzisun** [comment]
please see the [supported matrix ](https://kserve.github.io/website/admin/serverless/#recommended-version-matrix), Kubernetes 1.21 only works on Istio 1.10 above.

**Comment by molejnik-mergebit** [comment]
@yuzisun why did you close that issue?

I'm familiar with the matrix. I'm just saying that quick_install script mentions Istio 1.9.0, which does not work on Kubernetes 1.21. When I tried to simply change the version to 1.10 in the quick_install script, it did not install on the cluster. Maybe some additional changes are needed?
