### ISSUE TITLE
network overhead

### ISSUE THREAD

**Issue by caffeinism** [kserve/kserve#1957]
/kind bug
/kind feature
/kind question

**What steps did you take and what happened:**
When I sent a request with vegeta, I thought had sufficient capacity but not handled properly.

**What did you expect to happen:**
I draw diagram with network flow.
![diagram](https://i.ibb.co/yXggWnY/2021-12-21-11-17-30.png)
I think the part marked in red is network overhead. In that part, if the transformer and predictor communicate directly, the load will be reduced by half. Also, you can use a trick to reduce the network load by placing the predictor and transformer on the same node. 

Currently I am receiving a 640x640 rgb image as input. In order to reduce external traffic, png/base64 data was received by the transformer, but the load was still large due to the following problems. A 640x640 fp32 image is 3x640x640*4Byte = 4.7MB in bytes. However, when this image is transmitted as png/base64, it is resolved within a few hundred kilobytes. The use of a transformer is inevitable.

However, due to this problem, even if a transformer is used, the bandwidth of the internal network is greatly affected. I tried to solve this problem by putting the transformer and predictor on the same node, but it failed for this reason.

Are there any options to solve this?

**Environment:**

- Istio Version: 1.10
- Knative Version: 0.22.3
- KFServing Version: 0.7.0
- Kubeflow version: X
- Kfdef:[k8s_istio/istio_dex/gcp_basic_auth/gcp_iap/aws/aws_cognito/ibm] X
- Minikube version: X
- Kubernetes version: (use kubectl version): 1.18.5
- OS (e.g. from /etc/os-release): ubuntu 20.04.2

**Comment by yuzisun** [comment]
@caffeinism You are running the no-mesh mode, if you choose to run the mesh mode by injecting the istio sidecar in transformer and predictor then transformer can directly communicate with the predictor without going through the ingress gateway.

**Comment by caffeinism** [comment]
@yuzisun Could it be possible to use a transformer in the model mesh as well? I can't find that information.

**Comment by yuzisun** [comment]
Not right now, transformer is not supported for modelmesh but this is something on our roadmap. Transformer and predictor can also be placed in the same pod as multi containers or even same container, which predictor you are using?

**Comment by caffeinism** [comment]
@yuzisun I use triton predictor.

**Comment by caffeinism** [comment]
@yuzisun How can I use transformer in the same pod as multi containers?

**Comment by akakakakakaa** [comment]
Transformer and Predictor has own Pod by the inferenceservice spec. So, In my opinion, In kserve architecture, Can not use transformer and predictor in same pod.

But, To use preprocess and postprocess in triton, it seems that you need to use triton python backend and ensemble.

Please see [triton preprocessing example.](https://github.com/triton-inference-server/python_backend/tree/main/examples/preprocessing)

So, In order to implement triton ensemble using kfserving, it seems to be necessary to create 4 trainedModel: Preprocess TrainedModel, Postprocess TrainedModel, Model TrainedModel, and Ensemble TrainModel.

But it is hard to use and manage them...

**Comment by yuzisun** [comment]
> @yuzisun How can I use transformer in the same pod as multi containers?

There was a [WIP PR](https://github.com/kserve/kserve/pull/1415/files) you can see the [example](https://github.com/kserve/kserve/blob/e7b57cd80f05cc84912591a5988d0bc3c6b67c8b/docs/samples/v1beta1/transformer/torchserve_image_transformer/transformer_same_pod.yaml) here using localhost between transformer and predictor.

**Comment by caffeinism** [comment]
@yuzisun That's a nice feature! But more clearly, shouldn't it be implemented outside of predictor and transformer? As follows..
```
apiVersion: serving.kubeflow.org/v1beta1
kind: InferenceService
metadata:
  name: torchserve-transformer
spec:
  collocate: true
  predictor:
    containers:
    - image: kfserving/torchserve-kfs:0.3.0
      name: kfserving-container
         ...
  transformer:
    containers:
    - image: kfserving/torchserve-image-transformer:latest
      name: transformer-container
         ...
```
It would be good to be able to use a predictor like triton rather than a custom container.

**Comment by yuzisun** [comment]
That’s the goal but as you know the current code is structured to create separate pods for predictor and transformer, It will take a bit effort to achieve the above. I am just showing colocation is possible with current inference service spec.

**Comment by caffeinism** [comment]
Thanks. Some questions have been resolved. I will close this issue.
