### ISSUE TITLE
Storage Initializer Azure Fileshare download tgz RuntimeError ContentType check

### ISSUE THREAD

**Issue by AntPeixe** [kserve/kserve#1967]
/kind bug

**What steps did you take and what happened:**
Downloading a model from Azure Fileshare URI with a SAS results in RuntimeError due to a mismatch in ContentType.
On previous versions this would succeed as there were no ContentType checks.

 * URI example: `https://<STORAGE_ACCOUNT>.file.core.windows.net/path/to/file.tgz?<SAS_TOKEN>`
 * Detected mimetype: `'application/x-tar'`
 * Detected encoding: `'gzip'`
 * Response ContentType: `'application/octet-stream'`

This is a clear violation of the checks that were added. I wonder if it's better to add an exception when the URI contains `file.core.windows.net` or if there is another solution. For me to deploy I could try to just skip the checks and build a new image but it isn't ideal.

**What did you expect to happen:**
Expected the model to be downloaded and extracted from the archive.

**Environment:**
Tested the download locally on master branch.

**Comment by yuzisun** [comment]
@AntPeixe Seems currently we only check the [URL pattern](https://github.com/kserve/kserve/blob/master/python/kserve/kserve/storage.py#L42) with `_BLOB_RE = "https://(.+?).blob.core.windows.net/(.+)"`, I guess we need to add `file.core.windows.net` as well?

**Comment by laozc** [comment]
I believe there are a few endpoints for Azure storage accounts in different Azure clouds
which we might need to add those as well.
I can work on this.

**Comment by AntPeixe** [comment]
I think that adding another pattern and function to handle this would be the best option indeed.
Sorry I didn't get back sooner. I could have also worked on this but if you already started go ahead.

For now I've basically created my own image with a patch and changed the cluster configs to pull that instead of the default one.

**Comment by laozc** [comment]
@AntPeixe I added the file share support in storage initalizer.
The URI needs to be pointed to the directory where the tar.gz file locates.
https://<STORAGE_ACCOUNT>.file.core.windows.net/path/to/?<SAS_TOKEN>

I'm still working on some test cases. Hopefully I could get the PR done soon.

**Comment by yuzisun** [comment]
implemented with https://github.com/kserve/kserve/pull/1985 and https://github.com/kserve/kserve/pull/2180
