### ISSUE TITLE
Unable to pull storage intiializer image - gcr.io/kfserving/storage-initializer:v0.6.0

### ISSUE THREAD

**Issue by daganida88** [kserve/kserve#1976]
/kind bug

**What steps did you take and what happened:**
Try to run an inference service using this version of storage initializer
[A clear and concise description of what the bug is.]
When the pod start to run it first need to download the models using the storage intiailizer.
We've started to receive this error:
Error response from daemon: Head "https://gcr.io/v2/kfserving/storage-initializer/manifests/v0.6.0": denied: Permission denied: Consumer 'project:kfserving' has been suspended.

**What did you expect to happen:**
I was expecting to be able to pull the image successfully like I did so far.

**Anything else you would like to add:**
version 0.6 kfserving
Running on kubernetes

**Comment by daganida88** [comment]
we changed the image path from the inferenceservice-config configmap located in kfserving-system.

**Comment by dtpryce** [comment]
@daganida88 we are experiencing this also ... what did you change / fix exactly?

**Comment by dtpryce** [comment]
We have ```Failed to pull image "gcr.io/kfserving/storage-initializer:v0.4.0": rpc error: code = Unknown desc = Error response from daemon: Get https://gcr.io/v2/kfserving/storage-initializer/manifests/v0.4.0: denied: Permission denied: Consumer 'project:kfserving' has been suspended```

**Comment by dtpryce** [comment]
And haven't change anything on our side for weeks in the relevant charts

**Comment by yuzisun** [comment]
@daganida88 Please upgrade to v0.6.1 release in which we have ported all images to docker hub
e.g `gcr.io/kfserving/storage-initializer:v0.6.1` -> `kfserving/storage-initializer:v0.6.1`

**Comment by daganida88** [comment]
@dtpryce inside the inference-service configmap we changed to image to point to :  kfserving/storage-initializer:v0.6.1.
We restarted the inference services and they took the right image.

**Comment by dtpryce** [comment]
Appears to have fixed that! Thanks!

**Comment by jmalobicky** [comment]
We cannot just upgrade to v0.6.1 - are the older v0.4.x images available anywhere or is the GCR Project suspension going to be resolved?

**Comment by yuzisun** [comment]
> We cannot just upgrade to v0.6.1 - are the older v0.4.x images available anywhere or is the GCR Project suspension going to be resolved?

Yes we are requesting Google to restore the project asap.

**Comment by zijianjoy** [comment]
I have appealed for resuming the GCP project. It should be available now, please confirm if this unblocks you. @jmalobicky

**Comment by jmalobicky** [comment]
> I have appealed for resuming the GCP project. It should be available now, please confirm if this unblocks you. @jmalobicky

I see the images being pulled now!

**Comment by yuzisun** [comment]
Thanks @zijianjoy for the quick response! really appreciate it.

**Comment by zijianjoy** [comment]
Awesome, thank you @jmalobicky for confirming!

To @yuzisun , thank you for bringing this to our attention.
In order to prevent similar situation to happen again, I recommend making a copy of all the existing images on the kfserving GCP container registry, and serve them on Dockerhub or any public registry. Because I expect something similar to happen again, this will cause similar disruption to the community. After that, we should announce/communicate with existing users to switch to new registry for their existing KFServing deployment, so they can prevent sudden downtime when the GCP project is suspended again.

**Comment by daganida88** [comment]
Sounds good.

**Comment by yuzisun** [comment]
KFServing releases `v0.4.0`/`v0.4.1`/`v0.5.0`/`v0.5.1`/`v0.6.0` images have been backed up now under [dockerhub kfserving](https://hub.docker.com/u/kfserving). To prevent project suspension again in future as KServe working group no longer own the GCP kfserving project after moving out, we highly recommend updating kfserving controller image and `inferenceservice-config` configmap to use the images from dockerhub by changing the image prefix from `gcr.io/kfserving` to `kfserving` if you are using releases older than v0.6.1.
