### ISSUE TITLE
Leftover in the manifests

### ISSUE THREAD

**Issue by juliusvonkohout** [kserve/kserve#1995]
/kind bug

**What steps did you take and what happened:**
[A clear and concise description of what the bug is.]

There is a service https://github.com/kserve/kserve/blob/2208f100af02c05031e1910516f31ae3ece87aaf/manifests/charts/templates/service.yaml#L26 that lists port 443 for the kserve-controller-manager, but according to the deployment nothing at 443 is served https://github.com/kserve/kserve/blob/2208f100af02c05031e1910516f31ae3ece87aaf/manifests/charts/templates/deployment.yaml. This would also be a severe security issue because 443 prevents run as non root pods.

**Comment by yuzisun** [comment]
Thanks @juliusvonkohout ! Seems to be a bug when generating the metrics service, the port here should be 8443 which targets to the https port in kube rbac proxy used to authenticate and authorize the metrics scraping requests.

**Comment by juliusvonkohout** [comment]
and another security issue https://github.com/kserve/kserve/pull/1996

**Comment by juliusvonkohout** [comment]
> Thanks @juliusvonkohout ! Seems to be a bug when generating the metrics service, the port here should be 8443 which targets to the https port in kube rbac proxy used to authenticate and authorize the metrics scraping requests.

Can I just change it in the template to 8443 and create a pull request or will you do that. It seems to be wrong in line 8 and 26 https://github.com/kserve/kserve/blob/master/manifests/charts/templates/service.yaml
