### ISSUE TITLE
High availability control plane

### ISSUE THREAD

**Issue by howespt** [kserve/kserve#2010]
/kind feature

**Describe the solution you'd like**
The control plane for kserve should support highly available configurations.

**Anything else you would like to add:**
It's not clear whether the replica count for the kserve-controler-manager statefulset can be increased > 1. I am not familiar enough with the architecture to determine if it is possible to add additional replicas without side effects, is it? 

I have experienced disruptions to the controller which cascaded into other parts of our cluster (failing webhooks caused non kserve related pods to experience issues), it would be good to create some redundancy if possible.

**Comment by yuzisun** [comment]
@howespt Only kserve pods go through the kserve webhook as we use object selector, other parts of the cluster should not be affected.

**Comment by howespt** [comment]
@yuzisun fair enough, I don't have a good enough recollection of the issues involved from when this happened. Nevertheless the initial question still stands: is it possible to add additional replicas to the controller-manager statefulset?

**Comment by yuzisun** [comment]
> @yuzisun fair enough, I don't have a good enough recollection of the issues involved from when this happened. Nevertheless the initial question still stands: is it possible to add additional replicas to the controller-manager statefulset?

Yes we will convert from statefulset to deployment so can be deployed with more replicas by enabling leader election.
