### ISSUE TITLE
pytorch kfserving fails in kfserving v0.5.1

### ISSUE THREAD

**Issue by vijay-nag** [kserve/kserve#2023]
/kind bug

**What steps did you take and what happened:**
[A clear and concise description of what the bug is.]

we are trying to create pytorch isvc ( both v1alpha2 and v1beta1 api versions )

https://github.com/kserve/kserve/blob/release-0.5/docs/samples/v1alpha2/pytorch/pytorch.yaml
https://github.com/kserve/kserve/blob/release-0.5/docs/samples/v1alpha2/pytorch/pytorch_v1beta1.yaml

I am using the above two samples, also modified the storageURI as per our needs

``` 
       "pytorch": {
          "v1" : {
            "image": "slb.artifactory.local/org/kubeflow/kfserving/pytorchserver",
            "defaultImageVersion": "v0.5.1",
            "defaultGpuImageVersion": "v0.5.1-gpu",
            "supportedFrameworks": [
              "pytorch"
            ],
            "multiModelServer": false
          },
          "v2" : {
            "image": "slb.artifactory.local/org/kubeflow/kfserving/torchserve-kfs",
            "defaultImageVersion": "0.3.0",
            "defaultGpuImageVersion": "0.3.0-gpu",
            "supportedFrameworks": [
              "pytorch"
            ],
            "multiModelServer": false
          }
        } 
 ```

here is the configmap of kserving-controller-manager

**What did you expect to happen:**

sklearn predictor is working good! facing issues while running pytorch

```
  Conditions:
    Last Transition Time:  2022-02-01T04:44:51Z
    Message:               Configuration "pytorch-cifar10-predictor-default" is waiting for a Revision to become ready.
    Reason:                RevisionMissing
    Severity:              Info
    Status:                Unknown
    Type:                  PredictorConfigurationReady
    Last Transition Time:  2022-02-01T04:44:51Z
    Message:               Configuration "pytorch-cifar10-predictor-default" is waiting for a Revision to become ready.
    Reason:                RevisionMissing
    Status:                Unknown
    Type:                  PredictorReady
    Last Transition Time:  2022-02-01T04:44:51Z
    Severity:              Info
    Status:                Unknown
    Type:                  PredictorRouteReady
    Last Transition Time:  2022-02-01T04:44:51Z
    Message:               Configuration "pytorch-cifar10-predictor-default" is waiting for a Revision to become ready.
    Reason:                RevisionMissing
    Status:                Unknown
    Type:                  Ready
```

when I saw the yaml of ksvc 

```
      image: 'slb.artifactory.local/org/kubeflow/kfserving/pytorchserver:'
          name: kfserving-container
          readinessProbe:
            successThreshold: 1
            tcpSocket:
              port: 0
          resources:
```

 **image: 'slb.artifactory.local/org/kubeflow/kfserving/pytorchserver:'**

image tags are not being added to the image name
tried with image digests
both are failing

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

**Environment:**

- Istio Version: 1.9.0
- Knative Version: 0.14.3
- KFServing Version: 0.5.1
- Kubeflow version: 1.3.0rc1
- Kfdef:[k8s_istio/istio_dex/gcp_basic_auth/gcp_iap/aws/aws_cognito/ibm]
- Minikube version:
- Kubernetes version: (use `kubectl version`): 1.18.6
- OS (e.g. from `/etc/os-release`):

**Comment by yurkoff-mv** [comment]
Try changing the config. 
```
    "pytorch": {
          "v1" : {
            "image": "kfserving/pytorchserver",
            "defaultImageVersion": "v0.6.1",
            "defaultGpuImageVersion": "v0.6.1-gpu",
            "supportedFrameworks": [
              "pytorch"
            ],
            "multiModelServer": false
          },
          "v2" : {
            "image": "pytorch/torchserve-kfs",
            "defaultImageVersion": "0.4.1",
            "defaultGpuImageVersion": "0.4.1-gpu",
            "supportedFrameworks": [
              "pytorch"
            ],
            "multiModelServer": false
          }
        },
```

It's works for me.

**Comment by vijay-nag** [comment]
> Try changing the config.
> 
> ```
>     "pytorch": {
>           "v1" : {
>             "image": "kfserving/pytorchserver",
>             "defaultImageVersion": "v0.6.1",
>             "defaultGpuImageVersion": "v0.6.1-gpu",
>             "supportedFrameworks": [
>               "pytorch"
>             ],
>             "multiModelServer": false
>           },
>           "v2" : {
>             "image": "pytorch/torchserve-kfs",
>             "defaultImageVersion": "0.4.1",
>             "defaultGpuImageVersion": "0.4.1-gpu",
>             "supportedFrameworks": [
>               "pytorch"
>             ],
>             "multiModelServer": false
>           }
>         },
> ```
> 
> It's works for me.

No revision is not recognising digests and tags configured in inferenceservice-config
`  image: 'slb.artifactory.local/org/kubeflow/kfserving/pytorchserver:`

**Comment by yurkoff-mv** [comment]
Perhaps I misunderstood you, but try replacing your line with this:
`"image": "pytorch/torchserve-kfs"`

**Comment by yuzisun** [comment]
@vijay-nag pytorchserver is deprecated as of 0.8.0, please try to migrate to torchserve instead.
https://kserve.github.io/website/0.8/modelserving/v1beta1/torchserve/
