### ISSUE TITLE
Ability to use template for generating Inference Service URL when using raw deployment

### ISSUE THREAD

**Issue by pradithya** [kserve/kserve#2046]
/kind feature

**Describe the solution you'd like**

Currently, inference service URL when using raw deployment is generated using hardcoded template.
```
{{ Name }}-{{ Namespace }}.{{ Domain }}
```
In some organisation, these template might need to be customised (for example at Gojek, we are using `{{ Name }}.{{ Namespace }}.{{ Domain }}` template (using dot to separate Name and Namespace), hence it should be possible for kserve admin to specify their own template. 

In the template it should be possible to use:
- Name (Inference service name)
- Namespace
- Domain ( https://github.com/kserve/kserve/blob/7464e0c0ea60279ae0e592dba2a46800e34a8c5f/pkg/apis/serving/v1beta1/configmap.go#L121 )
- Annotations
- Labels

**Comment by pradithya** [comment]
I can work on it if it's approved.

**Comment by yuzisun** [comment]
@pradithya +1 on this, it is what knative has been doing though we need to replicate that logic in kserve.
