### ISSUE TITLE
Need to add more descriptions to the new feature ServerRuntime

### ISSUE THREAD

**Issue by Iamlovingit** [kserve/kserve#2047]
Kserve 0.8 is included `Server Runtime` feature, but there is rare of infomation or samples for that. It is better to add more documents, explain to user:
1. what can user do by `Server Runtime`
2. how to deploy new `Server Runtime`
3. Add more samples

At last, is the `inferenceservic-config.predictors` still useful?

**Comment by yuzisun** [comment]
@pvaneck I think you mostly wrote up this in the 0.8 release blog, we can move some of the content to the main doc and add an example ?

**Comment by pvaneck** [comment]
@yuzisun Right, I will add some content and explanation around ServingRuntimes to the main doc.
