### ISSUE TITLE
Failed to load model, missing model file

### ISSUE THREAD

**Issue by yangyang919** [kserve/kserve#2061]
/kind bug

**What steps did you take and what happened:**
We have a model gets trained and stored in Minio storage. Then we are applying InferenceService to deploy the model. But the pods failed to load the model:
`/usr/local/lib/python3.7/site-packages/ray/autoscaler/_private/cli_logger.py:61: FutureWarning: Not all Ray CLI dependencies were found. In Ray 1.4+, the Ray CLI, autoscaler, and dashboard will only be usable via `pip install 'ray[default]'`. Please update your install command.
  "update your install command.", FutureWarning)
[I 220225 06:32:36 storage:52] Copying contents of /mnt/models/data to local
[E 220225 06:32:36 __main__:37] fail to load model failure-rate-model from dir /mnt/models/data. exception type <class 'RuntimeError'>, exception msg: Missing Model File.
[I 220225 06:32:36 kfserver:120] Setting asyncio max_workers as 5
[I 220225 06:32:36 kfserver:127] Listening on port 8080
[I 220225 06:32:36 kfserver:129] Will fork 1 workers`

_If exec into pod, actually the model is copied from Minio and unzip there.
kubectl exec -it failure-rate-model-predictor-default-00001-deployment-675dwtz8q sh
kubectl exec [POD] [COMMAND] is DEPRECATED and will be removed in a future version. Use kubectl exec [POD] -- [COMMAND] instead.
Defaulted container "kserve-container" out of: kserve-container, queue-proxy, storage-initializer (init)
ls
bin  boot  dev	etc  home  kserve  lib	lib64  media  mnt  opt	proc  root  run  sbin  sklearnserver  srv  sys	third_party  tmp  usr  var
cd mnt/models/data
ls
failure-rate-model.pkl

Not sure why it cannot be loaded. The yaml file is like this
`
apiVersion: "serving.kserve.io/v1beta1"
kind: "InferenceService"
metadata:
  name: "failure-rate-model"
  namespace: "dev-profile"
  annotations:
    sidecar.istio.io/inject: "false"
spec:
  predictor:
    serviceAccountName: minio-secret
    sklearn:
      args: 
        - --model_dir=/mnt/models/data
      storageUri: "s3://mlpipeline/artifacts/failure-rate-pipeline-j6bjg/2022/02/25/failure-rate-pipeline-j6bjg-2549919938/train-model-function-Data.tgz"
`

**What did you expect to happen:**

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

**Environment:**

- Istio Version:
- Knative Version:
- KFServing Version:
- Kubeflow version:
- Kfdef:[k8s_istio/istio_dex/gcp_basic_auth/gcp_iap/aws/aws_cognito/ibm]
- Minikube version:
- Kubernetes version: (use `kubectl version`):
- OS (e.g. from `/etc/os-release`):

**Comment by yuzisun** [comment]
@yangyang919 it is looking for model.pkl, can you rename the model?

**Comment by yangyang919** [comment]
> @yangyang919 it is looking for model.pkl, can you rename the model?

thanks! I can have a try, but my question is, from error logs, looks like model name variable has been updated to my model name? _fail to load model failure-rate-model from dir /mnt/models/data._  So I thought it will look for failure-rate-model.pkl..

**Comment by yangyang919** [comment]
solved. Just use model.pkl as @yuzisun suggested. Thanks!
