### ISSUE TITLE
Support convert of input to numpy array - sklearnserver

### ISSUE THREAD

**Issue by eyalcha** [kserve/kserve#2066]
/kind feature

In some cases, there is a need to convert the input to numpy array before calling the predict function. Suggest to add a flag which when set, the predictor will convert the input to numpy array.

**Comment by yuzisun** [comment]
@eyalcha Can you provide an example which requires converting to numpy array ?

**Comment by eyalcha** [comment]
@yuzisun 

When using XGBoost model. e.g.:
```
xgbc = xgb.XGBClassifier()
```

See comment here which might be related: https://github.com/kserve/kserve/blob/master/python/xgbserver/xgbserver/model.py

**Comment by andyi2it** [comment]
/close
Closing as this should be fixed as part of changes done in #2748
Please re-open if you still find it not working.
