### ISSUE TITLE
Cannot use colon with proxy port in predictor image name in inferenceservice-config

### ISSUE THREAD

**Issue by michelverheijen** [kserve/kserve#2068]
We changed the configuration of the predictor images in the ```inferenceservice-config``` ConfigMap (https://github.com/kserve/kserve/blob/master/config/configmap/inferenceservice.yaml) to use a proxy and a proxy port.

So e.g. ```"image": "ourproxy:8888/tensorflow/serving"```
instead of  ```"image": "tensorflow/serving"```

However using a colon in the predictor image name doesn't work because of ```strings.Split(image, ":")[0]```
in https://github.com/kserve/kserve/blob/922a9b7e8a9a86b5ae65faf4ce863927873fd456/pkg/controller/v1beta1/inferenceservice/utils/utils.go#L189

Can this please be changed to split the image name and the runtimeversion using the last colon in this string?
Or is there another way to configure a proxy for pulling these predictor images?

**Comment by yuzisun** [comment]
@michelverheijen with 0.8 release, you can easily configure this by changing the `ServingRuntime` [yaml](https://github.com/kserve/kserve/blob/master/config/runtimes/kserve-tensorflow-serving.yaml#L15)

**Comment by michelverheijen** [comment]
@yuzisun that doesn't work.

I did a test with a triton inference service
I adapted the ClusterServingRuntime ```kserve-tritonserver``` to contain:
```image: ourproxy:8888/nvidia/tritonserver:21.09-py3```

I deployed an InferenceService with:
```
spec:
  predictor:
    triton:
      runtimeVersion: 22.01-py3
```

This resulted in:
```Revision "my-inference-predictor-default-00003" failed with message: Unable to fetch image "ourproxy:22.01-py3": failed to resolve image to digest```

This is exactly the bug I described above: the first colon in ```ourproxy:8888/nvidia/tritonserver:21.09-py3``` is used to split the image name and the runtime version, resulting in the concatenation of "ourproxy", ":" and "22.01-py3" instead of the concatenation of "ourproxy:8888/nvidia/tritonserver", ":" and "22.01-py3".

**Comment by yuzisun** [comment]
You could also directly override the image field on inference service yaml itself 

spec:
  predictor:
    triton:
      image: ourproxy:8888/tritonserver:22.01-py3

**Comment by michelverheijen** [comment]
@yuzisun : thanks for the work-around!
But it would be nice if the incorrect splitting on the first ":" could also be fixed.
Could you label this issue as bug?

**Comment by ittus** [comment]
@yuzisun I made a fix in https://github.com/kserve/kserve/pull/2074. Could you please help to review?
