### ISSUE TITLE
kserve 0.8 install error about  ClusterServingRuntime

### ISSUE THREAD

**Issue by fredbjer** [kserve/kserve#2069]
/kind bug

**What steps did you take and what happened:**
[A clear and concise description of what the bug is.]
`kubectl apply -f kserve.yaml` 

> unable to recognize kserve.yaml: no matches for kind ClusterServingRuntime in version serving.kserve.io/v1alpha1

**Comment by fredbjer** [comment]
using "serving.kserve.io/v1alpha2" or "serving.kserve.io/v1beta1" all have errors above.

**Comment by yuzisun** [comment]
This is a race condition I think, if you apply again it should work. @Suresh-Nakkeran I think we need to separate the runtimes install as a second step to wait for the crd to be in ready state.
