### ISSUE TITLE
Can we loose the requirement on numpy library

### ISSUE THREAD

**Issue by yangyang919** [kserve/kserve#2075]
/kind feature

**Describe the solution you'd like**
There are library version conflict for numpy:
#8 93.26 The conflict is caused by:
#8 93.26     The user requested numpy>=1.15.4
#8 93.26     cmdstanpy 0.9.68 depends on numpy>=1.15
#8 93.26     pystan 2.19.1.1 depends on numpy>=1.7
#8 93.26     matplotlib 2.0.0 depends on numpy>=1.7.1
#8 93.26     kserve 0.8.0rc0 depends on numpy~=1.19.2
#8 93.26     scikit-learn 1.0.1 depends on numpy>=1.14.6
#8 93.26     salesforce-merlion 1.1.1 depends on numpy>=1.21

Can we make numpy version from ~= to >= 1.19.2? Thanks for answering.

**Comment by Suresh-Nakkeran** [comment]
@yangyang919 we are working on upgrading numpy version. PR #2052

**Comment by yangyang919** [comment]
thanks @Suresh-Nakkeran , good to know!
