### ISSUE TITLE
Support for loading models with custom name

### ISSUE THREAD

**Issue by MimeZoe0628** [kserve/kserve#2079]
/kind feature

**Is there any way I can load models with custom name when I start a InferenceService**
[ In my project, I fetch model from external URI, and serve it by using InferenceService. But it dosen't work when the file name is not `model.joblib`. ]

**Comment by Suresh-Nakkeran** [comment]
@MimeZoe0628 can you mention the server that your using?

**Comment by MimeZoe0628** [comment]
> @MimeZoe0628 can you mention the server that your using?

scikit-learn

**Comment by markwinter** [comment]
@MimeZoe0628 
What uri were you using? http?

**Comment by Suresh-Nakkeran** [comment]
@MimeZoe0628 can you share example inferenceservice yaml?

**Comment by nmkrishna** [comment]
Currently kserve is assuming a default name for the models when they are mounted to the pod. So It works only if the name is `model.joblib`. This may be a defect. Can you pls add the support
