### ISSUE TITLE
Instructions not complete. 

### ISSUE THREAD

**Issue by vaporpin** [kserve/kserve#2081]
/kind feature

on the user guide page on "how to write a custom predictor", https://kserve.github.io/website/0.8/modelserving/v1beta1/custom/custom_model/#run-a-prediction .

I followed the example, however, I could not find the input.json example values that the custom predictor was tested with. Can anyone provide the link or values of the inputs? so that the instructions are complete. 

Thank you

**Comment by Suresh-Nakkeran** [comment]
@vaporpin can you refer [website](https://github.com/kserve/website/tree/main/docs/modelserving/v1beta1/custom/custom_model) github repo?

**Comment by vaporpin** [comment]
@Suresh-Nakkeran , got it. thanks for referencing me to the website github repo.
