### ISSUE TITLE
not finding inferenceservice_patch.yaml

### ISSUE THREAD

**Issue by alokhom** [kserve/kserve#2086]
/kind bug

**What steps did you take and what happened:**
cant find an example file inferenceservice_patch.yaml
https://github.com/kserve/kserve/blob/d1c24cd127523af1cc74d4e1536a816584699411/config/overlays/dev-image-config/kustomization.yaml#L5

**What did you expect to happen:**
inferenceservice_patch.yaml should be there

**Anything else you would like to add:**
using kserve in kubeFlow v1.5.0

**Environment:**

- Istio Version:
- Knative Version:
- KFServing Version: kfserving/kfserving-controller:v0.6.1
- Kubeflow version: 1.5.0
- Kfdef:[k8s_istio/istio_dex/gcp_basic_auth/gcp_iap/aws/aws_cognito/ibm]
- Minikube version: using aks 1.21
- Kubernetes version: (use `kubectl version`):
Client Version: version.Info{Major:"1", Minor:"23", GitVersion:"v1.23.4", GitCommit:"e6c093d87ea4cbb530a7b2ae91e54c0842d8308a", GitTreeState:"clean", BuildDate:"2022-02-16T12:38:05Z", GoVersion:"go1.17.7", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"21", GitVersion:"v1.21.7", GitCommit:"118c47a50b26423bb47369437d0b7592bf5e67ba", GitTreeState:"clean", BuildDate:"2022-02-07T20:48:54Z", GoVersion:"go1.16.10", Compiler:"gc", Platform:"linux/amd64"}
WARNING: version difference between client (1.23) and server (1.21) exceeds the supported minor version skew of +/-1
- OS (e.g. from `/etc/os-release`):
ubuntu wsl

**Comment by markwinter** [comment]
That file is generated by `hack/image_patch_dev.sh` which is called when you use `make deploy-dev`

**Comment by yuzisun** [comment]
This is the dev overlay which is only used for development purpose.
