### ISSUE TITLE
kserve e2e testing and optional-test-infra deprecation

### ISSUE THREAD

**Issue by theofpa** [kserve/kserve#2087]
We are using Kubeflow's optional-test-infra for the e2e tests.

The Kubeflow test team plans to deprecate that infrastructure, reference kubeflow/testing/issues/993

We've discussed in the past some options for the e2e tests, like stay in AWS and use Tekton, or move to Github Actions.

One of the reasons to stay in AWS was to have a test environment which is close to what people are using in production, essentially the ephemeral EKS cluster with the ALB capabilities.

On the other hand, looking at knative/serving's [e2e tests](https://github.com/knative/serving/blob/main/.github/workflows/kind-e2e.yaml) we are inspired by the powerful combination of different setups using Github Actions matrix and KinD.

Let's have a small discussion about it and eventually make a decision to move on to a future-proof option. Personally I like the later option with Github actions and KinD. @animeshsingh @pvaneck @yuzisun @chinhuang007

**Comment by yuzisun** [comment]
@theofpa let’s discuss in the community meeting Wednesday ?
