### ISSUE TITLE
torch_transformer curl issue

### ISSUE THREAD

**Issue by Omoong** [kserve/kserve#2093]
/kind bug

**What steps did you take and what happened:**

kubectl apply -f torch_transformer.yaml -n kubeflow-user-example-com

SERVICE_NAME=torch-transformer
MODEL_NAME=cifar10
INPUT_PATH=@./image.json

SERVICE_HOSTNAME=$(kubectl get inferenceservice $SERVICE_NAME -n kubeflow-user-example-com -o jsonpath='{.status.url}' | cut -d "/" -f 3)

curl -v -X POST -H "Host: ${SERVICE_HOSTNAME}" http://${INGRESS_HOST}:${INGRESS_PORT}/v1/models/$MODEL_NAME:predict -d $INPUT_PATH -H "Cookie: authservice_session=${SESSION}"

** this method worked for example without the transformer except the path was
    - /v2/models/cifar10/infer
   instead of 
    - /v1/models/$MODEL_NAME:predict

and i get the following error in the tranformer

 [E 220316 06:05:46 web:1792] Uncaught exception POST /v1/models/cifar10:predict (127.0.0.1) 
     HTTPServerRequest(protocol='http', host='torch-transformer-transformer-default.kubeflow-user-example-com.svc.cluster.local', method='POST', uri='/v1/models/cifar10:predict', version='HTTP/1.1', remote_ip='127.0.0.1') 
     Traceback (most recent call last): 
       File "/usr/local/lib/python3.7/site-packages/tornado/web.py", line 1703, in _execute 
         result = await result 
       File "/usr/local/lib/python3.7/site-packages/kfserving/handlers/http.py", line 57, in post 
         request = model.preprocess(body) 
       File "/image_transformer_v2/image_transformer_v2.py", line 54, in preprocess 
         'data': [image_transform(instance) for instance in inputs['instances']] 
       File "/image_transformer_v2/image_transformer_v2.py", line 54, in <listcomp> 
         'data': [image_transform(instance) for instance in inputs['instances']] 
       File "/image_transformer_v2/image_transformer_v2.py", line 33, in image_transform 
         image = Image.open(io.BytesIO(byte_array)) 
       File "/usr/local/lib/python3.7/site-packages/PIL/Image.py", line 2818, in open 
         raise IOError("cannot identify image file %r" % (filename if filename else fp)) 
     OSError: cannot identify image file <_io.BytesIO object at 0x7f1224ec9e90> 
 [E 220316 06:05:46 web:2250] 500 POST /v1/models/cifar10:predict (127.0.0.1) 0.94ms 

**What did you expect to happen:**

I was expecting a sucess as in the example 

> POST /v2/models/cifar:predict HTTP/2
> user-agent: curl/7.71.1
> accept: */*
> content-length: 3422
> content-type: application/x-www-form-urlencoded
> 
* We are completely uploaded and fine
* TLSv1.3 (IN), TLS handshake, Newsession Ticket (4):
* TLSv1.3 (IN), TLS handshake, Newsession Ticket (4):
* old SSL session ID is stale, removing
* Connection state changed (MAX_CONCURRENT_STREAMS == 4294967295)!
< HTTP/2 200 
< content-length: 338
< content-type: application/json; charset=UTF-8
< date: Thu, 08 Oct 2020 13:15:14 GMT
< server: istio-envoy
< x-envoy-upstream-service-time: 52
< 
{"model_name": "cifar", "model_version": "1", "outputs": [{"name": "OUTPUT__0", "datatype": "FP32", "shape": [1, 10], "data": [-0.7299326062202454, -2.186835289001465, -0.029627874493598938, 2.3753483295440674, -0.3476247489452362, 1.3253062963485718, 0.5721136927604675, 0.049311548471450806, -0.3691796362400055, -1.0804035663604736]}]}

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

**Environment:**

- Istio Version: 1.9.6
- Knative Version: v0.22.1
- KFServing Version: v0.6.1
- Kubeflow version: 1.4.0
- Kubernetes version: (use `kubectl version`): "v1.19.16"
- OS (e.g. from `/etc/os-release`): 20.04.3 LTS (Focal Fossa)

**Comment by Suresh-Nakkeran** [comment]
@Omoong may i know what input file you have passed?

**Comment by Omoong** [comment]
@Suresh-Nakkeran i passed image.json that was included in the sample 

{
  "instances": [
    {
      "image_bytes": { "b64": "aW1hZ2UgYnl0ZXM=" },
      "caption": "seaside"
    },
    {
      "image_bytes": { "b64": "YXdlc29tZSBpbWFnZSBieXRlcw==" },
      "caption": "mountains"
    }
  ]
}
