### ISSUE TITLE
Custom ModelServer not support inference v2 protocol ? 

### ISSUE THREAD

**Issue by kubbo** [kserve/kserve#2107]
/kind feature

**Describe the solution you'd like**
When will  custom modelServer supporte v2 protocol  ?  Thanks  .

**Anything else you would like to add:**
![image](https://user-images.githubusercontent.com/8613477/159126611-20e69be8-f514-4c1b-8d6e-e011ca186729.png)

**Comment by yuzisun** [comment]
@kubbo yes we are planning to support that, are you looking to use v2 rest or gRPC protocol ?

**Comment by kubbo** [comment]
v2 Rest , thanks

**Comment by kubbo** [comment]
May I ask when it can be supported ？
