### ISSUE TITLE
Proposal: Using poetry to management Python deps and venv

### ISSUE THREAD

**Issue by haoxins** [kserve/kserve#2108]
https://python-poetry.org/

The benefits will be:

1. More stable dependencies management, such as lock file.
2. Built-in virtual env supports
3. Integrate with `lint/format/unittest` tolls, such as `pytest`, `black`, `isort`, and others
4. More easier to add custom build scripts
5. More easier to link local package as dependency

**Comment by pbarker** [comment]
related https://github.com/kserve/kserve/issues/2220 kserve doesn't work well with poetry today

**Comment by pbarker** [comment]
would you all be up for accepting a contribution here?
