### ISSUE TITLE
fails to reconcile component: No ServingRuntimes or ClusterServingRuntimes with the name

### ISSUE THREAD

**Issue by dale1202** [kserve/kserve#2109]
/kind bug

**What steps did you take and what happened:**
[A clear and concise description of what the bug is.]
i click the command: kubectl apply -f sklearn.yaml -n kserve-test,
and i check the log, it reported: "error":"fails to reconcile component: No ServingRuntimes or ClusterServingRuntimes with the name: kserve-sklearnserver",

sklearn.yaml:
apiVersion: "serving.kserve.io/v1beta1"
kind: "InferenceService"
metadata:
  name: "sklearn-iris"
spec:
  predictor:
    sklearn:
      storageUri: "gs://kfserving-samples/models/sklearn/iris"

and i check the status of inferenceservices:
"kubectl get inferenceservices sklearn-iris -n kserve-test"

shows no Ready:
NAME           URL   READY   PREV   LATEST   PREVROLLEDOUTREVISION   LATESTREADYREVISION   AGE
sklearn-iris                                                                               13m

i used mode "RawDeployment" to install the kserve

so is anything wrong?

**Environment:**

- Istio Version: 1.13.2
- Knative Version: no 
- KFServing Version: 0.8
- Kubeflow version: no
- Kubernetes version: (use `kubectl version`): v1.23.5

**Comment by pvaneck** [comment]
Does `kubectl get clusterservingruntimes` show anything? You may not have any of the default [servingruntimes](https://kserve.github.io/website/0.8/modelserving/servingruntimes/) installed. This can be done by applying this file: https://github.com/kserve/kserve/releases/download/v0.8.0/kserve-runtimes.yaml

**Comment by dale1202** [comment]
@pvaneck thank you, you are right. throw your method i succeed .
