### ISSUE TITLE
What is the configmap kserve-config used for?

### ISSUE THREAD

**Issue by shydefoo** [kserve/kserve#2125]
/kind question

There is this configmap in `kserve.yaml` [here](https://github.com/kserve/kserve/blob/master/install/v0.8.0/kserve.yaml#L14998) that describes the ingressGateway field. However this looks like an overlap with the defined ingress configuration here [here](https://github.com/kserve/kserve/blob/master/install/v0.8.0/kserve.yaml#L14848). 

I tried searching for the code for use of `kserve-config` but couldn't find any, am i missing something here? If so, what's this configmap used for?

**Comment by Omoong** [comment]
@shydefoo 
i dont know if you have already figured this out or not but...
Im kind of new to kserve and dont understand it all to well, but I did some tests on my own and came to the following conclusion.
So, when you make an inferenceservice and look at the virtualservices(vs) that are created with it you will notice that vs is created for the inferenceservice itself and for each of the individual components inside the inferenceservice e.g. predictor, transformer and such.
the ingress that is defined in the configmap that you first mentioned, kserve-config, designates the gateways used by the vs for the inferenece service itself.
On the other hand the second configmap, inferenceservice-config, designates the gateways used by the individual components inside the inferenceservice, e.g. predictor, transformer and such.
I dont know why it is configured this way but thats my conclusion so far.
