### ISSUE TITLE
Allow disabling creation of the HPA in raw deployment mode

### ISSUE THREAD

**Issue by cmaddalozzo** [kserve/kserve#2131]
/kind feature

**Describe the solution you'd like**
Allow disabling creation of the HPA in raw deployment mode.

I would like to be able to control the scaling of the deployment created by my KServe inference service with an external tool ([KEDA](https://keda.sh/)). In order to support this use case I need a way to disable KServe's creation of the HPA. I was thinking adding a new autoscaler class called `none` which disables the creation of any resources by the autoscaler reconciler.

**Comment by shubhamrai1993** [comment]
Any updates on this? We have the same requirement
