### ISSUE TITLE
kfserving-samples bucket on GCS was gone

### ISSUE THREAD

**Issue by hsinhoyeh** [kserve/kserve#2133]
/kind bug

**What steps did you take and what happened:**
The existing codebase is running some test code with a prebuild model file located in GCS, especially `gs://kfserving-samples/models/tensorflow/flowers` but now seems the bucket is gone already. 
Do we have other alternative buckets? or this bucket should be live forever?

```
gsutil cp -r gs://kfserving-samples/models/tensorflow/flowers flowers

BucketNotFoundException: 404 gs://kfserving-samples bucket does not exist.
```

**What did you expect to happen:**
the model file should be downloaded.

**Anything else you would like to add:**
No

**Environment:**
not related to environment.

**Comment by yuzisun** [comment]
It should be back now, the project was accidentally closed.
