### ISSUE TITLE
In kubeflow 1.5 and 1.4 kfserving predict return 404 with sklearn 

### ISSUE THREAD

**Issue by nicozhang** [kserve/kserve#2138]
/kind bug

```
MODEL_NAME=sklearn-class
SESSION=MTY0OTM5OTczMnxOd3dBTkZSVlExaFhRa2N6UjBnMlJGWkpOMU5VUXpOT1ZVaEdUa3hMVlZsVVNrOWFVRFZUV2tsWVdVTkJOVkJYTWs5TVMwODFNa0U9fMIfXhMUu_0WjE0cXnzR2xcM3Yznwd4JVJWN2Tgij7zE
INPUT_PATH=@./input.json
CLUSTER_IP=$(kubectl -n istio-system get service istio-ingressgateway -o jsonpath='{.spec.clusterIP}')
SERVICE_HOSTNAME=$(kubectl get -n kubeflow-user-example-com inferenceservice ${MODEL_NAME} -o jsonpath='{.status.url}' | cut -d "/" -f 3)
curl -v -H "Host: ${SERVICE_HOSTNAME}" -H "Cookie: authservice_session=${SESSION}" http://localhost:30277/v1/models/${MODEL_NAME}:predict -d ${INPUT_PATH}

* About to connect() to localhost port 30277 (#0)
*   Trying ::1...
* Connected to localhost (::1) port 30277 (#0)
> POST /v1/models/sklearn-class-kube:predict HTTP/1.1
> User-Agent: curl/7.29.0
> Accept: */*
> Host: sklearn-class-kube.kubeflow-user-example-com.example.com
> Cookie: authservice_session=MTY0OTM5OTczMnxOd3dBTkZSVlExaFhRa2N6UjBnMlJGWkpOMU5VUXpOT1ZVaEdUa3hMVlZsVVNrOWFVRFZUV2tsWVdVTkJOVkJYTWs5TVMwODFNa0U9fMIfXhMUu_0WjE0cXnzR2xcM3Yznwd4JVJWN2Tgij7zE
> Content-Length: 93
> Content-Type: application/x-www-form-urlencoded
>
* upload completely sent off: 93 out of 93 bytes
< HTTP/1.1 404 Not Found
< content-length: 151
< content-type: text/html; charset=UTF-8
< date: Fri, 08 Apr 2022 09:18:09 GMT
< server: istio-envoy
< x-envoy-upstream-service-time: 51
<
* Connection #0 to host localhost left intact
<html><title>404: Model with name sklearn-class-kube does not exist.</title><body>404: Model with name sklearn-class-kube does not exist.

```

**Environment:**

- Istio Version:
- Knative Version:
- KFServing Version:
- Kubeflow version: 1.4 installed by kustomize
- Kfdef:[k8s_istio/istio_dex/gcp_basic_auth/gcp_iap/aws/aws_cognito/ibm]
- Minikube version:
- Kubernetes version: (use `kubectl version`):
- OS (e.g. from `/etc/os-release`):

**Comment by Omoong** [comment]
same issue here with kubeflow 1.5

**Comment by nicozhang** [comment]
I solve this problem. The model's sklearn version is different from the image's.So the container can not load the model success.

**Comment by nithin8702** [comment]
Hi @nicozhang, am also facing the same issue. Could you please explain how you fixed it.

**Comment by edi-bice** [comment]
Log in to Kubeflow, use Chrome Inspect to find session token in Application tab
Make sure to pass both headers, the token and the host in addition to the correct SERVICE URL 

INGRESS_DNS=${KUBEFLOW_NAME}.endpoints.${PROJECT}.cloud.goog
SERVICE_URL=https://${INGRESS_DNS}/v1/models/${ISVC_NAME}:predict

`curl -v -H "Authorization: Bearer ${TOKEN}" -H "Host: ${SERVICE_HOSTNAME}" ${SERVICE_URL} -d ${INPUT_PATH}`

**Comment by nicozhang** [comment]
> Hi @nicozhang, am also facing the same issue. Could you please explain how you fixed it.

I don't know exactly what you problem. Mine is because of the version of sklearn which trained the model is diff from the kfserver image's sklearn version. You can run exec command and login the container, then load the model mannuly, check whether it  can be loaded.
