### ISSUE TITLE
Supporting the AMD/Xilinx Inference Server in KServe

### ISSUE THREAD

**Issue by varunsh-xilinx** [kserve/kserve#2149]
/kind feature

We've been working on an official Xilinx/AMD inference server that is compatible with KServe to support AMD CPUs, GPUs and FPGAs. The work is [open-sourced](https://github.com/Xilinx/inference-server) and under active development. Let us know what we need to do to be more officially integrated in KServe. Thanks!

**Comment by yuzisun** [comment]
Hi @varunsh-xilinx, here is a list of tasks to integrate Xilinx to kserve and add to the supported serving runtime list.

- Create Xilinx cluster serving runtime CR and add to [kserve install manifests](https://github.com/kserve/kserve/tree/master/config/runtimes). On the cluster serving runtime CR specify the `supportModelFormats`  and `protocolVersions` supported by Xilinx inference server, please don't enable the `autoSelect` flag.
- Add e2e test for using the Xilinx serving runtime in https://github.com/kserve/kserve/tree/master/test/e2e/predictor with a test model.
- Add Xilinx serving runtime to the serving runtime list doc https://kserve.github.io/website/master/modelserving/servingruntimes/
https://kserve.github.io/website/master/modelserving/v1beta1/serving_runtime/
- Add Xilinx serving runtime documentation to https://github.com/kserve/website/tree/main/docs/modelserving/v1beta1
