### ISSUE TITLE
Cannot query custom prebuilt image deployment

### ISSUE THREAD

**Issue by jgoodman8** [kserve/kserve#2169]
/kind bug

When deploying an inference service based on the [pre-built](https://github.com/kserve/kserve/tree/master/docs/samples/v1beta1/custom/prebuilt-image) sample, the service is successfully deployed on Kubernetes.

However, when querying the `/model/predict` route, the resulting HTTP code is a 404 status code. As well, the request doesn't produce any log entry among the running containers.

This is the result of the curl command:

```
*   Trying ----...
* TCP_NODELAY set
* Connected to --- (---) port 80 (#0)
> POST /models/predict HTTP/1.1
> Host: ----
> User-Agent: curl/7.68.0
> Accept: */*
> Content-Length: 125759
> Content-Type: multipart/form-data; boundary=------------------------4f7797926bd65df9
> Expect: 100-continue
> 
* Mark bundle as not supporting multiuse
< HTTP/1.1 100 Continue
* We are completely uploaded and fine
* Mark bundle as not supporting multiuse
< HTTP/1.1 302 Found
< Date: Mon, 02 May 2022 14:21:34 GMT
< Content-Length: 0
< Connection: keep-alive
< location: /dex/auth?client_id=kubeflow-oidc-authservice&redirect_uri=%2Flogin%2Foidc&response_type=code&scope=openid+profile+email+groups+openid&state=MTY1MTUwMTI5NHxFd3dBRUZkeE9FbzFPRTlPWlVSaVowZGlWamM9fGKQFkkREIIn3_TRE5AaRgKhBgdplAYC4rofBH_P-3cN
< x-envoy-upstream-service-time: 1
< server: istio-envoy
< 
* Connection #0 to host --- left intact
```

**Environment:**

- KFServing Version: 0.7.0
- Kubeflow version: 1.4
- Kfdef:[k8s_istio/istio_dex/gcp_basic_auth/gcp_iap/aws/aws_cognito/ibm]
- Kubernetes version: (use `kubectl version`): 1.21.9

**Comment by markwinter** [comment]
The log shows that it's getting redirected to dex for authentication. I assume you're going through kubeflow's istio-ingressgateway. I'm not sure if there's a recommended way to deal with sending requests via the kubeflow gateway, but you should make an EnvoyFilter to exclude them from dex auth, or make a separate ingress for serving

**Comment by sivanantha321** [comment]
Follow [this tutorial to authenticate with dex](https://github.com/kserve/kserve/tree/master/docs/samples/istio-dex).
