### ISSUE TITLE
Can kserve support multi-model deployment?

### ISSUE THREAD

**Issue by SeibertronSS** [kserve/kserve#2183]
Can kserve support multi-model deployment like seldon-core?
![image](https://user-images.githubusercontent.com/69496864/168794698-1c8aa82b-fad3-4b0e-b0d8-08b3305c2c2f.png)
For example deploy two models with two isvcs. The output of the first isvc will be passed to the second isvc.

**Comment by yuzisun** [comment]
@SeibertronSS  this is going to be supported with inference graph https://github.com/kserve/kserve/pull/1910

**Comment by SeibertronSS** [comment]
Thank you very much!
