### ISSUE TITLE
TLS handshake error

### ISSUE THREAD

**Issue by SeibertronSS** [kserve/kserve#2184]
I got an error like
```
manager 2022/05/18 03:23:47 http: TLS handshake error from xx.xx.x.xxx:16032: remote error: tls: bad certificate 
```
What is the problem?

**Comment by yuzisun** [comment]
@SeibertronSS Please help clarify the issue with more details.

**Comment by SeibertronSS** [comment]
The specific phenomenon is that it cannot delete the isvc when I initiate a delete request.
More error messages:
![image](https://user-images.githubusercontent.com/69496864/169728341-01982d42-01fc-4f72-9c7e-d2026386ad11.png)

**Comment by Iamlovingit** [comment]
Hi @SeibertronSS , did you fix this issue? I am facing the same issue now.
