### ISSUE TITLE
Error - Cannot POST /v1/models/sklearn-iris:predict

### ISSUE THREAD

**Issue by Jensxy** [kserve/kserve#2186]
/kind bug

**What steps did you take and what happened:**
I installed Kubeflow 1.5 using kustomize. Then, I executed the [instructions](https://github.com/kserve/kserve/tree/master/docs/samples/v1beta1/sklearn/v1) to create a sklearn inferenceservice. Afterwards, I've tried to execute

`curl -v -H "Host: ${SERVICE_HOSTNAME}" http://${CLUSTER_IP}/v1/models/$MODEL_NAME:predict -d $INPUT_PATH` and it's returned

```
*   Trying XX.XX.XX.XX:80...
* TCP_NODELAY set
* Connected to XX.XX.XX.XX (XX.XX.XX.XX) port 80 (#0)
> POST /v1/models/sklearn-iris:predict HTTP/1.1
> Host: sklearn-iris.default.example.com
> User-Agent: curl/7.68.0
> Accept: */*
> Content-Length: 76
> Content-Type: application/x-www-form-urlencoded
>
* upload completely sent off: 76 out of 76 bytes
* Mark bundle as not supporting multiuse
< HTTP/1.1 404 Not Found
< x-powered-by: Express
< content-security-policy: default-src 'none'
< x-content-type-options: nosniff
< content-type: text/html; charset=utf-8
< content-length: 170
< date: Thu, 19 May 2022 13:53:26 GMT
< x-envoy-upstream-service-time: 5
< server: istio-envoy
<
<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8">
<title>Error</title>
</head>
<body>
<pre>Cannot POST /v1/models/sklearn-iris:predict</pre>
</body>
</html>
* Connection #0 to host XX.XX.XX.XX left intact
```

I saw this [post](https://github.com/kserve/kserve/issues/928#issuecomment-656163165) and tried to remove the lines. However, when I remove the lines and try to redeploy the inferenceservice, it doesn't work. The logs from `kubectl logs -n kserve kserve-controller-manager-0 -c manager` show **fails to create IngressConfig: Invalid ingress config, ingressGateway, ingressService are required.**

What did I do wrong?

**What did you expect to happen:**

I expected to get the output from the instructions:

```
Trying 169.63.251.68...
TCP_NODELAY set
Connected to 169.63.251.68 (169.63.251.68) port 80 (#0)
POST /models/sklearn-iris:predict HTTP/1.1
Host: sklearn-iris.default.svc.cluster.local
User-Agent: curl/7.60.0
Accept: */*
Content-Length: 76
Content-Type: application/x-www-form-urlencoded

upload completely sent off: 76 out of 76 bytes
 HTTP/1.1 200 OK
 content-length: 23
< content-type: application/json; charset=UTF-8
< date: Mon, 20 May 2019 20:49:02 GMT
< server: istio-envoy
< x-envoy-upstream-service-time: 1943
<
 Connection #0 to host 169.63.251.68 left intact
{"predictions": [1, 1]}
```

**Environment:**

- Istio Version: 1.11
- Knative Version: 0.22.1
- KFServing Version: Version from kubeflow 1.5
- Kubeflow version: 1.5
- Minikube version: - 
- Kubernetes version: v1.22.3
- OS (e.g. from `/etc/os-release`): Ubuntu 20.04

**Comment by yuzisun** [comment]
@Jensxy Are you using KFServing or KServe with Kubeflow 1.5 ?

**Comment by Jensxy** [comment]
@yuzisun I'm using KServe from here https://github.com/kubeflow/manifests

**Comment by zenglw06** [comment]
@yuzisun  it may be your error model files. The name of model file should be in `[model.joblib, model.pickle, model.pkl]`

it is hard code in kserve sklearn server

**Comment by Jensxy** [comment]
I think the logs from `kubectl logs -n kserve kserve-controller-manager-0 -c manager` indicate a previous error, which I have already solved. Currently, the corresponding error is no longer displayed.

**Comment by maganaluis** [comment]
@Jensxy I encountered the same issue deploying directly from the Kubeflow manifests. 

1. You need to ensure that the inferenceservice-config in the kserve namespace is using the Kubeflow Gateway rather than the knative serving defaults.
```
ingress: |-
    {
        "ingressGateway" : "kubeflow/kubeflow-gateway",
```
2. You need to ensure you  ensure the kserve-config in the kserve namespace is also using the Kubeflow Gateway
```
apiVersion: v1
data:
  ingressGateway: kubeflow/kubeflow-gateway
kind: ConfigMap
metadata:
  name: kserve-config
  namespace: kserve
```

I am assuming that the Kubeflow team intended to make these changes but the missed them or missed the documentation.

**Comment by ghost** [comment]
@maganaluis Thanks, the above changes fixed my issue.

Now models are accessible outside the kubernetes cluster.
