### ISSUE TITLE
 no kind "InferenceServiceList" is registered for version "serving/v1beta1"

### ISSUE THREAD

**Issue by JuHyung-Son** [kserve/kserve#2191]
/kind bug

**What steps did you take and what happened:**
[A clear and concise description of what the bug is.]
I'm using fake client using `NewSimpleClientset`.

and testing List function

```go
list, err := suite.fakeClient.Serving.List(v12.ListOptions{})
s.NoError(err)
```

this error occurs
` no kind "InferenceServiceList" is registered for version "serving/v1beta1" in scheme "pkg/runtime/scheme.go:100"`

**What did you expect to happen:**
I expect fake list function work

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]
other fake functions work well

- KFServing Version: 0.8.0
h- OS (e.g. from `/etc/os-release`): MacOS

**Comment by yuzisun** [comment]
I think the kserve go client API has not been updated for a while.

**Comment by sivanantha321** [comment]
no longer valid

/close
