### ISSUE TITLE
Readme file or design document

### ISSUE THREAD

**Issue by jinchihe** [kserve/kserve#22]
I'm interested the kfserving repo, and want to have a quick start for this, seems no basic operation introduction in Readme, any plan to deliver that? or could please share the design document? Thanks a lot!

**Comment by ellis-bigelow** [comment]
Thanks Jin,
There is an outdated one in another repo that I've been meaning to update and port over here. I'll also add a link to the original design proposal.

**Comment by jinchihe** [comment]
@ellis-bigelow Sounds great! That's better to have a quick start steps in Readme or have a development guide I think. :-) Thanks.

**Comment by ellis-bigelow** [comment]
Closing this. Dev guide is coming, but there's another issue for this.
