### ISSUE TITLE
Error occurs when attempting to increase gpu utilization of custom predictor

### ISSUE THREAD

**Issue by park12sj** [kserve/kserve#2207]
If I serve the predictor as below, but the gpu util comes out too low around 5%.

```
class RcModel(kserve.Model):
    def __init__(self, name: str):
        super().__init__(name)
        self.name = name
        self.device = torch.device('cuda:0' if torch.cuda.is_available() else 'cpu')
        self.load()

    def load(self):
        self.model = ReXNetV1(width_mult=2.0)
        self.model.output = nn.Sequential(
            nn.Dropout(0.5),
            nn.Conv2d(2560, 3, 1, bias=True))

        in_kservice = os.environ.get('K_SERVICE')
        self.model_pt_path = alluxio_path if in_kservice!=None else local_model_path
        checkpoint = torch.load(self.model_pt_path, map_location='cpu')
        self.model.load_state_dict(checkpoint['model'])
        self.model = self.model.to(self.device)
        self.model.eval()

    def predict(self, request: Dict):
        inputs = request["instances"]
        input_tensor = inputs[0]["tensor"]

        raw_data = base64.b64decode(input_tensor)
        raw_tensor = pickle.loads(raw_data)

        with torch.no_grad():
            raw_tensor = raw_tensor.to(self.device)
            output = self.model(raw_tensor)
            if self.device != 'cpu':
                torch.cuda.empty_cache()
            del input_tensor
            return pickle.dumps(output.cpu())

if __name__ == "__main__":
    model = RcModel(release_version)
    kserve.ModelServer(workers=1).start([model])

```
![image](https://user-images.githubusercontent.com/28818972/171105680-ed7d7263-ccc5-4503-b91c-e414b86a8470.png)

So I tried parallel inference at first. As a result, it was confirmed that the rps improved, but the gpuutil became 0%.
![image](https://user-images.githubusercontent.com/28818972/171105617-0b034dcf-e68c-40f0-914f-ac6926154766.png)

It was judged that the parallel inference does not work in gpu serving, so we tried to increase the number of workers as follows.
`kserve.ModelServer(workers=3).start([model])`
However, an error related to multiprocessing occurred.
`RuntimeError: Cannot re-initialize CUDA in forked subprocess. To use CUDA with multiprocessing, you must use the 'spawn' start method`

I tried a common fix for this error, but the error still won't fix.
https://stackoverflow.com/questions/48822463/how-to-use-pytorch-multiprocessing
```
from torch.multiprocessing import Pool, Process, set_start_method
try:
     set_start_method('spawn')
except RuntimeError:
    pass
```

Is there a way to get custom predictor to fully utilize gpu without a bug?

**Comment by markwinter** [comment]
How is the performance if you remove `torch.cuda.empty_cache()` ?

You can also try using the batcher to increase gpu utilisation and rps
https://kserve.github.io/website/0.8/modelserving/batcher/batcher/

**Comment by park12sj** [comment]
@markwinter 
I have a question about batch.

I think batcher sends batchesize of requests to predictor at once, in this case request 1, 2, 3... In what form are they going into predictor?

For example, my custom predictor is receiving the following input.
In this case, if I apply batch, does the list of data go into predictor?
What is the input format that predictor receives?
```
byte = pickle.dumps(image_tensor)
encoded_types = base64.b64encode(byte)
encoded_string = str(encoded_types, 'utf-8')

data = {
            "instances": [{"tensor":encoded_string}]        
        }

r = requests.post(url=kserve_url, json=data)
```

In summary, how does batcher combine requests that request data with one instance to input and deliver them to predictor?
For example, if user 1,2,3 sends data 1,2,3 respectively, what type of input will the predictor receive?
Could you give me an example as below?
`ex) [data1, data2, data3]
`

**Comment by park12sj** [comment]
After erasing the `torch.cuda.empty_cache()`, the gputil improved to 5->7~9%, but I want to apply batcher because it is not enough.
Thank you for answering the above questions.
