### ISSUE TITLE
Adding kserve into a poetry-managed package dramatically increases dependency resolution time

### ISSUE THREAD

**Issue by Lolologist** [kserve/kserve#2220]
/kind feature

**Describe the solution you'd like**
Hello KServe folks!
I'm sure you've heard of this issue but I didn't see any issues open for it right now so here we are.
I use poetry to manage packages I'm making and if I add kserve in there as a dependency you're looking at a bare minimum of 2000 seconds as it searches around for god knows what to help make your lock file.
It would be really swell if it didn't do that.

`[tool.black]
line-length = 88
target-version = ["py38"]

[tool.coverage.paths]
source = ["model.py", "serve.py"]

[tool.coverage.run]
branch = true
source = ["model.py", "serve.py"]

[tool.coverage.report]
show_missing = true
fail_under = 90
exclude_lines = [
    "if __name__ == .__main__.:",
    "pragma: no cover"
]

[tool.poetry]
(REDACTED)

[tool.poetry.dependencies]
python = "^3.8"
(REDACTED)
python-json-logger = "^2.0"
spacy = "^3.3"
spacy-transformers = "^1.1"
pytest = "^6.2"
ddtrace = "0.49.2"
kserve = "^0.8"
(REDACTED)
scikit-learn = "^1.0.2"
fastapi = "^0.77"
protobuf = "3.19.4"

[tool.poetry.dev-dependencies]
ipykernel = "^6.9"
jupyterlab = "^3.2"
pytest-cov = "^3"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

[[tool.poetry.source]]
name = "aws"
url = [REDACTED]
default = true
`

The above, with a few internal packages redacted, is my current. pyproject.toml.

**Comment by pbarker** [comment]
seeing the same issue:

my deps:
```
python = "^3.8"
pulumi = "^3.33.1"
GitPython = "^3.1.27"
kubernetes = "^23.6.0"
requests = "^2.27.1"
types-requests = "^2.27.30"
rootpath = "^0.1.1"
psutil = "^5.9.1"
```

**Comment by pbarker** [comment]
this appears to be an issue with the ray-serve dependency, that should ideally be made optional for people who don't plan on ever using ray serve

**Comment by yuzisun** [comment]
Finished the poetry support in https://github.com/kserve/kserve/issues/2404
