### ISSUE TITLE
Inference Graph SDK

### ISSUE THREAD

**Issue by vvnpan** [kserve/kserve#2226]
/kind feature

**Describe the solution you'd like**
Extend the existing kserve python SDK to support latest [inference graph API](https://github.com/kserve/kserve/pull/1910).

**Anything else you would like to add:**
@yuzisun will followup with instructions on how to contribute

**Comment by yuzisun** [comment]
@vvnpan You can follow the [sdk generation instruction](https://github.com/kserve/kserve/tree/master/hack/python-sdk) to create the inference graph python API and then we can add an e2e test for the inference graph like [here](https://github.com/kserve/kserve/blob/master/test/e2e/predictor/test_sklearn.py).

**Comment by vvnpan** [comment]
Thanks @yuzisun for the doc, I followed the doc and updated the api using the scripts, I think some apis didn't get generated. The InferenceGraph [API](https://github.com/vvnpan/kserve/blob/ecff2289899f2af60f6d81eca6b3209128dc0a43/python/kserve/docs/V1alpha1InferenceGraph.md) references `V1alpha1InferenceGraphSpec` and `V1alpha1InferenceGraphStatus` but neither were [generated](https://github.com/vvnpan/kserve/commit/ecff2289899f2af60f6d81eca6b3209128dc0a43)

I'm testing the the new API, but I need to wrap the inferencegraph API to be created with the kubernetes `client.api_instance.create_namespaced_custom_object()`, should I update the kserve client [logic](https://github.com/kserve/kserve/blob/c4e6b862d5f7b3d6789ae3c0440312cd131b9915/python/kserve/kserve/api/kserve_client.py#L88) to include inferencegraph?
