### ISSUE TITLE
Unable to create inferenceservice using kserve standalone on rhocp4.9

### ISSUE THREAD

**Issue by chintha-v** [kserve/kserve#2230]
Hi All,
I deployed standalone kserve 0.8.0 on rhocp4.9 cluster. While creating inferenceservice I am getting following error.
Can someone helm me out here please!
**HTTP response body: {"kind":"Status","apiVersion":"v1","metadata":{},"status":"Failure","message":"inferenceservices.serving.kserve.io is forbidden: User \"system:serviceaccount:sepmlpaas:mlpaas-service-account\" cannot create resource \"inferenceservices\" in API group \"serving.kserve.io\" in the namespace \"sepmlpaas\"","reason":"Forbidden","details":{"group":"serving.kserve.io","kind":"inferenceservices"},"code":403}**

**Comment by sivanantha321** [comment]
Follow [this updated tutoria](https://github.com/kserve/kserve/blob/master/docs/OPENSHIFT_GUIDE.md)l for using kserve with openshift.
