### ISSUE TITLE
can I use custom transformer and custom predictor in a pod??

### ISSUE THREAD

**Issue by JuHyung-Son** [kserve/kserve#2238]
In custom predictor example below, there is only `predict` method.

```python
import kserve
from typing import Dict
from ray import serve

@serve.deployment(name="custom-model", config={"num_replicas": 2})
class AlexNetModel(kserve.Model):
    def __init__(self):
       self.name = "custom-model"
       super().__init__(self.name)
       self.load()

    def load(self):
        pass

    def predict(self, request: Dict) -> Dict:
        pass

if __name__ == "__main__":
    kserve.ModelServer().start({"custom-model": AlexNetModel})
```

And if I implement `preprocess` and `postprocess` I get this error.

```
return Pickler.dump(self, obj)
TypeError: cannot pickle 'Struct' object
```

Is this expected behavior?? Is there any way I can use all of the method and use just one pod as possible as parallel inference?

**Comment by sivanantha321** [comment]
You can use custom transformer and custom predictor in the same pod but predictor and transformer should implemented in two different containers. This feature is supported from kseve 0.11.0rc0. There is an [example in the kserve website](https://kserve.github.io/website/master/modelserving/v1beta1/transformer/collocation/) on how to collocate the transformer and predictor.
