### ISSUE TITLE
Inferencing server with EKS Role annotation fails to start

### ISSUE THREAD

**Issue by pthalasta** [kserve/kserve#2239]
/kind bug

**What steps did you take and what happened:**
Unable to deploy inference server with Service Account/Secret created with EKS Role annotation fails to start with error while trying to refresh the AWS Web token

Here is the error
```
[I 220603 22:00:55 initializer-entrypoint:13] Initializing, args: src_uri [s3://model-bucket/model] dest_path[ [/mnt/models]
[I 220603 22:00:55 storage:52] Copying contents of s3://model-bucket/model to local
[W 220603 22:00:56 credentials:536] Refreshing temporary credentials failed during mandatory refresh period.
    Traceback (most recent call last):
      File "/usr/local/lib/python3.7/site-packages/botocore/credentials.py", line 531, in _protected_refresh
        metadata = self._refresh_using()
      File "/usr/local/lib/python3.7/site-packages/botocore/credentials.py", line 672, in fetch_credentials
        return self._get_cached_credentials()
      File "/usr/local/lib/python3.7/site-packages/botocore/credentials.py", line 682, in _get_cached_credentials
        response = self._get_credentials()
      File "/usr/local/lib/python3.7/site-packages/botocore/credentials.py", line 892, in _get_credentials
        return client.assume_role_with_web_identity(**kwargs)
      File "/usr/local/lib/python3.7/site-packages/botocore/client.py", line 386, in _api_call
        return self._make_api_call(operation_name, kwargs)
      File "/usr/local/lib/python3.7/site-packages/botocore/client.py", line 705, in _make_api_call
        raise error_class(parsed_response, operation_name)
    botocore.exceptions.ClientError: An error occurred (AccessDenied) when calling the AssumeRoleWithWebIdentity operation: Not authorized to perform sts:AssumeRoleWithWebIdentity
```

**What did you expect to happen:**
Model copied from AWS S3 and to start the inference server without any issues

**Anything else you would like to add:**
I tried to follow the details/instructions provided by @matty-rose here https://github.com/kserve/kserve/issues/2003#issuecomment-1053530385 but didn't work.

**Environment:**

- Istio Version: 1.11
- Knative Version: 0.22.1
- KServe Version: v0.7.0
- Kubeflow version: 1.4
- Kfdef:[k8s_istio/istio_dex/gcp_basic_auth/gcp_iap/aws/aws_cognito/ibm] istio_dex
- Minikube version:
- Kubernetes version: 1.20
- OS (e.g. from `/etc/os-release`):

**Comment by matty-rose** [comment]
Hey @pthalasta this looks more like an issue with your configuration of the IAM role itself, rather than permissions trying to download the model from S3. Have you followed the steps in https://docs.aws.amazon.com/eks/latest/userguide/iam-roles-for-service-accounts.html to configure the proper trust relationship between the EKS cluster and your role?

**Comment by pthalasta** [comment]
Hi @matty-rose , yes, i've followed the instructions provided in the link and it works fine when i access s3 from my kubeflow notebooks. However, kserve fails to pull the model from s3 bucket.

**Comment by pthalasta** [comment]
I found the issue. Closing the task as it was issue with IAM Role

**Comment by ashujain2** [comment]
> 

@pthalasta - I am also facing the same issue . If possible, Can you paste your trust policies IAM role and annotation you have used while creating SA ?
