### ISSUE TITLE
Deprecate kserve/kserve ECR repos

### ISSUE THREAD

**Issue by PatrickXYS** [kserve/kserve#2247]
/kind bug

**What steps did you take and what happened:**
As a post item of deprecating optional-test-infra, we'll deprecate kserve/kserve ECR repos provided by optional-test-infra.
Serves as sub-issue of https://github.com/kubeflow/testing/issues/1008

**What did you expect to happen:**
Deprecate kserve/kserve ECR repos provided by optional-test-infra

Repo List: 
**kserve/kserve:** `809251082950.dkr.ecr.us-west-2.amazonaws.com/kserve/`
* `agent` 
* `aix-explainer`
* `alibi-explainer`
* `art-explainer`
* `batcher `
* `image-transformer`
* `kserve-controller`
* `lgbserver `
* `paddleserver`
* `pmmlserver`
* `pytorchserver`
* `sklearnserver`
* `storage-initializer`
* `xgbserver`

@yuzisun  I believe those repos are not used in deployment by kserve/kserve, please confirm those repos are not in-use, if not, let's find alternatives by July.

**Comment by yuzisun** [comment]
@PatrickXYS we are not using these anymore, feel free to deprecate.

**Comment by yuzisun** [comment]
ECR deprecation has no impact to kserve, no action is needed from kserve side.
