### ISSUE TITLE
Path suffix missing from the `status.url` field of `InferenceServices`

### ISSUE THREAD

**Issue by kandrio** [kserve/kserve#2256]
I created an `InferenceService` that looks like the one below:

```yaml
apiVersion: serving.kubeflow.org/v1beta1
kind: InferenceService
metadata:
  ...
  managedFields:
    ...
  name: my-model
  namespace: kubeflow-user
spec:
  predictor:
    tensorflow:
      name: kfserving-container
      resources:
        ...
      runtimeVersion: 2.3.0
      storageUri: ...
  transformer:
    containers:
    - command:
      ...
      env:
        ...
      image: ...
      name: kfserving-container
      resources:
        ...
      securityContext:
        runAsUser: 0
```

After I applied this `InferenceService`, I looked at its `status` and I noticed that there was a discrepancy between the `status.url` and the `status.address.url` fields. Specifically, I notice that they look like this:
* `status.url`: `http://<isvc-name>-<namespace>.<domain>`
* `status.address.url`: `http://<isvc-name>.<namespace>.<domain>/v1/models/<isvc-name>:predict`

My question regards the `/v1/models/<isvc-name>:predict` path suffix.

*Why is the `/v1/models/<isvc-name>:predict` path present in `status.address.url` and **NOT** in the `status.url`?*

In my understanding, this path suffix is necessary to get predictions from a model, so I would expect that it was present in `status.url` as well.

**Environment:**

* KServe Version: `0.6.0`

**Comment by sivanantha321** [comment]
This is resolved by PR [Make status.address.url consistent across installations](https://github.com/kserve/kserve/pull/2875). For more context see https://github.com/kserve/kserve/issues/2874
