### ISSUE TITLE
Transformer examples uses incorrect function definition

### ISSUE THREAD

**Issue by smhgit** [kserve/kserve#2258]
/kind bug

Example use List   `def postprocess(self, inputs: List) -> List:`

https://github.com/kserve/kserve/blob/efda8c6f062e41368cb2eba3986e8cf9a7ba7dfc/docs/samples/v1beta1/transformer/torchserve_image_transformer/image_transformer/image_transformer.py#L87

While base uses Dict   `def postprocess(self, response: Union[Dict, ModelInferResponse]) -> Dict:`

https://github.com/kserve/kserve/blob/efda8c6f062e41368cb2eba3986e8cf9a7ba7dfc/python/kserve/kserve/model.py#L166

**Comment by yuzisun** [comment]
@smhgit Thanks for catching this! Are you interested to contribute the fix?

**Comment by smhgit** [comment]
@yuzisun sure, will take a look how to make contribution here.

**Comment by yuzisun** [comment]
Fixed in #2266
