### ISSUE TITLE
On prem - running a prediction with uri storage problem

### ISSUE THREAD

**Issue by szymonbcoding** [kserve/kserve#2261]
Hi,
I got non-admin access to on prem Kubeflow Platform and I would like to deploy and inference my previously created model with KServe.

I created InferenceService using: https://kserve.github.io/website/0.8/modelserving/storage/uri/uri/ (without secret feature).

**sklearn-from-uri.yaml:**
apiVersion: serving.kserve.io/v1beta1
kind: InferenceService
metadata:
  name: sklearn-from-uri
spec:
  predictor:
    sklearn:
      storageUri: https://github.com/szyba3224/kserve-test/blob/main/model.joblib?raw=true

(base) jovyan@j1-0:/uri_try$ kubectl apply -f sklearn-from-uri.yaml
inferenceservice.serving.kserve.io/sklearn-from-uri created
(base) jovyan@j1-0:/uri_try$ kubectl get inferenceservice 
NAME               URL                                                      READY   PREV   LATEST   PREVROLLEDOUTREVISION   LATESTREADYREVISION                        AGE
sklearn-from-uri   http://sklearn-from-uri.XXX.example.com   True           100                              sklearn-from-uri-predictor-default-00001   2m41s

And now I can't figure out how to get Ingress Host and Port for curl request, I can't find it in Kserve documentation - showed ways don't work for me ( https://kserve.github.io/website/0.8/get_started/first_isvc/#4-determine-the-ingress-ip-and-ports ):

(base) jovyan@j1-0:/uri_try$ kubectl get svc istio-ingressgateway -n istio-system
[...]
Error from server (Forbidden): services "istio-ingressgateway" is forbidden: User "system:serviceaccount:XXX:default-editor" cannot get resource "services" in API group "" in the namespace "istio-system"

Other commands in this kserve's documentation section also are forbidden.

I also tried to use example from kubeflow github:
https://github.com/kubeflow/examples/blob/master/kserve/sdk/first_isvc_kserve.ipynb

I modified Define InferenceService section for:
namespace = XXX
name='sklearn-from-uri'
api_version = "serving.kserve.io/v1beta1"

isvc = V1beta1InferenceService(api_version=api_version,
                               kind="InferenceService",
                               metadata=
                               client.V1ObjectMeta(
                               name=name, namespace=namespace),
                               spec=V1beta1InferenceServiceSpec(
                               predictor=V1beta1PredictorSpec(
                               sklearn=(V1beta1SKLearnSpec(
                                   storage_uri = "https://github.com/szyba3224/kserve-test/blob/main/model.joblib?raw=true",
                               ))))
)

InferenceService is giving me status Ready - True, but next step with prediction doesn't work for me:

import requests
​
isvc_resp = KServe.get(name, namespace=namespace)
isvc_url = isvc_resp['status']['address']['url']
​
print(isvc_url)
​
inference_input = {
  'instances': [
    [6.8,  2.8,  4.8,  1.4],
    [6.0,  3.4,  4.5,  1.6]
  ]
}
​
response = requests.post(isvc_url, json=inference_input)
print(response.text)

**Output:**
http://sklearn-from-uri.XXX.svc.cluster.local/v1/models/sklearn-from-uri:predict
<html><title>404: Model with name sklearn-from-uri does not exist.</title><body>404: Model with name sklearn-from-uri does not exist.</body></html>

My file in GitHub has name "model.joblib", changing name in InferenceService for model (name "model.joblib give me error) doesn't work. What can I do to get predictions?

Regards

**Comment by yuzisun** [comment]
@szymonbcoding can you help paste the log from predictor pod?

**Comment by szymonbcoding** [comment]
> @szymonbcoding can you help paste the log from predictor pod?

**(base) jovyan@j4-0:~$ kubectl logs sklearn-from-uri-predictor-default-00001-deployment-c466f7mkmp7**
error: a container name must be specified for pod sklearn-from-uri-predictor-default-00001-deployment-c466f7mkmp7, choose one of: [kserve-container queue-proxy] or one of the init containers: [storage-initializer]
**(base) jovyan@j4-0:~$ kubectl logs sklearn-from-uri-predictor-default-00001-deployment-c466f7mkmp7 --all-containers=true**
/usr/local/lib/python3.7/site-packages/ray/autoscaler/_private/cli_logger.py:61: FutureWarning: Not all Ray CLI dependencies were found. In Ray 1.4+, the Ray CLI, autoscaler, and dashboard will only be usable via `pip install 'ray[default]'`. Please update your install command.
  "update your install command.", FutureWarning)
[I 220626 01:33:26 initializer-entrypoint:13] Initializing, args: src_uri [https://github.com/szyba3224/kserve-test/blob/main/new_model.joblib?raw=true] dest_path[ [/mnt/models]
[I 220626 01:33:26 storage:52] Copying contents of https://github.com/szyba3224/kserve-test/blob/main/new_model.joblib?raw=true to local
/usr/local/lib/python3.7/site-packages/ray/autoscaler/_private/cli_logger.py:61: FutureWarning: Not all Ray CLI dependencies were found. In Ray 1.4+, the Ray CLI, autoscaler, and dashboard will only be usable via `pip install 'ray[default]'`. Please update your install command.
  "update your install command.", FutureWarning)
[I 220626 01:33:38 storage:52] Copying contents of /mnt/models to local
[E 220626 01:33:38 __main__:37] fail to load model sklearn-from-uri from dir /mnt/models. exception type <class 'RuntimeError'>, exception msg: Missing Model File.
[I 220626 01:33:38 kfserver:120] Setting asyncio max_workers as 5
[I 220626 01:33:38 kfserver:127] Listening on port 8080
[I 220626 01:33:38 kfserver:129] Will fork 1 workers
{"severity":"INFO","timestamp":"2022-06-26T01:33:37.355567287Z","caller":"logging/config.go:116","message":"Successfully created the logger."}
{"severity":"INFO","timestamp":"2022-06-26T01:33:37.355718836Z","caller":"logging/config.go:117","message":"Logging level set to: info"}
{"level":"info","ts":1656207217.3579745,"logger":"fallback","caller":"metrics/metrics_worker.go:76","msg":"Flushing the existing exporter before setting up the new exporter."}
{"level":"info","ts":1656207217.3581908,"logger":"fallback","caller":"metrics/prometheus_exporter.go:51","msg":"Created Prometheus exporter with config: &{knative.dev/internal/serving revision prometheus 5000000000 <nil> <nil>  false 9091 0.0.0.0 false   {   false}}. Start the server for Prometheus exporter."}
{"level":"info","ts":1656207217.3582313,"logger":"fallback","caller":"metrics/metrics_worker.go:91","msg":"Successfully updated the metrics exporter; old config: <nil>; new config &{knative.dev/internal/serving revision prometheus 5000000000 <nil> <nil>  false 9091 0.0.0.0 false   {   false}}"}
(base) jovyan@j4-0:~$

**Comment by szymonbcoding** [comment]
> @szymonbcoding can you help paste the log from predictor pod?

@yuzisun 

(base) jovyan@j1-0:~/uri_try2$ kubectl logs sklearn-from-uri-predictor-default-00001-deployment-85c77ckj8ms --all-containers=true
/usr/local/lib/python3.7/site-packages/ray/autoscaler/_private/cli_logger.py:61: FutureWarning: Not all Ray CLI dependencies were found. In Ray 1.4+, the Ray CLI, autoscaler, and dashboard will only be usable via `pip install 'ray[default]'`. Please update your install command.
  "update your install command.", FutureWarning)
[I 220629 13:33:03 initializer-entrypoint:13] Initializing, args: src_uri [https://github.com/szyba3224/kserve-test/blob/main/model.joblib?raw=true] dest_path[ [/mnt/models]
[I 220629 13:33:03 storage:52] Copying contents of https://github.com/szyba3224/kserve-test/blob/main/model.joblib?raw=true to local
/usr/local/lib/python3.7/site-packages/ray/autoscaler/_private/cli_logger.py:61: FutureWarning: Not all Ray CLI dependencies were found. In Ray 1.4+, the Ray CLI, autoscaler, and dashboard will only be usable via `pip install 'ray[default]'`. Please update your install command.
  "update your install command.", FutureWarning)
[I 220629 13:33:21 storage:52] Copying contents of /mnt/models to local
/usr/local/lib/python3.7/site-packages/sklearn/linear_model/least_angle.py:35: DeprecationWarning: `np.float` is a deprecated alias for the builtin `float`. To silence this warning, use `float` by itself. Doing this will not modify any behavior and is safe. If you specifically wanted the numpy scalar type, use `np.float64` here.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  eps=np.finfo(np.float).eps,
/usr/local/lib/python3.7/site-packages/sklearn/linear_model/least_angle.py:597: DeprecationWarning: `np.float` is a deprecated alias for the builtin `float`. To silence this warning, use `float` by itself. Doing this will not modify any behavior and is safe. If you specifically wanted the numpy scalar type, use `np.float64` here.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  eps=np.finfo(np.float).eps, copy_X=True, fit_path=True,
/usr/local/lib/python3.7/site-packages/sklearn/linear_model/least_angle.py:836: DeprecationWarning: `np.float` is a deprecated alias for the builtin `float`. To silence this warning, use `float` by itself. Doing this will not modify any behavior and is safe. If you specifically wanted the numpy scalar type, use `np.float64` here.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  eps=np.finfo(np.float).eps, copy_X=True, fit_path=True,
/usr/local/lib/python3.7/site-packages/sklearn/linear_model/least_angle.py:862: DeprecationWarning: `np.float` is a deprecated alias for the builtin `float`. To silence this warning, use `float` by itself. Doing this will not modify any behavior and is safe. If you specifically wanted the numpy scalar type, use `np.float64` here.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  eps=np.finfo(np.float).eps, positive=False):
/usr/local/lib/python3.7/site-packages/sklearn/linear_model/least_angle.py:1097: DeprecationWarning: `np.float` is a deprecated alias for the builtin `float`. To silence this warning, use `float` by itself. Doing this will not modify any behavior and is safe. If you specifically wanted the numpy scalar type, use `np.float64` here.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  max_n_alphas=1000, n_jobs=None, eps=np.finfo(np.float).eps,
/usr/local/lib/python3.7/site-packages/sklearn/linear_model/least_angle.py:1344: DeprecationWarning: `np.float` is a deprecated alias for the builtin `float`. To silence this warning, use `float` by itself. Doing this will not modify any behavior and is safe. If you specifically wanted the numpy scalar type, use `np.float64` here.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  max_n_alphas=1000, n_jobs=None, eps=np.finfo(np.float).eps,
/usr/local/lib/python3.7/site-packages/sklearn/linear_model/least_angle.py:1480: DeprecationWarning: `np.float` is a deprecated alias for the builtin `float`. To silence this warning, use `float` by itself. Doing this will not modify any behavior and is safe. If you specifically wanted the numpy scalar type, use `np.float64` here.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  eps=np.finfo(np.float).eps, copy_X=True, positive=False):
/usr/local/lib/python3.7/site-packages/sklearn/linear_model/randomized_l1.py:152: DeprecationWarning: `np.float` is a deprecated alias for the builtin `float`. To silence this warning, use `float` by itself. Doing this will not modify any behavior and is safe. If you specifically wanted the numpy scalar type, use `np.float64` here.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  precompute=False, eps=np.finfo(np.float).eps,
/usr/local/lib/python3.7/site-packages/sklearn/linear_model/randomized_l1.py:320: DeprecationWarning: `np.float` is a deprecated alias for the builtin `float`. To silence this warning, use `float` by itself. Doing this will not modify any behavior and is safe. If you specifically wanted the numpy scalar type, use `np.float64` here.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  eps=np.finfo(np.float).eps, random_state=None,
/usr/local/lib/python3.7/site-packages/sklearn/linear_model/randomized_l1.py:580: DeprecationWarning: `np.float` is a deprecated alias for the builtin `float`. To silence this warning, use `float` by itself. Doing this will not modify any behavior and is safe. If you specifically wanted the numpy scalar type, use `np.float64` here.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  eps=4 * np.finfo(np.float).eps, n_jobs=None,
**[E 220629 13:33:21 __main__:37] fail to load model sklearn-from-uri from dir /mnt/models. exception type <class 'ModuleNotFoundError'>, exception msg: No module named 'sklearn.svm._classes'**
[I 220629 13:33:21 kfserver:120] Setting asyncio max_workers as 5
[I 220629 13:33:21 kfserver:127] Listening on port 8080
[I 220629 13:33:21 kfserver:129] Will fork 1 workers
{"severity":"INFO","timestamp":"2022-06-29T13:33:20.068143838Z","caller":"logging/config.go:116","message":"Successfully created the logger."}
{"severity":"INFO","timestamp":"2022-06-29T13:33:20.068223548Z","caller":"logging/config.go:117","message":"Logging level set to: info"}
{"level":"info","ts":1656509600.068953,"logger":"fallback","caller":"metrics/metrics_worker.go:76","msg":"Flushing the existing exporter before setting up the new exporter."}
{"level":"info","ts":1656509600.0691125,"logger":"fallback","caller":"metrics/prometheus_exporter.go:51","msg":"Created Prometheus exporter with config: &{knative.dev/internal/serving revision prometheus 5000000000 <nil> <nil>  false 9091 0.0.0.0 false   {   false}}. Start the server for Prometheus exporter."}
{"level":"info","ts":1656509600.069142,"logger":"fallback","caller":"metrics/metrics_worker.go:91","msg":"Successfully updated the metrics exporter; old config: <nil>; new config &{knative.dev/internal/serving revision prometheus 5000000000 <nil> <nil>  false 9091 0.0.0.0 false   {   false}}"}

I think this line is crucial: 
[E 220629 13:33:21 __main__:37] fail to load model sklearn-from-uri from dir /mnt/models. exception type <class 'ModuleNotFoundError'>, exception msg: No module named 'sklearn.svm._classes'

I checked also version of scikit-learn in pod sklearn-from-uri-predictor-default-00001-deployment-85c77ckj8ms using commands:
kubectl exec -it sklearn-from-uri-predictor-default-00001-deployment-85c77ckj8ms -- bash
pip freeze

It is scikit-learn 0.20.3
I cannot update scikit-learn version in pod:
ERROR: Could not install packages due to an OSError: [Errno 13] Permission denied: '/.local'
Check the permissions.

I created virtualenv with python 2.7 and scikit-learn 0.20.3, I train svm model there and upload new model to github repository.

Now it works. I got prediction. 

However, is it necessery to use old versions of scikit-learn? How can I use inference service with models trained with newer versions of ML libraries?

**Comment by sivanantha321** [comment]
The scikit-version is updated to latest version in the KServe latest releases. This should fix the issue.
