### ISSUE TITLE
Waiting for load balancer to be ready

### ISSUE THREAD

**Issue by yurkoff-mv** [kserve/kserve#2263]
/kind bug

**What steps did you take and what happened:**
I had a single node cluster with Kubeflow and KServe. I added another node to it using the microk8s add-node command. When I deploy an InferenceService with GPU requests from the second node I get the following error:
```
  Conditions:
    Last Transition Time:  2022-06-21T14:53:41Z
    Message:               Waiting for load balancer to be ready
    Reason:                Uninitialized
    Severity:              Info
    Status:                Unknown
    Type:                  PredictorConfigurationReady
    Last Transition Time:  2022-06-21T14:53:41Z
    Message:               Waiting for load balancer to be ready
    Reason:                Uninitialized
    Status:                Unknown
    Type:                  PredictorReady
    Last Transition Time:  2022-06-21T14:53:40Z
    Severity:              Info
    Status:                True
    Type:                  PredictorRouteReady
    Last Transition Time:  2022-06-21T14:53:41Z
    Message:               Waiting for load balancer to be ready
    Reason:                Uninitialized
    Status:                Unknown
    Type:                  Ready
```
At the same time, GPU resources are successfully provided and the model itself (in TorchServe) is deployed.

**Environment:**
Istio Version: 1.9
Knative Version: 0.22.1
KFServing Version: 0.7.0
Kubeflow version: 1.5
Kubernetes version: (use kubectl version): Microk8s 1.20
OS (e.g. from /etc/os-release): Ubuntu 20.04
- Minikube version:
- Kubernetes version: (use `kubectl version`):
- OS (e.g. from `/etc/os-release`):

**Comment by yurkoff-mv** [comment]
I solved the problem: there was an error in the СonfigMap inferenceservice-config in kubeflow namespace.

**Comment by mcrisafu** [comment]
Hi @yurkoff-mv, I have exactly the same issue. What was the error in the ConfigMap?

**Comment by yurkoff-mv** [comment]
An incorrect TorchServe image was specified. Now it looks like this:
```
"pytorch": {
          "v1" : {
            "image": "kserve/pytorchserver",
            "defaultImageVersion": "v0.7.0",
            "defaultGpuImageVersion": "latest-gpu",
            "supportedFrameworks": [
              "pytorch"
            ],
            "multiModelServer": false
          },
          "v2" : {
            "image": "pytorch/torchserve-kfs",
            "defaultImageVersion": "0.4.1",
            "defaultGpuImageVersion": "0.4.1-gpu",
            "supportedFrameworks": [
              "pytorch"
            ],
            "multiModelServer": false
          }
        },
```

**Comment by mcrisafu** [comment]
Thank you. I will look into this. But as I am using a default predictor I am not sure if this helps.

**Comment by yurkoff-mv** [comment]
Can you provide your yaml file?

**Comment by mcrisafu** [comment]
We should not discuss this on a closed ticket. I am experiencing a similar issue with the iris example. It has to do with Knative custom domain. The 'Waiting for load balancer' error only occurs when a custom domain is set. I will look further into it and create a new issue if needed. Thank you for your help.
