### ISSUE TITLE
Kserve dependencies conflicts with KFP - Tensorflow - etc...

### ISSUE THREAD

**Issue by safoinme** [kserve/kserve#2277]
/kind feature

**Describe the solution you'd like**
Hi kserve team, I have been trying to install kserve on python with other libraries but this seems to be an impossible task due to dependencies conflicts. **Kserve0.8.0** had some old libraries like `numpy` that don't get along with `tensorflow`. I was hoping this problem would be fixed with **kserve0.9.0** which actually happened and many dependencies were updated to a newer version, but those versions are now set to a new and pinned that won't work with other libraries like `kfp` because of `kubernetes` dependency

> Is there a possibility to have dependencies requirements that can match other famous libraries requirements such as `tensorflow` & `kfp` etc...?

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

**Comment by yuzisun** [comment]
@safoinme which dependencies are causing the problem with kfp ?

**Comment by safoinme** [comment]
@yuzisun Thank you for the reply! 
For kfp 1.8.12:
  `kserve 0.9.0rc0` depends on kubernetes>=21.7.0
  `kfp 1.8.12` depends on kubernetes<19 and >=8.0.0
For kfp 1.8.10:
   `kserve 0.9.0rc0` depends on google-cloud-storage>=2.1.0
   `kfp 1.8.10` depends on google-cloud-storage<2 and >=1.20.0

**Comment by yuzisun** [comment]
kubernetes 1.19 is EOL already, not sure why kfp requires < 19 I think we should create an issue to kfp for upgrading that.

**Comment by safoinme** [comment]
**_Update:_**: I have been trying to install Kserve via Setuptools with KFP and Tensorflow and change the requirements.
These is the versions that work with KFP:
- google-cloud-storage>=1.20.0
- kubernetes>=18.20.0

@yuzisun I hope kserve could support older versions by setting greater than for a bit old version which makes it easier to solve a bigger range of dependencies version conflicts. But I think the right thing is what you said, that KFP should upgrade their dependencies to new versions. Thanks again for the response

**Comment by yuzisun** [comment]
I think what you proposed is ok. @markwinter what do you think?

**Comment by markwinter** [comment]
I think that will be okay too.

I think Kubeflow is currently trying to upgrade everything to Kubernetes 1.22 for the next release.

It seems KFP is focusing on v2 SDK so haven't updated the v1 SDK to allow/support new K8s versions.

**Comment by safoinme** [comment]
@markwinter  WIll it be okay if I create a PR for this or do you guys have an internal process for It?

**Comment by markwinter** [comment]
@safoinme 

It would be great if you could create a PR for this! 👍 
You can add myself and @yuzisun as reviewers

**Comment by safoinme** [comment]
I'm closing this issue! Thank you so much guys
