### ISSUE TITLE
Can't get the sklearn-iris Kserve example to work - InferenceService has no status

### ISSUE THREAD

**Issue by wenyangzz** [kserve/kserve#2280]
/kind bug

I'm trying to run the sklearn-iris exmple on kubebetes  ,using RawDeployment mode ,with no success
I run the example :
![image](https://user-images.githubusercontent.com/83051791/175928928-4aae2e48-59b4-4854-8f03-830be0812c5e.png)

**The problem:**
The InferenceService doesn't get deployed:
**output:**
![image](https://user-images.githubusercontent.com/83051791/175931361-f5c40d6f-5f2b-4f82-a9d9-95b99c8217e4.png)
 there's no values for "url", "Ready", etc...

**add:**
Running:
kubectl describe inferenceservices sklearn-iris -n kserve-test
Returns:
Name:         sklearn-iris
Namespace:    kserve-test
Labels:       <none>
Annotations:  <none>
API Version:  serving.kserve.io/v1beta1
Kind:         InferenceService
Metadata:
  Creation Timestamp:  2022-06-27T18:34:16Z
  Finalizers:
    inferenceservice.finalizers
  Generation:  1
  Managed Fields:
    API Version:  serving.kserve.io/v1beta1
    Fields Type:  FieldsV1
    fieldsV1:
      f:metadata:
        f:annotations:
          .:
          f:kubectl.kubernetes.io/last-applied-configuration:
      f:spec:
        .:
        f:predictor:
          .:
          f:model:
            .:
            f:modelFormat:
              .:
              f:name:
            f:storageUri:
    Manager:      kubectl-client-side-apply
    Operation:    Update
    Time:         2022-06-27T18:34:15Z
    API Version:  serving.kserve.io/v1beta1
    Fields Type:  FieldsV1
    fieldsV1:
      f:metadata:
        f:finalizers:
      f:status:
    Manager:         manager
    Operation:       Update
    Time:            2022-06-27T18:34:16Z
  Resource Version:  85541
  UID:               f6980129-6b75-4abf-9a49-dbd0eb8a3c3a
Spec:
  Predictor:
    Model:
      Model Format:
        Name:  sklearn
      Name:    
      Resources:
      Storage Uri:  gs://kfserving-examples/models/sklearn/1.0/model
**Events:**
  Type      Reason                  Age                                    From                       Message
  Warning  InternalError  8m13s (x19 over 30m)      v1beta1Controllers       **no runtime found to support predictor with model type: {sklearn \<nil\>}**

**Environment:**
- Istio Version:1.11
- KFServing Version: 0.8.0
- Kubernetes version: (use `kubectl version`): 1.20
- OS (e.g. from `/etc/os-release`): Centos

How can I solve this problem?

**Comment by yuzisun** [comment]
@wenyangzz did you install kserve serving runtimes?

**Comment by wenyangzz** [comment]
> @wenyangzz did you install kserve serving runtimes?

Thanks, I ran the command apply -f 
 https://github.com/kserve/kserve/releases/download/v0.8.0/kserve.yaml to install kserve. 
How do I check if KServe Serving RunTimes is installed ?

**Comment by yuzisun** [comment]
you would need to install serving runtimes with KServe 0.8 
https://kserve.github.io/website/0.8/admin/serverless/#5-install-kserve-built-in-clusterservingruntimes

**Comment by wenyangzz** [comment]
> you would need to install serving runtimes with KServe 0.8 https://kserve.github.io/website/0.8/admin/serverless/#5-install-kserve-built-in-clusterservingruntimes
Many thanks , I have deployed the InferenceService .
![image](https://user-images.githubusercontent.com/83051791/176165409-6437de7b-9165-4ade-8256-46ad06f1f299.png)

But when I run the "curl -v http://sklearn-iris.kserve-test/v1/models/sklearn-iris:predict -d @./iris-input.json "  on the master node , the return is could not resolve host
![image](https://user-images.githubusercontent.com/83051791/176164383-684b1368-6fb9-40ae-97ac-6bfc0b51f0da.png)

**Comment by capoolebugchat** [comment]
Hello fellow KServe user. How did you resolve the "could not resolve host" return problem while calling a ready service.
