### ISSUE TITLE
Fail validate when converting to numpy array in transformer

### ISSUE THREAD

**Issue by eyalcha** [kserve/kserve#2291]
/kind bug

Issue #1972 removed np.array check and now conversion should be done in transformer (which is the correct approach). 
The issue is that currently when converting to np.array it fails in validate function in transformer because it is not a list

https://github.com/kserve/kserve/blob/aefac29b9b3fb7a1b8475c118bd1746406ef0b77/python/kserve/kserve/model.py#L109

**Comment by yuzisun** [comment]
@eyalcha transformer needs to send the request to predictor over the wire so I think it still needs to convert to a list according to the protocol right?

**Comment by eyalcha** [comment]
@yuzisun the issue is here : 

https://github.com/kserve/kserve/blob/c75e52663daf18a78b8385de35afa95fc2467284/python/kserve/kserve/model.py#L78

If we need to convert to numpy array and then send to predict (with REST V1/V2), the validate function in transformer will fail. 

```
import numpy as np

request = {
    "instances": [
      {}  
    ]
}
print(isinstance(request["instances"], list))
# True

request["instances"] = np.array(request["instances"])
print(isinstance(request["instances"], list))
# False
```

The assumption is that we need to convert the instances to array before sending it to predict. Before issue #1972 it was done in predictor, in the predict function with no validation. Now it was moved to pre process of transformer and the validate function fails because of the type change.

Am I missing something?

**Comment by yuzisun** [comment]
@eyalcha Can you provide a more detailed example for the issue ? As I understand sklearn predict is able to convert to either numpy or pandas data framework accordingly.

**Comment by yuzisun** [comment]
The validation is only done when the input is a dict type, you can pass the np array to the predict function. 

https://github.com/kserve/kserve/blob/09f5f60f91bb413f9a340cebf8d9e10971c9fabd/python/kserve/kserve/model.py#L160
