### ISSUE TITLE
The nodeSelector in explainer doesn't work

### ISSUE THREAD

**Issue by SeibertronSS** [kserve/kserve#2299]
I set the nodeSelector in explainer but it doesn't work.

**Comment by SeibertronSS** [comment]
The nodeSelector in explainer pod is `None`
![image](https://user-images.githubusercontent.com/69496864/176817530-9a9078c1-a94b-487d-adaa-a13fb0e9674f.png)

**Comment by sivanantha321** [comment]
You have to enable the feature in knative's `config-features` config map. https://knative.dev/docs/serving/configuration/feature-flags/#kubernetes-node-selector
