### ISSUE TITLE
No access to kfserving-samples GCP Storage bucket

### ISSUE THREAD

**Issue by djmcgreal-cc** [kserve/kserve#2306]
/kind bug

**What steps did you take and what happened:**
Browse to https://storage.googleapis.com/kfserving-samples
403 Anonymous access not allowed

**What did you expect to happen:**
To be able to retrieve models listed in sample documentation and run the samples from within Kserve.
For example https://storage.googleapis.com/kfserving-samples/models/sklearn/iris

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

**Environment:**

- Istio Version:
- Knative Version:
- KFServing Version:
- Kubeflow version:
- Kfdef:[k8s_istio/istio_dex/gcp_basic_auth/gcp_iap/aws/aws_cognito/ibm]
- Minikube version:
- Kubernetes version: (use `kubectl version`):
- OS (e.g. from `/etc/os-release`):

**Comment by djmcgreal-cc** [comment]
I've found kfserving-samples in some documentation, and now found kfserving-examples. `-examples` seems to have things in it but not a direct translation from what some of the samples describe being in -samples.

**Comment by yuzisun** [comment]
@djmcgreal-cc `kfserving-samples` has been deprecated as the gcp project which it belongs to is disabled, please use `kfserving-examples` instead.

see https://github.com/kserve/kserve/issues/2234
