### ISSUE TITLE
package update request

### ISSUE THREAD

**Issue by JuHyung-Son** [kserve/kserve#2308]
/kind feature

kserve is using old packages
```
k8s.io/api v0.22.3
k8s.io/apimachinery v0.22.3
k8s.io/client-go v0.22.3
```

it does not have issue when using with kubectl, but when using kserve go client, these old packages conflict with other packages so it`s hard to use it.

for example.
kserve use k8s.io@v.0.22.3
k8s.io@v.0.22.3 use controller-runtime@v0.10.2
controller-runtime@v0.10.2 use logr@v0.4.0

but many of packages use logr@v1.x  so it they conflicts.

**Describe the solution you'd like**
[A clear and concise description of what you want to happen.]
update k8s.io related packages in go.mod

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

**Comment by yuzisun** [comment]
it is now on v0.23.9 and controller-runtime 0.11.2
https://github.com/kserve/kserve/blob/master/go.mod#L32
