### ISSUE TITLE
Setup kserve without Knative in e2e for testing raw deployments

### ISSUE THREAD

**Issue by andyi2it** [kserve/kserve#2318]
/kind feature

**Describe the solution you'd like**
Currently all the e2e environments have knative installed. 
Even the e2e tests that are raw deployments based ones are being tested in a knative environment with raw 
deployment mode annotation.

We would like to have a separate e2e environment without knative installed, that could test raw deployments in parallel.

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

**Comment by sivanantha321** [comment]
Done as part of #3440
