### ISSUE TITLE
kserve-runtimes.yaml contains duplicate resources

### ISSUE THREAD

**Issue by pbarker** [kserve/kserve#2325]
/kind bug

https://github.com/kserve/kserve/releases/download/v0.9.0-rc0/kserve-runtimes.yaml contains two resources with the name `kserve-mlserver` which breaks some install tools

**What did you expect to happen:**
there to just be one

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

**Environment:**

- Istio Version:
- Knative Version:
- KFServing Version: v0.9.0-rc0
- Kubeflow version:
- Kfdef:[k8s_istio/istio_dex/gcp_basic_auth/gcp_iap/aws/aws_cognito/ibm]
- Minikube version:
- Kubernetes version: (use `kubectl version`):
- OS (e.g. from `/etc/os-release`):

**Comment by pbarker** [comment]
This is actually true of all the servers not just `mlserver`

**Comment by yuzisun** [comment]
hmm seems the yaml is correct in the release branch https://github.com/kserve/kserve/blob/release-0.9/install/v0.9.0-rc0/kserve-runtimes.yaml, fixed now
