### ISSUE TITLE
Wrong version of sklearn libraries

### ISSUE THREAD

**Issue by szymonbcoding** [kserve/kserve#2330]
I use kserve 0.8.0.1

I created inferenceservice with v1beta1 (python sdk). Accoarding to:
https://kserve.github.io/website/0.8/modelserving/v1beta1/serving_runtime/

sklearn predictor pod should have scikitlearn version 1.0.1, but when I checked it with these commands:
_kubectl exec -it {my_pod_name} -- bash
pip freeze_

I got this output:
[...]
scikit-learn==0.20.3
[...]

I think it should be updated.

**Comment by yuzisun** [comment]
@szymonbcoding it is correct, can you check if you are running with the right image?
```
docker run -it --entrypoint=/bin/bash kserve/sklearnserver:v0.8.0 
kserve@6bc87902e7a9:/$ pip freeze |grep scikit
scikit-learn==1.0.1
```

**Comment by yuzisun** [comment]
make sure you installed the right version of KServe, not just sdk. For example if you installed KServe 0.7, using sdk 0.8 does not create sklearn inferenceservice with 1.0.1 version by default , though you can use `runtimeVersion=v0.8.0` to override the default servingruntime version from sdk.
