### ISSUE TITLE
Add support for inference graphs to models web app UI since kserve supports Inference graphs too starting 0.9.0

### ISSUE THREAD

**Issue by rachitchauhan43** [kserve/kserve#2333]
/kind feature

**Describe the solution you'd like**
Since 0.9.0, kserve will start supporting Infrence Graphs. Models web app should inference graphs as there is no UI as of today to manage Inference Graphs.
Only interfacing available is `kubectl` command line.

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

**Comment by sivanantha321** [comment]
Models Web app is maintained by kubeflow. Please raise the issue in [models web app repository](https://github.com/kserve/models-web-app/issues)
