### ISSUE TITLE
CLI to get authservice session is not seems to be updated

### ISSUE THREAD

**Issue by mdrijwan123** [kserve/kserve#2335]
/kind bug

**What steps did you take and what happened:**
I tried to get session cookie but the github page I followed i.e., [istio-dex](https://github.com/kserve/kserve/tree/master/docs/samples/istio-dex) seems to be not updated to give correct  REQ_VALUE. I am getting state value correctly as mention there but the second step giving me 400 bad request, the curl I am using as below:
`curl -v "http://${CLUSTER_IP}/dex/auth?client_id=kubeflow-oidc-authservice&redirect_uri=%2Flogin%2Foidc&response_type=code&scope=profile+email+groups+openid&amp;state=MTY1Nzg5NTIwNnxFd3dBRUZKelRWRmtPRXBYYzBWa1VWRk9Wa2s9fETldx32xleeN1YiYTOBlNkv8YT2PYYlC0tAjU8ijr5Q"`

It giving response as below:
![image](https://user-images.githubusercontent.com/35109373/179245989-a01ec95f-5ce9-4fdd-9eba-2ce7056ace83.png)
It doesn't have any response like 
`<a href="/dex/auth/local?req=REQ_VALUE">Found</a>`
**What did you expect to happen:**
I want REQ_VALUE in above step, and other commands also should work as mentioned in github page.

**Anything else you would like to add:**
I am using EXTERNAL_IP same as which I use for kserve predict, as the first step in github page:
`CLUSTER_IP=$(kubectl -n istio-system get service istio-ingressgateway -o jsonpath='{.spec.clusterIP}')`
Its giving me the CLUSTER_IP but not able to give any response when I use curl -v http://${CLUSTER_IP}, so I replace this with EXTERNAL_IP or load-balancer ingress IP and its able to give me state value as mention in the doc.

Also the [kftcl_istio_dex.yaml](https://raw.githubusercontent.com/kubeflow/manifests/v1.1-branch/kfdef/kfctl_istio_dex.yaml) mention there, I haven't touched it but logging in kubeflow UI and getting cookie from there, I am able to get my kserve response. Its only cli which is not working. And its important, If some external application want to consume the kserve application it will get the session token from cli only.
I am not sure if I am doing something wrong and moving right.

**Environment:**

- Istio Version: 1.9.0
- Knative Version: v1.2.5
- KFServing Version: v0.8.0
- Kubeflow version: v.1.5.1
- Kfdef:[k8s_istio/istio_dex/gcp_basic_auth/gcp_iap/aws/aws_cognito/ibm]
- Minikube version: 
- Kubernetes version: (use `kubectl version`): v1.24.3
- OS (e.g. from `/etc/os-release`): Ubuntu 20.04

**Comment by mdrijwan123** [comment]
Hi @sachua can you please help in this issue, if something I doing wrong. I an new to this dex authentication process but able to get kserve response from UI cookie but not from CLI.

**Comment by sachua** [comment]
Hi @mdrijwan123 , I haven't been active, but from the error message it seems like there is an additional semicolon somewhere in your query? Also you might want to look into more secure ways of obtaining the authentication token. This kfctl issue may be a good reference https://github.com/kubeflow/kfctl/issues/140

**Comment by mdrijwan123** [comment]
Hey @sachua Thankyou for response. I'll look into this and if worked then I will close this soon.

**Comment by raahulraa** [comment]
It looks like you need to execute the below line
`curl -v "http://${CLUSTER_IP}/dex/auth?client_id=kubeflow-oidc-authservice&redirect_uri=%2Flogin%2Foidc&response_type=code&scope=profile+email+groups+openid&state=MTY1Nzg5NTIwNnxFd3dBRUZKelRWRmtPRXBYYzBWa1VWRk9Wa2s9fETldx32xleeN1YiYTOBlNkv8YT2PYYlC0tAjU8ijr5Q"`
