### ISSUE TITLE
Inference Service Defaulter overrides deployment mode if it does not match default

### ISSUE THREAD

**Issue by cmaddalozzo** [kserve/kserve#2337]
/kind bug

**What steps did you take and what happened:**
1. Set the `defaultDeploymentMode` to `RawDeployment`. 
2. Create an inference service with the annotation `serving.kserve.io/deploymentMode: ModelMesh`

Upon creation the defaulter will set the annotation to `RawDeployment` instead of leaving it as `ModelMesh`.

https://github.com/kserve/kserve/blob/master/pkg/apis/serving/v1beta1/inference_service_defaults.go#L83

**What did you expect to happen:**
The inference service should be created with `deploymentMode` set to `ModelMesh`.

**Environment:**

- KServe Version: 0.8.0
- Kind version:  0.12.0
- Kubernetes version: 1.23.4
- OS: CentOS Linux 7

**Comment by yuzisun** [comment]
@cmaddalozzo just to be clear, this isn't an issue for 0.8.0 and the bug is introduced in 0.9 release branch.
