### ISSUE TITLE
Transformer pod is not running when installing kserve in serverless.

### ISSUE THREAD

**Issue by mdrijwan123** [kserve/kserve#2347]
/kind bug

**What steps did you take and what happened:**
I installed kserve serverless with knative and istio few days ago it was working fine, but due to some testing I have to delete kserve and required dependencies, and reinstall it but after that my transformer pod is not running in serverless mode, If I change it to raw deployment then its working fine and both predictor and transformer is running. I am clueless whats happening. Any help I will appreciate. 

**What did you expect to happen:**
I serverless I am should run both pods normally.

**Anything else you would like to add:**
I installed istio-dex and other kubeflow menifest to test authentication in kserve but due to no requirement I have to delete everything but after reinstall transformer is not working. I have installed kserve and its dependencies from: [quick_install.sh](https://raw.githubusercontent.com/kserve/kserve/release-0.8/hack/quick_install.sh)

**Environment:**

- Istio Version: 1.10.3
- Knative Version: v1.0.0
- KFServing Version: v0.8.0
- Kubeflow version: --
- Kfdef:[k8s_istio/istio_dex/gcp_basic_auth/gcp_iap/aws/aws_cognito/ibm]
- Minikube version:
- Kubernetes version: (use `kubectl version`): v1.21.9
- OS (e.g. from `/etc/os-release`): ubuntu

**Comment by sivanantha321** [comment]
To use kserve with kubeflow you have to install it from kserve_kubeflow.yaml manifest. But quick_install.sh does not use this manifest. This script is meant for standalone installation of kserve. For installing kserve with kubeflow please, [follow the docs provided in kubeflow repository](https://github.com/kubeflow/manifests/tree/master/contrib/kserve).
