### ISSUE TITLE
storage-initializer error os.symlink(src, dest_path) 11FileExistsError: [Errno 17] File exists:

### ISSUE THREAD

**Issue by amybachir** [kserve/kserve#2354]
Our inference service pods occasionally run into an init error so the storage-initializer container restarts and gets stuck in an Init:CrashLoopBackOff when attempting to run the following:

```
[I 220726 13:08:23 storage:284] Linking: /mnt/pvc/junk-news/models/2021-09-14T00:56:33.734729/pytorch_model.bin to /mnt/models/pytorch_model.bin
4Traceback (most recent call last):
5  File "/storage-initializer/scripts/initializer-entrypoint", line 14, in <module>
6    kserve.Storage.download(src_uri, dest_path)
7  File "/usr/local/lib/python3.7/site-packages/kserve/storage.py", line 78, in download
8    return Storage._download_local(uri, out_dir)
9  File "/usr/local/lib/python3.7/site-packages/kserve/storage.py", line 285, in _download_local
10    os.symlink(src, dest_path)
11FileExistsError: [Errno 17] File exists: '/mnt/pvc/junk-news/models/2021-09-14T00:56:33.734729/pytorch_model.bin' -> '/mnt/models/pytorch_model.bin'
```

I think the `storage.py code` should handle `FileExistsError` when running `os.symlink`. Otherwise, we would have to manually delete the pod and have another one get created to fix the `Init:CrashLoopBackOff`

This can probably be accomplished by wrapping the code that calls `os.symlink` in a try-except block and pass when `FileExistsError` occurs.
I think this is the responsible line of code: 
https://github.com/kserve/kserve/blob/master/python/kserve/kserve/storage.py#L487

**Comment by yanfeng-li** [comment]
I have the same problem.

![image](https://user-images.githubusercontent.com/60999693/206647300-32550859-23a1-4148-8f59-fef5638ab52e.png)
