### ISSUE TITLE
gs://kfserving-examples/models/triton/bert-transformer does not exist

### ISSUE THREAD

**Issue by phlo46** [kserve/kserve#2356]
/kind bug

**What steps did you take and what happened:**

Apply InferenceService with: https://github.com/kserve/kserve/blob/57d4f570d3a1bf7829269526285e43d6d8418862/docs/samples/v1beta1/triton/bert/bert_v1beta1.yaml

Container storage-initializer of transformer pod cannot copy contents of `gs://kfserving-examples/models/triton/bert-transformer` to local /mnt/models because the path does not exist

**What did you expect to happen:**
Container storage-initializer of transformer pod CAN copy contents of `gs://kfserving-examples/models/triton/bert-transformer` to local /mnt/models

**Comment by yuzisun** [comment]
Uploaded the vocab.txt to `gs://kfserving-examples/models/triton/bert-transformer` now
