### ISSUE TITLE
Send inference request to TensorFlow Flowers example models cause Restart in GPU environment

### ISSUE THREAD

**Issue by IntelliJJ824** [kserve/kserve#2361]
/kind bug

**What steps did you take and what happened:**
1. I have tested on using TensorFlow example models in CPU, and everything goes well.

2. When deploying the model in GPU, it fail to process the requests. See the Yaml file I deploy:
<img width="1440" alt="Screenshot 2022-07-29 at 2 19 55 PM" src="https://user-images.githubusercontent.com/27443676/181769115-f8c66304-9cd5-4dbf-ab72-a022b488b7ae.png">

3. Here is the error we found:
<img width="1440" alt="Screenshot 2022-07-29 at 2 22 28 PM" src="https://user-images.githubusercontent.com/27443676/181769572-21be222d-0da2-4437-a238-cb645f9bd159.png">

The inference pod restart everything, when the request is sent by curl. Therefore, none of the requests have been successfully processed.

4. Further error logs and description.
Triton Pod logs:
<img width="1440" alt="Screenshot 2022-07-29 at 2 24 30 PM" src="https://user-images.githubusercontent.com/27443676/181769935-c5eed39c-356d-429f-b424-330fb3b19713.png">

Triton Pod description: there is an error reason called `OOMKilled`, may I know how to fix it?
<img width="1440" alt="Screenshot 2022-07-29 at 2 28 01 PM" src="https://user-images.githubusercontent.com/27443676/181770487-5e6b292c-7f69-4180-b5b1-d4e6cae36347.png">

**Environment:**
- KFServing Version: 0.9

**Comment by yuzisun** [comment]
@IntelliJJ824 I noticed that you are running on k9s, do you have GPU installed there? Also the default memory limit is 2Gi, you might want to bump up the memory limit if it is getting OOM error.

**Comment by IntelliJJ824** [comment]
Hi, yes, when assigning more CPU memory in the Yaml file, it works. This ticket can be safely closed.
