### ISSUE TITLE
HIGH Vulnerability found in non-os package type (java) - /usr/local/lib/python3.8/dist-packages/ray/jars/ray_dist.jar:protobuf-java (fixed in: 3.16.1)(GHSA-wrvw-hg22-4m67 - https://github.com/advisories/GHSA-wrvw-hg22-4m67)

### ISSUE THREAD

**Issue by shubamsharma** [kserve/kserve#2387]
/kind bug

**What steps did you take and what happened:**
We are getting vulnerability issue one of the kserve dependency.

**What did you expect to happen:**
Is it possible to update kserve dependency to use latest ray - 1.13.0

**Anything else you would like to add:**
Two vulnerability with current dependency for kserve
HIGH Vulnerability found in non-os package type (java) - /usr/local/lib/python3.8/dist-packages/ray/jars/ray_dist.jar:gson (fixed in: 2.8.9)(GHSA-4jrv-ppp4-jm57 - https://github.com/advisories/GHSA-4jrv-ppp4-jm57)
HIGH Vulnerability found in non-os package type (java) - /usr/local/lib/python3.8/dist-packages/ray/jars/ray_dist.jar:protobuf-java (fixed in: 3.16.1)(GHSA-wrvw-hg22-4m67 - https://github.com/advisories/GHSA-wrvw-hg22-4m67)

**Environment:**

- Istio Version:
- Knative Version:
- KFServing Version:
- Kubeflow version:
- Kfdef:[k8s_istio/istio_dex/gcp_basic_auth/gcp_iap/aws/aws_cognito/ibm]
- Minikube version:
- Kubernetes version: (use `kubectl version`):
- OS (e.g. from `/etc/os-release`):

**Comment by yuzisun** [comment]
We have upgraded ray to 2.0 now
