### ISSUE TITLE
Inference graph always returns response with Content-Type as "text/plain; charset=utf-8"

### ISSUE THREAD

**Issue by rachitchauhan43** [kserve/kserve#2401]
/kind bug

**What steps did you take and what happened:**
Created a an IG with a single ISVC as a node that is a custom predictor. This node returns JSON response body with Content-Type header as `application/json`.
Now when I call IG with this single node then IG returns response with Content-Type header as `text/plain; charset=utf-8`.

**What did you expect to happen:**
I expected Content-Type header of IG's response as `application/json`.
Ideally, IG's response should have all the characteristics of the last node's response in that IG.

**Anything else you would like to add:**
On investigating further I found that this is happening because of using ResponseWriter's `Write` method on line [L181](https://github.com/kserve/kserve/blob/master/cmd/router/main.go#L181) in router's code.
If you see [documentation of ResponseWriter's `Write`](https://go.dev/src/net/http/server.go#L120) method, the we see that , this method uses `DetectContentType` which uses https://mimesniff.spec.whatwg.org/ algorithm.
And this algorithm can't determine `application/json` and hence IG returns Content-Type as `text/plain; charset=utf-8`.
See this [issue](https://github.com/golang/go/issues/10630)

**Environment:**

- Istio Version: 1.13
- Knative Version: 1.4.0
- KServe Version: 0.9.0
- Kubeflow version: NA
- Kfdef:[k8s_istio/istio_dex/gcp_basic_auth/gcp_iap/aws/aws_cognito/ibm]
- Minikube version: NA
- Kubernetes version: (use `kubectl version`): v1.21.13-eks-84b4fe6
- OS (e.g. from `/etc/os-release`):

**Comment by tanvithakur94** [comment]
Please assign this issue to me.
