### ISSUE TITLE
kserve not able to handle built-in registry having colon e.g 10.10.10.10:3000/kserve/tensorflow:1.14.0

### ISSUE THREAD

**Issue by shubamsharma** [kserve/kserve#2416]
/kind bug

**What steps did you take and what happened:**
Inference is not working on using built-in registry having colon

Expected Image tag - 10.10.10.10:3000/kserve/tensorflow:1.14.0
kserve image tag - 10.10.10.10:1.14.0

**What did you expect to happen:**
Kserve should replace runtime version for text after the last colon

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]
Issue file - https://github.com/kserve/kserve/blob/master/pkg/controller/v1beta1/inferenceservice/utils/utils.go

// UpdateImageTag Update image tag if GPU is enabled or runtime version is provided
func UpdateImageTag(container *v1.Container, runtimeVersion *string, isvcConfig *v1beta1.InferenceServicesConfig) {
	image := container.Image
	if runtimeVersion != nil {
		re := regexp.MustCompile(`(:([\w.\-_]*))$`)
		if len(re.FindString(image)) == 0 {
			container.Image = image + ":" + *runtimeVersion
		} else {
			container.Image = re.ReplaceAllString(image, ":"+*runtimeVersion)
		}
		return
	}
	if utils.IsGPUEnabled(container.Resources) && len(strings.Split(image, ":")) > 0 {
		**imageName := strings.Split(image, ":")[0]  #Code which requires fix** 
		if imageName == isvcConfig.Predictors.Tensorflow.ContainerImage {
			container.Image = imageName + ":" + isvcConfig.Predictors.Tensorflow.DefaultGpuImageVersion
		} else if imageName == isvcConfig.Predictors.PyTorch.ContainerImage {
			container.Image = imageName + ":" + isvcConfig.Predictors.PyTorch.DefaultGpuImageVersion
		}
	}
}

**Environment:**

- Istio Version:
- Knative Version:
- KFServing Version: kserve 0.8
- Kubeflow version: 1.5
- Kfdef:[k8s_istio/istio_dex/gcp_basic_auth/gcp_iap/aws/aws_cognito/ibm]
- Minikube version:
- Kubernetes version: (use `kubectl version`):
- OS (e.g. from `/etc/os-release`):

**Comment by shubamsharma** [comment]
@jagadeeshi2i @yuzisun, Issue mentioned above limits offline deployment with built-in registry so update to support image tag with multiple colon will surely help here.

Many thanks in advance.

**Comment by yuzisun** [comment]
Should be fixed in https://github.com/kserve/kserve/commit/33bb7afdbf3daee77a3a4bf058473aa1ad7f5397
