### ISSUE TITLE
KServe v0.9 helm updated CRDs without incrementing version

### ISSUE THREAD

**Issue by dagondagon666** [kserve/kserve#2419]
Hi there, I noticed that a few CRDs got updated from v0.8 -> v0.9 (i.e. `protocolVersions` is introduced to `v1alpha1.ServingRuntime` and the versions still remain the same as `v1alpha1` or `v1beta1`. This causes `helm upgrade` fail as helm upgrades doesn’t update CRDs with same version. While we could just manually upgrade the CRDs and then perform the `helm upgrade`. I’m wondering if there’s a specific reason for not upgrading the CRD version when updating CRDs? 

If we decide to not upgrading CRD version, then maybe we should have this caveat (as well as maybe [Helm's reasoning](https://github.com/helm/community/blob/main/hips/hip-0011.md)) under the `charts/` so that users who use Helm to maintain their KServe installation know in advance.

**Comment by yuzisun** [comment]
agreed, that's the item we wanted to address before we officially support the helm installation option.

**Comment by dagondagon666** [comment]
When would we consider helm installation to be officially supported? We could help in some improvements if you already have a criteria in mind.

**Comment by yuzisun** [comment]
@dagondagon666 KServe 0.10 has separated out the crd chart so the version should be upgraded now
