### ISSUE TITLE
Problems with go when deploying Kserve in my development environment

### ISSUE THREAD

**Issue by oyy2000** [kserve/kserve#2422]
/kind bug

**What steps did you take and what happened:**
[A clear and concise description of what the bug is.]
1. I'm trying to follow the Developer Guide in https://kserve.github.io/website/master/developer/developer/
2. I've configured all the knative things and try to deploy kserve in my development environment.

**What did you expect to happen:**
I run make deploy in ${GOPATH}/src/github.com/kserve/kserve but the error below happened.
Go version 1.17.13:
![image](https://user-images.githubusercontent.com/56588848/190051513-a13f6b1e-fe37-436c-9403-47fe5b1f94a3.png)

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

In the same directory, using go version 1.18 or 1.19:
<img width="827" alt="image" src="https://user-images.githubusercontent.com/56588848/190051638-92e6658c-7aab-4939-8aa7-658a2724b244.png">
<img width="1300" alt="image" src="https://user-images.githubusercontent.com/56588848/190051657-e887f3b9-687e-461c-8f8e-f1596f69ec96.png">
 
**Environment:**

- Istio Version:  1.14.0
- Knative Version: 
<img width="780" alt="image" src="https://user-images.githubusercontent.com/56588848/190047747-9c4ecfae-887b-4b45-a60c-42ac328a026f.png">
- KFServing Version:
- Kubeflow version:
- Kfdef:[k8s_istio/istio_dex/gcp_basic_auth/gcp_iap/aws/aws_cognito/ibm]
- Minikube version: 
- Kubernetes version: (use `kubectl version`): 
- OS (e.g. from `/etc/os-release`): ubuntu 18.04.6
- GO version: 1.17.13 1.18.6 1.19

**Comment by yuzisun** [comment]
We just upgraded to go 1.18 a few days ago, `make deploy` should install `controller-gen` to your local kserve bin directory.
It works for me though, see logs below.
```
make deploy
test -s /Users/dsun20/github/test/kserve/bin/controller-gen || GOBIN=/Users/dsun20/github/test/kserve/bin go install sigs.k8s.io/controller-tools/cmd/controller-gen@v0.4.0
/Users/dsun20/github/test/kserve/bin/controller-gen "crd:maxDescLen=0" paths=./pkg/apis/serving/... output:crd:dir=config/crd
/Users/dsun20/github/test/kserve/bin/controller-gen rbac:roleName=kserve-manager-role paths=./pkg/controller/... output:rbac:artifacts:config=config/rbac
/Users/dsun20/github/test/kserve/bin/controller-gen object:headerFile="hack/boilerplate.go.txt" paths=./pkg/apis/serving/v1alpha1
/Users/dsun20/github/test/kserve/bin/controller-gen object:headerFile="hack/boilerplate.go.txt" paths=./pkg/apis/serving/v1beta1
```

**Comment by oyy2000** [comment]
> We just upgraded to go 1.18 a few days ago, `make deploy` should install `controller-gen` to your local kserve bin directory. It works for me though, see logs below.
> 
> ```
> make deploy
> test -s /Users/dsun20/github/test/kserve/bin/controller-gen || GOBIN=/Users/dsun20/github/test/kserve/bin go install sigs.k8s.io/controller-tools/cmd/controller-gen@v0.4.0
> /Users/dsun20/github/test/kserve/bin/controller-gen "crd:maxDescLen=0" paths=./pkg/apis/serving/... output:crd:dir=config/crd
> /Users/dsun20/github/test/kserve/bin/controller-gen rbac:roleName=kserve-manager-role paths=./pkg/controller/... output:rbac:artifacts:config=config/rbac
> /Users/dsun20/github/test/kserve/bin/controller-gen object:headerFile="hack/boilerplate.go.txt" paths=./pkg/apis/serving/v1alpha1
> /Users/dsun20/github/test/kserve/bin/controller-gen object:headerFile="hack/boilerplate.go.txt" paths=./pkg/apis/serving/v1beta1
> ```

It will send out the error I've attached above. The downloading of controller-gen was not successful.

**Comment by shubamsharma** [comment]
I am also trying to deploy kserve in my development environment but getting below issue

[root@master kserve]# make deploy
/root/go/src/github.com/kserve/kserve/bin/controller-gen "crd:maxDescLen=0" paths=./pkg/apis/serving/... output:crd:dir=config/crd
/root/go/src/github.com/kserve/kserve/bin/controller-gen rbac:roleName=kserve-manager-role paths=./pkg/controller/... output:rbac:artifacts:config=config/rbac
/root/go/src/github.com/kserve/kserve/bin/controller-gen object:headerFile="hack/boilerplate.go.txt" paths=./pkg/apis/serving/v1alpha1
/root/go/src/github.com/kserve/kserve/bin/controller-gen object:headerFile="hack/boilerplate.go.txt" paths=./pkg/apis/serving/v1beta1
......
......
......
......
mutatingwebhookconfiguration.admissionregistration.k8s.io/inferenceservice.serving.kserve.io configured
validatingwebhookconfiguration.admissionregistration.k8s.io/inferencegraph.serving.kserve.io configured
validatingwebhookconfiguration.admissionregistration.k8s.io/inferenceservice.serving.kserve.io configured
validatingwebhookconfiguration.admissionregistration.k8s.io/trainedmodel.serving.kserve.io configured
Error from server (Invalid): error when creating "STDIN": CustomResourceDefinition.apiextensions.k8s.io "clusterservingruntimes.serving.kserve.io" is invalid: spec.validation.openAPIV3Schema.properties[spec].properties[containers].items.properties[ports].items.properties[protocol].default: Required value: this property is in x-kubernetes-list-map-keys, so it must have a default or be a required property
Error from server (Invalid): error when creating "STDIN": CustomResourceDefinition.apiextensions.k8s.io "inferenceservices.serving.kserve.io" is invalid: [metadata.annotations: Too long: must have at most 262144 bytes, spec.validation.openAPIV3Schema.properties[spec].properties[explainer].properties[art].properties[ports].items.properties[protocol].default: Required value: this property is in x-kubernetes-list-map-keys, so it must have a default or be a required property, spec.validation.openAPIV3Schema.properties[spec].properties[explainer].properties[ephemeralContainers].items.properties[ports].items.properties[protocol].default: Required value: this property is in x-kubernetes-list-map-keys, so it must have a default or be a required property, spec.validation.openAPIV3Schema.properties[spec].properties[explainer].properties[containers].items.properties[ports].items.properties[protocol].default: Required value: this property is in x-kubernetes-list-map-keys, so it must have a default or be a required property, spec.validation.openAPIV3Schema.properties[spec].properties[explainer].properties[alibi].properties[ports].items.properties[protocol].default: Required value: this property is in x-kubernetes-list-map-keys, so it must have a default or be a required property, spec.validation.openAPIV3Schema.properties[spec].properties[explainer].properties[initContainers].items.properties[ports].items.properties[protocol].default: Required value: this property is in x-kubernetes-list-map-keys, so it must have a default or be a required property, spec.validation.openAPIV3Schema.properties[spec].properties[explainer].properties[aix].properties[ports].items.properties[protocol].default: Required value: this property is in x-kubernetes-list-map-keys, so it must have a default or be a required property, spec.validation.openAPIV3Schema.properties[spec].properties[predictor].properties[paddle].properties[ports].items.properties[protocol].default: Required value: this property is in x-kubernetes-list-map-keys, so it must have a default or be a required property, spec.validation.openAPIV3Schema.properties[spec].properties[predictor].properties[xgboost].properties[ports].items.properties[protocol].default: Required value: this property is in x-kubernetes-list-map-keys, so it must have a default or be a required property, spec.validation.openAPIV3Schema.properties[spec].properties[predictor].properties[pmml].properties[ports].items.properties[protocol].default: Required value: this property is in x-kubernetes-list-map-keys, so it must have a default or be a required property, spec.validation.openAPIV3Schema.properties[spec].properties[predictor].properties[lightgbm].properties[ports].items.properties[protocol].default: Required value: this property is in x-kubernetes-list-map-keys, so it must have a default or be a required property, spec.validation.openAPIV3Schema.properties[spec].properties[predictor].properties[model].properties[ports].items.properties[protocol].default: Required value: this property is in x-kubernetes-list-map-keys, so it must have a default or be a required property, spec.validation.openAPIV3Schema.properties[spec].properties[predictor].properties[ephemeralContainers].items.properties[ports].items.properties[protocol].default: Required value: this property is in x-kubernetes-list-map-keys, so it must have a default or be a required property, spec.validation.openAPIV3Schema.properties[spec].properties[predictor].properties[tensorflow].properties[ports].items.properties[protocol].default: Required value: this property is in x-kubernetes-list-map-keys, so it must have a default or be a required property, spec.validation.openAPIV3Schema.properties[spec].properties[predictor].properties[pytorch].properties[ports].items.properties[protocol].default: Required value: this property is in x-kubernetes-list-map-keys, so it must have a default or be a required property, spec.validation.openAPIV3Schema.properties[spec].properties[predictor].properties[triton].properties[ports].items.properties[protocol].default: Required value: this property is in x-kubernetes-list-map-keys, so it must have a default or be a required property, spec.validation.openAPIV3Schema.properties[spec].properties[predictor].properties[containers].items.properties[ports].items.properties[protocol].default: Required value: this property is in x-kubernetes-list-map-keys, so it must have a default or be a required property, spec.validation.openAPIV3Schema.properties[spec].properties[predictor].properties[initContainers].items.properties[ports].items.properties[protocol].default: Required value: this property is in x-kubernetes-list-map-keys, so it must have a default or be a required property, spec.validation.openAPIV3Schema.properties[spec].properties[predictor].properties[sklearn].properties[ports].items.properties[protocol].default: Required value: this property is in x-kubernetes-list-map-keys, so it must have a default or be a required property, spec.validation.openAPIV3Schema.properties[spec].properties[predictor].properties[onnx].properties[ports].items.properties[protocol].default: Required value: this property is in x-kubernetes-list-map-keys, so it must have a default or be a required property, spec.validation.openAPIV3Schema.properties[spec].properties[transformer].properties[containers].items.properties[ports].items.properties[protocol].default: Required value: this property is in x-kubernetes-list-map-keys, so it must have a default or be a required property, spec.validation.openAPIV3Schema.properties[spec].properties[transformer].properties[initContainers].items.properties[ports].items.properties[protocol].default: Required value: this property is in x-kubernetes-list-map-keys, so it must have a default or be a required property, spec.validation.openAPIV3Schema.properties[spec].properties[transformer].properties[ephemeralContainers].items.properties[ports].items.properties[protocol].default: Required value: this property is in x-kubernetes-list-map-keys, so it must have a default or be a required property]
Error from server (Invalid): error when creating "STDIN": CustomResourceDefinition.apiextensions.k8s.io "servingruntimes.serving.kserve.io" is invalid: spec.validation.openAPIV3Schema.properties[spec].properties[containers].items.properties[ports].items.properties[protocol].default: Required value: this property is in x-kubernetes-list-map-keys, so it must have a default or be a required property
make: *** [deploy] Error 1
[root@master kserve]#

**Comment by nguyenthai0107** [comment]
Hello @shubamsharma  
Im facing same exactly error, Did you resolve this?
