### ISSUE TITLE
Can't install KServe on local machine with quick installation

### ISSUE THREAD

**Issue by Inkorak** [kserve/kserve#2432]
/kind bug

**What steps did you take and what happened:**
Trying install the KServe "Quickstart" environment with 
curl -s "https://raw.githubusercontent.com/kserve/kserve/release-0.9/hack/quick_install.sh" | bash

  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   101  100   101    0     0    222      0 --:--:-- --:--:-- --:--:--   221
100  4856  100  4856    0     0   5505      0 --:--:-- --:--:-- --:--:--  5505

Downloading istio-1.14.0 from https://github.com/istio/istio/releases/download/1.14.0/istio-1.14.0-linux-amd64.tar.gz ...

Istio 1.14.0 Download Complete!

Istio has been successfully downloaded into the istio-1.14.0 folder on your system.

Next Steps:
See https://istio.io/latest/docs/setup/install/ to add Istio to your Kubernetes cluster.

To configure the istioctl client tool for your workstation,
add the /home/user/istio-1.14.0/bin directory to your environment path variable with:
	 export PATH="$PATH:/home/user/istio-1.14.0/bin"

Begin the Istio pre-installation check by running:
	 istioctl x precheck 

Need more information? Visit https://istio.io/latest/docs/setup/install/ 
namespace/istio-system unchanged
✔ Istio core installed                                                                                                                                                   
- Processing resources for Istiod.                                                                                                                                       2022-09-20T02:15:49.632161Z	error	installer	failed to update resource with server-side apply for obj PodDisruptionBudget/istio-system/istiod: no matches for kind "PodDisruptionBudget" in version "policy/v1beta1"
✘ Istiod encountered an error: failed to update resource with server-side apply for obj PodDisruptionBudget/istio-system/istiod: no matches for kind "PodDisruptionBudget" in version "policy/v1beta1"
- Processing resources for Ingress gateways.                                                                                                                             2022-09-20T02:15:49.657749Z	error	installer	failed to update resource with server-side apply for obj PodDisruptionBudget/istio-system/istio-ingressgateway: no matches for kind "PodDisruptionBudget" in version "policy/v1beta1"
✘ Ingress gateways encountered an error: failed to update resource with server-side apply for obj PodDisruptionBudget/istio-system/istio-ingressgateway: no matches for kind "PodDisruptionBudget" in version "policy/v1beta1"
- Pruning removed resources                                                                                                                                              2022-09-20T02:15:49.705049Z	warn	installer	retrieving resources to prune type autoscaling/v2beta1, Kind=HorizontalPodAutoscaler: no matches for kind "HorizontalPodAutoscaler" in version "autoscaling/v2beta1"
2022-09-20T02:15:50.190390Z	warn	installer	retrieving resources to prune type policy/v1beta1, Kind=PodDisruptionBudget: no matches for kind "PodDisruptionBudget" in version "policy/v1beta1"
Error: failed to install manifests: errors occurred during operation
root@ml2070s:/home/user# ^C

**Environment:**

- Istio Version:
- Knative Version:
- KFServing Version:
- Kubeflow version:
- Kfdef:[k8s_istio/istio_dex/gcp_basic_auth/gcp_iap/aws/aws_cognito/ibm]
- Minikube version:
- Kubernetes version: (use `kubectl version`):
Client Version: version.Info{Major:"1", Minor:"25", GitVersion:"v1.25.1", GitCommit:"e4d4e1ab7cf1bf15273ef97303551b279f0920a9", GitTreeState:"clean", BuildDate:"2022-09-16T02:32:15Z", GoVersion:"go1.19", Compiler:"gc", Platform:"linux/amd64"}
Kustomize Version: v4.5.7
Server Version: version.Info{Major:"1", Minor:"25", GitVersion:"v1.25.0", GitCommit:"a866cbe2e5bbaa01cfd5e969aa3e033f3282a8a2", GitTreeState:"clean", BuildDate:"2022-09-01T23:30:43Z", GoVersion:"go1.19", Compiler:"gc", Platform:"linux/amd64"}
- OS (e.g. from `/etc/os-release`): Ubuntu 20.04.4 LTS

**Comment by yuzisun** [comment]
@Inkorak I see you are running with Kube 1.25, you would need to install the latest Istio 1.15 in that case, the quick install uses 1.14 which does not work for 1.25 as `policy/v1beta1` is deprecated.

**Comment by Inkorak** [comment]
@yuzisun Thank you. Everything is working now.

**Comment by Inkorak** [comment]
@yuzisun Do I need to change apiVersion: "serving.kserve.io/v1beta1" in yaml?

**Comment by yuzisun** [comment]
No that’s not needed.
