### ISSUE TITLE
Connect InferenceServices deployed on different kubernetes clusters

### ISSUE THREAD

**Issue by rajeshdhanda** [kserve/kserve#2442]
I want to connect **InferenceService_1** in kubernetes cluster ( **region_1** )  to **InferenceService_2** in kubernetes cluster ( **region_2** ). Facing the same issue for inferenceservice deployed in model mesh. Couldn't find anything related to this in docs.

Thanks.

**Comment by yuzisun** [comment]
@rajeshdhanda Can you elaborate more on what "connect" means here?
