### ISSUE TITLE
Kserve endpoint does not work if modelname contains `.`

### ISSUE THREAD

**Issue by f4hy** [kserve/kserve#2447]
/kind bug

**What steps did you take and what happened:**
[A clear and concise description of what the bug is.]

I deployed a model where I wanted to include the version of the model in the model name. This version was `1.0.1` so my model was `mycoolmodel-v1.0.1`. However this made reaching the endpoint for predict not work due to https://github.com/kserve/kserve/blob/master/python/kserve/kserve/model_server.py#L100 not including `.` in the regex.

**What did you expect to happen:**

If `.` is not supported, it should have at least errored rather than looking like it deployed successfully. Ideally endpoints should work fine with models that include `.` in their name.

**Anything else you would like to add:**

I think this could be fixed by just adding `\.` to the regex https://github.com/kserve/kserve/blob/master/python/kserve/kserve/model_server.py#L100 so 
`([a-zA-Z0-9_-]+)` -> `([a-zA-Z0-9_-\.]+)`

**Environment:**

- Istio Version:
- Knative Version:
- KFServing Version: 0.9.0
- Kubeflow version:
- Kfdef:[k8s_istio/istio_dex/gcp_basic_auth/gcp_iap/aws/aws_cognito/ibm]
- Minikube version:
- Kubernetes version: (use `kubectl version`):
- OS (e.g. from `/etc/os-release`):

**Comment by yuzisun** [comment]
Fixed in 0.10
