### ISSUE TITLE
Upgrade to yq v4?

### ISSUE THREAD

**Issue by jvujjini** [kserve/kserve#2460]
/kind bug

**What steps did you take and what happened:**
`make test` fails at yq with `Error: 1:1: invalid input text "d"`.

**What did you expect to happen:**
I did see in the instructions that the recommended version to install is v3 for this specific reason, but it looks like the Apple Silicone compatible binaries arent built for yq v3. Is it time to think about moving to a newer version of yq?

**Environment:**

- Kubernetes version: (use `kubectl version`): `v1.25.0`
- OS (e.g. from `/etc/os-release`): `macOS 12.5.1 (21G83) Darwin 21.6.0`

**Comment by jvujjini** [comment]
@yuzisun Is it ok to do this now? Just want to know if there is anything else thats blocking this.

**Comment by yuzisun** [comment]
> @yuzisun Is it ok to do this now? Just want to know if there is anything else thats blocking this.

@jagan120 nothing is blocking this, just need work to convert to use yq 4 as there are quite a few things changed.

**Comment by jvujjini** [comment]
I can give it a shot and see how it goes
