### ISSUE TITLE
`make undeploy` hangs for a long time. 

### ISSUE THREAD

**Issue by sindhuvahinis** [kserve/kserve#2470]
/kind bug

https://kserve.github.io/website/0.9/developer/developer/#run-e2e-tests-locally

Trying to run end to end testing locally in my Ubuntu environment. When I do `make undeploy` it hangs for a long time. Is it expected? 

I stopped the un-deploy command abruptly, now I get Internal error in my Inferenceservice. 

<img width="893" alt="Screen Shot 2022-10-12 at 4 46 36 PM" src="https://user-images.githubusercontent.com/56774226/195467905-ad198f38-f4ba-4e98-8e21-a29d6dca8695.png">

**Comment by sivanantha321** [comment]
@sindhuvahinis If you uninstall kserve before deleting any kserve resources (i.e) inferenceservice/inferencegraph the command will hang.
