### ISSUE TITLE
S3 storage initializer doesn't work as expected for file without extension

### ISSUE THREAD

**Issue by lizzzcai** [kserve/kserve#2473]
/kind bug

**What steps did you take and what happened:**
[A clear and concise description of what the bug is.]

I created the following files in my s3 bucket:
```
test/churn-pickle
test/churn-pickle-logs
test/churn-pickle-report
```
`churn-pickle`, `churn-pickle-logs` and `churn-pickle-report` are `file` without `extension`.

I use storage initializer to download `s3://<bucket>/test/churn-pickle` to `/mnt/models`. However, I got the following result:

```
❯ ls /mnt/models
total 24
-rw-r--r--  1 i543026  staff    12B 14 Oct 19:25 -logs
-rw-r--r--  1 i543026  staff    12B 14 Oct 19:25 -report
-rw-r--r--  1 i543026  staff    12B 14 Oct 19:25 churn-pickle
```

**What did you expect to happen:**

1. if the given path is a `file`, only the file is downloaded. In this case, `s3://<bucket>/test/churn-pickle` will be downloaded to `/mnt/models/churn-pickle`.
2. If the given path is a `folder`, all the files under the folder will be downloaded. 
3. If the given path is a `prefix` (not a folder or file), nothing should be downloaded.

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

I assume that the storage initializer can only download from folders and files, not from `prefix`.

The issue was probably caused by:
1. objects are filter by the [prefix](https://github.com/kserve/kserve/blob/master/python/kserve/kserve/storage.py#L167).
2. replace logic [here](https://github.com/kserve/kserve/blob/master/python/kserve/kserve/storage.py#L167).

**Environment:**

- Istio Version:
- Knative Version:
- KFServing Version: 0.9
- Kubeflow version:
- Kfdef:[k8s_istio/istio_dex/gcp_basic_auth/gcp_iap/aws/aws_cognito/ibm]
- Minikube version:
- Kubernetes version: (use `kubectl version`): v1.21.14
- OS (e.g. from `/etc/os-release`):

**Comment by lizzzcai** [comment]
even with the extension, it will not work as expected.

for example, if you have path `path/file.txt` , but there are `path/file.txt-1`, `path/file.txt-2`  and `path/file.txt` , then beside path/file.txt there will be files named `-1`  and `-2`  being downloaded.

**Comment by ckadner** [comment]
@lizzzcai any chance you tried this with ModelMesh? I'm curious if we have similar bugs there.

**Comment by lizzzcai** [comment]
> @lizzzcai any chance you tried this with ModelMesh? I'm curious if we have similar bugs there.

Hi @ckadner , sorry for the late reply. I did a quick test.

with the following files:
```
sklearn2/mnist-svm-joblib
sklearn2/mnist-svm-joblib-logs
sklearn2/mnist-svm-joblib-report
```

and isvc:
```
apiVersion: serving.kserve.io/v1beta1
kind: InferenceService
metadata:
  name: example-sklearn-isvc
  annotations:
    serving.kserve.io/deploymentMode: ModelMesh
spec:
  predictor:
    model:
      modelFormat:
        name: sklearn
      storage:
        key: localMinIO
        path: sklearn2/mnist-svm-joblib
```
logs:
```
1.6945155976098053e+09  INFO    MLServer Adapter.MLServer Adapter Server.LoadModel      Model details   {"modelId": "example-sklearn-isvc__isvc-8dee2e5911", "modelType": "sklearn", "modelPath": "sklearn2/mnist-svm-joblib"}
1.6945155976101086e+09  DEBUG   MLServer Adapter.MLServer Adapter Server        Reading storage credentials
1.6945155976103303e+09  DEBUG   MLServer Adapter.MLServer Adapter Server        creating new repository client  {"type": "s3", "cacheKey": "s3|0x33b60418eef4115e"}
1.6945155976411862e+09  DEBUG   MLServer Adapter.MLServer Adapter Server        ignore downloading s3 object with prefix not followed by a slash      {"type": "s3", "cacheKey": "s3|0x33b60418eef4115e", "prefix": "sklearn2/mnist-svm-joblib", "s3_path": "sklearn2/mnist-svm-joblib-logs"}
1.6945155976413112e+09  DEBUG   MLServer Adapter.MLServer Adapter Server        ignore downloading s3 object with prefix not followed by a slash      {"type": "s3", "cacheKey": "s3|0x33b60418eef4115e", "prefix": "sklearn2/mnist-svm-joblib", "s3_path": "sklearn2/mnist-svm-joblib-report"}
1.694515597641396e+09   DEBUG   MLServer Adapter.MLServer Adapter Server        found objects to download       {"type": "s3", "cacheKey": "s3|0x33b60418eef4115e", "path": "sklearn2/mnist-svm-joblib", "count": 1}
1.694515597641625e+09   DEBUG   MLServer Adapter.MLServer Adapter Server        downloading object      {"type": "s3", "cacheKey": "s3|0x33b60418eef4115e", "path": "sklearn2/mnist-svm-joblib", "filename": "/models/example-sklearn-isvc__isvc-8dee2e5911/mnist-svm-joblib"}
```

it is working fine.

**Comment by ckadner** [comment]
@lizzzcai -- thank you for verifying this on ModelMesh!
