### ISSUE TITLE
Calling a transformer using GRPC

### ISSUE THREAD

**Issue by Naegionn** [kserve/kserve#2482]
Hi,

I am struggling to find the answer to following question:
Is it possible to create a transformer that:
  1. not only uses grpc to call the predictor (that part I got working)
  2. but can also be called using grpc. 

I am unable to find documentation indicating how to set the transformer up this way.

Thanks a lot

**Comment by yuzisun** [comment]
@Naegionn PR soon to be merged to support gRPC for transformer
https://github.com/kserve/kserve/pull/2415

**Comment by Naegionn** [comment]
Good to know, Thanks
