### ISSUE TITLE
Making HTTP calls to local InferenceGraph

### ISSUE THREAD

**Issue by MichalPitr** [kserve/kserve#2497]
Hi folks,

I'm following [this](https://github.com/kserve/kserve/tree/master/docs/samples/graph) guide to setup the iris sequence inference graph. My graph is running and I can make requests to its inference services succesfully, but I can't figure out how to make an http request to the graph itself. I am developing locally and would like to just use port forwarding. 

The provided guide uses `curl http://model-chainer.default.10.166.15.29.sslip.io -d @./iris-input.json`, but I don't have DNS setup. Could someone point me to how to achieve the same using the Ingress gateway with host header? 

I tried the below without success.
`curl -v -H "Host: ${SERVICE_HOSTNAME}" http://${INGRESS_HOST}:${INGRESS_PORT} -d @./iris-input.json`

Many thanks! Appreciate it.

**Comment by rachitchauhan43** [comment]
First do port-forwarding like this:
```INGRESS_GATEWAY_SERVICE=$(kubectl get svc --namespace istio-system --selector="app=istio-ingressgateway" --output jsonpath='{.items[0].metadata.name}')
kubectl port-forward --namespace istio-system svc/${INGRESS_GATEWAY_SERVICE} 8080:80
# start another terminal
export INGRESS_HOST=localhost
export INGRESS_PORT=8080
```

Then, make a call:
```curl -v -H "Host: ${IG_NAME}.${NAMESPACE}.svc.cluster.local" http://localhost:8080/v1/inferencegraphs/${IG_NAME} -d @./input.json -v```

**Comment by MichalPitr** [comment]
Many thanks @rachitchauhan43 ! Didn't see the `/v1/inferencegraphs/{name}` api documented anywhere so that's super useful!

Oddly enough, I still can't get it running. I've attached my terminal output below, any idea what it could be?

I'm running kserve installed with quick_start.sh from master, minikube 1.26 (also tried kind, same outcome). Otherwise I'm just using the `sequence.yaml` file from the guide linked in the previous post. 

istion ingress gateway
```
(base) michal@gala1-G482-Z54-00:~/kservekubectl get svc istio-ingressgateway -n istio-system
NAME                   TYPE           CLUSTER-IP     EXTERNAL-IP   PORT(S)                                      AGE
istio-ingressgateway   LoadBalancer   10.103.93.84   <pending>     15021:32138/TCP,80:32011/TCP,443:30779/TCP   24m
```

Status of the inference graph and its isvcs
```
(base) michal@gala1-G482-Z54-00:~/kserve$ kubectl get pods -n dag
NAME                                                              READY   STATUS    RESTARTS   AGE
model-chainer-00001-deployment-565c94f6df-9mfbl                   2/2     Running   0          11m
sklearn-iris-predictor-default-00001-deployment-cb9656b89-rsmk9   2/2     Running   0          14m
xgboost-iris-predictor-default-00001-deployment-5c544fd775h9s2p   2/2     Running   0          14m
```

setting env vars
```
export INGRESS_HOST=localhost
export INGRESS_PORT=8080
export IG_NAME=model-chainer
export NAMESPACE=dag
```

Posting input to the endpoit
```
(base) michal@gala1-G482-Z54-00:~/kserve$ curl -v -H "Host: ${IG_NAME}.${NAMESPACE}.svc.cluster.local" http://localhost:8080/v1/inferencegraphs/${IG_NAME} -d @./input.json
*   Trying 127.0.0.1:8080...
* TCP_NODELAY set
* Connected to localhost (127.0.0.1) port 8080 (#0)
> POST /v1/inferencegraphs/model-chainer HTTP/1.1
> Host: model-chainer.dag.svc.cluster.local
> User-Agent: curl/7.68.0
> Accept: */*
> Content-Length: 86
> Content-Type: application/x-www-form-urlencoded
> 
* upload completely sent off: 86 out of 86 bytes
* Mark bundle as not supporting multiuse
< HTTP/1.1 404 Not Found
< date: Wed, 02 Nov 2022 13:37:04 GMT
< server: istio-envoy
< connection: close
< content-length: 0
< 
* Closing connection 0
```

My other terminal running the port forwarding only logs "Handling connecting for 8080" whenever I try to post to the IG. 


Would be grateful for any pointers!

**Comment by MichalPitr** [comment]
I found a solution, turns out my `IG_HOSTNAME` doesn't use the".svc.cluster.local" domain, but ".example.com".

```
export IG_HOSTNAME=$(kubectl get ig model-chainer -n dag -o jsonpath='{.status.url}' | cut -d "/" -f 3)
curl -v -H "Host: ${IG_HOSTNAME}" http://${INGRESS_HOST}:${INGRESS_PORT}/v1/inferencegraphs/model-chainer -d @./input.json
```

This now correctly outputs `{"predictions": [1.0, 1.0]}`

Thanks for your assistance!

**Comment by rachitchauhan43** [comment]
@MichalPitr : Can you close this if this is resolved for you ?

**Comment by MichalPitr** [comment]
@rachitchauhan43 Yes, closing!
