### ISSUE TITLE
InferenceService Deployments cannot scale beyond 1 replica due to Reconciliation

### ISSUE THREAD

**Issue by DanielTemesgen** [kserve/kserve#2521]
/kind bug

What steps did you take and what happened:
`InferenceService` Deployments fail to autoscale beyond 1 replica if other non-kserve controllers inject labels/annotations in deployment after it is deployed.

When deploying an `InferenceService` in `RawDeployment` mode:
1. KServe controller-manager creates the set of resources for the KServe application (Deployment, Service, HPA)
2. After the Deployment is created, another non-kserve controller adds its labels and annotations.
3. This annotation/label injection triggers Deployment Reconciliation.
4. The reconciled change is immediately overwritten by the non-kserve controller which re-adds its labels/annotations.
5. Step 3 occurs, preventing deployments from scaling beyond 1 replica.

What did you expect to happen:
1. KServe to ignore non-KServe labels and annotations during the Deployment Reconciliation process.
2. The ability to configure which parts of the `DeploymentSpec` are ignored for the purposes of Reconciliation e.g.`“Template.Spec.ServiceAccountName”`

We have an in-house patch which solves this issue by addressing the points above, which involves only considering KServe annotations and labels during reconciliation and adding more fields to the ignored fields during comparison.

Environment:
- Istio Version: 1.14.1
- KFServing Version: 0.9.0
- Kubernetes version: (use `kubectl version`): `Server Version: version.Info{Major:“1", Minor:“21+“, GitVersion:“v1.21.14-eks-fb459a0”, GitCommit:“b07006b2e59857b13fe5057a956e86225f0e82b7", GitTreeState:“clean”, BuildDate:“2022-10-24T20:32:54Z”, GoVersion:“go1.16.15”, Compiler:“gc”, Platform:“linux/amd64”}`

**Comment by tdoublep** [comment]
@DanielTemesgen I am facing the exact same issue. Would it be possible to share any info on your workaround?

**Comment by DanielTemesgen** [comment]
Hi @tdoublep, the workaround has two parts, firstly we include more fields in the list of `ignoreFields` [here](https://github.com/kserve/kserve/blob/377a39a813fa9f8d98afcc8c4cfabbbe6adbd61f/pkg/controller/v1beta1/inferenceservice/reconcilers/deployment/deployment_reconciler.go#L100), this stops the reconciliation for the affected fields which are not labels and annotations. For the labels and annotations themselves we create a [`Comparer`](https://pkg.go.dev/github.com/google/go-cmp/cmp#Comparer) object which only compares the relevant KServe annotations and labels.

Also apologies for the late reply on this, I was OOO.

**Comment by sivanantha321** [comment]
fixed by 
- https://github.com/kserve/kserve/pull/2279
