### ISSUE TITLE
Example to integrate with Fluid to Accelerate KServe Scaling via Model Artifact Caching

### ISSUE THREAD

**Issue by lizzzcai** [kserve/kserve#2529]
**Motivation**

In model serving use case, an application usually contains a model artifact and a servingruntime (main user container). 
Referring to the design of KServe, the user usually provides the model artifact via `storageUri` and defines the `modelFormat` which will leverage the matched servngruntime to serve the model. Before the servingruntime start serving the model, the `storage-initializer`(init container) will download the model artifact from remote storage (usually a cloud object store) to the shared local storage with the servingruntime container. 

As KServe support `serverless`, so every time when an inference service `scales up` from 0 to N, the storage-initializer will kick in to download the model artifact from the remote storage, and usually, the model artifact size varies from MBs to GBs which causes unnecessary bandwidth usage and increase the `cold start` time (A typical `1 GB` model usually take around `1 min+` to download from cloud storage like S3 via storage initializer). It will be very challenging for a user to wait 1 min (not including the image download and request process time) for the first response under serverless mode.

If we can pull the model artifact from a distributed cache (near the cluster) rather than download it from remote cloud storage every time the application scale up, it will help to improve the serverless performance. 

**Describe the solution you'd like**

Introduce [Fluid](https://fluid-cloudnative.github.io/) which is a cloud native distributed dataset orchestrator and accelerator for data-intensive applications as an `example and practice` to reduce the data access time and improve the serverless performance. 

Scopes of this topic:
	1. Add a doc about how to use Fluid to accelerate the Model Artifact access of KServe.
	2. Solve any issues during the integration if any.

**Anything else you would like to add:**

From my own testing, Fluid is able to reduce the access time of model artifact (1.3 GB for example) from 1 min+ to 5-20s (results vary from different runtime used in Fluid)

Fluid is able to work with KNative perfectly (find an example [here](https://github.com/fluid-cloudnative/fluid/blob/master/docs/en/samples/knative.md#demo---how-to-run-in-a-serverless-environment-with-knative-as-an-example)). As Kserve is built on top of KNative and [PVC](https://kserve.github.io/website/master/modelserving/storage/pvc/pvc/#copy-model-to-pv) is a supported storage type as well, it shouldn't be too hard to integrate Fluid with KServe.

**Comment by lizzzcai** [comment]
cc @yuzisun @cheyang @wsxiaozhang

**Comment by peterableda** [comment]
This seems very relevant for LLMs. Can we tag with [kserve/llm]?
