### ISSUE TITLE
[WebApp] Rename "Model Servers" to "Endpoints"

### ISSUE THREAD

**Issue by StefanoFioravanzo** [kserve/kserve#2534]
/kind feature

**Current State**

The KServe web app refers to served models as "Model Servers".
The KServe web app is also exposed in the Kubeflow dashboard using the 'Models' noun.

**Considerations**

1. "Model" refers to a static *artifact* that can be instantiated many times as a serving entity. There is a one-to-many relationship between a model 'artifact' and its 'inference servers'.
2. Kubeflow components are working towards tight integration with a pub/sub artifact system. It's just a matter of time until Kubeflow has its own Model Registry. At that point, we will really want to expose those entities as "Models". This will result in some naming clash between the artifacts and their instances, the inference servers.

**Proposal**

We propose to change the "Model Server" terminology in the KServe UI to "Endpoints".

1. "Endpoints" is a single-word noun, easy to use and remember. This is consistent with the rest of the nouns in the Kubeflow dashboard
2. Using the word Endpoint in a Machine Learning context refers distinctively to a *model* being served
3. Other platforms such as Google Vertex, Azure ML, HuggingFace use this terminology

The bottom line is:
* Models are reusable and shareable artifacts
* Endpoints are instantiations of these artifacts

The scope of the proposed changes includes:

1. Renaming some labels in the KServe UI from "Model Server(s)" to "Endpoint(s)" [ Screenshots follow ] 
2. Documentation: I am not aware of user guides that describe UI usage, but if there are any we can update those
3. Renaming the Kubeflow Centraldashboard sidebar menu item. This is not a concern for the people here, but would definitely follow up after implementing (1) and (2).

**Considerations**

* We know most of the documentation refers to "InferenceService(s)" in user guides and admin guides. We don't propose changing all that, since this would require a more fundamental renaming, down to the CRD itself, which is not necessary to pursue.
* This naming change is mostly targeted at people who consume Kubeflow mostly from the UI and don't have to deal with the lower-level "InferenceService" details.
* We can clarify in the documentation the relationship between "Endpoints" and "InferenceServices", the former being just a better user-friendly name that we expose in the UI and potentially high-level Python APIs.

**Scope**

The UI changes will be minimal (see screenshots):
- Headings
- "New" button

![image (5)](https://user-images.githubusercontent.com/3354305/202161337-1e04ce71-8837-4189-8bb8-481d61bc7498.png)
![image (4)](https://user-images.githubusercontent.com/3354305/202161351-093e444b-ba68-4add-98f4-d65de5e5bf36.png)
![image (3)](https://user-images.githubusercontent.com/3354305/202161362-903a322d-41c5-4d68-9b85-58027276d757.png)

cc @kimwnasptd @yuzisun

**Comment by yuzisun** [comment]
@StefanoFioravanzo My concern is that currently the UI deploys with yaml which exposes the underlying KServe `InferenceService`, anyone who deploys needs to know `InferenceService` spec. I think whatever running in the Kubernetes is an `InferenceService`, `Endpoint` is really an interface to the caller for sending requests to the `InferenceService` and the caller does not need to care how the `InferenceService` is deployed and how many replicas are running. I think we need to differentiate between `InferenceService` deployments and endpoints.

**Comment by kimwnasptd** [comment]
I really like this approach! Especially considering the recent efforts we've seen in Kubeflow for better defining a Model registry https://github.com/kubeflow/kubeflow/issues/6647 we'll need to be more explicit on the distinction between a model as an artifact and a model as a something that runs and is used for inferencing.

So although this is a very small change in UI, I really think it goes a long way in establishing a better terminology to refer to served models and be better poised to integrate with model artifact capabilities.

**Comment by kimwnasptd** [comment]
@yuzisun I think you are raising very valid concerns, although IIUC the above seem inline to me with the change that was proposed above

**Comment by StefanoFioravanzo** [comment]
Thanks, @kimwnasptd !

@yuzisun I agree, the "lower level" interface is and will still be an `InferenceService`. The `InferenceService` is the actual deployment, and the `Endpoint` is a sort of abstraction, although currently, it would be just semantics as we are not proposing building separate APIs.

So do you think that these UI changes are a good first step towards simplifying nomenclature?

**Comment by StefanoFioravanzo** [comment]
Hey @yuzisun, what do you think about the above? Would you agree on moving forward with the changes we proposed?

**Comment by yuzisun** [comment]
> Hey @yuzisun, what do you think about the above? Would you agree on moving forward with the changes we proposed?

sorry for the late reply, we can move forward with what you proposed, thanks!

**Comment by StefanoFioravanzo** [comment]
That's great to hear!
