### ISSUE TITLE
[Quickstart] error: timed out waiting for the condition on pods/kserve-controller-manager-

### ISSUE THREAD

**Issue by r-matsuzaka** [kserve/kserve#2558]
/kind bug

**What steps did you take and what happened:**
 I tried to run quick start on minikube https://kserve.github.io/website/0.9/get_started/
Then I fail.

**What's the InferenceService yaml:**
[To help us debug please run `kubectl get isvc $name -n $namespace -oyaml` and paste the output]

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

**Environment:**

- Istio Version: Sorry I do't know how to check it... Could you tell me?
- Knative Version: Sorry I do't know how to check it... Could you tell me?
- KServe Version: 0.9
- Kubeflow version: For quick start, I do not use kubeflow
- Cloud Environment:[k8s_istio/istio_dex/gcp_basic_auth/gcp_iap/aws/aws_cognito/ibm]
- Minikube/Kind version:

```
$ minikube version 
minikube version: v1.28.0
$ kubectl version --short
Client Version: v1.21.14
Server Version: v1.21.14
```

- OS (e.g. from `/etc/os-release`): Ubuntu 22.04.1 LTS

> ryo@ryo:~/Code/kserve-test$ curl -s "https://raw.githubusercontent.com/kserve/kserve/release-0.9/hack/quick_install.sh" | bash
> bash: line 40: [: .2: integer expression expected
>   % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
>                                  Dload  Upload   Total   Spent    Left  Speed
> 100   101  100   101    0     0    401      0 --:--:-- --:--:-- --:--:--   402
> 100  4856  100  4856    0     0  14975      0 --:--:-- --:--:-- --:--:-- 14975
> 
> Downloading istio-1.14.0 from https://github.com/istio/istio/releases/download/1.14.0/istio-1.14.0-linux-amd64.tar.gz ...
> 
> Istio 1.14.0 Download Complete!
> 
> Istio has been successfully downloaded into the istio-1.14.0 folder on your system.
> 
> Next Steps:
> See https://istio.io/latest/docs/setup/install/ to add Istio to your Kubernetes cluster.
> 
> To configure the istioctl client tool for your workstation,
> add the /home/ryo/Code/kserve-test/istio-1.14.0/bin directory to your environment path variable with:
> 	 export PATH="$PATH:/home/ryo/Code/kserve-test/istio-1.14.0/bin"
> 
> Begin the Istio pre-installation check by running:
> 	 istioctl x precheck 
> 
> Need more information? Visit https://istio.io/latest/docs/setup/install/ 
> namespace/istio-system configured
> ✔ Istio core installed                                                                                                             
> ✔ Istiod installed                                                                                                                                                               
> ✔ Ingress gateways installed                                                                                                                                                     
> ✔ Installation complete                                                                                                                                                          Making this installation the default for injection and validation.
> 😀 Successfully installed Istio
> customresourcedefinition.apiextensions.k8s.io/certificates.networking.internal.knative.dev configured
> customresourcedefinition.apiextensions.k8s.io/configurations.serving.knative.dev configured
> customresourcedefinition.apiextensions.k8s.io/clusterdomainclaims.networking.internal.knative.dev configured
> customresourcedefinition.apiextensions.k8s.io/domainmappings.serving.knative.dev configured
> customresourcedefinition.apiextensions.k8s.io/ingresses.networking.internal.knative.dev configured
> customresourcedefinition.apiextensions.k8s.io/metrics.autoscaling.internal.knative.dev configured
> customresourcedefinition.apiextensions.k8s.io/podautoscalers.autoscaling.internal.knative.dev configured
> customresourcedefinition.apiextensions.k8s.io/revisions.serving.knative.dev configured
> customresourcedefinition.apiextensions.k8s.io/routes.serving.knative.dev configured
> customresourcedefinition.apiextensions.k8s.io/serverlessservices.networking.internal.knative.dev configured
> customresourcedefinition.apiextensions.k8s.io/services.serving.knative.dev configured
> customresourcedefinition.apiextensions.k8s.io/images.caching.internal.knative.dev configured
> namespace/knative-serving configured
> clusterrole.rbac.authorization.k8s.io/knative-serving-aggregated-addressable-resolver configured
> clusterrole.rbac.authorization.k8s.io/knative-serving-addressable-resolver configured
> clusterrole.rbac.authorization.k8s.io/knative-serving-namespaced-admin configured
> clusterrole.rbac.authorization.k8s.io/knative-serving-namespaced-edit configured
> clusterrole.rbac.authorization.k8s.io/knative-serving-namespaced-view configured
> clusterrole.rbac.authorization.k8s.io/knative-serving-core configured
> clusterrole.rbac.authorization.k8s.io/knative-serving-podspecable-binding configured
> serviceaccount/controller configured
> clusterrole.rbac.authorization.k8s.io/knative-serving-admin configured
> clusterrolebinding.rbac.authorization.k8s.io/knative-serving-controller-admin configured
> clusterrolebinding.rbac.authorization.k8s.io/knative-serving-controller-addressable-resolver configured
> customresourcedefinition.apiextensions.k8s.io/images.caching.internal.knative.dev unchanged
> customresourcedefinition.apiextensions.k8s.io/certificates.networking.internal.knative.dev unchanged
> customresourcedefinition.apiextensions.k8s.io/configurations.serving.knative.dev unchanged
> customresourcedefinition.apiextensions.k8s.io/clusterdomainclaims.networking.internal.knative.dev unchanged
> customresourcedefinition.apiextensions.k8s.io/domainmappings.serving.knative.dev unchanged
> customresourcedefinition.apiextensions.k8s.io/ingresses.networking.internal.knative.dev unchanged
> customresourcedefinition.apiextensions.k8s.io/metrics.autoscaling.internal.knative.dev unchanged
> customresourcedefinition.apiextensions.k8s.io/podautoscalers.autoscaling.internal.knative.dev unchanged
> customresourcedefinition.apiextensions.k8s.io/revisions.serving.knative.dev unchanged
> customresourcedefinition.apiextensions.k8s.io/routes.serving.knative.dev unchanged
> customresourcedefinition.apiextensions.k8s.io/serverlessservices.networking.internal.knative.dev unchanged
> customresourcedefinition.apiextensions.k8s.io/services.serving.knative.dev unchanged
> image.caching.internal.knative.dev/queue-proxy configured
> configmap/config-autoscaler configured
> configmap/config-defaults configured
> configmap/config-deployment configured
> configmap/config-domain configured
> configmap/config-features configured
> configmap/config-gc configured
> configmap/config-leader-election configured
> configmap/config-logging configured
> configmap/config-network configured
> configmap/config-observability configured
> configmap/config-tracing configured
> horizontalpodautoscaler.autoscaling/activator configured
> poddisruptionbudget.policy/activator-pdb configured
> deployment.apps/activator configured
> service/activator-service configured
> deployment.apps/autoscaler configured
> service/autoscaler configured
> deployment.apps/controller configured
> service/controller configured
> deployment.apps/domain-mapping configured
> deployment.apps/domainmapping-webhook configured
> service/domainmapping-webhook configured
> horizontalpodautoscaler.autoscaling/webhook configured
> poddisruptionbudget.policy/webhook-pdb configured
> deployment.apps/webhook configured
> service/webhook configured
> validatingwebhookconfiguration.admissionregistration.k8s.io/config.webhook.serving.knative.dev configured
> mutatingwebhookconfiguration.admissionregistration.k8s.io/webhook.serving.knative.dev configured
> mutatingwebhookconfiguration.admissionregistration.k8s.io/webhook.domainmapping.serving.knative.dev configured
> secret/domainmapping-webhook-certs configured
> validatingwebhookconfiguration.admissionregistration.k8s.io/validation.webhook.domainmapping.serving.knative.dev configured
> validatingwebhookconfiguration.admissionregistration.k8s.io/validation.webhook.serving.knative.dev configured
> secret/webhook-certs configured
> clusterrole.rbac.authorization.k8s.io/knative-serving-istio configured
> gateway.networking.istio.io/knative-ingress-gateway created
> gateway.networking.istio.io/knative-local-gateway configured
> service/knative-local-gateway configured
> configmap/config-istio configured
> peerauthentication.security.istio.io/webhook configured
> peerauthentication.security.istio.io/domainmapping-webhook configured
> peerauthentication.security.istio.io/net-istio-webhook configured
> deployment.apps/net-istio-controller configured
> deployment.apps/net-istio-webhook configured
> secret/net-istio-webhook-certs configured
> service/net-istio-webhook configured
> mutatingwebhookconfiguration.admissionregistration.k8s.io/webhook.istio.networking.internal.knative.dev configured
> validatingwebhookconfiguration.admissionregistration.k8s.io/config.webhook.istio.networking.internal.knative.dev configured
> 😀 Successfully installed Knative
> customresourcedefinition.apiextensions.k8s.io/certificaterequests.cert-manager.io configured
> customresourcedefinition.apiextensions.k8s.io/certificates.cert-manager.io configured
> customresourcedefinition.apiextensions.k8s.io/challenges.acme.cert-manager.io configured
> customresourcedefinition.apiextensions.k8s.io/clusterissuers.cert-manager.io configured
> customresourcedefinition.apiextensions.k8s.io/issuers.cert-manager.io configured
> customresourcedefinition.apiextensions.k8s.io/orders.acme.cert-manager.io configured
> namespace/cert-manager unchanged
> serviceaccount/cert-manager-cainjector configured
> serviceaccount/cert-manager configured
> serviceaccount/cert-manager-webhook configured
> clusterrole.rbac.authorization.k8s.io/cert-manager-cainjector configured
> clusterrole.rbac.authorization.k8s.io/cert-manager-controller-issuers configured
> clusterrole.rbac.authorization.k8s.io/cert-manager-controller-clusterissuers configured
> clusterrole.rbac.authorization.k8s.io/cert-manager-controller-certificates configured
> clusterrole.rbac.authorization.k8s.io/cert-manager-controller-orders configured
> clusterrole.rbac.authorization.k8s.io/cert-manager-controller-challenges configured
> clusterrole.rbac.authorization.k8s.io/cert-manager-controller-ingress-shim configured
> clusterrole.rbac.authorization.k8s.io/cert-manager-view configured
> clusterrole.rbac.authorization.k8s.io/cert-manager-edit configured
> clusterrole.rbac.authorization.k8s.io/cert-manager-controller-approve:cert-manager-io configured
> clusterrole.rbac.authorization.k8s.io/cert-manager-webhook:subjectaccessreviews configured
> clusterrolebinding.rbac.authorization.k8s.io/cert-manager-cainjector configured
> clusterrolebinding.rbac.authorization.k8s.io/cert-manager-controller-issuers configured
> clusterrolebinding.rbac.authorization.k8s.io/cert-manager-controller-clusterissuers configured
> clusterrolebinding.rbac.authorization.k8s.io/cert-manager-controller-certificates configured
> clusterrolebinding.rbac.authorization.k8s.io/cert-manager-controller-orders configured
> clusterrolebinding.rbac.authorization.k8s.io/cert-manager-controller-challenges configured
> clusterrolebinding.rbac.authorization.k8s.io/cert-manager-controller-ingress-shim configured
> clusterrolebinding.rbac.authorization.k8s.io/cert-manager-controller-approve:cert-manager-io configured
> clusterrolebinding.rbac.authorization.k8s.io/cert-manager-webhook:subjectaccessreviews configured
> role.rbac.authorization.k8s.io/cert-manager-cainjector:leaderelection configured
> role.rbac.authorization.k8s.io/cert-manager:leaderelection configured
> role.rbac.authorization.k8s.io/cert-manager-webhook:dynamic-serving configured
> rolebinding.rbac.authorization.k8s.io/cert-manager-cainjector:leaderelection configured
> rolebinding.rbac.authorization.k8s.io/cert-manager:leaderelection configured
> rolebinding.rbac.authorization.k8s.io/cert-manager-webhook:dynamic-serving configured
> service/cert-manager configured
> service/cert-manager-webhook configured
> deployment.apps/cert-manager-cainjector configured
> deployment.apps/cert-manager configured
> deployment.apps/cert-manager-webhook configured
> mutatingwebhookconfiguration.admissionregistration.k8s.io/cert-manager-webhook configured
> validatingwebhookconfiguration.admissionregistration.k8s.io/cert-manager-webhook configured
> deployment.apps/cert-manager-webhook condition met
> 😀 Successfully installed Cert Manager
> namespace/kserve created
> customresourcedefinition.apiextensions.k8s.io/clusterservingruntimes.serving.kserve.io configured
> customresourcedefinition.apiextensions.k8s.io/inferencegraphs.serving.kserve.io created
> customresourcedefinition.apiextensions.k8s.io/inferenceservices.serving.kserve.io configured
> customresourcedefinition.apiextensions.k8s.io/servingruntimes.serving.kserve.io configured
> customresourcedefinition.apiextensions.k8s.io/trainedmodels.serving.kserve.io configured
> serviceaccount/kserve-controller-manager created
> role.rbac.authorization.k8s.io/leader-election-role created
> clusterrole.rbac.authorization.k8s.io/kserve-manager-role configured
> clusterrole.rbac.authorization.k8s.io/kserve-proxy-role configured
> rolebinding.rbac.authorization.k8s.io/leader-election-rolebinding created
> clusterrolebinding.rbac.authorization.k8s.io/kserve-manager-rolebinding configured
> clusterrolebinding.rbac.authorization.k8s.io/kserve-proxy-rolebinding configured
> configmap/inferenceservice-config created
> configmap/kserve-config created
> secret/kserve-webhook-server-secret created
> service/kserve-controller-manager-metrics-service created
> service/kserve-controller-manager-service created
> service/kserve-webhook-server-service created
> deployment.apps/kserve-controller-manager created
> statefulset.apps/kserve-controller-manager created
> certificate.cert-manager.io/serving-cert created
> issuer.cert-manager.io/selfsigned-issuer created
> mutatingwebhookconfiguration.admissionregistration.k8s.io/inferenceservice.serving.kserve.io configured
> validatingwebhookconfiguration.admissionregistration.k8s.io/inferencegraph.serving.kserve.io created
> validatingwebhookconfiguration.admissionregistration.k8s.io/inferenceservice.serving.kserve.io configured
> validatingwebhookconfiguration.admissionregistration.k8s.io/trainedmodel.serving.kserve.io configured
> 
> error: timed out waiting for the condition on pods/kserve-controller-manager-5c5c4d8c89-tbglr

**Comment by wxlo0** [comment]
i have the same error, have you solved it?

**Comment by r-matsuzaka** [comment]
No

**Comment by sivanantha321** [comment]
Apparently, the kserve controller is not up within the specified timeout period. It may be related to network issues. Re running the script may solve the problem. Feel free to reopen the issue if you encounter it again.
