### ISSUE TITLE
nodeSelector support for InferenceGraph router

### ISSUE THREAD

**Issue by abhinavgpt** [kserve/kserve#2565]
/kind feature

**Describe the solution you'd like**
[A clear and concise description of what you want to happen.]
Right now, we can add nodeSelector for Inference services, but this is not possible for InferenceGraph.  

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

**Comment by rachitchauhan43** [comment]
> nodeSelector

@abhinavgpt : How about using affinity ? Does that work ? We are propagating all the annotations that come with IG to ksvc backing IG. Can you test if that works for you ?

**Comment by abhinavgpt** [comment]
@rachitchauhan43 Using node affinity with kserve 0.10 worked for me. Shall I close the issue or are you planning to implement nodeSelector functionality as well?

**Comment by rachitchauhan43** [comment]
If nodeAffinity solves the purpose, then you can close this.
