### ISSUE TITLE
conflict due to ray

### ISSUE THREAD

**Issue by r-matsuzaka** [kserve/kserve#2575]
/kind bug

Hi, according to [this tutorial](https://www.kubeflow.org/docs/external-add-ons/kserve/first_isvc_kserve/), at first I tried to install kserve with pip in Docker container but failed due to conflicts with ray.  
Could you tell me the reason or workaround?

> $ docker run -it --rm --name kserve-test python:3.10.8-bullseye /bin/bash
> Unable to find image 'python:3.10.8-bullseye' locally
> 3.10.8-bullseye: Pulling from library/python
> a8ca11554fce: Pull complete 
> e4e46864aba2: Pull complete 
> c85a0be79bfb: Pull complete 
> 195ea6a58ca8: Pull complete 
> 157f16ed0a0c: Pull complete 
> 884b144bec28: Pull complete 
> b7c6b1ad3022: Pull complete 
> c5ae41250acf: Pull complete 
> d1ffbfa02364: Pull complete 
> Digest: sha256:3739623443e3c6d6964047cd1548a0e7b96ef4cb7414852310ee538266203a4e
> Status: Downloaded newer image for python:3.10.8-bullseye
> root@d6096d32c0ff:/# pip install kserve
> Collecting kserve
>   Downloading kserve-0.9.0-py3-none-any.whl (304 kB)
>      ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 304.6/304.6 kB 6.4 MB/s eta 0:00:00
> Collecting numpy~=1.21.5
>   Downloading numpy-1.21.6-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (15.9 MB)
>      ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 15.9/15.9 MB 9.5 MB/s eta 0:00:00
> Collecting kserve
>   Downloading kserve-0.8.0.2-py3-none-any.whl (292 kB)
>      ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 292.3/292.3 kB 7.6 MB/s eta 0:00:00
> Collecting googleapis-common-protos==1.53.0
>   Downloading googleapis_common_protos-1.53.0-py2.py3-none-any.whl (198 kB)
>      ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 198.2/198.2 kB 8.8 MB/s eta 0:00:00
> Collecting psutil>=5.0
>   Downloading psutil-5.9.4-cp36-abi3-manylinux_2_12_x86_64.manylinux2010_x86_64.manylinux_2_17_x86_64.manylinux2014_x86_64.whl (280 kB)
>      ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 280.2/280.2 kB 8.5 MB/s eta 0:00:00
> Collecting numpy~=1.19.2
>   Downloading numpy-1.19.5.zip (7.3 MB)
>      ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 7.3/7.3 MB 8.9 MB/s eta 0:00:00
>   Installing build dependencies ... done
>   Getting requirements to build wheel ... done
>   Preparing metadata (pyproject.toml) ... done
> Collecting grpcio>=1.34.0
>   Downloading grpcio-1.50.0-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (4.7 MB)
>      ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 4.7/4.7 MB 9.7 MB/s eta 0:00:00
> Collecting tornado>=6.0.0
>   Downloading tornado-6.2-cp37-abi3-manylinux_2_5_x86_64.manylinux1_x86_64.manylinux_2_17_x86_64.manylinux2014_x86_64.whl (423 kB)
>      ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 424.0/424.0 kB 9.3 MB/s eta 0:00:00
> Collecting python-dateutil>=2.5.3
>   Downloading python_dateutil-2.8.2-py2.py3-none-any.whl (247 kB)
>      ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 247.7/247.7 kB 9.1 MB/s eta 0:00:00
> Collecting argparse>=1.4.0
>   Downloading argparse-1.4.0-py2.py3-none-any.whl (23 kB)
> Collecting certifi==2021.5.30
>   Downloading certifi-2021.5.30-py2.py3-none-any.whl (145 kB)
>      ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 145.5/145.5 kB 8.8 MB/s eta 0:00:00
> Collecting avro>=1.10.1
>   Downloading avro-1.11.1.tar.gz (84 kB)
>      ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 84.2/84.2 kB 7.5 MB/s eta 0:00:00
>   Installing build dependencies ... done
>   Getting requirements to build wheel ... done
>   Preparing metadata (pyproject.toml) ... done
> Collecting adal>=1.2.2
>   Downloading adal-1.2.7-py2.py3-none-any.whl (55 kB)
>      ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 55.5/55.5 kB 7.6 MB/s eta 0:00:00
> Collecting cachetools==4.2.2
>   Downloading cachetools-4.2.2-py3-none-any.whl (11 kB)
> Collecting google-auth==1.34.0
>   Downloading google_auth-1.34.0-py2.py3-none-any.whl (152 kB)
>      ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 152.9/152.9 kB 8.6 MB/s eta 0:00:00
> Collecting cffi==1.14.6
>   Downloading cffi-1.14.6.tar.gz (475 kB)
>      ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 475.7/475.7 kB 9.5 MB/s eta 0:00:00
>   Preparing metadata (setup.py) ... done
> Collecting jmespath==0.10.0
>   Downloading jmespath-0.10.0-py2.py3-none-any.whl (24 kB)
> Collecting azure-storage-blob==12.8.1
>   Downloading azure_storage_blob-12.8.1-py2.py3-none-any.whl (345 kB)
>      ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 345.8/345.8 kB 8.6 MB/s eta 0:00:00
> Collecting table-logger>=0.3.5
>   Downloading table_logger-0.3.6-py3-none-any.whl (14 kB)
> Requirement already satisfied: setuptools>=21.0.0 in /usr/local/lib/python3.10/site-packages (from kserve) (63.2.0)
> Collecting boto3==1.20.24
>   Downloading boto3-1.20.24-py3-none-any.whl (131 kB)
>      ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 131.8/131.8 kB 8.1 MB/s eta 0:00:00
> Collecting cryptography==3.4.7
>   Downloading cryptography-3.4.7-cp36-abi3-manylinux2014_x86_64.whl (3.2 MB)
>      ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 3.2/3.2 MB 10.2 MB/s eta 0:00:00
> Collecting protobuf~=3.19.0
>   Downloading protobuf-3.19.6-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (1.1 MB)
>      ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.1/1.1 MB 9.7 MB/s eta 0:00:00
> Collecting azure-core==1.17.0
>   Downloading azure_core-1.17.0-py2.py3-none-any.whl (165 kB)
>      ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 165.8/165.8 kB 8.9 MB/s eta 0:00:00
> Collecting azure-identity>=1.6.0
>   Downloading azure_identity-1.12.0-py3-none-any.whl (135 kB)
>      ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 135.5/135.5 kB 8.4 MB/s eta 0:00:00
> Collecting idna==3.2
>   Downloading idna-3.2-py3-none-any.whl (59 kB)
>      ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 59.6/59.6 kB 7.7 MB/s eta 0:00:00
> Collecting tritonclient==2.14.2
>   Downloading tritonclient-2.14.2-py3-none-manylinux1_x86_64.whl (7.7 MB)
>      ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 7.7/7.7 MB 10.2 MB/s eta 0:00:00
> Collecting urllib3>=1.15.1
>   Downloading urllib3-1.26.13-py2.py3-none-any.whl (140 kB)
>      ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 140.6/140.6 kB 8.4 MB/s eta 0:00:00
> Collecting kubernetes>=12.0.0
>   Downloading kubernetes-25.3.0-py2.py3-none-any.whl (1.4 MB)
>      ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.4/1.4 MB 9.6 MB/s eta 0:00:00
> Collecting six>=1.15
>   Downloading six-1.16.0-py2.py3-none-any.whl (11 kB)
> Collecting minio<7.0.0,>=4.0.9
>   Downloading minio-6.0.2-py2.py3-none-any.whl (73 kB)
>      ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 73.1/73.1 kB 6.6 MB/s eta 0:00:00
> Collecting kserve
>   Downloading kserve-0.8.0.1-py3-none-any.whl (275 kB)
>      ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 275.1/275.1 kB 10.9 MB/s eta 0:00:00
>   Downloading kserve-0.8.0-py3-none-any.whl (275 kB)
>      ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 275.1/275.1 kB 9.4 MB/s eta 0:00:00
> Collecting google-api-core==1.29.0
>   Downloading google_api_core-1.29.0-py2.py3-none-any.whl (93 kB)
>      ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 93.1/93.1 kB 6.5 MB/s eta 0:00:00
> Collecting kserve
>   Downloading kserve-0.7.0-py3-none-any.whl (284 kB)
>      ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 284.9/284.9 kB 10.2 MB/s eta 0:00:00
> Collecting grpcio==1.38.1
>   Downloading grpcio-1.38.1.tar.gz (21.4 MB)
>      ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 21.4/21.4 MB 8.8 MB/s eta 0:00:00
>   Preparing metadata (setup.py) ... done
> Collecting azure-identity==1.6.0
>   Downloading azure_identity-1.6.0-py2.py3-none-any.whl (108 kB)
>      ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 108.5/108.5 kB 5.1 MB/s eta 0:00:00
> ERROR: Cannot install kserve==0.7.0, kserve==0.8.0, kserve==0.8.0.1, kserve==0.8.0.2 and kserve==0.9.0 because these package versions have conflicting dependencies.
> 
> The conflict is caused by:
>     kserve 0.9.0 depends on ray[serve]==1.10.0
>     kserve 0.8.0.2 depends on ray[serve]==1.9.0
>     kserve 0.8.0.1 depends on ray[serve]==1.9.0
>     kserve 0.8.0 depends on ray[serve]==1.9.0
>     kserve 0.7.0 depends on ray[serve]==1.5.0
> 
> To fix this you could try to:
> 1. loosen the range of package versions you've specified
> 2. remove package versions to allow pip attempt to solve the dependency conflict
> 
> ERROR: ResolutionImpossible: for help visit https://pip.pypa.io/en/latest/topics/dependency-resolution/#dealing-with-dependency-conflicts
> 
> [notice] A new release of pip available: 22.2.2 -> 22.3.1
> [notice] To update, run: pip install --upgrade pip

**Comment by nachogarciam** [comment]
Hi, im having the same issue, any workaround?

**Comment by nachogarciam** [comment]
Hey @r-matsuzaka, I have the issue on my mb pro with m1 chip and I solved it with this: https://stackoverflow.com/questions/72239693/why-get-pip-install-error-when-run-docker-build-on-only-m1-mac

Hope it works for you!

**Comment by sivanantha321** [comment]
This should be resolved by the [Poetry dependecy reslover PR](https://github.com/kserve/kserve/pull/2602).
