### ISSUE TITLE
404 Not Found doing First InferenceService example with Knative 1.8

### ISSUE THREAD

**Issue by drew-two** [kserve/kserve#2596]
/kind bug

**What steps did you take and what happened:**
[A clear and concise description of what the bug is.]

- Installed via release 0.9 quick_install.sh from Quickstart (updated istio and knative versions as per version matrix
- Followed First InferenceService steps 1-4 choosing to Port Forward
- Getting 404 error running step 5 with "From Ingress gateway with HOST Header"

**What did you expect to happen:**
- Two predictions `{"predictions": [1, 1]}` returned from curl request

**What's the InferenceService yaml:**
[To help us debug please run `kubectl get isvc $name -n $namespace -oyaml` and paste the output]
```
apiVersion: serving.kserve.io/v1beta1
kind: InferenceService
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"serving.kserve.io/v1beta1","kind":"InferenceService","metadata":{"annotations":{"sidecar.istio.io/inject":"false"},"name":"sklearn-iris","namespace":"kserve-test"},"spec":{"predictor":{"model":{"modelFormat":{"name":"sklearn"},"storageUri":"gs://kfserving-examples/models/sklearn/1.0/model"}}}}
    sidecar.istio.io/inject: "false"
  creationTimestamp: "2022-12-09T23:03:54Z"
  finalizers:
  - inferenceservice.finalizers
  generation: 2
  name: sklearn-iris
  namespace: kserve-test
  resourceVersion: "127853"
  uid: 6db76f79-211f-428e-a718-5189bc6da954
spec:
  predictor:
    model:
      modelFormat:
        name: sklearn
      name: ""
      resources: {}
      storageUri: gs://kfserving-examples/models/sklearn/1.0/model
status:
  address:
    url: http://sklearn-iris.kserve-test.svc.cluster.local/v1/models/sklearn-iris:predict
  components:
    predictor:
      address:
        url: http://sklearn-iris-predictor-default.kserve-test.svc.cluster.local
      latestCreatedRevision: sklearn-iris-predictor-default-00002
      latestReadyRevision: sklearn-iris-predictor-default-00002
      latestRolledoutRevision: sklearn-iris-predictor-default-00002
      previousRolledoutRevision: sklearn-iris-predictor-default-00001
      traffic:
      - latestRevision: true
        percent: 100
        revisionName: sklearn-iris-predictor-default-00002
      url: http://sklearn-iris-predictor-default.kserve-test.svc.cluster.local
  conditions:
  - lastTransitionTime: "2022-12-10T19:17:33Z"
    status: "True"
    type: IngressReady
  - lastTransitionTime: "2022-12-10T19:17:33Z"
    severity: Info
    status: "True"
    type: PredictorConfigurationReady
  - lastTransitionTime: "2022-12-10T19:17:33Z"
    status: "True"
    type: PredictorReady
  - lastTransitionTime: "2022-12-10T19:17:33Z"
    severity: Info
    status: "True"
    type: PredictorRouteReady
  - lastTransitionTime: "2022-12-10T19:17:33Z"
    status: "True"
    type: Ready
  modelStatus:
    copies:
      failedCopies: 0
      totalCopies: 1
    states:
      activeModelState: Loaded
      targetModelState: Loaded
    transitionStatus: UpToDate
  url: http://sklearn-iris.kserve-test.svc.cluster.local
```

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]
curl command:
```
$ curl -v -H "Host: ${SERVICE_HOSTNAME}" http://${INGRESS_HOST}:${INGRESS_PORT}/v1/models/sklearn-iris:predict -d @./iris-input.json
*   Trying 127.0.0.1:8080...
* Connected to localhost (127.0.0.1) port 8080 (#0)
> POST /v1/models/sklearn-iris:predict HTTP/1.1
> Host: sklearn-iris.kserve-test.svc.cluster.local
> User-Agent: curl/7.71.1
> Accept: */*
> Content-Length: 76
> Content-Type: application/x-www-form-urlencoded
> 
* upload completely sent off: 76 out of 76 bytes
* Mark bundle as not supporting multiuse
< HTTP/1.1 404 Not Found
< date: Sat, 10 Dec 2022 20:20:42 GMT
< server: istio-envoy
< connection: close
< content-length: 0
< 
* Closing connection 0
* 
```

istio log:
```
[2022-12-10T20:20:42.703Z] "POST /v1/models/sklearn-iris:predict HTTP/1.1" 404 NR route_not_found - "-" 0 0 0 - "10.244.0.17" "curl/7.71.1" "f4357d86-17b6-4b5a-81fc-7f13fd9d5e00" "sklearn-iris.kserve-test.svc.cluster.local" "-" - - 127.0.0.1:8080 127.0.0.1:43690 - -
```

**Environment:**

- Istio Version: 1.16.0
- Knative Version: v1.8.0
- KServe Version: v0.9.0-rc0
- Kubeflow version: N/A
- Cloud Environment:[k8s_istio/istio_dex/gcp_basic_auth/gcp_iap/aws/aws_cognito/ibm] N/A
- Minikube/Kind version: v0.17.0
- Kubernetes version: (use `kubectl version`): v1.25.0
- OS (e.g. from `/etc/os-release`): Ubuntu 18.04.4 LTS (WSL)

**Comment by yuzisun** [comment]
@drew-two you have configured knative with cluster local visibility right ?

**Comment by drew-two** [comment]
@yuzisun I have tried adjusting knative-serving configmap as well as sklearn isvc to only have cluster local visibility, without success. Have the same log within istio and the URL of the sklearn-iris isvc is still `http://sklearn-iris.kserve-test.example.com` if that helps

**Comment by nickaggarwal** [comment]
I also have the same problem, I have done the same config with Kourier ( Ingress controller ). I am also getting the same error 404 not found 

textPayload: "[2023-01-13T08:52:58.945Z] "POST /v1/models/sklearn-iris:predict HTTP/1.1" 404 NR 0 0 0 - "-" "curl/7.79.1" "f75db2ac-ae35-47a9-bdd1-6bfcee52a591" "sklearn-iris.kserve-test.127.0.0.1.nip.io" "-""

Is there a problem with InferenceService ? or the route to inference service?

If i  expose the cluster service directly it works

**Comment by yuzisun** [comment]
This is the issue from [Knative 1.8 breaking change ](https://github.com/knative/serving/releases/tag/knative-v1.8.2)

## Breaking or Notable
Uses the cluster domain suffix svc.cluster.local as the default domain. As routes using the cluster domain suffix are not exposed through Ingress, users will need to [configure DNS](https://knative.dev/docs/install/yaml-install/serving/install-serving-with-yaml/#configure-dns) in order to expose their services (most users probably already are). (https://github.com/knative/serving/pull/13259, @psschwei)
