### ISSUE TITLE
"error":"open /tmp/k8s-webhook-server/serving-certs/tls.crt: no such file or directory"}

### ISSUE THREAD

**Issue by pengyuan** [kserve/kserve#2597]
/kind bug

**What steps did you take and what happened:**
[A clear and concise description of what the bug is.]

{"level":"info","ts":1670769478.0864744,"logger":"controller-runtime.webhook","msg":"registering webhook","path":"/mutate-serving-kserve-io-v1beta1-inferenceservice"}
{"level":"info","ts":1670769478.0864933,"logger":"controller-runtime.builder","msg":"Registering a validating webhook","GVK":"serving.kserve.io/v1beta1, Kind=InferenceService","path":"/validate-serving-kserve-io-v1beta1-inferenceservice"}
{"level":"info","ts":1670769478.086521,"logger":"controller-runtime.webhook","msg":"registering webhook","path":"/validate-serving-kserve-io-v1beta1-inferenceservice"}
{"level":"info","ts":1670769478.0865471,"logger":"entrypoint","msg":"Starting the Cmd."}
I1211 14:37:58.086732       1 leaderelection.go:248] attempting to acquire leader lease kserve/kserve-controller-manager-leader-lock...
{"level":"info","ts":1670769478.0867977,"logger":"controller-runtime.webhook.webhooks","msg":"starting webhook server"}
{"level":"info","ts":1670769478.0868256,"msg":"starting metrics server","path":"/metrics"}
E1211 14:37:58.086961       1 leaderelection.go:330] error retrieving resource lock kserve/kserve-controller-manager-leader-lock: Get "https://10.43.0.1:443/api/v1/namespaces/kserve/configmaps/kserve-controller-manager-leader-lock": context canceled
{"level":"error","ts":1670769478.087007,"logger":"entrypoint","msg":"unable to run the manager","error":"open /tmp/k8s-webhook-server/serving-certs/tls.crt: no such file or directory"}

**What did you expect to happen:**

**What's the InferenceService yaml:**
[To help us debug please run `kubectl get isvc $name -n $namespace -oyaml` and paste the output]

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

**Environment:**

- Istio Version:
- Knative Version:
- KServe Version:
- Kubeflow version:
- Cloud Environment:[k8s_istio/istio_dex/gcp_basic_auth/gcp_iap/aws/aws_cognito/ibm]
- Minikube/Kind version:
- Kubernetes version: (use `kubectl version`):
- OS (e.g. from `/etc/os-release`):

**Comment by sivanantha321** [comment]
It seems the webhook certificate is not created for some reason. If you are using `certmanager` please verify if the Certificate resource `serving-cert` is in ready state. It may also caused by the broken installation of kserve. In that case reinstalling kserve may resolve the problem.
