### ISSUE TITLE
Is there a managed version of this?

### ISSUE THREAD

**Issue by akshhack** [kserve/kserve#2608]
/kind feature

**Describe the solution you'd like**
Hi, I'm wondering if there is a managed version of this available for public use yet? If not, I can debt finance this project for a few million dollars to expose a GPU cluster available for hobby ML engineers or startups. 

**Anything else you would like to add:**
If interested, please email me at ack@usecamb.ai

**Comment by yuzisun** [comment]
@akshhack we’d love a publicly available managed kserve! Let’s chat

**Comment by akshhack** [comment]
Excellent, do you guys already have a pitch deck? Please send that across
and Dan if you can shoot me a direct email on ***@***.*** that'll be
great. We'll take it on a thread there. Thanks!

Best,
Akshat Prakash
LinkedIn <https://www.linkedin.com/in/akshat-prakash/>
Calendar <https://calendly.com/akshatp-cs/chat>
