### ISSUE TITLE
Add unit tests for v2 endpoints in Python SDK

### ISSUE THREAD

**Issue by ghost** [kserve/kserve#2618]
/kind feature

**Describe the solution you'd like**

We didn't get the chance to add unit tests for v2 endpoints implementations the last time we switched to FastAPI (see https://github.com/kserve/kserve/pull/2444). It would be nice to include unit tests for v2 endpoints in the Python SDK as well.

**Comment by yuzisun** [comment]
tests added in https://github.com/kserve/kserve/pull/2655
