### ISSUE TITLE
Unit tests needed for v2 endpoints

### ISSUE THREAD

**Issue by alexagriffith** [kserve/kserve#2624]
/kind feature

**Describe the solution you'd like**
We currently don't have good unit test coverage for our endpoints/datamodels files in python SDK (kserve/python/kserve/kserve/handlers). Our goal would be to have better test coverage. We do currently have tests for dataplane.py. 
- Separate out v1 and v2 tests
- adding more tests for v2 endpoints to increase the test coverage

**Comment by yuzisun** [comment]
Can run coverage as below to identify missing tests
https://github.com/kserve/kserve/blob/29e35154df6de0fdae05aaf8a541d276cb652be9/.github/workflows/python-test.yml#L75C11-L75C39

**Comment by tessapham** [comment]
Created https://github.com/kserve/kserve/issues/3137 for refactoring v1 vs. v2 endpoint tests.
