### ISSUE TITLE
Flaky minikube setup github action

### ISSUE THREAD

**Issue by yuzisun** [kserve/kserve#2633]
/kind bug

**What steps did you take and what happened:**
```
Run ./test/scripts/gh-actions/setup-deps.sh
  ./test/scripts/gh-actions/setup-deps.sh
  
  kubectl get pods -n istio-system
  kubectl describe svc -n istio-system istio-ingressgateway
  kubectl get pods -n knative-serving
  kubectl get pods -n cert-manager
  shell: /usr/bin/bash --noprofile --norc -e -o pipefail {0}
  env:
    GITHUB_TOKEN: ***
    GOROOT: /opt/hostedtoolcache/go/1.17.3/x64
    MINIKUBE_HOME: /home/runner/work/_temp
Installing/Updating kustomize ...
Github rate-limiter failed the request. Either authenticate or wait a couple of minutes.
```

**What did you expect to happen:**

**What's the InferenceService yaml:**
[To help us debug please run `kubectl get isvc $name -n $namespace -oyaml` and paste the output]

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

**Environment:**

- Istio Version:
- Knative Version:
- KServe Version:
- Kubeflow version:
- Cloud Environment:[k8s_istio/istio_dex/gcp_basic_auth/gcp_iap/aws/aws_cognito/ibm]
- Minikube/Kind version:
- Kubernetes version: (use `kubectl version`):
- OS (e.g. from `/etc/os-release`):

**Comment by yuzisun** [comment]
@tenzen-y Any thoughts on this? it happens a lot after switching over to use the minikube github action

**Comment by tenzen-y** [comment]
@yuzisun Does that mean https://github.com/kserve/kserve/actions/runs/3863911315/jobs/6586738068?

**Comment by tenzen-y** [comment]
As I can see, that issue occurred by a script to install kustomize. 

https://github.com/kubernetes-sigs/kustomize/blob/master/hack/install_kustomize.sh#L139-L142

So maybe, we need to wait for https://github.com/kubernetes-sigs/kustomize/pull/4946 or to modify our kustomize installation step.

https://github.com/kserve/kserve/blob/60dc5faf2c3c0b28edc3dc1911deb6868b895c15/test/scripts/gh-actions/setup-deps.sh#L35

**Comment by tenzen-y** [comment]
Or we can use `kubectl kustomize ${KUSTOMIZATION_FILE_PATH}` command instead of `kustomize build ${KUSTOMIZATION_FILE_PATH}`.

**Comment by yuzisun** [comment]
I do not see the actual error which says it failed in Kustomize installation though. It just gives the rate limit error, not sure what caused this.

**Comment by yuzisun** [comment]
Oh I see what you are saying, the error is from the kustomize installation script, ye I agree we can try kubectl kustomize instead.

**Comment by tenzen-y** [comment]
It might be easy to replace the following with `go install sigs.k8s.io/kustomize/kustomize/v4@${KUSTOMIZE_VERSION}`.

https://github.com/kserve/kserve/blob/60dc5faf2c3c0b28edc3dc1911deb6868b895c15/test/scripts/gh-actions/setup-deps.sh#L35
