### ISSUE TITLE
KServe online documentation for 0.9 release shows non-existent routes

### ISSUE THREAD

**Issue by brooks-ulap** [kserve/kserve#2637]
**What steps did you take and what happened:**
- Visit the documentation link at: https://kserve.github.io/website/0.9/modelserving/inference_api/
- Notice that routes explaining `/v2` endpoints such as `/v2/health/ready` and `/v2/models/[name]` are listed as available endpoints.
- I struggled for an hour trying to get these requests to work with response of: `"error": "invalid path"`

**What did you expect to happen:**
- I expected to be able to query these v2 endpoints in the 0.9 release of kserve

**Anything else you would like to add:**
It appears that the online documentation is referencing the most recent changes to the kserve platform, instead of the most recent release. The documentation should clarify that these endpoints are not implemented before 0.10x

I've attached a screenshot of the routes included in release 0.9 which does not match the documentation
![image](https://user-images.githubusercontent.com/119872184/211404628-23b98671-48db-476a-b89a-ad4581acfa5b.png)

**Comment by yuzisun** [comment]
@brooks-ulap v2 endpoints are not officially supported in KServe custom model as of 0.9, that's what we plan to release as part of 0.10. Please check the support matrix here https://kserve.github.io/website/0.9/modelserving/v1beta1/serving_runtime/

**Comment by yuzisun** [comment]
@brooks-ulap if you try 0.10 RC release, v2 endpoints are now supported.

**Comment by brooks-ulap** [comment]
@yuzisun Thanks, that became clear after looking at the code. Is there any way the documentation can be updated to be explicit about which version is required for those changes? It's odd that the documentation references features that are not released yet

**Comment by yuzisun** [comment]
@brooks-ulap i think you misunderstood here, the v2 inference api is an open protocol and we initially published as api spec. The protocol was already implemented and released by the out-of-the-box serving runtimes like triton, mlserver, torchserve for quite some time, and more recently we implemented the protocol in kserve custom runtime.

**Comment by yuzisun** [comment]
@brooks-ulap we have the doc PR to update and make this more clear https://github.com/kserve/website/pull/205, feel free to provide your feedback.

**Comment by yuzisun** [comment]
These routes are now implemented in https://github.com/kserve/kserve/releases/tag/v0.10.0
