### ISSUE TITLE
kserve 0.9.0 requiring protobuf~=3.19.0 causing dependency conflict

### ISSUE THREAD

**Issue by tuan-ff** [kserve/kserve#2641]
/kind bug

**What steps did you take and what happened:**
[A clear and concise description of what the bug is.]
Upgrading Python `kserve` library to [version 0.9.0](https://pypi.org/project/kserve/0.9.0/) caused a dependency conflict in our code base, due to `kserve` 0.9.0 [pins](https://github.com/kserve/kserve/pull/2201) `protobuf` to 3.19.0 , and other parts in our code base require `protobuf` 0.20.0 or later.

**What did you expect to happen:**
We'd be able to use protobuf `0.20.0` or later.

We'd like to request `kserve` upgrading `protobuf` or relaxing the version requirement on this dependency, so that dependency conflict with other packages can be removed. Thanks!

**Comment by yuzisun** [comment]
@andyi2it can you help on this issue ?

**Comment by sholsapp** [comment]
Thank you @yuzisun for looking into this and considering it for KServe 0.11. I'm not familiar with KServe's release cadence/protocol... would you mind giving me a rouge sense of when this change may go out to a publicly available release?

**Comment by sholsapp** [comment]
@yuzisun any pointers here for someone not familiar with KServe's release process to gauge when this might go out? Are all of the issues listed in https://github.com/orgs/kserve/projects/6 needing to be "done" before the KServe 0.11 release will go out?

**Comment by yuzisun** [comment]
@sholsapp We have a patch release 0.10.1 going out soon

**Comment by yuzisun** [comment]
#2673
