### ISSUE TITLE
Custom model example does not work in master branch

### ISSUE THREAD

**Issue by papagala** [kserve/kserve#2647]
/kind bug

**What steps did you take and what happened:**

If you follow the [instructions](https://kserve.github.io/website/0.9/modelserving/v1beta1/custom/custom_model/#build-the-custom-image-with-buildpacks) provided on the documentation of Kserve, which requires you clone kserve repository as instructed here:

![image](https://user-images.githubusercontent.com/6526276/212365660-e7a0921f-d5b9-4cfe-877b-e48de9fdeea8.png)

It is never mentioned that you should go to a specific branch. What happens is that if you do as instructed and run

```bash
pack build --builder=heroku/buildpacks:20 ${DOCKER_USER}/custom-model:v1
```

Then you will actually be building a custom model that requires the latest release candidate, since it tries to use a function not found on the latest stable version of kserve. This funcion is `generate_uuid`

![image](https://user-images.githubusercontent.com/6526276/212366447-b7432d6d-65a9-4aae-94be-9fe0bb754fe9.png)

So we should either pin the versions found on `master` branch to the release candidates, or mention to use a specific branch that works. I'm happy to make a Pull Request to add this to the `requirements.txt` or simply add a note to the documentation.

¿

**What did you expect to happen:**

I'm expecting for master branch to contain a `custom-model` example that is able to get installed with the `python/custom_model/requirements.txt` which are simply unpinned `kserve` and `fastapi`. 

```bash
**kserve==v0.10.0-rc1
torchvision
fastapi==0.85.0**
```
work well. However, they only work with the `docs/samples/v1beta1/custom/custom_model/input.json` from master branch. 

Finally, `release-0.10`seems to work correctly. 

**What's the InferenceService yaml:**

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

**Environment:**

Istio Version: 1.15.3
Knative Version: 1.22
KServe Version: 0.8
Kubeflow version: 1.6
Cloud Environment: AWS EKS
Kubernetes version: 1.23
OS (e.g. from /etc/os-release): Amazon Linux 2 AMI

**Comment by yuzisun** [comment]
@papagala the genernate_uuid function should still exist in master branch https://github.com/kserve/kserve/blob/master/python/kserve/kserve/utils/utils.py#L130.

**Comment by yuzisun** [comment]
We should fix the doc to pin to the specific release branch

**Comment by papagala** [comment]
@yuzisun To my surprise `generate_uuid` was actually not present in master branch. Thank you for fixing the docs. Really great, we could close this issue. Thank you 👍
