### ISSUE TITLE
Rename the "V2 Protocol" to "Open Inference Protocol"

### ISSUE THREAD

**Issue by adriangonz** [kserve/kserve#2663]
/kind feature

**Describe the solution you'd like**

We currently refer to the inference protocol used in KServe as the "V2 Protocol". However, many users find this name confusing. To help make it clear, we suggest renaming the "V2 Protocol" to the "Open Inference Protocol".

When referring, internally, to the protocol as the "Open Inference Protocol", we have noticed that users understand its context almost immediately (i.e. as opposed to "V2 Protocol", which can get confused with component versions, releases, etc.). 

**Anything else you would like to add:**

The V2 Protocol is implemented by a number of inference servers and model orchestrators, like Triton, TorchServe, KServe, Seldon Core and MLServer. Therefore, this change will require alignment from all the other parts. With this in mind, we also propose a sort of "joint forum" for us to discuss the rename. 

Outside of the scope of this change, this forum can also be used in the future, to discuss extensions to the protocol, best practices, etc. The "V2 Protocol" / "Open Inference Protocol" has already been in use for more than a year - therefore I'm sure everyone already has a few suggestions in mind on how to improve the protocol, and take it to the next level.

**Comment by yuzisun** [comment]
Cc @chauhang(torchserve), @varunsh-xilinx(amd inference server), @joohoon(triton)

Here is a list of documentation reference for current KServe's v2 inference protocol:

KServe: https://kserve.github.io/website/0.10/modelserving/data_plane/v2_protocol/
TorchServe: https://github.com/pytorch/serve/tree/master/kubernetes/kserve
AMD Inference Server: https://xilinx.github.io/inference-server/main/kserve.html
OpenVino: https://docs.openvino.ai/latest/ovms_docs_rest_api_kfs.html and https://docs.openvino.ai/latest/ovms_docs_grpc_api_kfs.html
Triton Inference Server: https://docs.nvidia.com/deeplearning/triton-inference-server/user-guide/docs/customization_guide/inference_protocols.html
Seldon-Core/MLServer: https://docs.seldon.io/projects/seldon-core/en/latest/reference/apis/v2-protocol.html

**Comment by varunsh-xilinx** [comment]
The only point I'd add is that if this goes forward, something should be done about the V1 protocol for the same reasons you outlined here. It's confusing when you have two different protocols named V1 and V2 (implying deprecation even though that's not the case) but if one is renamed then the meaning of a "V1 protocol" becomes even more confusing

**Comment by adriangonz** [comment]
Hey @varunsh-xilinx , 

That's a great point - in Seldon Core we actually opted for calling the "old protocol" the `seldon` protocol. Although in that case, Seldon's "v1" protocol is on a clear path to deprecation.

Having said that though, as industry collaboration, the "V2 Protocol" (as-is) is used by a number of other projects - some of which don't have even a concept of a v1 protocol. In those cases, talking about a V2 Protocol becomes even more confusing.
