### ISSUE TITLE
Question: How to access the swagger UI when port forwaring the istio gateway service?

### ISSUE THREAD

**Issue by SebastianScherer88** [kserve/kserve#2669]
Question, not a feature.

[In this section you describe how to access the Swagger UI
](https://kserve.github.io/website/0.10/get_started/swagger_ui/#interact-with-inferenceservice)

What I havent been able to work out yet is how to access that page from my local machine's webbrowser - is the best way to find chrome/firefox utilities that allow me to specify `headers` ? 🤔 

Thanks for the new `0.10` release, looks exciting!

**Comment by sivanantha321** [comment]
@SebastianScherer88 You can port forward to the pod to access the swagger UI from your local machine's web browser.

**Comment by boringbyte** [comment]
@SebastianScherer88 . Not sure if you were able to solve the issue or not, I stumbled upon the same issue and followed below steps to resolve the issue as I'm using minikube. I'm a newbie, so there might be other simple ways to do this.

```
kubectl get svc -n kserve-test
kubectl get deployments -n kserve-test
kubectl expose deployment sklearn-iris-predictor-00001-deployment -n kserve-test --type=NodePort --port=8080
kubectl get svc -n kserve-test

kubectl port-forward service/sklearn-iris-predictor-00001-deployment -n kserve-test 8080:8080 --> Ubuntu Terminal
ssh -N -f -L 127.0.0.1:8080:127.0.0.1:8080 username_of_VM@VM_IP --> In local windows terminal
```
Access link using http://localhost:8080/docs locally.
