### ISSUE TITLE
Loosen tritonclient version range for python sdk?

### ISSUE THREAD

**Issue by jinserk** [kserve/kserve#2675]
/kind feature

## Problem
I need to use `kserve` with `mlserver` latest version (>=1.2.0) and they have a dependency with `tritonclient[http] >= 2.24`. Since the current `kserve` python sdk stuck with `tritonclient == 2.18.0`, pip cannot settle down the versions. 

`mlserver` 1.1.0 meets the `tritonclient` 2.18.0, but `mlserver` has changed lots of things from `1.1.0` to `1.2.0`: https://github.com/SeldonIO/MLServer/releases

## Suggestion
Could you loosen the tritonclient dependency to `tritonclient >= 2.18.0`?

**Comment by yuzisun** [comment]
@jinserk we can loose the version, I am curious how you are using mlserver along with kserve?

**Comment by jinserk** [comment]
Thanks for your response, @yuzisun ! Basically I used `seldon-core` and `mlflow` with `mlserver`, but now trying to replace `seldon-core` to `kserve` because of the "zero" replica support. AFAIK, `mlflow` support in `kserve` is only through the `mlserver`. Am I correct?

**Comment by yuzisun** [comment]
Currently yes, but mlserver and kserve python model server are separate serving runtimes, so they should not have conflicts with each other.

**Comment by jinserk** [comment]
@yuzisun Yes, I understand that. I was just concern about the `tritonclient` version condition to block to install latest `mlserver`. Since we're using an internal python package depending both on `kserve` and `mlserver`, need to resolve this conflict.
