### ISSUE TITLE
KServe 0.11.0 release tracking

### ISSUE THREAD

**Issue by rachitchauhan43** [kserve/kserve#2676]
/kind feature

**Describe the solution you'd like**
KServe 0.11.0 release tracking:
RC0 release Date: Will be released in the week of `Friday, April 28, 2023 - Thursday, May 4, 2023`

Release Date: Will be released in the week of `Friday, June 9, 2023 | Thursday, June 15,   2023`

## KServe Model Serving:
See [project dashboard](https://github.com/orgs/kserve/projects/6/views/1?sortedBy%5Bdirection%5D=asc&sortedBy%5BcolumnId%5D=Status) to see what all features/bugs are covered as part 0.11 and their current status 

## Website:

# **TIMELINE**
| Week | Start                     | End                         | When | Event (Actual timelines)                                                                                |
| ---- |---------------------------| --------------------------- | ---- | ------------------------------------------------------------------------------------------------------- |
| 0    | Friday, January 27, 2023  | Thursday, February 2, 2023  |      | Gap week between releases. 0.10.0 release happened on Sunday, January 22, 2023                          |
| 1    | Friday, February 3, 2023  | Thursday, February 9, 2023  |      | Development                                                                                             |
| 2    | Friday, February 10, 2023 | Thursday, February 16, 2023 |      | Development                                                                                             |
| 3    | Friday, February 17, 2023 | Thursday, February 23, 2023 |      | Development                                                                                             |
| 4    | Friday, February 24, 2023 | Thursday, March 2, 2023     |      | Development                                                                                             |
| 5    | Friday, March 3, 2023     | Thursday, March 9, 2023     |      | Development                                                                                             |
| 6    | Friday, March 10, 2023    | Thursday, March 16, 2023    |      | Development                                                                                             |
| 7    | Friday, March 17, 2023    | Thursday, March 23, 2023    |      | Development                                                                                             |
| 8    | Friday, March 24, 2023    | Thursday, March 30, 2023    |      | Development                                                                                             |
| 9    | Friday, March 31, 2023    | Thursday, April 6, 2023     |      | Development                                                                                             |
| 10   | Friday, April 7, 2023     | Thursday, April 13, 2023    |      | Development                                                                                             |
| 11   | Friday, April 14, 2023    | Thursday, April 20, 2023    |      | Development +<br>Start the prep i.e.<br>Announce/Reminder about upcoming feature freeze date in 2 weeks |
| 12   | Friday, April 21, 2023    | Thursday, April 27, 2023    |      | Development (Last week of development)                                                                  |
| 13   | **Friday, April 28, 2023**    | **Thursday, May 4, 2023**       |      | **Feature Freeze + RC0 Released + Documentation update starts**                                             |
| 14   | Friday, May 5, 2023       | Thursday, May 11, 2023      |      | Testing                                                                                                 |
| 15   | **Friday, May 12, 2023**  | **Thursday, May 18, 2023**      |      | **RC1 Released if necessary**                                                                               |
| 16   | Friday, May 19, 2023      | Thursday, May 25, 2023      |      | Testing                                                                                                 |
| 17   | **Friday, May 26, 2023**      | **Thursday, June 1, 2023**      |      | **RC2 Released if necessary**                                                                               |
| 18   | Friday, June 2, 2023      | Thursday, June 8, 2023      |      | Testing + End of documentation                                                                          |
| 19   | **Friday, June 9, 2023**      | **Thursday, June 15, 2023**     |      | **Final release - 0.11.0 released**

**Comment by yc2984** [comment]
Hi in the new release, PR: https://github.com/kserve/kserve/pull/2645/files, why is this file ` charts/kserve-resources/templates/servingruntimes.yaml` deleted? Does it mean servingruntimes is not supported anymore or by default it's using clusterservingruntime?

**Comment by rachitchauhan43** [comment]
I guess we have moved to `clusterservingruntimes` now. 
@yuzisun: I don't see a point in release notes. Am I missing something ?

**Comment by yuzisun** [comment]
> I guess we have moved to `clusterservingruntimes` now. @yuzisun: I don't see a point in release notes. Am I missing something ?

This is for ModelMesh, see the release notes https://github.com/kserve/modelmesh-serving/releases/tag/v0.10.0.
cc @njhill @ckadner. The servingruntimes are still supported, just that if you do not have servingruntime it falls back to clusterservingruntime. It works the same way as KServe now.

**Comment by yc2984** [comment]
@yuzisun Thanks for the reply! @njhill what is the reason of removing the servingruntimes from the helm chart? We are forking this chart only keeping the modelmesh part of it, but we keep it up to date from here.
We are running modelmesh all in one namespace now, and we'd like to keep all the model serving related resources in just one namespace.  Could the clusterservingruntimes potentially interfere with the resources in other namespaces? 
Do you suggest that we migrate to `clusterservingruntimes`? Would there be a downtime?

**Comment by ckadner** [comment]
@yuzisun -- we are still working on the ModelMesh helm chart updates for the upcoming v0.11.0-rc1 #2969

**Comment by ckadner** [comment]
https://github.com/kubeflow/manifests/issues/2447

**Comment by yuzisun** [comment]
This is slightly behind the schedule, the target date now is end of July.
