### ISSUE TITLE
GPL License Violation in the kserve python package

### ISSUE THREAD

**Issue by StefanoFioravanzo** [kserve/kserve#2683]
The version of the `kserve` package that is currently on PyPI (version `0.10`) violates the GPL license because it depends on [`table-logger`](https://github.com/AleksTk/table-logger), distributed under GPLv2 (you'll see that the library is now MIT, the author updated the license just a few days ago, but hasn't released a new version with the new license yet). No GPLv2 packages should be imported given that `kserve` has an Apache 2 license.

This was recently fixed by this PR https://github.com/kserve/kserve/pull/2673, which accidentally resolved the issue by replacing `table-logger` with `tabulate` (MIT License)

cc @yuzisun @cliveseldon @jinchihe @ellistarn 

Is it possible to quickly release a patch release `0.10.1` to include the above patch and make sure `kserve` is compliant with the Apache license? As it stands, any distribution and vendor using `kserve` is liable for a license violation.

**Comment by yuzisun** [comment]
@StefanoFioravanzo i do not think this is released in 0.10. 

@andyi2it can you confirm and see if we can remove table-logger ?

**Comment by StefanoFioravanzo** [comment]
@yuzisun Indeed, the PR I mentioned was merged 3 days ago, so it's not part of 0.10. If we were to release a patch version (0.10.1) including that PR (https://github.com/kserve/kserve/pull/2673) we would solve this.

**Comment by yuzisun** [comment]
> @yuzisun Indeed, the PR I mentioned was merged 3 days ago, so it's not part of 0.10. If we were to release a patch version (0.10.1) including that PR (#2673) we would solve this.

@StefanoFioravanzo thanks for the catch! Curious how you found out this and want to make sure we can prevent this next time.

**Comment by StefanoFioravanzo** [comment]
@yuzisun We did an internal license audit of all the software we bundle in Arritko EKF, and this came up.  We will bring it up to the community if we ever detect anything out of the ordinary.

**Comment by yuzisun** [comment]
> @yuzisun We did an internal license audit of all the software we bundle in Arritko EKF, and this came up. We will bring it up to the community if we ever detect anything out of the ordinary.

How did this come up as it is not released yet?

**Comment by StefanoFioravanzo** [comment]
@yuzisun Every version up to 0.10 is dependent on `table-logger`. The current `master` is not, thanks to this PR https://github.com/kserve/kserve/pull/2673, merged a few days ago. We scanned a version prior to 0.10 in EKF and this came up.

**Comment by StefanoFioravanzo** [comment]
Hi @yuzisun , I see that you merged the cherry-pick to branch `release-0.10`, that's great! (Thanks @andyi2it ).

When do you think you'll manage to publish a new version? Do you have a timeline?

**Comment by yuzisun** [comment]
> Hi @yuzisun , I see that you merged the cherry-pick to branch `release-0.10`, that's great! (Thanks @andyi2it ).
> 
> When do you think you'll manage to publish a new version? Do you have a timeline?
We have a few other bug fixes which needs to go in, the current ETA is to release 0.10.1 by end of month.

**Comment by StefanoFioravanzo** [comment]
Closing this since 0.10.1 has been released. @yuzisun Thanks for the quick fix!

**Comment by zoramthanga** [comment]
Hi @StefanoFioravanzo, @yuzisun if table-logger is no longer used since 0.10.1, why is the license still included in python/third_party/library/license.txt, python/third_party/license_info.csv, and the repo in python/third_party/repo.txt?

FOSSA flagged this for us as incompatible with the Apache 2.0 license of KServe. I don't know how the tool scans files, but I suspect it's scanning the license.txt file.
