### ISSUE TITLE
Allow setting affinity spec for inference graph

### ISSUE THREAD

**Issue by navneetraju** [kserve/kserve#2696]
/kind feature

**Describe the solution you'd like**
Today inference services as part of its pod spec, allows to introduce affinity, which allows for HA across availability zones. As minReplicas will be introduced as part of #2456, affinity becomes more important, so that all routers dont end up on the same node. 

Also, since InferenceService can be distributed across nodes (use pod-anti affinity and AZ topology key) with a high chance of all Inference services part of the graph scheduled on the same node, it make sense for the routers to also be distributed.

The below is what i am envisioning using minReplicas as well as pod anti affinity

![ig-affinity](https://user-images.githubusercontent.com/42941586/218678722-16295807-9e87-418f-9f7a-6d875cf636fc.png)

**Anything else you would like to add:**
Min replicas for IG router is being solved by: #2456

**Comment by rachitchauhan43** [comment]
@navneetraju : Will be fixed as part of #2711
