### ISSUE TITLE
Reframing CI/CD test to avoid running unrelated tests for each PR

### ISSUE THREAD

**Issue by jinchihe** [kserve/kserve#270]
/kind feature

**Describe the solution you'd like**
For now, each PR will trigger long time CI/CD testing, in fact some of them are not related with the PR, for example if we changed files under pkg/api, that's not related the build images Stepes, those images sometime running timeout and failed, that waste time. Suggest to create a separated workflow for those testing by define reasonable prow file.

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

**Comment by jinchihe** [comment]
We need to take high priority to handle this, the CI/CD tests always failed for timeout or some other strange reasons.

**Comment by jinchihe** [comment]
Need to enhance build steps to save CI test time.

**Comment by nm2107** [comment]
Hello,
Maybe this tool can help you ? https://github.com/KnpLabs/should-skip-ci

**Comment by jinchihe** [comment]
@nm2107 Thanks sharing, we need to inestigate how to integrate with current CI famerwork, and I think we need to consider when to skip or not, such as some dir is not changed etc...

**Comment by yuzisun** [comment]
closing as the issue is staled and we have done so much improvements for the e2e infra
