### ISSUE TITLE
Installation OpenShift with Operators

### ISSUE THREAD

**Issue by mgiessing** [kserve/kserve#2712]
Hello, I'm wondering whether there are any instructions on how to install KServe standalone (Serverless) on OpenShift with the appropriate operators (kiali, jaeger, service mesh, cert manager, serverless) from the catalog (+ the models web app)?
There is a ~2 year old instruction under docs, however that is quite outdated I guess.

Service Mesh seems to be up and running:

```bash
$ oc get pods -n istio-system
NAME                                   READY   STATUS    RESTARTS      AGE
grafana-847757d67c-rwzmc               2/2     Running   0             5d19h
istio-egressgateway-7b47b5b78c-ln28c   1/1     Running   0             5d19h
istio-ingressgateway-bc446949b-2tc88   1/1     Running   0             5d19h
istiod-basic-59d7548c55-6g6vz          1/1     Running   0             5d19h
jaeger-6bfb9c97bc-qklx9                2/2     Running   0             2d2h
kiali-7b4c9db8ff-jdwwq                 1/1     Running   2 (11h ago)   5d7h
prometheus-664b4b8975-gmcxc            2/2     Running   4 (45h ago)   5d19h
```

Kserve + webapp is also installed:

```bash
[root@p1217-bastion ~]# oc get pods -n kserve
NAME                                         READY   STATUS    RESTARTS           AGE
kserve-controller-manager-5d577f846b-5xgcm   2/2     Running   1005 (6m24s ago)   5d7h
kserve-models-web-app-7f574c68-p6pkk         1/1     Running   40 (141m ago)      5d7h
```

I would expect to reach the webapp under `istio-ingressgateway-istio-system.apps.<cluster-url>/kserve-endpoints` however that doesn't work 🤔

Any input is appreciated :-)

**Comment by yuzisun** [comment]
@mgiessing please checkout the latest openshift doc https://github.com/kserve/kserve/pull/2855
