### ISSUE TITLE
Question: Custom storage initializer container

### ISSUE THREAD

**Issue by SebastianScherer88** [kserve/kserve#2727]
/kind feature

**Describe the solution you'd like**
A question rather than a feature request. My team uses a dedicated model registry with an S3 storage backend. it comes with versioning and downloading utilities. We would like our storage initializer container to 
- check if the model required in the manifest is present in the locally mounted pod volume
  - if yes: great!
  - if not: download it from the model registry and put it there

Then the serving container would start up and access the artifact in the mounted pod volume much like the current off the shelve runtimes.

My question is: how would i best implement that?

My current approach would be to use the custom predictor and its pod spec to define all of the above resources much like with any other K8s deployment manifest. I.e. list the custom storage initializer image as one of the init containers etc.

Is there a better way, maybe using custom serving runtimes or something? and is there a place in the repo where i would see the manifests (i.e. the runtimes that you are providing out of the box, like sklearn etc) that are implementing the current storage initializer behaviour (the one that simply downloads the file specified in the `storageUri` field of the off the shelve predictor manifest)?

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

**Comment by zenglw06** [comment]
we had the same problem.......

**Comment by zenglw06** [comment]
we meet the same problem. our models are saved in CubeFS which supports s3 protocol. we refactor the storage init container, if the storage URI starts with CFS, we add a  CFS volume in the storage init container, then just copy the file

@SebastianScherer88
