### ISSUE TITLE
Support setting labels and annotations on component level

### ISSUE THREAD

**Issue by lizzzcai** [kserve/kserve#2743]
/kind feature

**Describe the solution you'd like**

To have dedicated `labels` and `annotations` fields under `predictor` and `transformer` and `explainer`, so that the user is able to assign dedicated labels and annotations for each component.

**Anything else you would like to add:**

Currently, in KServe InferenceService, the labels and annotations on the metadata will be passed to the actual pod of predictor, transformer and explainer. 

Use cases:
1. set different KNative autoscaling [annotations](https://knative.dev/docs/serving/autoscaling/autoscaling-metrics/) on each component, for example, predictor scales based on `rps` and transformer scales based on `cpu`.
2. we are using `annotation` to inject the `resources` and `node selector`, in the current KServe, as the annotations are on the metadata level, all the components will be using the same resources (for example GPU node for predictor, transformer and explainer) which is not expected.

**Comment by lizzzcai** [comment]
Hi @yuzisun, I create a [PR](https://github.com/kserve/kserve/pull/2925) for this issue, not sure if possible to include it in `v0.11`.

**Comment by yuzisun** [comment]
We are still a month away from the official 0.11 release, we should be able to include this.
