### ISSUE TITLE
Support for v2 inference request of datatype bytes in HTTP

### ISSUE THREAD

**Issue by jagadeeshi2i** [kserve/kserve#2746]
/kind bug

With the earlier tornado web server the data field with `string` input and datatype `BYTES` was considered valid. Example - https://github.com/kserve/kserve/blob/master/docs/samples/v1beta1/torchserve/v2/bytes_conv/mnist_v2_bytes.json

WIth current FastAPI server, the validator expects the data field to be a list. 

From the docs there is no example for representing bytes datatype in v2 protocol inference request. So what is the recommended way of sending the bytesarray for HTTP request ?

**Environment:**

- Istio Version:
- Knative Version:
- KServe Version:
- Kubeflow version:
- Cloud Environment:[k8s_istio/istio_dex/gcp_basic_auth/gcp_iap/aws/aws_cognito/ibm]
- Minikube/Kind version:
- Kubernetes version: (use `kubectl version`):
- OS (e.g. from `/etc/os-release`):

**Comment by Suresh-Nakkeran** [comment]
@jagadeeshi2i  Can you try as follow?
`{
  "inputs": [
    {
      "name": "mixed",
      "shape": [
        1
      ],
      "datatype": "BYTES",
      "contents": {
        "bytes_contents": [
          {
            "MSZoning": "RL",
            "LotArea": 8450,
            "LotShape": "Reg",
            "Utilities": "AllPub",
            "YrSold": 2008,
            "Neighborhood": "CollgCr",
            "OverallQual": 7,
            "YearBuilt": 2003,
            "SaleType": "WD",
            "GarageArea": 548
          }
        ]
      }
    }
  ]
}`

**Comment by Suresh-Nakkeran** [comment]
@jagadeeshi2i  Can you try as follow?
`{
  "inputs": [
    {
      "name": "mixed",
      "shape": [
        1
      ],
      "datatype": "BYTES",
      "contents": {
        "bytes_contents": [
          {
            "MSZoning": "RL",
            "LotArea": 8450,
            "LotShape": "Reg",
            "Utilities": "AllPub",
            "YrSold": 2008,
            "Neighborhood": "CollgCr",
            "OverallQual": 7,
            "YearBuilt": 2003,
            "SaleType": "WD",
            "GarageArea": 548
          }
        ]
      }
    }
  ]
}`

**Comment by jagadeeshi2i** [comment]
@Suresh-Nakkeran I doubt the above format seems to be the one for gRPC. https://github.com/kserve/kserve/blob/38d9a5695446f2610d274ab8efb4238a90bbc943/docs/predict-api/v2/grpc_predict_v2.proto#L283 From the docs the HTTP might expect `data` field in the input - https://github.com/kserve/kserve/blob/master/docs/predict-api/v2/required_api.md#request-input

**Comment by Suresh-Nakkeran** [comment]
@jagadeeshi2i  Sorry, you're right. It's for gRPC. Can you try as follow for HTTP?
```
{
  "inputs": [
    {
      "name": "foo",
      "shape": [1,1],
      "datatype": "BYTES",
      "data": [
        "hello world!"
      ]
    }
  ]
}
```

**Comment by jagadeeshi2i** [comment]
Seems that is the right approach and even MLServer represents bytesarray as you suggested.

https://github.com/SeldonIO/MLServer/blob/master/docs/user-guide/content-type.md#base64
```
{
  "inputs": [
    {
      "name": "foo",
      "parameters": {
        "content_type": "base64"
      },
      "data": ["UHl0aG9uIGlzIGZ1bg=="]
      "datatype": "BYTES",
      "shape": [1],
    }
  ]
}
```
Thanks @Suresh-Nakkeran will proceed with this.
