### ISSUE TITLE
Inference Service prediction failed with 403 Forbidden when run the first InferenceService 

### ISSUE THREAD

**Issue by saintnoah** [kserve/kserve#2750]
/kind bug

**What steps did you take and what happened:**
1. Installed KF 1.6 on k8s 1.24.9.
2. Deployed kubeflow using one line command and all pods are up and running
3. Follow the [instruction ](https://kserve.github.io/website/0.8/get_started/first_isvc/)to run the first inferenceservice
4. perform inference

```
$curl -v -H "Host: ${SERVICE_HOSTNAME}" -H "Cookie: authservice_session=${SESSION}" http://${INGRESS_HOST}:${INGRESS_PORT}/v1/models/sklearn-iris:predict -d @./iris-input.json
*   Trying 20.237.250.102:80...
* Connected to 20.237.250.102 (20.237.250.102) port 80 (#0)
> POST /v1/models/sklearn-iris:predict HTTP/1.1
> Host: sklearn-iris.kserve-test.example.com
> User-Agent: curl/7.86.0
> Accept: */*
> Cookie: authservice_session=hJR2oiSpPsTdpqz1i_ikwBYr1nCA9Iu
> Content-Length: 76
> Content-Type: application/x-www-form-urlencoded
>
* Mark bundle as not supporting multiuse
< HTTP/1.1 403 Forbidden
< date: Sun, 12 Mar 2023 09:48:46 GMT
< server: istio-envoy
< content-length: 0
<
* Connection #0 to host 20.237.250.102 left intact
```

**What did you expect to happen:**
see two predictions returned (i.e. {"predictions": [1, 1]})

**What's the InferenceService yaml:**

```
apiVersion: "serving.kserve.io/v1beta1"
kind: "InferenceService"
metadata:
  name: "sklearn-iris"
spec:
  predictor:
    model:
      modelFormat:
        name: sklearn
      storageUri: "gs://kfserving-examples/models/sklearn/1.0/model"
```

**Anything else you would like to add:**

**Environment:**

- Istio Version: 1.14
- Knative Version: 1.2.5
- KServe Version: 0.8
- Kubeflow version: 1.6
- Cloud Environment: [aks]
- Minikube/Kind version: NA
- Kubernetes version: (use `kubectl version`):1.24.9
- OS (e.g. from `/etc/os-release`): Ubuntu

**Comment by saintnoah** [comment]
InferenceService  Status:
```
$ k get inferenceservice -n kserve-test
NAME           URL                                           READY   PREV   LATEST   PREVROLLEDOUTREVISION   LATESTREADYREVISION
 AGE
sklearn-iris   http://sklearn-iris.kserve-test.example.com   True           100                              sklearn-iris-predictor-default-00001  
 30m
```

**Comment by sivanantha321** [comment]
Please follow the [tutorial here to authenticate with istio-dex](https://github.com/kserve/kserve/tree/master/docs/samples/istio-dex).
