### ISSUE TITLE
Docker Free Teams Organizations will be sunset

### ISSUE THREAD

**Issue by tenzen-y** [kserve/kserve#2758]
Currently, kserve is using dockerhub to publish our container images, and we have a dockerhub Org.

- https://hub.docker.com/u/kserve

However, according to [this Docker official blog](https://www.docker.com/blog/we-apologize-we-did-a-terrible-job-announcing-the-end-of-docker-free-teams/), Docker will stop providing Free Team Organization on April 13, 2023, and It seems that we will be unavailable to push new images and tags, although we will be able to pull existing Images.

ref: https://github.com/docker/hub-feedback/issues/2314

So we must apply for Docker-Sponsored Open Source (DSOS) program or migrate the image registry to another one.

cc: @kserve/kserve-owners @kserve/modelmesh-maintainers 

/kind discussion

**Comment by yuzisun** [comment]
We have already applied for DSOS, but we will need to have a contingency plan to get the funding to migrate to the other image registry.

**Comment by tenzen-y** [comment]
> We have already applied for DSOS

Thank you for applying DSOS!

>  we will need to have a contingency plan to get the funding to migrate to the other image registry.

Migrating to [quai.io](https://quay.io/) might be a better way.

**Comment by ckadner** [comment]
> Migrating to [quai.io](https://quay.io/) might be a better way.

Migrating to another registry would work for future releases of KServe/ModelMesh only. Existing installations will break once the current `kserve` DockerHub org gets shut down.

@yuzisun -- did you already reach out to LFAI for possible bridge-founding until the OS exemption may get approved?

**Comment by ckadner** [comment]
We may have some more time to consider our long-term strategy :-)

**This just came in from Docker:**
> On March 14, 2023, we emailed you about your _Free Team subscription_, outlining our intention to sunset that plan. After listening to the concerns of the community, **we’ve decided to reverse course, and are no longer sunsetting the Free Team plan.**
> If you’re currently on the Free Team plan, you no longer have to migrate to another plan by April 14. All customers who upgraded to a paid subscription will automatically receive a full refund for the transaction in the next 30 days, allowing them to use their new paid subscription for free for the duration of the term they purchased.
We apologize for the alarm our decision caused. For more details, please [visit our FAQ](https://em.docker.com/NzkwLVNTQi0zNzUAAAGKtH0YHn9ipRJPWTkzYJQbAN5-Jo1s7oIOVxV0PMcCkguRTUlS7zCEVxbSOYw2s2-XhzuuB0s=).

**Comment by tenzen-y** [comment]
Thank you for letting me know!

**Comment by ckadner** [comment]
@yuzisun -- did you get any notification from Docker about your DSOS application yet?

I had applied for the Docker Open Source sponsorship program for another project and I received this email from Docker earlier this week:

> Congratulations! Your project has been approved for the Docker-Sponsored Open Source program. A Docker Team subscription will be allocated to the project organization Docker ID specified in your application within the next 3 weeks. In addition to a Team subscription, you now have:
> - free autobuilds
> - rate-limit removal for all users pulling public images from your project namespace
> - special badging on Docker Hub (this will be visible within two weeks)
> 
> If you haven’t already, please take the time to update your project’s Hub pages to include a detailed project description, links to your project source code, as well as contributing guidelines, and a link to your organization’s website. Projects lacking this information may not receive the Docker Sponsored Open Source badging for their images on Docker Hub.
Membership in the Docker-Sponsored Open Source (DSOS) program is valid for one year. You will receive a reminder email from us when it is time to renew your membership.
> 
> We are thrilled to have you as an open-source partner. If you have any questions regarding the open source program please contact [opensource@docker.com](mailto:opensource@docker.com) and include the name of your project in the subject line. If you have questions regarding technical support please contact [support@docker.com](mailto:support@docker.com).
Thank you!
