### ISSUE TITLE
Customize the Uvicorn's access log format on Kserve 0.10+

### ISSUE THREAD

**Issue by elukey** [kserve/kserve#2778]
/kind feature

**Describe the solution you'd like**
Hi folks! As far as I can see the Uvicorn's logging config in 0.10+ for FastAPI is hardcoded in the `UvicornServer`, and I didn't find a good way to change the access log format to something custom. For example, I'd like to use a json/ECS format to be able to ingest my model server's access logs, index them and query the results via Kibana (for example, to inspect traffic patterns etc..).

Maybe we could allow to pass a custom configuration from the `ModelServer`'s class parameters?

**Anything else you would like to add:**
None

**Comment by rachitchauhan43** [comment]
@elukey : This is what I was able to do override root logger but I don't think this is the right and suggested pattern. 
``` 

import kserve
from typing import Dict
import argparse
import logging

logger = logging.getLogger()

class CusomPredictor(kserve.Model):
    def __init__(self, name: str):
        super().__init__(name)
        self.name = name
        self.load()

    def load(self):
        self.ready = True

    def setup_logger(self, trace_id):
        print('inside setup_logger')
        formatter = logging.Formatter(f'%(asctime)s.%(msecs)03d - {trace_id} - %(levelname)s - %(module)s: %(message)s')
        hdlr = logger.handlers[0]
        hdlr.setFormatter(formatter)
        logger.addHandler(hdlr)

    def predict(self, request: Dict, headers: Dict) -> Dict:
        self.setup_logger(headers["trace_id"])
        logger.info("SAMPLE LOG LINE")
        .......
        return response
```

Basically I am hijacking the root logger's `setup_logger` handler to add trace_id in every log line so that I can search all logs using that trace_id.

After this I was able to see trace_id , `1-82cce9f1-7d3b-49e2-9777-0c00bd711f10`,  in every log:
```
2023-01-31 23:53:16,389.389 - 1-82cce9f1-7d3b-49e2-9777-0c00bd711f10 - INFO - model: SAMPLE LOG LINE
2023-01-31 23:53:16,943.943 - 1-82cce9f1-7d3b-49e2-9777-0c00bd711f10 - INFO - model: requestId: N.A., preprocess_ms: 0.070810318, explain_ms: 0, predict_ms: 553.462028503, postprocess_ms: 0.032663345
2023-01-31 23:53:16,943.943 - 1-82cce9f1-7d3b-49e2-9777-0c00bd711f10 - INFO - server: kserve.io.kserve.protocol.rest.v1_endpoints.predict 0.5562052726745605, ['http_status:200', 'http_method:POST', 'time:wall']
2023-01-31 23:53:16,944.944 - 1-82cce9f1-7d3b-49e2-9777-0c00bd711f10 - INFO - server: kserve.io.kserve.protocol.rest.v1_endpoints.predict 0.032679999999999994, ['http_status:200', 'http_method:POST', 'time:cpu']
```
I agree with you that we should be able to influence the logger.

**Comment by elukey** [comment]
@rachitchauhan43 thanks for the info!

While working on the KServe code I noticed something odd though - namely I am not 100% sure that it logs the Uvicorn's access logs to stdout.

For example, in your example above:

```
2023-01-31 23:53:16,943.943 - 1-82cce9f1-7d3b-49e2-9777-0c00bd711f10 - INFO - model: requestId: N.A., preprocess_ms: 0.070810318, explain_ms: 0, predict_ms: 553.462028503, postprocess_ms: 0.032663345
2023-01-31 23:53:16,943.943 - 1-82cce9f1-7d3b-49e2-9777-0c00bd711f10 - INFO - server: kserve.io.kserve.protocol.rest.v1_endpoints.predict 0.5562052726745605, ['http_status:200', 'http_method:POST', 'time:wall']
2023-01-31 23:53:16,944.944 - 1-82cce9f1-7d3b-49e2-9777-0c00bd711f10 - INFO - server: kserve.io.kserve.protocol.rest.v1_endpoints.predict 0.032679999999999994, ['http_status:200', 'http_method:POST', 'time:cpu']
```

The first line is related `enable_latency_logging`, and prints precise timings. The other two lines should be related to the following bit of code in `server.py`:

```
        app.add_middleware(
            TimingMiddleware,
            client=PrintTimings(),
            metric_namer=StarletteScopeToName(prefix="kserve.io", starlette_app=app)
        )
```
But I don't see anything related to the access formatter, that is:

```
'%(asctime)s.%(msecs)03d %(name)s %(levelprefix)s %(client_addr)s %(process)s - '
                           '"%(request_line)s" %(status_code)s'
```
For example, given the above, I'd expect to see some IP addresses in my pod's stdout, but I don't find any. Probably I am missing something, but I am wondering if the access log is not configured properly.

**Comment by elukey** [comment]
I found out something super interesting about Uvicorn: https://github.com/encode/uvicorn/blob/master/uvicorn/config.py#L385

If the log config is a string ending up with "json" or "yaml", it is interpreted as file path and the config is loaded from there.

**Comment by elukey** [comment]
Ok so I think that something like https://github.com/elukey/kfserving/commit/8fcd7d1013345dcc8388dfde1097914c4644df9a may work, but I'd need to figure out why the current config (the dictionary hardcoded) doesn't work (namely why I don't see an access log with IPs etc.. in my pod's stdout).

**Comment by elukey** [comment]
Ok I think I found something odd in the config, it used "rest" and not "handlers" like suggested in https://docs.python.org/3/library/logging.config.html. I need to find a way to test this change, after that I'll report back :) Feedback welcome!

Change is https://github.com/elukey/kfserving/commit/771fff092a883b12b192b3be06e025c5aa395f9a

**Comment by elukey** [comment]
The PR should be ready for reviews!

**Comment by elukey** [comment]
Adding https://github.com/encode/uvicorn/issues/527 to the conversation - ideally I'd like to be able to configure the uvicorn's access log with basic info like User Agent etc.. (basically HTTP request headers), but I still haven't found a way to do it.

**Comment by elukey** [comment]
Interesting, the way to go seems to use https://github.com/Kludex/asgi-logger and avoid the uvicorn.access handler.

I updated the PR to use asgi-logger :)
