### ISSUE TITLE
Explore supporting SSE (Server-Sent Events) streaming for LLM

### ISSUE THREAD

**Issue by ghost** [kserve/kserve#2788]
/kind feature

Why: currently, KServe has no ability to stream the outputs (e.g. ChatGPT), it would be very useful for KServe to support this feature out-of-box in the Python SDK to enable use cases in language models.

**Describe the solution you'd like**

- Extend current Inference request/response protocol to support `stream`
- Leverage https://github.com/sysid/sse-starlette to return `EventSourceResponse` in FastAPI

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

Related links:
- https://learn.microsoft.com/en-us/azure/cognitive-services/openai/reference#:~:text=max_tokens%20and%20stop.-,stream,-boolean
- https://huggingface.co/docs/transformers/internal/generation_utils
- https://twitter.com/joao_gante/status/1641435222679130112?s=46
- https://betterprogramming.pub/openai-sse-sever-side-events-streaming-api-733b8ec32897

**Comment by ghost** [comment]
For reference, OpenAI API stream response looks like this:

```
data: {"id":"chatcmpl-71zdOYCb0s0P6rNQOxNLacZML4KoE","object":"chat.completion.chunk","created":1680709606,"model":"gpt-3.5-turbo-0301","choices":[{"delta":{"role":"assistant"},"index":0,"finish_reason":null}]}

data: {"id":"chatcmpl-71zdOYCb0s0P6rNQOxNLacZML4KoE","object":"chat.completion.chunk","created":1680709606,"model":"gpt-3.5-turbo-0301","choices":[{"delta":{"content":"Hello"},"index":0,"finish_reason":null}]}

data: {"id":"chatcmpl-71zdOYCb0s0P6rNQOxNLacZML4KoE","object":"chat.completion.chunk","created":1680709606,"model":"gpt-3.5-turbo-0301","choices":[{"delta":{"content":"!"},"index":0,"finish_reason":null}]}

data: {"id":"chatcmpl-71zdOYCb0s0P6rNQOxNLacZML4KoE","object":"chat.completion.chunk","created":1680709606,"model":"gpt-3.5-turbo-0301","choices":[{"delta":{"content":" How"},"index":0,"finish_reason":null}]}

data: {"id":"chatcmpl-71zdOYCb0s0P6rNQOxNLacZML4KoE","object":"chat.completion.chunk","created":1680709606,"model":"gpt-3.5-turbo-0301","choices":[{"delta":{"content":" may"},"index":0,"finish_reason":null}]}

data: {"id":"chatcmpl-71zdOYCb0s0P6rNQOxNLacZML4KoE","object":"chat.completion.chunk","created":1680709606,"model":"gpt-3.5-turbo-0301","choices":[{"delta":{"content":" I"},"index":0,"finish_reason":null}]}

data: {"id":"chatcmpl-71zdOYCb0s0P6rNQOxNLacZML4KoE","object":"chat.completion.chunk","created":1680709606,"model":"gpt-3.5-turbo-0301","choices":[{"delta":{"content":" assist"},"index":0,"finish_reason":null}]}

data: {"id":"chatcmpl-71zdOYCb0s0P6rNQOxNLacZML4KoE","object":"chat.completion.chunk","created":1680709606,"model":"gpt-3.5-turbo-0301","choices":[{"delta":{"content":" you"},"index":0,"finish_reason":null}]}

data: {"id":"chatcmpl-71zdOYCb0s0P6rNQOxNLacZML4KoE","object":"chat.completion.chunk","created":1680709606,"model":"gpt-3.5-turbo-0301","choices":[{"delta":{"content":" today"},"index":0,"finish_reason":null}]}

data: {"id":"chatcmpl-71zdOYCb0s0P6rNQOxNLacZML4KoE","object":"chat.completion.chunk","created":1680709606,"model":"gpt-3.5-turbo-0301","choices":[{"delta":{"content":"?"},"index":0,"finish_reason":null}]}

data: {"id":"chatcmpl-71zdOYCb0s0P6rNQOxNLacZML4KoE","object":"chat.completion.chunk","created":1680709606,"model":"gpt-3.5-turbo-0301","choices":[{"delta":{},"index":0,"finish_reason":"stop"}]}

data: [DONE]
```

the format follows `data: <data>`, if it's not `[DONE]` then it can be parsed as normal JSON, and the output of the model resides in `resp.Choices[0].Delta.Content`

**Comment by cmaddalozzo** [comment]
Should we just use chunked encoding for this rather than server sent events? The SSE specification [doesn't support `POST`](https://stackoverflow.com/a/34285526) so clients will not be able to leverage the [`EventSource` API](https://developer.mozilla.org/en-US/docs/Web/API/Server-sent_events/Using_server-sent_events). It would like similar to the example from OpenAI except there will be no `data` labels and instead of sending a special `[DONE]` token we can just close the connection on the server side when we are done sending the response.

**Comment by cakeislife100** [comment]
@yuzisun what's the thinking on whether KServe will support this? This will be huge to enable LLM support. Wanted to bump the thread because it's been a couple months since the last activity

**Comment by ghost** [comment]
Related PR: https://github.com/kserve/kserve/pull/3334

**Comment by mginfn** [comment]
Hi, I found that on the master branch the v2 endpoints support streaming, routing to the following handler:
https://github.com/kserve/kserve/blob/99ac7b2050fafb14b7114b94ad6e3fd7ecfe3d15/python/kserve/kserve/protocol/rest/v2_endpoints.py#L211

However, I had a problem with the generated output of the above handler:
https://github.com/kserve/kserve/blob/99ac7b2050fafb14b7114b94ad6e3fd7ecfe3d15/python/kserve/kserve/protocol/rest/v2_endpoints.py#L260

I would say that the above output is not compliant with SSE, as it's missing the "data: " prefix (as shown [here](https://html.spec.whatwg.org/multipage/server-sent-events.html#server-sent-events-intro)) and the double newline to complete the event.
Modifying the above line with the following:
`  yield ("data: " + ret.json() + "\r\n\r\n").encode("utf-8")`
fixes the issue.

I tried the fixed endpoint on an Angular application using the library [sse.js](https://www.npmjs.com/package/sse) and it works fine.
The library sse.js indeed assumes the "data: " prefix and double newline to split different events. 

To complete the issue, I faced another problem with the frontend application, that is the missing CORS headers, currently I've solved adding the following lines:
`
app.add_middleware(
  CORSMiddleware,
  allow_origins=["*"],
            allow_credentials=True,
            allow_methods=["*"],
            allow_headers=["*"],
        )
`
just after:
https://github.com/kserve/kserve/blob/99ac7b2050fafb14b7114b94ad6e3fd7ecfe3d15/python/kserve/kserve/protocol/rest/server.py#L146
I still don't know if there's a way to have KServe support CORS headers, any hint?
Thanks

**Comment by yuzisun** [comment]
streaming is fully supported via openai protocol in 0.13.
