### ISSUE TITLE
Revision "sklearn-iris-predictor-default-00001" failed with message: Unable to fetch image "docker.io/seldonio/mlserver:0.5.3": failed to resolve image to digest: Get "https://index.docker.io/v2/": context deadline exceeded

### ISSUE THREAD

**Issue by vinayK34** [kserve/kserve#2822]
Hi, I am trying to build a inferenceserver using below example set 
https://github.com/yingding/kf-examples/blob/main/kserve_example.ipynb
And getting below error - 
Revision "sklearn-iris-predictor-default-00001" failed with message: Unable to fetch image "docker.io/seldonio/mlserver:0.5.3": failed to resolve image to digest: Get "https://index.docker.io/v2/": context deadline exceeded

I was thinking to build my custom seldonio/mlserver:0.5.3 in our private image repo. Can someone help mr how to do that, can I directly create a InferenceService using yaml configuration where I can provide storageUri and my custom  mlserver image

**Comment by sivanantha321** [comment]
@vinayK34 It might be a network problem. The documentation for [building custom runtime](https://kserve.github.io/website/0.10/modelserving/v1beta1/custom/custom_model/) can be found on the kserve website. Also refer [serving runtime](https://kserve.github.io/website/0.10/modelserving/servingruntimes/).

**Comment by vinayK34** [comment]
@sivanantha321 Is their way to run this runtime server in our private repository and point to that specific server runtime instead of docker.io

**Comment by yuzisun** [comment]
> @sivanantha321 Is their way to run this runtime server in our private repository and point to that specific server runtime instead of docker.io

You can update serving runtimes to point to your images in private repository. For example https://github.com/kserve/kserve/blob/65cb2216540ca5f97d47c4e278325bf6a8fb32e1/config/runtimes/kserve-sklearnserver.yaml#L17

**Comment by vinayK34** [comment]
Hi @sivanantha321 @yuzisun  I have tried that one also, created my own ClusterServingRuntime
apiVersion: serving.kserve.io/v1alpha1
kind: ClusterServingRuntime
metadata:
  name: kserve-sklearnserver-vinay
spec:
  supportedModelFormats:
    - name: sklearn
      version: "1"
      autoSelect: true
  containers:
    - name: kserve-container
      image: url/seldonio-mlserver:0.5.3
      args:
        - --model_name={{.Name}}
        - --model_dir=/mnt/models
        - --http_port=8080
      resources:
        requests:
          cpu: "1"
          memory: 2Gi
        limits:
          cpu: "1"
          memory: 2Gi



But still my inferenceservice are in failed state. I see the revision event that says  - InternalError  14s   revision-controller  failed to update deployment "example-sklearn-isvc-v2-predictor-default-00001-deployment": Operation cannot be fulfilled on deployments.apps "example-sklearn-isvc-v2-predictor-default-00001-deployment": the object has been modified; please apply your changes to the latest version and try again

**Comment by kenwoodjw** [comment]
same

**Comment by sivanantha321** [comment]
@vinayK34 Is the pods up and running? If yes, then can you provide predictor pod logs?

**Comment by skuchipu** [comment]
I see similar issue , do we have a solution for this ?

**Comment by yuzisun** [comment]
> Hi @sivanantha321 @yuzisun I have tried that one also, created my own ClusterServingRuntime apiVersion: serving.kserve.io/v1alpha1 kind: ClusterServingRuntime metadata: name: kserve-sklearnserver-vinay spec: supportedModelFormats: - name: sklearn version: "1" autoSelect: true containers: - name: kserve-container image: url/seldonio-mlserver:0.5.3 args: - --model_name={{.Name}} - --model_dir=/mnt/models - --http_port=8080 resources: requests: cpu: "1" memory: 2Gi limits: cpu: "1" memory: 2Gi
> 
> But still my inferenceservice are in failed state. I see the revision event that says - InternalError 14s revision-controller failed to update deployment "example-sklearn-isvc-v2-predictor-default-00001-deployment": Operation cannot be fulfilled on deployments.apps "example-sklearn-isvc-v2-predictor-default-00001-deployment": the object has been modified; please apply your changes to the latest version and try again

I think it worked and that error is benign, it is a kubernetes internal retry when there are version conflicts.

**Comment by yuzisun** [comment]
Let us know if this is still an issue
