### ISSUE TITLE
option to load credentials directly from a secret for s3

### ISSUE THREAD

**Issue by ryandawsonuk** [kserve/kserve#284]
Currently to download from a private S3 bucket [you create both a secret and a service account that you link it to](https://github.com/kubeflow/kfserving/blob/master/docs/samples/s3/s3_secret.yaml). You then set the [serviceAccountName on the KFService ](https://github.com/kubeflow/kfserving/blob/master/docs/samples/s3/tensorflow_s3.yaml#L7) and it is [used to add env vars based on the secret to the initContainer that downloads the model](https://github.com/kubeflow/kfserving/blob/master/pkg/controller/kfservice/resources/credentials/service_account_credentials.go#L94).

It might be easier for s3 users to just create a secret containing entries intended as environment variables and link that directly by having a 'envSecretRefName' entry in the CRD. This could be used in the implementation to use 'envFrom' to apply the secret's values.

It seems the[ original idea for credentials was to use a Secret ](https://github.com/kubeflow/kfserving/issues/36)and this morphed into a ServiceAccount as a 'first pass'. Presumably there's no in principle objection to also supporting a direct secret for s3?

**Comment by axsaucedo** [comment]
I would second this, and even making it easier by using a secret with the name `s3-auth` or similar by default if present, as this would make AWS support easier (and could be a similar approach to other cloud providers)

**Comment by ca-scribner** [comment]
Did this ever get actioned?  I see still in the docs that a `ServiceAccount` is used as the way to pass credentials.  Can I also pass them directly via a `Secret`?

**Comment by greenmoon55** [comment]
> Did this ever get actioned? I see still in the docs that a `ServiceAccount` is used as the way to pass credentials. Can I also pass them directly via a `Secret`?

Hi, I believe you can create a secret named `storage-config` and pass the credential key in the InferenceService spec. Here's an example. https://github.com/kserve/kserve/blob/master/docs/samples/storage/storageSpec/README.md

Here's the code pointer. https://github.com/kserve/kserve/blob/master/pkg/webhook/admission/pod/storage_initializer_injector.go#L301-L320

**Comment by greenmoon55** [comment]
Looks like it will be fixed by #3034
