### ISSUE TITLE
KServe RestServer Disabling Other Customized Module Level Loggings

### ISSUE THREAD

**Issue by Yucao42** [kserve/kserve#2851]
/kind bug

**What steps did you take and what happened:**
We have used our own module level loggings but no log from our code will show up. Our logs are likely to be suppressed by this part of the [code](https://github.com/kserve/kserve/blob/389659a0c5067d2086cf960dcb1149d676254025/python/kserve/kserve/protocol/rest/server.py#L141-L176) where `disable_existing_loggers=False` is not included. Since this value is defaulted to be `True` according to the [document](https://docs.python.org/3/library/logging.config.html#logging-config-dictschema) of logging . Omitting this will disable every other logger but just keep the kserve *rest server ones*.

**What did you expect to happen:** Our customized module level loggings to show up.

**What's the InferenceService yaml:**
[To help us debug please run `kubectl get isvc $name -n $namespace -oyaml` and paste the output]

**Anything else you would like to add:**
A one line change of adding  `disable_existing_loggers=False` between [code](https://github.com/kserve/kserve/blob/389659a0c5067d2086cf960dcb1149d676254025/python/kserve/kserve/protocol/rest/server.py#L141-L176) might be able to fix this. Also we might want to use module level logger in `model_server` [here](https://github.com/kserve/kserve/blob/389659a0c5067d2086cf960dcb1149d676254025/python/kserve/kserve/model_server.py#L63) according to [logging library documentation which suggests not using root logger](https://docs.python.org/3/howto/logging.html#configuring-logging-for-a-library) just like the used uvicorn server [logger](https://github.com/encode/uvicorn/blob/master/uvicorn/server.py#L34). Thank you!

**Environment:**

- Istio Version:
- Knative Version:
- KServe Version:
- Kubeflow version:
- Cloud Environment:[k8s_istio/istio_dex/gcp_basic_auth/gcp_iap/aws/aws_cognito/ibm]
- Minikube/Kind version:
- Kubernetes version: (use `kubectl version`):
- OS (e.g. from `/etc/os-release`):

**Comment by yuzisun** [comment]
Thanks @Yucao42 for submitting the issue!

**Comment by yuzisun** [comment]
Thanks @Yucao42 for submitting the issue!

**Comment by amitchnick** [comment]
Thank you @Yucao42 for submitting this (and great find)! Would it be possible for this fix to go into a patch version, instead of waiting until `0.11`? This is blocking my team from being able to upgrade from `kfserving` -> `kserve`, since we cannot see any of our own system logs.
Thank you!
