### ISSUE TITLE
Transformer image approx 7GB in size, transformer pod takes a lot of time to start

### ISSUE THREAD

**Issue by pallav0894** [kserve/kserve#2861]
/kind bug

**What steps did you take and what happened:**
Its not exactly a bug, just a functionally inefficiency. 

I followed steps given [here](https://kserve.github.io/website/0.10/modelserving/v1beta1/transformer/torchserve_image_transformer/) to package and push a transformer docker image ([Dockerfile](https://github.com/kserve/kserve/blob/release-0.10/python/custom_transformer.Dockerfile)) 
The image comes out to be ~7.5GB in size. This results in transformer pod taking a huge amount of time to start and hence inference service is not ready even after 15 min. This is not ideal for a production environment and a use case that I am trying to build. 

**What did you expect to happen:**
Lightweight image for the transformer code which is fast to push to a registry and pull from a registry

**What's the InferenceService yaml:**
N/A

**Anything else you would like to add:**
`pip install kserve` takes the most amount of time. It installs a large number of packages. Maybe we could separate packages into smaller modules instead of installing everything at once?

I might be missing something. Help is greatly appreciated

**Environment:**

- Istio Version: 1.14.6
- Knative Version: 1.4.0
- KServe Version: 0.10
- Kubeflow version:
- Minikube/Kind version:
- Kubernetes version: (use `kubectl version`): 1.24.9
- OS (e.g. from `/etc/os-release`): Ubuntu 22.04

**Comment by sivanantha321** [comment]
@pallav0894 There has been many changes since 0.10 release. Kserve storage dependency is optional now #2700. Also there is a WIP PR which makes ray as optional dependency #2854. Please try the [new custrom transformer dockerfile](https://github.com/kserve/kserve/blob/master/python/custom_transformer.Dockerfile)  which has much reduced size around ~1.5GB. Also, the custom transformer is used for demonstration purposes only.

**Comment by pallav0894** [comment]
Thanks for the quick answer @sivanantha321 . Let me try the new dockerfile

**Comment by elukey** [comment]
@pallav0894 another suggestion is to test `docker history $name-of-the-image` to figure out what layer is the biggest, maybe it is not `kserve` but something else.

**Comment by yuzisun** [comment]
The image should be much smaller now
https://hub.docker.com/r/kserve/image-transformer/tags

**Comment by pallav0894** [comment]
Thanks a lot! It's working much better for me now.

**Comment by pallav0894** [comment]
Could you also point me to the Dockerfile used to build that image? It already has a model.py and an entrypoint which I would like to customize according to my use case.

**Comment by pallav0894** [comment]
Nevermind, that was a stupid question. For others reading; I just did 

```
FROM kserve/image-transformer:latest

COPY my-own-transformer.py custom_transformer/

ENTRYPOINT ["python", "-m", "custom_transformer.my-own-transformer.py"]
```
