### ISSUE TITLE
Update Knative dependencies to a supported version

### ISSUE THREAD

**Issue by skonto** [kserve/kserve#2866]
/kind question

What is the process for upgrading KServe deps wrt Knative (is there component version support matrix for the next release)?  

For example KServe uses Knative Serving 0.34 (1.7). However, current Knative version is 1.10 and 1.7 is out of community support and soon 1.8 will be too. Check more [here](https://github.com/knative/community/blob/main/mechanics/RELEASE-SCHEDULE.md) about the version support. 
Should we go to Knative 1.10 given that Knative supports upgrading by a [single minor version](https://knative.dev/docs/install/upgrade/) number only? I suspect that Knative upgrades have not been a problem for users so far so this is mostly a go dep update issue for Kserve, correct?

**Comment by yuzisun** [comment]
This is handled as part of PR https://github.com/kserve/kserve/pull/2914
