### ISSUE TITLE
Adding prometheus annotations to InferenceService does not show torchserve metrics

### ISSUE THREAD

**Issue by yribeiro** [kserve/kserve#2894]
/kind bug

**What steps did you take and what happened:**

I am trying to deploy a custom `InferenceService` with a `torchserve` server backend image. I have all the torchserve configuration properties set as follows (and as [outlined here](https://pytorch.org/serve/metrics_api.html#prometheus-server)):

```bash
inference_address=http://0.0.0.0:8080
management_address=http://0.0.0.0:8081
metrics_address=http://0.0.0.0:8082
enable_metrics_api=true
metrics_format=prometheus
number_of_netty_threads=4
job_queue_size=10
service_envelope=kserve
model_store=/mnt/models/model-store
max_request_size=100000000
max_response_size=100000000
model_snapshot={"name":"startup.cfg", "modelCount":1, "models":{"player_detector":{"1.0":{"defaultVersion":true, "marName":"ai_object_detection.mar", "minWorkers":1, "maxWorkers":4, "batchSize":1, "maxBatchDelay":200, "responseTimeout":30000}}}}
```

I tested the metrics endpoint inside the pod, and it seems to be running as expected:

![image](https://github.com/kserve/kserve/assets/20907507/d3f9fc96-6fa0-46c9-a891-78f2a13ffeb7)

I followed [this guide](https://kserve.github.io/website/0.9/modelserving/v1beta1/torchserve/metrics/#create-the-inferenceservice) to add Prometheus monitoring metrics to my custom inference service (based on a torchserve server image - see YAML below). I also found [this guide](https://github.com/kserve/kserve/blob/master/qpext/README.md#configs) and I tried to apply the  `serving.kserve.io/enable-prometheus-scraping='true'` annotation to the YAML, but this did not work either. **Note:** I did not apply the patch as suggested in that guide. 

Both approaches above did not work as I could not get the torchserve specific metrics i.e. `ts_queue_latency_microseconds` etc in my prometheus dashboard. See below.

**What did you expect to happen:**

I expected to be able to select torchserve specific metrics such as `ts_latency`

![image](https://github.com/kserve/kserve/assets/20907507/e75f3175-5907-4f74-9881-4de94e00cc35)

I also expect to see `istio_agent_*` metrics in prometheus:

![image](https://github.com/kserve/kserve/assets/20907507/97addd3c-90d1-424d-a49f-3616945e1650)

**What's the InferenceService yaml:**

```bash
apiVersion: serving.kserve.io/v1beta1
kind: InferenceService
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"serving.kserve.io/v1beta1","kind":"InferenceService","metadata":{"annotations":{"proxy.istio.io/config":"{ \"holdApplicationUntilProxyStarts\": true }"},"labels":{"app.kubernetes.io/env":"kubeflow","app.kubernetes.io/instance":"predictor","app.kubernetes.io/name":"ai-object-detection","app.kubernetes.io/version":"0.3.0-8377259","kserve.cloudxlr8r.ai/bypass-auth":"true"},"name":"ai-object-detection","namespace":"ns-ci"},"spec":{"predictor":{"batcher":{"maxBatchSize":16,"maxLatency":200},"containers":[{"env":[{"name":"STORAGE_URI","value":"<OMITTED>"},{"name":"ENV_STATE","value":"kubeflow"}],"image":"368836370510.dkr.ecr.eu-west-2.amazonaws.com/ai_object_detection:torchserve-0.3.0-8377259","name":"kfserving-container","resources":{"limits":{"memory":"6Gi","nvidia.com/gpu":1},"requests":{"memory":"6Gi"}}}],"initContainers":{"args":["<OMITTED>","/mnt/models"],"image":"kfserving/storage-initializer:v0.6.1","name":"storage-initializer"},"maxReplicas":1,"minReplicas":1,"serviceAccountName":"kserve-s3-reader","timeout":120,"volumeMounts":[{"mountPath":"/mnt/models","name":"kfserving-provision-location","readonly":"true"}]}}}
    prometheus.io/port: "8082"
    prometheus.io/scrape: "true"
    proxy.istio.io/config: '{ "holdApplicationUntilProxyStarts": true }'
    serving.kserve.io/enable-prometheus-scraping: "true"
  creationTimestamp: "2023-04-20T11:54:39Z"
  finalizers:
  - inferenceservice.finalizers
  generation: 1
  labels:
    app.kubernetes.io/env: kubeflow
    app.kubernetes.io/instance: predictor
    app.kubernetes.io/name: ai-object-detection
    app.kubernetes.io/version: 0.3.0-8377259
  name: ai-object-detection
  namespace: ns-ci
  resourceVersion: "664087042"
  uid: b531f7f0-7b1f-4833-b3ae-5198521b0bcb
spec:
  predictor:
    batcher:
      maxBatchSize: 16
      maxLatency: 200
    containers:
    - env:
      - name: STORAGE_URI
        value: <OMITTED>
      - name: ENV_STATE
        value: kubeflow
      image: 368836370510.dkr.ecr.eu-west-2.amazonaws.com/ai_object_detection:torchserve-0.3.0-8377259
      name: kserve-container
      resources:
        limits:
          cpu: "1"
          memory: 6Gi
          nvidia.com/gpu: "1"
        requests:
          cpu: "1"
          memory: 6Gi
    maxReplicas: 1
    minReplicas: 1
    serviceAccountName: kserve-s3-reader
    timeout: 120
status:
  address:
    url: http://ai-object-detection.ns-ci.svc.cluster.local/v1/models/ai-object-detection:predict
  components:
    predictor:
      address:
        url: <OMITTED>
      latestCreatedRevision: ai-object-detection-predictor-default-00004
      latestReadyRevision: ai-object-detection-predictor-default-00004
      latestRolledoutRevision: ai-object-detection-predictor-default-00004
      previousRolledoutRevision: ai-object-detection-predictor-default-00003
      traffic:
      - latestRevision: true
        percent: 100
        revisionName: ai-object-detection-predictor-default-00004
      url: <OMITTED>
  conditions:
  - lastTransitionTime: "2023-05-11T11:55:15Z"
    status: "True"
    type: IngressReady
  - lastTransitionTime: "2023-05-11T11:55:13Z"
    severity: Info
    status: "True"
    type: PredictorConfigurationReady
  - lastTransitionTime: "2023-05-11T11:55:15Z"
    status: "True"
    type: PredictorReady
  - lastTransitionTime: "2023-05-11T11:55:15Z"
    severity: Info
    status: "True"
    type: PredictorRouteReady
  - lastTransitionTime: "2023-05-11T11:55:15Z"
    status: "True"
    type: Ready
  modelStatus:
    copies:
      failedCopies: 0
      totalCopies: 1
    states:
      activeModelState: Loaded
      targetModelState: Loaded
    transitionStatus: UpToDate
  url: <OMITTED>
```

**Environment:**

- Istio Version: 1.9.6
- Knative Version: 
- KServe Version: 0.9
- Kubeflow version: 1.4
- Cloud Environment: aws
- Minikube/Kind version: 
- Kubernetes version: (use `kubectl version`): 1.21
- OS (e.g. from `/etc/os-release`): Ubuntu 20.04

Any help here would be fantastic!

**Comment by yribeiro** [comment]
Just seen that the `queue-proxy` pod also creates a Prometheus exporter: 

![image](https://github.com/kserve/kserve/assets/20907507/870b54cd-584b-4f93-952e-ba3925593afa)

**Comment by jgoodman8** [comment]
An interesting finding, having this solved would be very useful!

**Comment by yuzisun** [comment]
@yribeiro the metrics aggregation was added in kserve 0.10 version, you also need **serving.kserve.io/enable-metric-aggregation** annotation to have queue proxy aggregate the metrics from torchserve container.

please check the doc here https://kserve.github.io/website/0.10/modelserving/observability/prometheus_metrics/

**Comment by yribeiro** [comment]
@yuzisun thanks for the quick response! Appreciate it. 

Thanks for the link as well. Bit unsure about this:

![image](https://github.com/kserve/kserve/assets/20907507/55f3137d-d21d-41cf-a773-8dd107c79ed8)

We have kubeflow + kserve installed as apps on our AWS EKS cluster. Once we upgrade to KServe 0.10, do we still need to apply the queue proxy extension?

**Comment by yuzisun** [comment]
> @yuzisun thanks for the quick response! Appreciate it.
> 
> Thanks for the link as well. Bit unsure about this:
> 
> ![image](https://user-images.githubusercontent.com/20907507/238309787-55f3137d-d21d-41cf-a773-8dd107c79ed8.png)
> 
> We have kubeflow + kserve installed as apps on our AWS EKS cluster. Once we upgrade to KServe 0.10, do we still need to apply the queue proxy extension?

Yes you would need to modify the knative configuration to use the queue proxy extension image, we are working on to upstream this feature to Knative itself so in future hopefully we do not need to do this.

**Comment by yribeiro** [comment]
Alright. Thanks for the response. Will close the issue now and move on to upgrading Kserve. 🔥
