### ISSUE TITLE
KServe storage-initializer error....!

### ISSUE THREAD

**Issue by HrushikeshGowda** [kserve/kserve#2938]
### Discussed in https://github.com/kserve/kserve/discussions/2937

<div type='discussions-op-text'>

<sup>Originally posted by **HrushikeshGowda** May 24, 2023</sup>
Hello guys...!
I am following https://kserve.github.io/website/0.7/modelserving/storage/uri/uri/ documentation to serve Tensorflow model
Once I run the tensorflow-from-uri-gzip.yaml (given in documentation) It gives storage-initialiser error like

raise RuntimeError("URI: %s did not respond with any of following \'Content-Type\': " % uri +
RuntimeError: URI: https://raw.githubusercontent.com/tduffy000/kfserving-uri-examples/master/tensorflow/frozen/model_artifacts.tar.gz did not respond with any of following 'Content-Type': application/x-tar, application/x-gtar, application/x-gzip, application/gzip

Please help me solve.....Thanks.... 🙏 </div>

**Comment by greenmoon55** [comment]
Have you checked if the url returns the correct content type?

**Comment by wjp-cn** [comment]
Hi, I tested this example in v0.10.0 without any issues. Perhaps you can try switching to v0.10.0

**Comment by sivanantha321** [comment]
As @Wercurial noted, this should be working. Feel free to open the issue if it is not resolved.
