### ISSUE TITLE
Need larger github action node to run triton test

### ISSUE THREAD

**Issue by yuzisun** [kserve/kserve#2950]
/kind bug

**What steps did you take and what happened:**
Triton images are too big to fit into the current size of github action node, and currently the test is disable because of that.
https://github.com/kserve/kserve/blob/master/test/e2e/predictor/test_triton.py#L31

**What did you expect to happen:**

**What's the InferenceService yaml:**
[To help us debug please run `kubectl get isvc $name -n $namespace -oyaml` and paste the output]

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

**Environment:**

- Istio Version:
- Knative Version:
- KServe Version:
- Kubeflow version:
- Cloud Environment:[k8s_istio/istio_dex/gcp_basic_auth/gcp_iap/aws/aws_cognito/ibm]
- Minikube/Kind version:
- Kubernetes version: (use `kubectl version`):
- OS (e.g. from `/etc/os-release`):

**Comment by ckadner** [comment]
@yuzisun -- and the GitHub workflow file is this one?

https://github.com/kserve/kserve/blob/6a824724aed4a1ffcca4623719858a83460df8d9/.github/workflows/e2e-test.yml#L176-L179

https://github.com/kserve/kserve/blob/6a824724aed4a1ffcca4623719858a83460df8d9/test/scripts/gh-actions/run-e2e-tests.sh#L26

**Comment by yuzisun** [comment]
Yes, that’s correct

**Comment by ckadner** [comment]
Okay, I will take a stab at it
