### ISSUE TITLE
What is the Default value of containerConcurrency in Inference Service

### ISSUE THREAD

**Issue by sidharthkumarpradhan** [kserve/kserve#2964]
/kind feature

Need help with understanding the default value for container concurrency value. If I will not specify any value, will 1 be taken as concurrency value? 

Thanks.

`
apiVersion: "serving.kserve.io/v1beta1"
kind: "InferenceService"
metadata:
  name: "flowers-sample"
spec:
  predictor:
    containerConcurrency: 10
    model:
      modelFormat:
        name: tensorflow
      storageUri: "gs://kfserving-examples/models/tensorflow/flowers"
`

**Comment by lizzzcai** [comment]
Hi @sidharthkumarpradhan , as far as I know the default `containerConcurrency` for KServe ISVC is `0`, which is [no limit](https://knative.dev/docs/serving/autoscaling/concurrency/#hard-limit), you can verify it by checking the knative resources `service.serving.knative.dev`.

**Comment by sivanantha321** [comment]
The default container concurrency is depends on the [knative configuration](https://knative.dev/docs/serving/configuration/config-defaults/#container-concurrency).

/close
