### ISSUE TITLE
How can i specify priviate image for predictor/triton

### ISSUE THREAD

**Issue by charlieye-dev** [kserve/kserve#2971]
1. How can i specify custom triton image and update the commands? dose it support?
> https://github.com/kserve/kserve/blob/release-0.6/docs/samples/v1beta1/triton/bert/bert_v1beta1.yaml#L19

2. How can i use the storage local, for example /home/test/models

**Comment by lizzzcai** [comment]
Hi @charlieye-dev 
1. you should be able to edit the image of the triton in the [clusterServingRuntime](https://github.com/kserve/kserve/blob/master/config/runtimes/kserve-tritonserver.yaml#L2-L4), try `kubectl get ClusterServingRuntime`
2. you should be able to enable [PVC](https://knative.dev/docs/serving/configuration/feature-flags/#kubernetes-persistentvolumeclaim-pvc) in KNative and play around the volumes, kind of like [this](https://github.com/kserve/kserve/issues/2975).
