### ISSUE TITLE
How to add custom model in kserve of a different framework and the custom model is stored in GCS?  

### ISSUE THREAD

**Issue by Rstar1998** [kserve/kserve#2987]
So I have a custom model  of a different framework (not supported by kserve) and the custom model is stored in GCS. Now how to deploy such scenarios in kserve ? 
There is no example provided by kserve documentation 
In the examples provided all models are loaded from libraries rather using custom models and custom framework 

Ref : https://github.com/kserve/kserve/tree/master/python/custom_model

**Comment by sivanantha321** [comment]
@Rstar1998 You can load the model from gcs by setting [`STORAGE_URI` env variable for custom model servers](https://kserve.github.io/website/master/modelserving/v1beta1/custom/custom_model/#environment-variables).
