### ISSUE TITLE
Please update ray dependency

### ISSUE THREAD

**Issue by lewj85** [kserve/kserve#2988]
/kind bug

**What steps did you take and what happened:**
Running my code gives me this r-string error:

`/home/vscode/.cache/pypoetry/virtualenvs/change-detection-kserve-caller-Y9bCySsg-py3.9/lib/python3.9/site-packages/ray/dag/class_node.py:3: in <module>  `
`    from ray.dag.input_node import InputNode  `
`E     File "/home/vscode/.cache/pypoetry/virtualenvs/change-detection-kserve-caller-Y9bCySsg-py3.9/lib/python3.9/site-packages/ray/dag/input_node.py", line 13  `
`E       """Ray dag node used in DAG building API to mark entrypoints of a DAG.  `
`E       ^  `
`E   SyntaxError: invalid escape sequence \`  

**Solution:**
kserve (0.11.0rc0) depends on ray (>=2.0.0,<2.1.0)
But ray (2.1.0) fixed several r-string bugs here:
https://github.com/ray-project/ray/commit/d6b6dc560dd2920bf8ee1e4de01c4ec25fdab555

Please allow for later versions of ray, specifically (>=2.10). Thanks!

**Comment by sivanantha321** [comment]
@lewj85 The ray serve is already [updated to version 2.4](https://github.com/kserve/kserve/blob/baf9f191349ffa2432ffb960642ecaefe90f4e7b/python/kserve/pyproject.toml#L45) :)

**Comment by Rstar1998** [comment]
@sivanantha321 strangely I am getting this https://github.com/kserve/kserve/issues/3015
Even after using kserve == 0.11.0rc0 in requirements.txt

**Comment by sivanantha321** [comment]
@Rstar1998 kserve == 0.11.0rc0 still depends on ray serve ~= 2.0.0. The updated ray requirement will be available on 0.11.0 release.

**Comment by sivanantha321** [comment]
As for the issue #3015, please refer the [comment](https://github.com/kserve/kserve/issues/3015#issuecomment-1614041897)
