### ISSUE TITLE
Unable to fetch image "docker.io/kserve/sklearnserver:v0.10.0" in Minikube/Kind version: v1.30.1 on Darwin 13.4 (arm64)

### ISSUE THREAD

**Issue by Manindhar** [kserve/kserve#2989]
/kind bug

**What steps did you take and what happened:**
I am facing issue in running inference service on my minikube for Kserve.

<img width="740" alt="Screenshot 2023-06-13 at 6 06 26 AM" src="https://github.com/kserve/kserve/assets/32701843/9ed9b33a-8fec-4295-a423-324c89f24306">

When trying to create my first inference service - https://kserve.github.io/website/0.10/get_started/first_isvc/#run-your-first-inferenceservice

I am getting below error

docker.io/kserve/sklearnserver:v0.10.0 image is available on my minikube list of images (I have loaded it)
<img width="1012" alt="Screenshot 2023-06-13 at 6 08 11 AM" src="https://github.com/kserve/kserve/assets/32701843/712537fb-05fa-42ae-a260-3eaae0860b92">

Please find the describe logs:
kubectl describe inferenceservices sklearn-iris -n kserve
Name: sklearn-iris
Namespace: kserve
Labels:
Annotations:
API Version: serving.kserve.io/v1beta1
Kind: InferenceService
Metadata:
Creation Timestamp: 2023-06-13T00:20:30Z
Finalizers:
inferenceservice.finalizers
Generation: 1
Resource Version: 742007
UID: 14692e0f-cce0-42fa-a743-fab3fc3cb830
Spec:
Predictor:
Model:
Model Format:
Name: sklearn
Name:
Resources:
Storage Uri: gs://kfserving-examples/models/sklearn/1.0/model
Status:
Components:
Predictor:
Latest Created Revision: sklearn-iris-predictor-default-00001
Conditions:
Last Transition Time: 2023-06-13T00:20:40Z
Message: Revision "sklearn-iris-predictor-default-00001" failed with message: Unable to fetch image "docker.io/kserve/sklearnserver:v0.10.0": failed to resolve image to digest: Get "https://index.docker.io/v2/": context deadline exceeded.
Reason: RevisionFailed
Severity: Info
Status: False
Type: PredictorConfigurationReady
Last Transition Time: 2023-06-13T00:20:40Z
Message: Configuration "sklearn-iris-predictor-default" does not have any ready Revision.
Reason: RevisionMissing
Status: False
Type: PredictorReady
Last Transition Time: 2023-06-13T00:20:40Z
Message: Configuration "sklearn-iris-predictor-default" does not have any ready Revision.
Reason: RevisionMissing
Severity: Info
Status: False
Type: PredictorRouteReady
Last Transition Time: 2023-06-13T00:20:40Z
Message: Configuration "sklearn-iris-predictor-default" does not have any ready Revision.
Reason: RevisionMissing
Status: False
Type: Ready
Model Status:
States:
Active Model State:
Target Model State: Pending
Transition Status: InProgress
Observed Generation: 1
Events:
Type Reason Age From Message

Warning InternalError 4m18s v1beta1Controllers fails to reconcile predictor: fails to update knative service: Operation cannot be fulfilled on services.serving.knative.dev "sklearn-iris-predictor-default": the object has been modified; please apply your changes to the latest version and try again

Any help would be appreciated.

**What did you expect to happen:** The inference service takes the pre loaded image from minikube and starts the serving

**What's the InferenceService yaml:**
[To help us debug please run `kubectl get isvc $name -n $namespace -oyaml` and paste the output]

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

**Environment:**

- Istio Version: 1.17.2
- Knative Version: 
- KServe Version: 1.10.0
- Kubeflow version: 
- Cloud Environment: local
- Minikube/Kind version: v1.30.1 on Darwin 13.4 (arm64)
- Kubernetes version: (use `kubectl version`): v1.27.2
- OS (e.g. from `/etc/os-release`): Darwin 13.4 (arm64)

**Comment by ghost** [comment]
> Message: Revision "sklearn-iris-predictor-default-00001" failed with message: Unable to fetch image "docker.io/kserve/sklearnserver:v0.10.0": failed to resolve image to digest: Get "https://index.docker.io/v2/": context deadline exceeded.

the container image cannot be downloaded.

**Comment by Manindhar** [comment]
Once all the above pods are running, we tried to create an InferenceService for IRIS model and loaded image docker.io/kserve/sklearnserver:v0.10.0 into the minikube cluster.

still getting the error image cannot be downloaded

kubectl describe ClusterServingRuntime kserve-sklearnserver
 
<img width="1012" alt="Screenshot 2023-06-13 at 6 08 11 AM" src="https://github.com/kserve/kserve/assets/32701843/3194dca2-7bb7-4975-9859-d0be81679602">

<img width="611" alt="image004" src="https://github.com/kserve/kserve/assets/32701843/b7fe7fbb-1fd5-4aa7-b06f-08f3f674fbfc">

Expected the inference service to run. Please help

**Comment by Rstar1998** [comment]
@Manindhar does that image exists ? 
<img width="1054" alt="image" src="https://github.com/kserve/kserve/assets/42741300/74225d48-da80-46d2-9df2-62d73b890e86">

**Comment by Manindhar** [comment]
https://hub.docker.com/layers/kserve/sklearnserver/v0.10.0/images/sha256-b4408da5783b7cc35afb60fd159fe794bcbf01ea3533323bbfda4f83daf0829e?context=explore

**Comment by D3f0** [comment]
Found the same bug with kind 0.19.0 creating the cluster like this:
```
kind create cluster  --image kindest/node:v1.25.11
```

**Comment by D3f0** [comment]
It works with k3d, not sure what the issue is with kind.

**Comment by Manindhar** [comment]
I am using minikube

docker.io/kserve/sklearnserver:v0.10.0 image is available on my minikube list of images (I have loaded it)

**Comment by Rstar1998** [comment]
@Manindhar Can you send the output of `kubectl describe pod <podname>` ?

**Comment by Manindhar** [comment]
I have issue with creating inference service only. All other pods are running screenshot above

**kubectl describe inferenceservices sklearn-iris -n kserve**


Name: sklearn-iris
Namespace: kserve
Labels:
Annotations:
API Version: serving.kserve.io/v1beta1
Kind: InferenceService
Metadata:
Creation Timestamp: 2023-06-13T00:20:30Z
Finalizers:
inferenceservice.finalizers
Generation: 1
Resource Version: 742007
UID: 14692e0f-cce0-42fa-a743-fab3fc3cb830
Spec:
Predictor:
Model:
Model Format:
Name: sklearn
Name:
Resources:
Storage Uri: gs://kfserving-examples/models/sklearn/1.0/model
Status:
Components:
Predictor:
Latest Created Revision: sklearn-iris-predictor-default-00001
Conditions:
Last Transition Time: 2023-06-13T00:20:40Z
Message: Revision "sklearn-iris-predictor-default-00001" failed with message: Unable to fetch image "docker.io/kserve/sklearnserver:v0.10.0": failed to resolve image to digest: Get "https://index.docker.io/v2/": context deadline exceeded.
Reason: RevisionFailed
Severity: Info
Status: False
Type: PredictorConfigurationReady
Last Transition Time: 2023-06-13T00:20:40Z
Message: Configuration "sklearn-iris-predictor-default" does not have any ready Revision.
Reason: RevisionMissing
Status: False
Type: PredictorReady
Last Transition Time: 2023-06-13T00:20:40Z
Message: Configuration "sklearn-iris-predictor-default" does not have any ready Revision.
Reason: RevisionMissing
Severity: Info
Status: False
Type: PredictorRouteReady
Last Transition Time: 2023-06-13T00:20:40Z
Message: Configuration "sklearn-iris-predictor-default" does not have any ready Revision.
Reason: RevisionMissing
Status: False
Type: Ready
Model Status:
States:
Active Model State:
Target Model State: Pending
Transition Status: InProgress
Observed Generation: 1
Events:
Type Reason Age From Message

Warning InternalError 4m18s v1beta1Controllers fails to reconcile predictor: fails to update knative service: Operation cannot be fulfilled on services.serving.knative.dev "sklearn-iris-predictor-default": the object has been modified; please apply your changes to the latest version and try again

**Comment by ckadner** [comment]
Could this be an issue with a missing **ARM64** architecture build? You are running on a new Mac with **Apple Silicon** chip (M1, M2)?

<img width="985" alt="image" src="https://github.com/kserve/kserve/assets/12246093/74a0fc81-ba88-4461-83d3-769678e37855">

Versus `docker.io/kserve/kserve-controller` image builds:
<img width="985" alt="image" src="https://github.com/kserve/kserve/assets/12246093/3c5bc15c-9a8a-4325-b2b6-c96b99a47a19">

**Comment by Manindhar** [comment]
Yes, its a new Mac M1 chip.
What you pointed out could be the issue.  Sorry how do I resolve it from my end in that case.

**Comment by ckadner** [comment]
Well, we (the kserve team) should update our Github Action workflows to build and push this (and other) images for `arm64` and other platforms. 

In the meantime, you could try to build the image yourself locally and push it to your Minikube/Kind image registry, see the Github action for reference here: [`.github/workflows/sklearnserver-docker-publish.yml`](https://github.com/kserve/kserve/blob/1314130e93375bbda6ba46703af07a52262d1399/.github/workflows/sklearnserver-docker-publish.yml#L53)

**Comment by Manindhar** [comment]
Ah got it, let me try this. Thanks @ckadner for your suggestion. I was blocked by this for a long time
