### ISSUE TITLE
Broken v0.10.1.1 Python SDK

### ISSUE THREAD

**Issue by ghost** [kserve/kserve#2995]
/kind bug

**What steps did you take and what happened:**
[A clear and concise description of what the bug is.]

1. Install `pip install kserve==0.10.1.1`
2. In the code `models.py`:

<img width="602" alt="image" src="https://github.com/kserve/kserve/assets/91221920/f8e3ad34-9b33-4036-b395-b337c6da9e6f">

<img width="1022" alt="image" src="https://github.com/kserve/kserve/assets/91221920/0dbe3137-027d-4cec-9054-f56c341c6098">

`_http_predict` call will fail because `PREDICTOR_URL_FORMAT` requires 3 positional args, but only 2 are provided.

And the custom model would return the following

```json
{
    "error": "IndexError : Replacement index 2 out of range for positional args tuple"
}
```

Something's off when cherry-pick/publish this release version:

https://github.com/kserve/kserve/blob/release-0.10/python/kserve/kserve/model.py#L37
https://github.com/kserve/kserve/blob/release-0.10/python/kserve/kserve/model.py#L256

**What did you expect to happen:**

**What's the InferenceService yaml:**
[To help us debug please run `kubectl get isvc $name -n $namespace -oyaml` and paste the output]

N/A

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

Suggest re-release a new patch version with correct patch based on v0.10.1

**Environment:**

- Istio Version:
- Knative Version:
- KServe Version: 0.10.1.1
- Kubeflow version:
- Cloud Environment:[k8s_istio/istio_dex/gcp_basic_auth/gcp_iap/aws/aws_cognito/ibm]
- Minikube/Kind version:
- Kubernetes version: (use `kubectl version`):
- OS (e.g. from `/etc/os-release`):

**Comment by ghost** [comment]
@yuzisun shall we cut a patch release on 0.10.1 and mark 0.10.1.1 a pre-release?

**Comment by yuzisun** [comment]
> @yuzisun shall we cut a patch release on 0.10.1 and mark 0.10.1.1 a pre-release?

We will do 0.10.2 and I think we need to yank the 0.10.1.1 release https://snarky.ca/what-to-do-when-you-botch-a-release-on-pypi/amp/
