### ISSUE TITLE
Support InferenceGraph on RawDeployment mode

### ISSUE THREAD

**Issue by zzr93** [kserve/kserve#3011]
/kind question

**Describe the solution you'd like**
[A clear and concise description of what you want to happen.]

InferenceGraph is a key feature of kserve, however users who prefer RawDeployment mode cannot benefit from it.
Controller would raise error "RawDeployment mode is not supported for InferenceGraph".

Is there any chance we can support InferenceGraph on RawDeployment mode?
If the answer is no, I think some illustration can be added to the [document](https://kserve.github.io/website/0.10/admin/kubernetes_deployment/), to specify the restriction on RawDeployment mode.

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

**Comment by rachitchauhan43** [comment]
Duplicate of https://github.com/kserve/kserve/issues/2454
