### ISSUE TITLE
Run custom serving image prompts "python -m model: command not found"

### ISSUE THREAD

**Issue by YishuiLi** [kserve/kserve#3053]
Create Custom Serving Image with BuildPacks. Then launch the docker image. 
```
docker run -ePORT=8080 -p8080:8080 ${DOCKER_USER}/custom-model:v1
```
It prompts "python -m model: command not found". 
![image](https://github.com/kserve/kserve/assets/16732930/956d597a-d9d9-44ed-828b-b49ac47f150c)

When I create images without Procfile, launch the docker image and run python -m model is normal.
Procfile:
```
web: python -m model
```
runtime.txt
```
python-3.8.17
```
project.toml
```
[[build.env]]
name = "BP_CPYTHON_VERSION"
value = "3.8.17"
```

**Environment:**

- Istio Version: 1.13.0
- KServe Version: 0.10.1
- Kubernetes version: (use `kubectl version`): 1.23.10
- OS (e.g. from `/etc/os-release`): CentOS7

**Comment by RohanGlitched** [comment]
Hey If no-one Is assigned to this issue i would like to get assigned thanks.

**Comment by Future-Outlier** [comment]
#take

**Comment by Future-Outlier** [comment]
# take

**Comment by Future-Outlier** [comment]
#self-assign
