### ISSUE TITLE
Paddle does not support for arm64/aarch64

### ISSUE THREAD

**Issue by ckadner** [kserve/kserve#3055]
Paddle does not have [support for ARM64](https://github.com/deepjavalibrary/djl/issues/2083#issuecomment-1309157578).

There are a few arm64/aarch64 related issues on the Paddle issue queue, i.e. https://github.com/PaddlePaddle/Paddle/issues/44712

_Originally posted by @sivanantha321 in https://github.com/kserve/kserve/issues/3038#issuecomment-1653410150_

**Comment by ckadner** [comment]
https://github.com/kserve/kserve/blob/32be7464b1a23a59c7980f91175c6c1ff35f4b0a/.github/workflows/paddle-docker-publish.yml#L83

**Comment by sivanantha321** [comment]
paddle runtime supports arm64 arch from 0.13.0.
https://github.com/kserve/kserve/blame/de96bd3f516597a2e07b9c92936f06357f94efd2/.github/workflows/paddle-docker-publish.yml#L96
