### ISSUE TITLE
Pandas 2 support

### ISSUE THREAD

**Issue by yk4r2** [kserve/kserve#3068]
/kind feature

**When will pandas 2 be supported?**
Current pandas version is 1.5.3 for the last dev version with no possibility of version upgrade / downgrade. When will [pandas 2](https://pandas.pydata.org/docs/dev/whatsnew/v2.0.3.html) or at least a wider range of versions be supported?

**Comment by sivanantha321** [comment]
@yk4r2 The latest kserve 0.11.0 [supports pandas 2](https://github.com/kserve/kserve/blob/f2f0717a9d6341b6ec9b939bdd324b2c8c507551/python/kserve/pyproject.toml#L54).

**Comment by yk4r2** [comment]
Sorry, my bad. Another lib forces me to use pandas@1.5.3 :(
