### ISSUE TITLE
Documentation update - kubernetes 1.27

### ISSUE THREAD

**Issue by luntropy** [kserve/kserve#3076]
/kind feature

**Describe the solution you'd like**
The [Kserve Quickstart guide](https://kserve.github.io/website/0.10/get_started/) is outdated for Kubernetes 1.27. It is not working by directly using the provided command: 
`curl -s "https://raw.githubusercontent.com/kserve/kserve/release-0.10/hack/quick_install.sh" | bash`

Also maybe the table in the [serverless installation guide](https://kserve.github.io/website/0.10/admin/serverless/serverless/) can be updated as well.

**Anything else you would like to add:**
Worked by changing the versions inside the script to: 
istio: 1.18.0
knative: knative-v1.9.0
kserve: v0.10.1
cert manager: v1.12.0

So instead of this: 
export ISTIO_VERSION=1.15.0
export KNATIVE_VERSION=knative-v1.7.0
export KSERVE_VERSION=v0.10.2
export CERT_MANAGER_VERSION=v1.3.0
export SCRIPT_DIR="$( dirname -- "${BASH_SOURCE[0]}" )"

in the script we use this: 
export ISTIO_VERSION=1.18.0
export KNATIVE_VERSION=knative-v1.9.0
export KSERVE_VERSION=v0.10.1
export CERT_MANAGER_VERSION=v1.12.0
export SCRIPT_DIR="$( dirname -- "${BASH_SOURCE[0]}" )"

**Comment by sivanantha321** [comment]
@luntropy Kserve 0.10 does not support k8s 1.27 officially. Please Use Kserve 0.11 which is tested on k8s 1.27. The latest [quick_install script](https://github.com/kserve/kserve/blob/master/hack/quick_install.sh) is already updated. You can use that to install it on k8s 1.27. The [support matrix](https://kserve.github.io/website/master/admin/serverless/serverless/#recommended-version-matrix) is already updated in the master version. Soon the documentation for kserve 0.11 will be released :) .

**Comment by luntropy** [comment]
@sivanantha321 Great, thank you very much!
