### ISSUE TITLE
Thoughts on adding some LLM specific runtime?

### ISSUE THREAD

**Issue by yuzisun** [kserve/kserve#3109]
### Discussed in https://github.com/kserve/kserve/discussions/3097

<div type='discussions-op-text'>

<sup>Originally posted by **Peilun-Li** August 25, 2023</sup>
There are some emerging serving runtimes dedicated to LLM hosting, e.g., vllm https://vllm.readthedocs.io/en/latest/index.html which requires a fully controlled web server to achieve the best performance. This seems to be suited well as a new serving runtime (along with torchserve, etc.) we could potentially introduce so that we can host LLMs easily. Curious any thoughts on that?</div>

**Comment by yuzisun** [comment]
We are looking into vllm which can be a good option for KServe LLM runtime, we originally looked into Huggingface Text generation inference but they changed the license.

**Comment by ishaan-jaff** [comment]
Hi @yuzisun I believe we can help with this issue. I’m the maintainer of LiteLLM https://github.com/BerriAI/litellm

**TLDR:**
**We allow you to use any LLM as a drop in replacement for `gpt-3.5-turbo`. 
You can use our proxy server or spin up your own proxy server using LiteLLM**

## Usage
This calls the provider API directly

```python
from litellm import completion
import os
## set ENV variables 
os.environ["OPENAI_API_KEY"] = "your-key" # 
messages = [{ "content": "Hello, how are you?","role": "user"}]

# openai call
response = completion(model="gpt-3.5-turbo", messages=messages)

# falcon call
response = completion(model="falcon-40b", messages=messages)
```

**Comment by sivanantha321** [comment]
KServe already supports vLLM from 0.13
