### ISSUE TITLE
Ability to add custom storage initializer prefixes 

### ISSUE THREAD

**Issue by thomas-vanderwal** [kserve/kserve#3121]
/kind feature

**Describe the solution you'd like**
Right now I have a custom storage initializer logic that will look for a prefix that indicates it should use our internal model registry and client logic to download. That all seems to be working fine but then for the validating webhook it fails because the list is hardcoded to specific prefixes. Would it be possible to have additional ones via config and have the default storage initializer pod injection logic? 

**Anything else you would like to add:**
https://github.com/kserve/kserve/blob/47442aeeac438c5697c8e6f4494bfbc6b31e7fd8/pkg/apis/serving/v1beta1/component.go#L49
This is the section that hardcodes the prefixes

**Comment by yuzisun** [comment]
Cc @greenmoon55

**Comment by thomas-vanderwal** [comment]
FWIW I did mirror your repo and tested a custom version with our Prefix and it worked great.

**Comment by greenmoon55** [comment]
Hi @thomas-vanderwal , thanks for reporting it! I didn't realize that we have this check. Could you share your inference service spec? I'm wondering why I didn't run into this when I tested #3060 a while ago.

**Comment by greenmoon55** [comment]
> Hi @thomas-vanderwal , thanks for reporting it! I didn't realize that we have this check. Could you share your inference service spec? I'm wondering why I didn't run into this when I tested #3060 a while ago.

nvm, I was able to reproduce it.

**Comment by rhuss** [comment]
FWIW, I had the same issue that I had to extend while experimenting with an `oci` prefix for using modelcars in #3110 . I think one solution could also be to just ignore URLs with an unknown schema, potentially writing out a warning.

@greenmoon55, just out of curiosity, how have you implemented your storage logic itself? By replacing the initializer mutating webhook with your own?

**Comment by yuzisun** [comment]
> FWIW, I had the same issue that I had to extend while experimenting with an `oci` prefix for using modelcars in #3110 . I think one solution could also be to just ignore URLs with an unknown schema, potentially writing out a warning.
> 
> @greenmoon55, just out of curiosity, how have you implemented your storage logic itself? By replacing the initializer mutating webhook with your own?

kserve has now introduced the storage initializer CR for customized storage initializer https://github.com/kserve/kserve/pull/3060
