### ISSUE TITLE
Quick install script should install storageContainer CRD and the default CR

### ISSUE THREAD

**Issue by greenmoon55** [kserve/kserve#3132]
/kind feature

**Describe the solution you'd like**
[A clear and concise description of what you want to happen.]
Quick install script should install storageContainer CRD and the default CR

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

**Comment by RohanGlitched** [comment]
If No-one is working on this would love to work on this.

**Comment by homily707** [comment]
now our install file contains 3 file `kserve.yaml`, `kserve-runtimes.yaml`, `kserve_kubeflow.yaml`
there are 3 ways to add default cr
1. append to `kserve.yaml`, but what if there are more storagecontainers in the future
2. make a new file for it. But now ther will be only one resource in this file
3. append to `kserve-runtimes.yaml` and rename it to `cluster-resources.yaml`

I'm not sure which one is better, or is theree any other solution.

**Comment by greenmoon55** [comment]
Sorry for the late reply! #3219 Looks good to me.
