### ISSUE TITLE
Update Makefile to apply default storage container CR

### ISSUE THREAD

**Issue by greenmoon55** [kserve/kserve#3133]
/kind feature

**Describe the solution you'd like**
[A clear and concise description of what you want to happen.]
Similar to the serving runtimes https://github.com/kserve/kserve/blob/4142342940465b54172d363dba1a44fe69c32b18/Makefile#L83 
We should call `k apply` on the default storage container CR in `make deploy` and `make deploy-dev`

Default CR https://github.com/kserve/kserve/blob/823107299b8d93481c8d179ce2bbc726d0414448/charts/kserve-resources/templates/clusterstoragecontainer.yaml

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

**Comment by Cretus-iosDev** [comment]
hi @greenmoon55  
I've generated the PR  please let me know if need any changes
please take a look to it
if needed I'll make that too

**Comment by greenmoon55** [comment]
@Cretus-iosDev Thanks for working on it. I think this should be fixed by #3219.

**Comment by sivanantha321** [comment]
fixed by #3219
