### ISSUE TITLE
Configurable timeouts for InferenceGraph

### ISSUE THREAD

**Issue by ianonavy** [kserve/kserve#3149]
/kind feature

**Describe the solution you'd like**

InferenceServices in a Serverless deployment of KServe allow you to configure the Knative `timeoutSeconds` field by way of the `timeout` field in ComponentExtensionSpec. We'd like the same feature for an InferenceGraph.

**Anything else you would like to add:**

If we cannot update the InfereceGraph spec at this time, I would request the InferenceGraph controller at the very least be able to check the existing InferenceServices for Knative-backed components and match the highest `timeoutSeconds`.

Thanks for your consideration!

**Comment by rachitchauhan43** [comment]
@ianonavy :  If it's urgent to you, let's do it in 2 phases:
1. Phase-1 Allow setting timeout in IG spec without any logic in IG controller to check for timeout of individual ISVCs
2. Phase-2 Do add check in IG controller that you can't set timeout in IG controller less than highest timeoutSecs or sum of all ISVCs timeouts.

WDYT ?

**Comment by ianonavy** [comment]
> @ianonavy : If it's urgent to you, let's do it in 2 phases:
> 
> 1. Phase-1 Allow setting timeout in IG spec without any logic in IG controller to check for timeout of individual ISVCs
> 2. Phase-2 Do add check in IG controller that you can't set timeout in IG controller less than highest timeoutSecs or sum of all ISVCs timeouts.
> 
> WDYT ?

Thanks for the reply! That sounds like an excellent plan.
