### ISSUE TITLE
Extend ClusterStorageContainer to support Modelcars

### ISSUE THREAD

**Issue by rhuss** [kserve/kserve#3192]
/kind feature

**Describe the solution you'd like**

In order to support Modelcars as described in this [design document](https://docs.google.com/document/d/1Bs4fnP8rhPMaoPoLSYVvuRq-z9vkGPQ0rKbmfH4I7js/edit#bookmark=id.qb0sqvo6n1bq), in the PR #3110 and the initial issue #3043 
some additional feature are required from the `ClusterStorageContainer` support.

As described in the design doc:

ClusterStorageContainer as introduced in #3060 allows to flexibly delegate the initialization process to an instance of a custom image that is specified in a custom resource `ClusterStorageContainer`. This feature maps one or more specific URL schemas to a single initialization image that is then used as an init container for a runtime deployment to initialize the model data. This mapping and the image are fixed and provided as part of the KServe installation by the operator persona. A user deploying an `InferenceService` can give the URL prefix but cannot change the image used for it.

The modelcar approach can not directly use the current implementation of the `ClusterStorageContainer` for two reasons:

* A modelcar must be configured as a sidecar, not as an init-container. 
* The user specifies the container image used for a model car as part of the storage URL and cannot be fixed within a `ClusterStorageContainer` upfront.

To integrate modelcars with the ClusterStorageContainer indirection, the following changes might be needed:

* An indication in the `ClusterStorageContainer` CRD that a sidecar container (in `.spec.containers`) should be created instead of an init-container (in `.spec.initContainers`). An enumeration-type field is recommended, something like "setupMode" with values "init-container" (default) and "sidecar" (or "app-container")
* The field `.spec.container.image` would need to be extended to allow a more flexible format to extract the image name from the storage URL provided. A simple way to enable this would be to regexp grouping: The `.spec.supportedUriFormats.regex` could allow capturing groups that could be referred to in the `.spec.container.image` like in this example:

```yaml
apiVersion: "serving.kserve.io/v1alpha1"
kind: ClusterStorageContainer
….
spec:
  container:
    # First capturing group from regex matching. Error if no such group exists
    image: "$1"
    …
  supportedUriFormats:
    # Regex with capturing groups
    - regex: "oci://(.+)"
```

* A way for setting the Pod's `.spec.shareProcessNamespace` would be needed. It can't be part of the CSC' `.spec.container` section as this is pod-wide specification (for all containers of the inference service, including the serving runtime specified via the `InferenceService`). Also, being able to set the containers' UID (the one of the sidecar and the one of the main-container with the serving runtime) might be needed in certain circumstances.
   
**Anything else you would like to add:**

Setting up the modelcar container is a bit more involved than setting up init-containers, as it also touches other parts of the overall Pod. The question that we should decide is, whether it makes sense to make the modelcar approach part of the ClusterStorageContainer approach or should stay as an internal handler as implemented in #3110 . The current implementation within the storage initializer is more straightforward, but if the final goal is to move all initialization predefined ClusterStorageContainer, we would need the changes described here.

**Links to the design documents:**

https://docs.google.com/document/d/1Bs4fnP8rhPMaoPoLSYVvuRq-z9vkGPQ0rKbmfH4I7js/edit#bookmark=id.qb0sqvo6n1bq

**Comment by rhuss** [comment]
If we agree on the proposed extension, I could work on it.

**Comment by yuzisun** [comment]
@rhuss Thanks for bringing this up! The original design was aimed to provide a way to integrate private model registry which could be layered on top of S3 or other cloud storage, so we need a way to customize the storage initializer with custom images or container environment variables. 

Currently for storage initializer there are still pod level fields like model volume mounts which are coded in KServe but not defined on the `ClusterStorageContainer`.  If there are no benefits making model sidecar as part of customized storage container approach and no future customization we can foresee with model sidecar, we can stay with your current implementation. But I am not sure if things like `SharedNamespace` can work across platforms and the container limits might also need to be tuned or customized.

@greenmoon55 @rachitchauhan43 @ckadner Any thoughts on this?

**Comment by greenmoon55** [comment]
Sorry for the late reply. I think modelcar is more of an independent feature. I might be wrong but I can't think of any customization based on the storageUri for oci images. It would be useful to extend `ClusterStorageContainer` if the administrator or users needed custom configs for different oci images.

**Comment by rhuss** [comment]
I agree, so let's keep the injection code in the original storage initializer, so let's close that issue for now.
