### ISSUE TITLE
Sklearn wrapped keras/tensorflow models can't be used with sklearn server

### ISSUE THREAD

**Issue by ukclivecox** [kserve/kserve#321]
/kind bug

Should we allow an option for the model load to be done per Tornado worker? At present it's done once:

https://github.com/kubeflow/kfserving/blob/34809b91c57a9f7dfb27592f1f4ad895bc074eb7/python/sklearnserver/sklearnserver/__main__.py#L33

A sklearn keras wrapped model fails due to underlying Tensorflow session needing to be loaded in each worker. 

Or we say you have to use the Tensorflow Server for these models.

**Comment by sivanantha321** [comment]
Closing this issue as it is no longer valid
