### ISSUE TITLE
Could I run Inference Service without model ?

### ISSUE THREAD

**Issue by ChaejinE** [kserve/kserve#3212]
/kind bug

**What steps did you take and what happened:**
- Could I run Inference Service without model ? like a API function

**What did you expect to happen:**
```python
import argparse
from typing import Dict
from kserve import Model, ModelServer


class Comp1(Model):
    def __init__(self, name: str):
        super().__init__(name)
        self.name = name
        self.model = None
        self.ready = True

    def predict(self, payload: Dict, headers: Dict[str, str] = None) -> Dict:
        data = payload["query"]["a"]
        return {"a": data}


if __name__ == "__main__":
    comp = Comp1("comp1")
    ModelServer().start([comp])
```

```
ERROR: failed to launch: determine start command: when there is no default process a command is required
```
- After packaging, i did test app using docker. But it wasn't operate well. 
- It is not bug. but i wanna use sequence process without model. my project is not required 3 of 4 stages
   - For Example, Inference stage1 (X) - stage2 (X) - stage3 (O, required model) - stage4
   - I just wanna use like multiple transformer !

i'll wait answer or solution. Thank you

**Comment by sivanantha321** [comment]
@ChaejinE Yes, You can run the model server without a model https://github.com/kserve/kserve/blob/215e58378849d153a034b083701435a725a87675/python/sklearnserver/sklearnserver/__main__.py#L42C4-L43C40. 
Have you specified entrypoint / cmd in your dockerfile ?

**Comment by ChaejinE** [comment]
@sivanantha321 No, But i wanna know that (use CMD ENTRYPOINT)

I just read only [custom predict docs](https://kserve.io/website/0.11/modelserving/v1beta1/custom/custom_model/#build-custom-serving-image-with-buildpacks) before

Well, Running without a model is to transfer empty list to kserve server ?
It might be not operated my predict logic..

I just wanna operate predict logic like a transformer's preprocess, postprocess

**Comment by sivanantha321** [comment]
> @sivanantha321 No, But i wanna know that (use CMD ENTRYPOINT).
> 
> Well, Running without a model is to transfer empty list to kserve server ?

Yes, by providing an empty list, you can run the server without the model. However, some endpoints may not work (e.g) /predict. The error you are getting is because of not specifying CMD or ENTRYPOINT

**Comment by sivanantha321** [comment]
@ChaejinE I am not sure. What is the use case of hitting predict endpoint without a model ?

**Comment by ChaejinE** [comment]
> @ChaejinE I am not sure. What is the use case of hitting predict endpoint without a model ?

@sivanantha321 
Yeah, My use case is NeRF model..
It is different from other models
Its inference processes are independent each other

Stages consist of video download - model train/inference - 3d mesh postprocess etc...

So i wanna make inference service and use inference graph included not required model stage

Is there any solution else?

**Comment by ChaejinE** [comment]
i choose inference graph
