### ISSUE TITLE
Switch the KFServing build to Kubeflow build being based on Tekton+Kaniko

### ISSUE THREAD

**Issue by animeshsingh** [kserve/kserve#322]
Follow the conversation here
https://github.com/kubeflow/kfserving/pull/319

/assign @jinchihe 

cc @ellis-bigelow @kkasravi

**Comment by kkasravi** [comment]
thanks @animeshsingh 

does kfserving do something similar as some of the other kubeflow repos (kubeflow, kfctl, manifests) which involves prow, presubmit, postsubmit, periodic?

**Comment by yuzisun** [comment]
@kkasravi ye it's prow with presubmit, there is no postsubmit and periodic setup.

**Comment by kkasravi** [comment]
@yuzisun thanks

the current kfctl Pipeline isn't parameterized under kustomize to the extent that any Github source and Image can be plugged in, but i'll take a look at kfserving's prow presubmit to see if it would be possible

**Comment by jinchihe** [comment]
@animeshsingh @kkasravi I'm glad to do that, thanks!

**Comment by animeshsingh** [comment]
@jinchihe any movement along these lines?

**Comment by jinchihe** [comment]
@animeshsingh not yet due to higher priority things, but will start very soon.
