### ISSUE TITLE
Need Interface Spec for the Custom Container

### ISSUE THREAD

**Issue by ultrons** [kserve/kserve#323]
Hi , I am looking for some pointers on using custom container for inference using kf_serving.
While the samples provide in this repo has an example of yaml file with custom container, but We are missing an interface/protocol specification that this custom container is to abide by.

Looked through kubeflow official website.

**Comment by rakelkar** [comment]
The data plane is being discussed here #273 and here: https://docs.google.com/document/d/1scfWSB4d8GeC03riu4AVhdG5sD1I0ZRO4mUhfN6aXAg/edit?ts=5d6954d2

I would suggest looking at the KFServer implementation and follow that for now: https://github.com/kubeflow/kfserving/tree/master/python/kfserving/kfserving

**Comment by andyi2it** [comment]
/close
This issue is stale and with dataplane implementation in KServe, this should be possible now.
