### ISSUE TITLE
Explainer is not working with path based routing

### ISSUE THREAD

**Issue by sivanantha321** [kserve/kserve#3231]
/kind bug

**What steps did you take and what happened:**
[A clear and concise description of what the bug is.]
Followed the [Alibi explainer example in the website](https://kserve.github.io/website/0.11/modelserving/explainer/alibi/income/) with path based routing enabled.

Getting following error
```bash
 curl -v -H "Host: example.com" -H "Content-Type: application/json" -H "Knative-Serving-Tag: latest" http://localhost:8080/serving/default/income/v1/models/income:explain -d '{"instances":[[39, 7, 1, 1, 1, 1, 4, 1, 2174, 0, 40, 9]]}'
* Uses proxy env variable NO_PROXY == 'localhost,127.0.0.1'
*   Trying 127.0.0.1:8080...
* Connected to localhost (127.0.0.1) port 8080 (#0)
> POST /serving/default/income/v1/models/income:explain HTTP/1.1
> Host: example.com
> User-Agent: curl/7.85.0
> Accept: */*
> Content-Type: application/json
> Knative-Serving-Tag: latest
> Content-Length: 57
> 
* Mark bundle as not supporting multiuse
< HTTP/1.1 501 Not Implemented
< content-length: 42
< content-type: application/json
< date: Wed, 08 Nov 2023 09:31:59 GMT
< server: istio-envoy
< x-envoy-upstream-service-time: 12
< 
* Connection #0 to host localhost left intact
{"error":"Could not find explainer_host."}
```
Ingress config
```json
{
    "ingressGateway" : "knative-serving/knative-ingress-gateway",
    "ingressService" : "istio-ingressgateway.istio-system.svc.cluster.local",
    "localGateway" : "knative-serving/knative-local-gateway",
    "localGatewayService" : "knative-local-gateway.istio-system.svc.cluster.local",
    "ingressDomain"  : "example.com",
    "ingressClassName" : "istio",
    "domainTemplate": "{{ .Name }}-{{ .Namespace }}.{{ .IngressDomain }}",
    "urlScheme": "http",
    "disableIstioVirtualHost": false,
    "pathTemplate": "/serving/{{ .Namespace }}/{{ .Name }}"
}
```
**What did you expect to happen:**
Explainer should work with path based routing enabled

**What's the InferenceService yaml:**
[To help us debug please run `kubectl get isvc $name -n $namespace -oyaml` and paste the output]

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

**Environment:**

- Istio Version:
- Knative Version:
- KServe Version: 0.11.1
- Kubeflow version:
- Cloud Environment:[k8s_istio/istio_dex/gcp_basic_auth/gcp_iap/aws/aws_cognito/ibm]
- Minikube/Kind version:
- Kubernetes version: (use `kubectl version`):
- OS (e.g. from `/etc/os-release`):

**Comment by skuchipu** [comment]
@sivanantha321  , can you let me know where you add ingress config ?

**Comment by sivanantha321** [comment]
> @sivanantha321  , can you let me know where you add ingress config ?

In the `inferenceservice-config` configmap.

**Comment by skuchipu** [comment]
@sivanantha321  Thank you for quick response , I've tried adding this to inferenceservice-config and tried for prediction and its failing , is it working for you to predict ?

**Comment by sivanantha321** [comment]
> @sivanantha321  Thank you for quick response , I've tried adding this to inferenceservice-config and tried for prediction and its failing , is it working for you to predict ?

Yes, it is.
