### ISSUE TITLE
expose prometheus metric port in qpext container

### ISSUE THREAD

**Issue by JuHyung-Son** [kserve/kserve#3241]
/kind feature

**Describe the solution you'd like**
[A clear and concise description of what you want to happen.]
on isvc pod, qpext container does not have metric port. i want to scrape kserve container metric using podMonitor.

when I try to scrape isvc metric using podMonitor, prometheus cannot scrape it.
because podMonitor's [PodMetricsEndpoint](https://github.com/prometheus-operator/prometheus-operator/blob/main/Documentation/api.md#monitoring.coreos.com/v1.PodMetricsEndpoint) should be port's name, not port integer. since qpext does not expose port 9088, there is no port name to put in podMonitor

<img width="1054" alt="CleanShot 2023-11-10 at 22 19 34@2x" src="https://github.com/kserve/kserve/assets/20140126/61d6406d-8f37-4cbe-a446-cb235c298555">

**Comment by sivanantha321** [comment]
@JuHyung-Son I believe you can still use the targetPort field to specify the port number.
@yuzisun WDYT ?

**Comment by JuHyung-Son** [comment]
@sivanantha321 
I thought so too because `PodMetricEndpoint` still had the `targetPort`, but when I tried it, it didn't work. it's deprecated
