### ISSUE TITLE
does the latest kserver support the xgboost 2.0 of the vector-leaf tree ? 

### ISSUE THREAD

**Issue by flybywind** [kserve/kserve#3243]
At this Sep Xgoobst announced its [2.0 version](https://github.com/dmlc/xgboost/releases/tag/v2.0.0).
But I find the latest kserver hasn't support it. Am I right ?

**Comment by sivanantha321** [comment]
@flybywind Kserve currently using xgboost 1.7.6.

**Comment by sivanantha321** [comment]
@flybywind xgboost is upgraded to version 2.0.2. View the detalis in the PR  #3309
