### ISSUE TITLE
Python publish to PyPI GH action failure

### ISSUE THREAD

**Issue by isaranto** [kserve/kserve#3252]
/kind bug

**What steps did you take and what happened:**
Latest version of kserve python package is not published in pypi due to the [GH action failure.](https://github.com/kserve/kserve/actions/runs/6878455485/job/18708429594)

**Anything else you would like to add:**
Action fails in Install poetry and version [plugin step](https://github.com/kserve/kserve/blob/master/test/scripts/gh-actions/setup-poetry.sh) and gives the following output:
```

Notice:  A new release of pip is available: 23.2.1 -> 23.3.1
Notice:  To update, run: pip install --upgrade pip

No module named 'distutils'
Error: Process completed with exit code 1
```

**Comment by sivanantha321** [comment]
fixed by #3253
