### ISSUE TITLE
Having trouble creating an inference service

### ISSUE THREAD

**Issue by mary26pz** [kserve/kserve#3254]
https://github.com/kserve/kserve/blame/8d5f574f49f91ae700b282a23716f6445aa44f7a/docs/samples/v1beta1/sklearn/v1/sklearn.yaml#L8

Good afternoon,

I've attempted to run my first inference service following the docs from KServe https://kserve.github.io/website/master/get_started/first_isvc/#2-create-an-inferenceservice. 

```
kubectl apply -n kserve-test -f - <<EOF
apiVersion: "serving.kserve.io/v1beta1"
kind: "InferenceService"
metadata:
  name: "sklearn-iris"
spec:
  predictor:
    model:
      modelFormat:
        name: sklearn
      storageUri: "gs://kfserving-examples/models/sklearn/1.0/model"
EOF
```

However, I keep getting the following error. 

(It occurred to me that I might not have access to the storage uri. But that's just a guess. What can I do different? I am verbatim following the example from the docs. I am trying to learn how to use Kserve to deploy ML models for work.)

```
Error from server (InternalError): error when retrieving current configuration of:
Resource: "serving.kserve.io/v1beta1, Resource=inferenceservices", GroupVersionKind: "serving.kserve.io/v1beta1, Kind=InferenceService"
Name: "sklearn-iris", Namespace: "kserve-test"
from server for: "STDIN": Internal error occurred: error resolving resource
```
---------------------------------------------------------------------------------------------------------------------------
More Info:

 kubectl version 
> Client Version: v1.28.4
> Kustomize Version: v5.0.4-0.20230601165947-6ce0bf390ce3
> Server Version: v1.28.3

 kubectl get namespace
> NAME                   STATUS   AGE
> default                Active   103m
> kserve                 Active   89m
> kserve-test            Active   75m
> kube-node-lease        Active   103m
> kube-public            Active   103m
> kube-system            Active   103m
> kubernetes-dashboard   Active   103m

 kubectl get nodes
> NAME       STATUS   ROLES           AGE    VERSION
> minikube   Ready    control-plane   104m   v1.28.3

kubectl config current-context
> minikube

kubectl get crd      
> NAME                                         CREATED AT
> certificaterequests.cert-manager.io          2023-11-17T18:36:47Z
> certificates.cert-manager.io                 2023-11-17T18:36:47Z
> challenges.acme.cert-manager.io              2023-11-17T18:36:47Z
> clusterissuers.cert-manager.io               2023-11-17T18:36:47Z
> clusterservingruntimes.serving.kserve.io     2023-11-17T18:35:46Z
> clusterstoragecontainers.serving.kserve.io   2023-11-17T18:35:46Z
> inferencegraphs.serving.kserve.io            2023-11-17T18:35:46Z
> inferenceservices.serving.kserve.io          2023-11-17T18:35:46Z
> issuers.cert-manager.io                      2023-11-17T18:36:47Z
> orders.acme.cert-manager.io                  2023-11-17T18:36:47Z
> servingruntimes.serving.kserve.io            2023-11-17T18:35:47Z
> trainedmodels.serving.kserve.io              2023-11-17T18:35:47Z

kubectl get namespace
> NAME                   STATUS   AGE
> default                Active   109m
> kserve                 Active   95m
> kserve-test            Active   81m
> kube-node-lease        Active   109m
> kube-public            Active   109m
> kube-system            Active   109m
> kubernetes-dashboard   Active   108m

kubectl get pods -A
> NAMESPACE              NAME                                         READY   STATUS              RESTARTS      AGE
> kserve                 kserve-controller-manager-5d995bd58-v64fv    0/2     ContainerCreating   0             96m
> kube-system            coredns-5dd5756b68-2cgf8                     1/1     Running             1 (34m ago)   109m
> kube-system            etcd-minikube                                1/1     Running             1 (34m ago)   110m
> kube-system            kube-apiserver-minikube                      1/1     Running             1 (34m ago)   110m
> kube-system            kube-controller-manager-minikube             1/1     Running             1 (34m ago)   110m
> kube-system            kube-proxy-xrv7m                             1/1     Running             1 (34m ago)   109m
> kube-system            kube-scheduler-minikube                      1/1     Running             1 (34m ago)   110m
> kube-system            storage-provisioner                          1/1     Running             1 (34m ago)   110m
> kubernetes-dashboard   dashboard-metrics-scraper-7fd5cb4ddc-c48cx   1/1     Running             1 (34m ago)   109m
> kubernetes-dashboard   kubernetes-dashboard-8694d4445c-c2nk7        1/1     Running             1 (34m ago)   109m

**Comment by ainnedge** [comment]
Hi @mary26pz , I too am facing similar issue. Followed [https://www.kubeflow.org/docs/external-add-ons/kserve/first_isvc_kserve/](url)

After executing , `KServe.get(name, namespace=namespace, watch=True, timeout_seconds=120)`.

Below is the output.

> NAME            READY    PREV    LATEST    URL
> sklearn-iris   Unknown

**Setup** : 
OS: Ubuntu 20.04
RAM : 64GB
CPU CORES: 24
Charmed kubeflow using microk8s. [https://charmed-kubeflow.io/docs/get-started-with-charmed-kubeflow](url)

**Logs**
master@master-mac:~$ juju status
Model     Controller          Cloud/Region        Version  SLA          Timestamp
kubeflow  microk8s-localhost  microk8s/localhost  3.1.6    unsupported  14:02:54+05:30

App                        Version                  Status  Scale  Charm                    Channel         Rev  Address         Exposed  Message
admission-webhook          res:oci-image@2d74d1b    active      1  admission-webhook        1.7/stable      224  10.152.183.119  no       
argo-controller            res:oci-image@3902c16    active      1  argo-controller          3.3/stable      376                  no       
argo-server                res:oci-image@e2292c9    active      1  argo-server              3.3/stable      309                  no       
dex-auth                                            active      1  dex-auth                 2.31/stable     346  10.152.183.56   no       
istio-ingressgateway                                active      1  istio-gateway            1.16/stable     663  10.152.183.116  no       
istio-pilot                                         active      1  istio-pilot              1.16/stable     662  10.152.183.36   no       
jupyter-controller         res:oci-image@1167186    active      1  jupyter-controller       1.7/stable      805                  no       
jupyter-ui                                          active      1  jupyter-ui               1.7/stable      739  10.152.183.151  no       
katib-controller           res:oci-image@111495a    active      1  katib-controller         0.15/stable     282  10.152.183.120  no       
katib-db                   8.0.34-0ubuntu0.22.04.1  active      1  mysql-k8s                8.0/stable       99  10.152.183.152  no       
katib-db-manager                                    active      1  katib-db-manager         0.15/stable     253  10.152.183.69   no       
katib-ui                                            active      1  katib-ui                 0.15/stable     267  10.152.183.153  no       
kfp-api                                             active      1  kfp-api                  2.0/stable      866  10.152.183.186  no       
kfp-db                     8.0.34-0ubuntu0.22.04.1  active      1  mysql-k8s                8.0/stable       99  10.152.183.187  no       
kfp-persistence            res:oci-image@ebed770    active      1  kfp-persistence          2.0/stable      870                  no       
kfp-profile-controller     res:oci-image@aa75b0c    active      1  kfp-profile-controller   2.0/stable      831  10.152.183.229  no       
kfp-schedwf                res:oci-image@2cb9087    active      1  kfp-schedwf              2.0/stable      932                  no       
kfp-ui                     res:oci-image@ae72602    active      1  kfp-ui                   2.0/stable      865  10.152.183.154  no       
kfp-viewer                 res:oci-image@899e25f    active      1  kfp-viewer               2.0/stable      895                  no       
kfp-viz                    res:oci-image@ffaf37e    active      1  kfp-viz                  2.0/stable      822  10.152.183.47   no       
knative-eventing                                    active      1  knative-eventing         1.8/stable      345  10.152.183.103  no       
knative-operator                                    active      1  knative-operator         1.8/stable      320  10.152.183.96   no       
knative-serving                                     active      1  knative-serving          1.8/stable      346  10.152.183.45   no       
kserve-controller                                   active      1  kserve-controller        0.10/stable     394  10.152.183.38   no       
kubeflow-dashboard                                  active      1  kubeflow-dashboard       1.7/stable      439  10.152.183.114  no       
kubeflow-profiles                                   active      1  kubeflow-profiles        1.7/stable      336  10.152.183.113  no       
kubeflow-roles                                      active      1  kubeflow-roles           1.7/stable      148  10.152.183.93   no       
kubeflow-volumes           res:oci-image@d261609    active      1  kubeflow-volumes         1.7/stable      204  10.152.183.117  no       
metacontroller-operator                             active      1  metacontroller-operator  2.0/stable      204  10.152.183.88   no       
minio                      res:oci-image@1755999    active      1  minio                    ckf-1.7/stable  214  10.152.183.79   no       
oidc-gatekeeper            res:oci-image@6b720b8    active      1  oidc-gatekeeper          ckf-1.7/stable  269  10.152.183.57   no       
seldon-controller-manager                           active      1  seldon-core              1.15/stable     548  10.152.183.204  no       
tensorboard-controller     res:oci-image@c52f7c2    active      1  tensorboard-controller   1.7/stable      156  10.152.183.178  no       
tensorboards-web-app       res:oci-image@929f55b    active      1  tensorboards-web-app     1.7/stable      158  10.152.183.44   no       
training-operator                                   active      1  training-operator        1.6/stable      305  10.152.183.194  no       

Unit                          Workload  Agent  Address      Ports          Message
admission-webhook/0*          active    idle   10.1.88.212  4443/TCP       
argo-controller/0*            active    idle   10.1.88.193                 
argo-server/0*                active    idle   10.1.88.215  2746/TCP       
dex-auth/0*                   active    idle   10.1.88.210                 
istio-ingressgateway/0*       active    idle   10.1.88.211                 
istio-pilot/0*                active    idle   10.1.88.213                 
jupyter-controller/0*         active    idle   10.1.88.255                 
jupyter-ui/0*                 active    idle   10.1.88.214                 
katib-controller/0*           active    idle   10.1.88.196  443,8080/TCP   
katib-db-manager/0*           active    idle   10.1.88.218                 
katib-db/0*                   active    idle   10.1.88.219                 Primary
katib-ui/0*                   active    idle   10.1.88.221                 
kfp-api/0*                    active    idle   10.1.88.223                 
kfp-db/0*                     active    idle   10.1.88.222                 Primary
kfp-persistence/0*            active    idle   10.1.88.195                 
kfp-profile-controller/0*     active    idle   10.1.89.10   80/TCP         
kfp-schedwf/0*                active    idle   10.1.88.253                 
kfp-ui/0*                     active    idle   10.1.89.9    3000/TCP       
kfp-viewer/0*                 active    idle   10.1.88.248                 
kfp-viz/0*                    active    idle   10.1.88.249  8888/TCP       
knative-eventing/0*           active    idle   10.1.88.224                 
knative-operator/0*           active    idle   10.1.88.229                 
knative-serving/0*            active    idle   10.1.88.227                 
kserve-controller/0*          active    idle   10.1.88.232                 
kubeflow-dashboard/0*         active    idle   10.1.88.231                 
kubeflow-profiles/0*          active    idle   10.1.88.234                 
kubeflow-roles/0*             active    idle   10.1.88.230                 
kubeflow-volumes/0*           active    idle   10.1.88.250  5000/TCP       
metacontroller-operator/0*    active    idle   10.1.88.233                 
minio/0*                      active    idle   10.1.88.197  9000-9001/TCP  
oidc-gatekeeper/0*            active    idle   10.1.89.11   8080/TCP       
seldon-controller-manager/0*  active    idle   10.1.88.235                 
tensorboard-controller/0*     active    idle   10.1.88.252  9443/TCP       
tensorboards-web-app/0*       active    idle   10.1.88.251  5000/TCP       
training-operator/0*          active    idle   10.1.88.236


master@master-mac:~$ microk8s kubectl get pods -A 
NAMESPACE                       NAME                                               READY   STATUS                  RESTARTS          AGE
kube-system                     calico-kube-controllers-6c99c8747f-7nt95           0/1     Terminating             0                 4d23h
kube-system                     hostpath-provisioner-58694c9f4b-xrkql              1/1     Running                 1 (2d ago)        2d
kube-system                     coredns-7745f9f87f-snnvs                           1/1     Running                 1 (2d ago)        2d
ingress                         nginx-ingress-microk8s-controller-hdbmp            1/1     Running                 1 (2d ago)        2d
kube-system                     calico-kube-controllers-6cdcdfc67-krzxv            1/1     Running                 0                 2d
metallb-system                  controller-8467d88d69-wrqqz                        1/1     Running                 1 (2d ago)        2d
controller-microk8s-localhost   controller-0                                       3/3     Running                 0                 2d
controller-microk8s-localhost   modeloperator-854bb8bd97-ch8lm                     1/1     Running                 0                 2d
kubeflow                        modeloperator-549c547c95-hvcpj                     1/1     Running                 0                 2d
kubeflow                        admission-webhook-operator-0                       1/1     Running                 0                 2d
kubeflow                        argo-controller-operator-0                         1/1     Running                 0                 2d
kubeflow                        argo-server-operator-0                             1/1     Running                 0                 2d
kubeflow                        dex-auth-0                                         2/2     Running                 0                 2d
kubeflow                        istio-ingressgateway-0                             1/1     Running                 0                 2d
kubeflow                        admission-webhook-5f87b4d599-qts48                 1/1     Running                 0                 2d
kubeflow                        katib-controller-operator-0                        1/1     Running                 0                 2d
kubeflow                        katib-db-0                                         2/2     Running                 0                 2d
kubeflow                        istiod-59b57c567f-mhprn                            1/1     Running                 0                 2d
kubeflow                        jupyter-ui-0                                       2/2     Running                 0                 2d
kubeflow                        jupyter-controller-operator-0                      1/1     Running                 0                 47h
kubeflow                        istio-pilot-0                                      1/1     Running                 0                 2d
kubeflow                        katib-db-manager-0                                 2/2     Running                 0                 2d
kubeflow                        argo-server-5c55485f46-fsdcr                       1/1     Running                 0                 2d
kubeflow                        kfp-profile-controller-operator-0                  1/1     Running                 0                 47h
kubeflow                        kfp-schedwf-operator-0                             1/1     Running                 0                 47h
kubeflow                        kfp-viz-operator-0                                 1/1     Running                 0                 47h
kubeflow                        kfp-persistence-operator-0                         1/1     Running                 0                 47h
kubeflow                        tensorboards-web-app-operator-0                    1/1     Running                 0                 47h
kubeflow                        kfp-ui-operator-0                                  1/1     Running                 0                 47h
kubeflow                        kfp-viewer-operator-0                              1/1     Running                 0                 47h
kubeflow                        minio-operator-0                                   1/1     Running                 0                 47h
kubeflow                        tensorboard-controller-operator-0                  1/1     Running                 0                 47h
kubeflow                        kubeflow-volumes-operator-0                        1/1     Running                 0                 47h
kubeflow                        oidc-gatekeeper-operator-0                         1/1     Running                 0                 47h
kubeflow                        istio-ingressgateway-workload-796c944d6-pgvpg      1/1     Running                 0                 2d
kubeflow                        kfp-viewer-66db55db54-xk6kf                        1/1     Running                 0                 47h
kubeflow                        kubeflow-profiles-0                                3/3     Running                 0                 47h
kubeflow                        kfp-viz-6d78cb6984-2m86z                           1/1     Running                 0                 47h
kubeflow                        tensorboards-web-app-78745df494-ds9br              1/1     Running                 0                 47h
kubeflow                        minio-0                                            1/1     Running                 0                 47h
kubeflow                        kfp-schedwf-6ccbff666b-lt5ln                       1/1     Running                 0                 47h
kubeflow                        jupyter-controller-ccbdb85b9-hhs9d                 1/1     Running                 0                 47h
kubeflow                        kubeflow-volumes-59c7579899-6dl55                  1/1     Running                 0                 47h
kubeflow                        training-operator-0                                2/2     Running                 0                 47h
kubeflow                        tensorboard-controller-79d678cb7f-nqpzm            1/1     Running                 0                 47h
kubeflow                        kfp-db-0                                           2/2     Running                 0                 2d
kubeflow                        katib-controller-6ff7648c74-977td                  1/1     Running                 0                 47h
kubeflow                        argo-controller-7d8f9fddb5-2xrq7                   1/1     Running                 0                 47h
kubeflow                        kfp-api-0                                          2/2     Running                 0                 2d
kubeflow                        katib-ui-0                                         2/2     Running                 0                 2d
kubeflow                        knative-serving-0                                  1/1     Running                 0                 47h
kubeflow                        kubeflow-roles-0                                   1/1     Running                 0                 47h
kubeflow                        knative-eventing-0                                 1/1     Running                 0                 2d
kubeflow                        kserve-controller-0                                3/3     Running                 0                 47h
kubeflow                        kubeflow-dashboard-0                               2/2     Running                 0                 47h
kubeflow                        metacontroller-operator-0                          1/1     Running                 0                 47h
kubeflow                        knative-operator-0                                 3/3     Running                 0                 47h
kubeflow                        seldon-controller-manager-0                        2/2     Running                 0                 47h
kubeflow                        kfp-ui-5f585ccc85-qkdhn                            1/1     Running                 0                 47h
kubeflow                        kfp-persistence-68bbf7c67-mbkq4                    1/1     Running                 0                 47h
knative-eventing                mt-broker-controller-6b5958cdb9-fcjff              1/1     Running                 1 (47h ago)       47h
kubeflow                        kfp-profile-controller-854fdbcc8b-dq2zv            1/1     Running                 0                 47h
knative-serving                 domain-mapping-59f75c48f8-z2lh2                    1/1     Running                 2 (47h ago)       47h
knative-eventing                imc-controller-6cd6876c75-sm5z5                    1/1     Running                 2 (47h ago)       47h
knative-eventing                eventing-webhook-cd8f97669-86ds4                   1/1     Running                 2 (47h ago)       47h
knative-eventing                eventing-controller-7cb9ffbbfc-hfljq               1/1     Running                 4 (47h ago)       47h
kubeflow                        metacontroller-operator-charm-0                    1/1     Running                 5 (47h ago)       47h
knative-serving                 autoscaler-7dbb889d56-mhqfh                        1/1     Running                 3 (47h ago)       47h
knative-serving                 controller-957896fcf-crf9l                         1/1     Running                 3 (47h ago)       47h
knative-serving                 activator-768d7d48d9-lkl7f                         1/1     Running                 2 (47h ago)       47h
knative-eventing                mt-broker-filter-68fd99dc64-zg4k8                  1/1     Running                 6 (47h ago)       47h
kubeflow                        oidc-gatekeeper-75599c6f89-sjfwg                   1/1     Running                 0                 47h
knative-eventing                mt-broker-ingress-7c59885f49-lr6x9                 1/1     Running                 6 (47h ago)       47h
knative-eventing                imc-dispatcher-8c94567cf-5rpd2                     1/1     Running                 6 (47h ago)       47h
admin                           ml-pipeline-visualizationserver-9d8bfdc78-p2g6z    2/2     Running                 0                 47h
admin                           ml-pipeline-ui-artifact-6cfb9c4886-c92rf           2/2     Running                 0                 47h
minio-operator                  minio-operator-66847c5bd7-fv6fw                    0/1     Pending                 0                 46h
minio-operator                  console-78d567bfc8-2pt4x                           1/1     Running                 0                 46h
minio-operator                  minio-operator-66847c5bd7-7d468                    1/1     Running                 0                 46h
minio-operator                  microk8s-ss-0-0                                    1/1     Running                 0                 46h
admin                           kfp-examples-0                                     2/2     Running                 0                 4h57m
kserve-test                     sklearn-iris-predictor-default-54b57d7c45-tfz4z    1/1     Running                 0                 167m
kube-system                     calico-node-qrwls                                  0/1     CrashLoopBackOff        752 (4m45s ago)   2d
admin                           sklearn-iris-1-predictor-default-5f69b747f-2sjdd   0/1     Init:CrashLoopBackOff   264 (4m54s ago)   23h
admin                           sklearn-iris-predictor-default-86c895bfb7-rg4q9    0/1     Init:CrashLoopBackOff   507 (4m55s ago)   44h
metallb-system                  speaker-5tgwr                                      0/1     CrashLoopBackOff        570 (115s ago)    2d
knative-serving                 domainmapping-webhook-5b77d8484f-rkwf5             0/1     Running                 776 (5m53s ago)   47h

**Comment by sivanantha321** [comment]
@mary26pz I believe the kserve controller is not up yet

> kserve kserve-controller-manager-5d995bd58-v64fv 0/2 ContainerCreating 0 96m

**Comment by sivanantha321** [comment]
@ainnedge It will be eventually ready
> kserve-test sklearn-iris-predictor-default-54b57d7c45-tfz4z 1/1 Running 0 167m
