### ISSUE TITLE
how does request batching work?

### ISSUE THREAD

**Issue by mmoya91** [kserve/kserve#3261]
Hello, I was wondering how request batching worked as far as kserve? Given the [get_predict_input](https://github.com/kserve/kserve/blob/master/python/kserve/kserve/utils/utils.py#L141) source code, kserve expects payload requests to be structured in the following format
```json
{
   "inputs":[
      {
         "data":[
             ,...,
         ]
      }
   ]
}
```
assuming I add something like
```yaml
batcher:
      maxBatchSize: 32
      maxLatency: 500
```
to my deployment, does the request batcher know that it must batch inputs found in `["inputs"][0]["data"]`? Trying to wrap my head around the source code and whether it actually iterates through `["inputs"]`

**Comment by sivanantha321** [comment]
@mmoya91 batching is handle by [agent sidecar](https://github.com/kserve/kserve/blob/6f4bf79e4dd8bd15fb920508b2652bb20222ad9f/pkg/batcher/handler.go#L156).  For more info you can [read about batcher in the website](https://kserve.github.io/website/latest/modelserving/batcher/batcher/)

**Comment by mmoya91** [comment]
thank you @sivanantha321 I was wondering what the request payload structure would require in order to run batching. For instance, would my request payload have to be 
```json
{
   "inputs":[
      {
         "data":[
             "foo",
             "bar"
         ]
      }
   ]
}
```
or 
```json
{
   "inputs":[
      {
         "data":[
            "foo"
         ]
      },
      {
         "data":[
            "bar"
         ]
      }
   ]
}
```
from the looks of [get_predict_input](https://github.com/kserve/kserve/blob/master/python/kserve/kserve/utils/utils.py#L141) looks like it might be the latter. The documentation around the batcher, https://kserve.github.io/website/latest/modelserving/batcher/batcher/, didn't include what  the`input.json` structure would entail. Most documentation includes payload structure that reflects the first payload rather than the second

**Comment by sivanantha321** [comment]
@mmoya91 Use the second format.
```json
{
   "inputs":[
      {
         "data":[
            "foo"
         ]
      },
      {
         "data":[
            "bar"
         ]
      }
   ]
}
```
