### ISSUE TITLE
Model is ready even if there is no model

### ISSUE THREAD

**Issue by eyalcha** [kserve/kserve#3262]
/kind bug

This is the code for starting a model
```
kserve.ModelServer().start([model] if model.ready else [])
```
If model is not ready, model server gets empty model `[]`

The thing is that if you call
```
kubectl get isvc -A
```
You get the the model is ready, which is not true because actually there is no model.
```
NAMESPACE      NAME        URL                                         READY   PREV   LATEST   PREVROLLEDOUTREVISION   LATESTREADYREVISION         AGE
user           demomodel   http://demomodel.kmodels-user.example.com   True           100                              demomodel-predictor-00001   5m25s
```

**Comment by yuzisun** [comment]
The Ready status is for the service health, if there is a single model in the model repository we can fail the service, however if there are multiple models and only some of the models are failed to load then we might not want to mark the service to be not ready. We could add checks to fail the service if there is only one model.
