### ISSUE TITLE
Extract zip/archive files in GCS download

### ISSUE THREAD

**Issue by gfkeith** [kserve/kserve#3282]
/kind bug

**What steps did you take and what happened:**

Created InferenceService with `storageUri` as a zip archive, e.g. `gs://bucket/folder/archive.zip` - no model files found.

Created InferenceService with `storageUri` as a folder containing a single archive, e.g. `gs://bucket/folder` - archive found and downloaded, but not extracted.

Used `kserve.storage.storage.Storage._download_gcs` directly, with either zip archive or gcs folder containing only a single archive - either downloads nothing, or downloads the zip but doesn't extract it.

**What did you expect to happen:**

I expected the zip to be downloaded and extracted.

**What's the InferenceService yaml:**
[To help us debug please run `kubectl get isvc $name -n $namespace -oyaml` and paste the output]

**Anything else you would like to add:**

https://github.com/kserve/kserve/pull/1836/files added code which should do this, but there are a couple of problems:

1. The uri is always used as a prefix, with a [trailing slash added](https://github.com/kserve/kserve/blob/cac5fb1407391eedee284009d31c5a45ef127b23/python/kserve/kserve/storage/storage.py#L250) - so specifying the uri as `gs://bucket/folder/archive.zip` results in any blobs with the prefix `folder/archive.zip/` being downloaded - there are none.
2. The folder itself is counted as a blob (I'm not sure if this is specific to the google cloud storage version I'm using - I created a fresh poetry project and just installed kserve (^0.11.2), and it chose google-cloud-storage 1.44.0), so the `file_count` is incremented for the folder as well which results in `file_count` of 2, so it [doesn't extract the archive](https://github.com/kserve/kserve/blob/cac5fb1407391eedee284009d31c5a45ef127b23/python/kserve/kserve/storage/storage.py#L272). I'm not sure including the folder in the count is the desired behaviour here - possibly this is an indentation issue?

**Environment:**

- Istio Version: 
- Knative Version: 
- KServe Version: 0.11.2
- Kubeflow version:
- Cloud Environment: 
- Minikube/Kind version:
- Kubernetes version: (use `kubectl version`):
- OS (e.g. from `/etc/os-release`): Debian GNU/Linux 10 (buster)

**Comment by ainnedge** [comment]
Similar issue on ubuntu 20.04 with charmed kubeflow(1.8) and kserve(0.11.0). Any insights?

**Comment by gfkeith** [comment]
I think if only files which are actually downloaded (e.g. not 'folders') are counted, it would fix this and not break anything else, so change (from [here](https://github.com/kserve/kserve/blob/cac5fb1407391eedee284009d31c5a45ef127b23/python/kserve/kserve/storage/storage.py#L262-L266)):
```python
if subdir_object_key.strip() != "" and not subdir_object_key.endswith("/"):
    dest_path = os.path.join(temp_dir, subdir_object_key)
    logging.info("Downloading: %s", dest_path)
    blob.download_to_filename(dest_path)
file_count += 1
```
to
```python
if subdir_object_key.strip() != "" and not subdir_object_key.endswith("/"):
    dest_path = os.path.join(temp_dir, subdir_object_key)
    logging.info("Downloading: %s", dest_path)
    blob.download_to_filename(dest_path)
    file_count += 1
```

As far as I can see, that would be safe.

**Comment by lizzzcai** [comment]
Hi @gfkeith , feel free to create a PR to fix it, you can refer to [S3](https://github.com/kserve/kserve/blob/cac5fb1407391eedee284009d31c5a45ef127b23/python/kserve/kserve/storage/storage.py#L161) as well.

so far from y understanding the behaviour in KServe is `gs://bucket/folder/archive.zip` will be downloaded and unzipped (single zip file).
