### ISSUE TITLE
Fix bug in quick_install.sh for quick installation

### ISSUE THREAD

**Issue by tanvithakur94** [kserve/kserve#3297]
/kind bug

**What steps did you take and what happened:**
[A clear and concise description of what the bug is.]
I tried to locally run the e2e tests. However, when I tried to install quick_install.sh, it gave me an error:

`
pod/kserve-controller-manager-7b9879d9d7-s8p4p condition met
error: unable to read URL "https://github.com/kserve/kserve/releases/download/v0.11.1/kserve-cluster-resouces.yaml", server reported 404 Not Found, status code=404
`

**What did you expect to happen:**
This happened due to `kubectl apply -f https://github.com/kserve/kserve/releases/download/${KSERVE_VERSION}/kserve-cluster-resouces.yaml`

**What's the InferenceService yaml:**
[To help us debug please run `kubectl get isvc $name -n $namespace -oyaml` and paste the output]

`apiVersion:` v1
items:
- apiVersion: serving.kserve.io/v1beta1
  kind: InferenceService
  metadata:
    annotations:
      serving.kserve.io/deploymentMode: RawDeployment
    finalizers:
    - inferenceservice.finalizers
    generation: 1
    name: isvc-sklearn-graph
    namespace: kserve-ci-e2e-test
  spec:
    predictor:
      minReplicas: 1
      model:
        modelFormat:
          name: sklearn
        name: ""
        resources:
          limits:
            cpu: 100m
            memory: 256Mi
          requests:
            cpu: 50m
            memory: 128Mi
        storageUri: gs://kfserving-examples/models/sklearn/1.0/model
  status:
    address:
      url: http://isvc-sklearn-graph-predictor.kserve-ci-e2e-test.svc.cluster.local
    components:
      predictor:
        latestCreatedRevision: "1"
        url: http://isvc-sklearn-graph-predictor-kserve-ci-e2e-test.example.com
    conditions:
      status: "True"
      type: Ready
    modelStatus:
      states:
        activeModelState: Loaded
        targetModelState: Loaded
      transitionStatus: UpToDate
    observedGeneration: 1
    url: http://isvc-sklearn-graph-kserve-ci-e2e-test.example.com
- apiVersion: serving.kserve.io/v1beta1
  kind: InferenceService
  metadata:
    annotations:
      serving.kserve.io/deploymentMode: RawDeployment
    finalizers:
    - inferenceservice.finalizers
    generation: 1
    name: isvc-xgboost-graph
    namespace: kserve-ci-e2e-test
    resourceVersion: "4608"
    uid: bb8cfcdb-ca17-4b06-9dbc-9a4e07d04dd5
  spec:
    predictor:
      minReplicas: 1
      model:
        modelFormat:
          name: xgboost
        name: ""
        resources:
          limits:
            cpu: 100m
            memory: 256Mi
          requests:
            cpu: 50m
            memory: 128Mi
        storageUri: gs://kfserving-examples/models/xgboost/1.5/model
  status:
    address:
      url: http://isvc-xgboost-graph-predictor.kserve-ci-e2e-test.svc.cluster.local
    components:
      predictor:
        latestCreatedRevision: "1"
        url: http://isvc-xgboost-graph-predictor-kserve-ci-e2e-test.example.com
    conditions:
      status: "True"
      type: Ready
    modelStatus:
      copies:
        failedCopies: 0
        totalCopies: 1
      states:
        activeModelState: Loaded
        targetModelState: Loaded
      transitionStatus: UpToDate
    observedGeneration: 1
    url: http://isvc-xgboost-graph-kserve-ci-e2e-test.example.com
kind: List
metadata:
  resourceVersion: ""
  selfLink: ""`

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]
The potential solution is to just get rid of `kubectl apply -f https://github.com/kserve/kserve/releases/download/v0.11.1/kserve-cluster-resouces.yaml` 

**Environment:**
Local testing 

- Istio Version:
- Knative Version:
- KServe Version: v0.11.1
- Kubeflow version:
- Cloud Environment:[k8s_istio/istio_dex/gcp_basic_auth/gcp_iap/aws/aws_cognito/ibm]
- Minikube/Kind version:
- Kubernetes version: (use `kubectl version`): v1.25.9
- OS (e.g. from `/etc/os-release`):

**Comment by tanvithakur94** [comment]
https://github.com/kserve/kserve/pull/3298

**Comment by Jooho** [comment]
Looks `kserve-cluster-resouces.yaml` file name was changed to `kserve-runtimes.yaml`. So the right approach would be changing the filename in the script.

**Comment by yuzisun** [comment]
fixed in https://github.com/kserve/kserve/pull/3311
