### ISSUE TITLE
Allow Custom Components

### ISSUE THREAD

**Issue by ukclivecox** [kserve/kserve#33]
Allow the creation of custom components initially provided by a `v1.Container` specification.

**Comment by ellis-bigelow** [comment]
Rakesh, I'd love to see you lead a discussion of this topic.

Is a custom component a "arbitrary image" or "arbitrary model server".

/assign @rakelkar

**Comment by krabhishek8260** [comment]
I have documented some thoughts around ModelSpec and Custom ModelSpec here:
https://docs.google.com/document/d/1oLN6EvLBUaT-lUDDoTRZuRjP5FpHP6FqpeJmH7LvoQM/edit?usp=sharing
