### ISSUE TITLE
Explore usage of `ClusterStorageContainer` and Model Registry

### ISSUE THREAD

**Issue by lampajr** [kserve/kserve#3343]
/kind feature

As part of the model registry proposal we made in Kubeflow [1] we started exploring the usage of the `ClusterStorageContainer` capability to provide a custom and model-registry specific storage initializer in order to be able to deploy models by just specifying a model-registry specific URI like `model-registry://<model-name>/<version-name>`.

**Describe the solution you'd like**

We created a custom storage image in this repo [lampajr/model-registry-storage-initializer](https://github.com/lampajr/model-registry-storage-initializer), in the [README](https://github.com/lampajr/model-registry-storage-initializer/blob/618001e4945fe13f4e92722ebcd1819fbf0e5f07/README.md) I also extended the Kserve quickstart tutorial [2] to showcase the new custom storage usage.

[1] https://github.com/kubeflow/kubeflow/issues/7396
[2] https://kserve.github.io/website/master/get_started/

**Anything else you would like to add:**
n/a

**Links to the design documents:**
n/a

**Comment by terrytangyuan** [comment]
Would you like to contribute the example on the website and maybe also consider demoing in the community meeting?

**Comment by lampajr** [comment]
> Would you like to contribute the example on the website and maybe also consider demoing in the community meeting?

Hey @terrytangyuan, yeah sure to both your questions!!
>contribute the example on the website

Is there a specific place where should I add it? I was thinking to enhance this page https://kserve.github.io/website/0.11/modelserving/storage/storagecontainers/ by adding a more concrete example at the bottom (i.e., extending the `model-registry` simple sample that already exists there)

Or do you prefer to create a dedicated step-by-step example somewhere else?

> consider demoing in the community meeting?

That would be great, for this specific demo I would re-use this https://github.com/lampajr/model-registry-storage-initializer as I think it is already good enough to showcase what we tried.

**Comment by terrytangyuan** [comment]
> Is there a specific place where should I add it? I was thinking to enhance this page https://kserve.github.io/website/0.11/modelserving/storage/storagecontainers/ by adding a more concrete example at the bottom (i.e., extending the model-registry simple sample that already exists there)

Yes that sounds like a good place.
