### ISSUE TITLE
failed with message: Unable to fetch image "kserve/sklearnserver:v0.11.2": failed to resolve image to digest: Get "https://index.docker.io/v2/": dial tcp 3.219.239.5:443: i/o timeout.

### ISSUE THREAD

**Issue by zamamohx** [kserve/kserve#3372]
/kind bug

**What steps did you take and what happened:**
[A clear and concise description of what the bug is.]

-> We install kserve using kubeflow doc https://github.com/kubeflow/manifests and isvc won't run
-> we tried installing using https://raw.githubusercontent.com/kserve/kserve/release-0.11/hack/quick_install.sh  and isvc won'run
-> we build new cluster as well but know luck with that.
-> https://kserve.github.io/website/0.11/get_started/first_isvc/ example we used to test.
-> if we run as pod image pulled.
-> i tried updating kubectl edit configmap -n knative-serving config-deployment to below values but none work

  registries-skipping-tag-resolving: kind.local,ko.local,dev.local,docker.io,kserve,index.docker.io

┌─[zamamohx][aia-nfs][~]
└─▪ kubectl get inferenceservices sklearn-iris -n kserve-test
NAME           URL   READY   PREV   LATEST   PREVROLLEDOUTREVISION   LATESTREADYREVISION   AGE
sklearn-iris         False                                                                 10h
┌─[zamamohx][aia-nfs][~]

**What did you expect to happen:**
Inference service to run

**What's the InferenceService yaml:**
[To help us debug please run `kubectl get isvc $name -n $namespace -oyaml` and paste the output]

apiVersion: v1
items:
- apiVersion: serving.kserve.io/v1beta1
  kind: InferenceService
  metadata:
    annotations:
      kubectl.kubernetes.io/last-applied-configuration: |
        {"apiVersion":"serving.kserve.io/v1beta1","kind":"InferenceService","metadata":{"annotations":{},"name":"sklearn-iris","namespace":"kserve-test"},"spec":{"predictor":{"model":{"modelFormat":{"name":"sklearn"},"storageUri":"gs://kfserving-examples/models/sklearn/1.0/model"}}}}
    creationTimestamp: "2024-01-18T07:16:39Z"
    finalizers:
    - inferenceservice.finalizers
    generation: 1
    managedFields:
    - apiVersion: serving.kserve.io/v1beta1
      fieldsType: FieldsV1
      fieldsV1:
        f:metadata:
          f:annotations:
            .: {}
            f:kubectl.kubernetes.io/last-applied-configuration: {}
        f:spec:
          .: {}
          f:predictor:
            .: {}
            f:model:
              .: {}
              f:modelFormat:
                .: {}
                f:name: {}
              f:storageUri: {}
      manager: kubectl-client-side-apply
      operation: Update
      time: "2024-01-18T07:16:37Z"
    - apiVersion: serving.kserve.io/v1beta1
      fieldsType: FieldsV1
      fieldsV1:
        f:metadata:
          f:finalizers:
            .: {}
            v:"inferenceservice.finalizers": {}
      manager: manager
      operation: Update
      time: "2024-01-18T07:16:39Z"
    - apiVersion: serving.kserve.io/v1beta1
      fieldsType: FieldsV1
      fieldsV1:
        f:status:
          .: {}
          f:components:
            .: {}
            f:predictor:
              .: {}
              f:latestCreatedRevision: {}
          f:conditions: {}
          f:modelStatus:
            .: {}
            f:states:
              .: {}
              f:activeModelState: {}
              f:targetModelState: {}
            f:transitionStatus: {}
          f:observedGeneration: {}
      manager: manager
      operation: Update
      subresource: status
      time: "2024-01-18T07:16:42Z"
    name: sklearn-iris
    namespace: kserve-test
    resourceVersion: "44159149"
    uid: 90fb5b96-0efe-4085-a364-59c9c956714d
  spec:
    predictor:
      model:
        modelFormat:
          name: sklearn
        name: ""
        resources: {}
        storageUri: gs://kfserving-examples/models/sklearn/1.0/model
  status:
    components:
      predictor:
        latestCreatedRevision: sklearn-iris-predictor-00001
    conditions:
    - lastTransitionTime: "2024-01-18T07:16:52Z"
      reason: PredictorConfigurationReady not ready
      severity: Info
      status: "False"
      type: LatestDeploymentReady
    - lastTransitionTime: "2024-01-18T07:22:23Z"
      message: 'Revision "sklearn-iris-predictor-00001" failed with message: Unable
        to fetch image "kserve/sklearnserver:v0.11.2": failed to resolve image to
        digest: Get "https://index.docker.io/v2/": dial tcp 3.219.239.5:443: i/o timeout.'
      reason: RevisionFailed
      severity: Info
      status: "False"
      type: PredictorConfigurationReady
    - lastTransitionTime: "2024-01-18T07:16:53Z"
      message: Configuration "sklearn-iris-predictor" does not have any ready Revision.
      reason: RevisionMissing
      status: "False"
      type: PredictorReady
    - lastTransitionTime: "2024-01-18T07:16:53Z"
      message: Configuration "sklearn-iris-predictor" does not have any ready Revision.
      reason: RevisionMissing
      severity: Info
      status: "False"
      type: PredictorRouteReady
    - lastTransitionTime: "2024-01-18T07:16:53Z"
      message: Configuration "sklearn-iris-predictor" does not have any ready Revision.
      reason: RevisionMissing
      status: "False"
      type: Ready
    - lastTransitionTime: "2024-01-18T07:16:53Z"
      reason: PredictorRouteReady not ready
      severity: Info
      status: "False"
      type: RoutesReady
    modelStatus:
      states:
        activeModelState: ""
        targetModelState: Pending
      transitionStatus: InProgress
    observedGeneration: 1
kind: List
metadata:
  resourceVersion: ""
  selfLink: ""

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

**Environment:**

Production environment on local Kubernetes cluster

- Istio Version: 1.17.5
- Knative Version: 0.11.2
- KServe Version: 0.11.2
- Kubeflow version: 1.17
- Cloud Environment:[k8s_istio/istio_dex/gcp_basic_auth/gcp_iap/aws/aws_cognito/ibm]
- Minikube/Kind version:
- Kubernetes version: (use `kubectl version`): 1.23
- OS (e.g. from `/etc/os-release`): ubuntu 22.04

**Comment by dsgli** [comment]
Got exactly the same problem on my serverless setup (tried to deploy sklearn example, since i could not make my own inference services to work)

<details><summary>My inference service yaml output</summary>
<p>

```

apiVersion: serving.kserve.io/v1beta1
kind: InferenceService
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"serving.kserve.io/v1beta1","kind":"InferenceService","metadata":{"annotations":{},"name":"sklearn-iris","namespace":"kserve-test2"},"spec":{"predictor":{"model":{"modelFormat":{"name":"sklearn"},"storageUri":"gs://kfserving-examples/models/sklearn/1.0/model"}}}}
  creationTimestamp: "2024-02-29T09:33:57Z"
  finalizers:
  - inferenceservice.finalizers
  generation: 1
  name: sklearn-iris
  namespace: kserve-test2
  resourceVersion: "161403"
  uid: 161b7721-1dae-4a8c-86c7-01fcba0428f3
spec:
  predictor:
    model:
      modelFormat:
        name: sklearn
      name: ""
      resources: {}
      storageUri: gs://kfserving-examples/models/sklearn/1.0/model
status:
  components:
    predictor:
      latestCreatedRevision: sklearn-iris-predictor-00001
  conditions:
  - lastTransitionTime: "2024-02-29T09:34:08Z"
    reason: PredictorConfigurationReady not ready
    severity: Info
    status: "False"
    type: LatestDeploymentReady
  - lastTransitionTime: "2024-02-29T09:34:08Z"
    message: 'Revision "sklearn-iris-predictor-00001" failed with message: Unable
      to fetch image "kserve/sklearnserver:v0.11.0": failed to resolve image to digest:
      Get "https://index.docker.io/v2/": context deadline exceeded.'
    reason: RevisionFailed
    severity: Info
    status: "False"
    type: PredictorConfigurationReady
  - lastTransitionTime: "2024-02-29T09:34:08Z"
    message: Configuration "sklearn-iris-predictor" does not have any ready Revision.
    reason: RevisionMissing
    status: "False"
    type: PredictorReady
  - lastTransitionTime: "2024-02-29T09:34:08Z"
    message: Configuration "sklearn-iris-predictor" does not have any ready Revision.
    reason: RevisionMissing
    severity: Info
    status: "False"
    type: PredictorRouteReady
  - lastTransitionTime: "2024-02-29T09:34:08Z"
    message: Configuration "sklearn-iris-predictor" does not have any ready Revision.
    reason: RevisionMissing
    status: "False"
    type: Ready
  - lastTransitionTime: "2024-02-29T09:34:08Z"
    reason: PredictorRouteReady not ready
    severity: Info
    status: "False"
    type: RoutesReady
  modelStatus:
    states:
      activeModelState: ""
      targetModelState: Pending
    transitionStatus: InProgress
  observedGeneration: 1


```

</p>
</details> 


**Environment:**

Production environment on local Kubernetes cluster

- Istio Version: 1.20.2
- Knative Version: 0.13.1
- KServe Version: 0.11.0
- Kubeflow version:  -
- Cloud Environment: on premises deployment
- Minikube/Kind version: -
- Kubernetes version: (use kubectl version): 1.29.1
- OS (e.g. from /etc/os-release): fedora 39 server

---
Although I can add that my own inference services started to work when i added sha instead of tag, but in case of sklearn example, not sure if/where it should be added to bypass digest issue.

**Comment by zamamohx** [comment]
We able to move forward by updating "registries-skipping-tag-resolving" in configmap  
Example:

```
kubectl edit configmap -n knative-serving config-deployment

apiVersion: v1
data:
  digest-resolution-timeout: 10s
  progress-deadline: 600s
  queue-sidecar-cpu-limit: 1000m
  queue-sidecar-cpu-request: 25m
  queue-sidecar-ephemeral-storage-limit: 1024Mi
  queue-sidecar-ephemeral-storage-request: 512Mi
  queue-sidecar-image: gcr.io/knative-releases/knative.dev/serving/cmd/queue@sha256:65b3be9cea1afea32c55c69403077d2dc3439f75c26a1e83f
  queue-sidecar-memory-limit: 800Mi
  queue-sidecar-memory-request: 400Mi
  queue-sidecar-rootca: ""
  queue-sidecar-token-audiences: ""
  **registries-skipping-tag-resolving: kind.local,ko.local,dev.local,docker.io,index.docker.io**

```

**Comment by sivanantha321** [comment]
@zamamohx By default, Knative resolves image tags to digest which may require correct access permissions for the registry. To avoid this you can provide the correct access permissions and credentials or disable tag digest for specific registry as mentioned in the above comment or simply use digest instead of tags.
