### ISSUE TITLE
Support pydantic 2

### ISSUE THREAD

**Issue by timothyjlaurent** [kserve/kserve#3373]
/kind feature

**Describe the solution you'd like**
[A clear and concise description of what you want to happen.]
The kserve package should support Pydantic 2 and newer FastAPI

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

**Links to the design documents:**
[Optional, start with the short-form [RFC template](https://docs.google.com/document/d/1UcBeLfZ_JMGpVrPJmYtEIVH_9Y4U3AEKQdq_IKuOMrU) to outline your ideas and get early feedback.]
[Required, use the longer-form [design doc template](https://docs.google.com/document/d/1Mtoui_PP2a9N59NjYHnsvrdJ8t2iKFwIJAx1zRO_I1c) to specify and discuss your design in more detail]

**Comment by terrytangyuan** [comment]
This is being worked on in https://github.com/kserve/kserve/pull/3273

**Comment by timothyjlaurent** [comment]
Thanks @terrytangyuan - I saw that PR. I have another PR that supersedes that one as there were a number of problems with it. See the linked PR #3374

**Comment by terrytangyuan** [comment]
Got it. Thanks
