### ISSUE TITLE
Re-enable dependabot

### ISSUE THREAD

**Issue by terrytangyuan** [kserve/kserve#3416]
/kind feature

This was discussed in the last community meeting. It might be a good idea to enable dependabot to fix issues faster automatically. 

I saw that dependabot was enabled before but then disabled. Was there any reason for that? Can we re-enable it?

cc @yuzisun @rachitchauhan43

**Comment by terrytangyuan** [comment]
cc @spolti

**Comment by terrytangyuan** [comment]
I proposed the dependabot configuration in https://github.com/kserve/kserve/pull/3417 so that we only use it for security updates to reduce noise.

**Comment by ckadner** [comment]
KServe is already using Dependabot -- with the GitHub recommended standard configuration

<details><summary>Screenshot:</summary>
<img width="938" alt="image" src="https://github.com/kserve/kserve/assets/12246093/81be1f1c-6022-4f3d-a4c4-16e4a21f4a7c">
</details>

---


There are currently 126 reported potential vulnerabilities, 886 previously addressed/closed ones:

<details><summary>Screenshot:</summary>
<img width="948" alt="image" src="https://github.com/kserve/kserve/assets/12246093/c958c07f-1b70-47b4-a45b-26654ee41baf">
</details>

---

Do you intend to add custom configurations that are not possible to configure using the GitHub repo settings? If not, I would prefer to keep using the standard setting, without having to maintain another .yaml file.

We disabled the automatic PRs as they often don't always produce ideal or even the correct fix. Especially with complex/intertwined dependency graphs.

---

The alerts are currently only visible to project admins, so maybe we could come up with some sort of new security responsibility for a bigger group of contributors.

<details><summary>Screenshot:</summary>
<img width="656" alt="image" src="https://github.com/kserve/kserve/assets/12246093/79e6c2c0-6443-47f8-b12a-09af1367db7e">
</details>

**Comment by terrytangyuan** [comment]
Thanks for your screenshots! Some motivations behind this:
1. The minimal set of YAML is very easy to maintain and can be used for multiple repos. No single maintainer can accidentally mess up with the configuration and deactivate dependabot since everything will go through PR reviews (thinking GitOps). They are also visible to non-maintainers.
2. Enable automatic PRs makes it easy for non-maintainers to contribute to discussions and get involved. We only enable automatic PRs for security patches which would reduce the noise.
3. No need to maintain a separate group of contributors with additional access to see the alerts.

**Comment by spolti** [comment]
Last time we discussed it (@terrytangyuan and myself) the dependabot security updates was disabled (PRs automation).
Guess the main focus here is to re-enable it so, as Yuan mentioned, make easier for people that does not have write rights in this repo to contribute more with the security part.

**Comment by spolti** [comment]
But if we could see all the alerts it would be nice as well, I mean, to help to keep even the docs, demo and subprojects free of critical/high/medium alerts.

**Comment by ckadner** [comment]
@terrytangyuan @spolti -- thumbs up this comment if you received (and accepted) an invite to join the [`kserve-security` team](https://github.com/orgs/kserve/teams/kserve-security)?

Security Alerts should now be visible to all members of that team:

<details><summary>Screenshot:</summary>
<img width="630" alt="image" src="https://github.com/kserve/kserve/assets/12246093/8af1582c-26c1-40c9-8492-53e2f40fa836">
 </details>

**Comment by terrytangyuan** [comment]
Yes I am able to see the alerts now. Thank you!

**Comment by ckadner** [comment]
Good. I would suggest we do a first round of (bulk) dependency updates manually, creating PRs ourselves to clean out the dependabot queue. After that we can re-evaluate enabling automatic PRs.

**Comment by sivanantha321** [comment]
@ckadner I would also like to be part of the security team if it is okay with you

**Comment by terrytangyuan** [comment]
> Good. I would suggest we do a first round of (bulk) dependency updates manually, creating PRs ourselves to clean out the dependabot queue. After that we can re-evaluate enabling automatic PRs.

Sounds good

**Comment by terrytangyuan** [comment]
@ckadner It seems like we only have triage permission on kserve but not other repos. Could you update the settings? https://github.com/orgs/kserve/teams/kserve-security/repositories

**Comment by ckadner** [comment]
> @ckadner It seems like we only have triage permission on kserve but not other repos. Could you update the settings? https://github.com/orgs/kserve/teams/kserve-security/repositories


I created a separate group for the ModelMesh repositories since it is a separate group of developers and differing processes/strategies.

https://github.com/orgs/kserve/teams/modelmesh-security/repositories

**Comment by terrytangyuan** [comment]
Sounds good. I'll close this for now. Thank you!

**Comment by spolti** [comment]
Thanks all, I am able to see the alerts as well.
