### ISSUE TITLE
Support OpenAI Schema for KServe LLM runtime

### ISSUE THREAD

**Issue by yuzisun** [kserve/kserve#3419]
/kind feature

**Describe the solution you'd like**
KServe recently added the support for [generate endpoint](https://github.com/kserve/open-inference-protocol/blob/main/specification/protocol/generate_rest.yaml) from open inference protocol and huggingface runtime API has already started to support the generate endpoint. KServe would like like to offer the OpenAI compatibility with generate endpoints. The benefits are that the API can be directly used with OpenAI's client libraries or third party tools like LangChain or LlamaIndex. It also can help people migrate from GPT4 to Mistral or Llama2. 

## Proposal:

KServe open inference protocol endpoints:
- v2/models/{model}/completion
- v2/models/{model}/chat/completion

OpenAI compatible endpoints:
- openai/v1/completion
- openai/v1/chat/completion

**Anything else you would like to add:**
References:
- OpenAI Schema: https://platform.openai.com/docs/api-reference/making-requests 
- OpenAI python types: https://github.com/openai/openai-python/tree/main/src/openai/types
- Azure OpenAI endpoints: https://learn.microsoft.com/en-us/azure/ai-services/openai/reference#completions

**Links to the design documents:**
[Optional, start with the short-form [RFC template](https://docs.google.com/document/d/1UcBeLfZ_JMGpVrPJmYtEIVH_9Y4U3AEKQdq_IKuOMrU) to outline your ideas and get early feedback.]
[Required, use the longer-form [design doc template](https://docs.google.com/document/d/1Mtoui_PP2a9N59NjYHnsvrdJ8t2iKFwIJAx1zRO_I1c) to specify and discuss your design in more detail]

**Comment by johnugeorge** [comment]
+1 Must feature to provide seamless user experience. Ecosystem support is a huge value addition with OpenAI API compatibility

**Comment by alexagriffith** [comment]
https://github.com/vllm-project/vllm/tree/main/vllm/entrypoints/openai
