### ISSUE TITLE
InferenceService CRD is too large

### ISSUE THREAD

**Issue by terrytangyuan** [kserve/kserve#3487]
/kind bug

KServe's [ISVC CRD](https://github.com/kserve/kserve/blob/master/config/crd/serving.kserve.io_inferenceservices.yaml) is too large and it's impossible to add new fields to the spec given the limitation of K8s CRD size in general.

This currently blocks a couple of community PRs, including https://github.com/kserve/kserve/pull/3479 and https://github.com/kserve/kserve/pull/3418.

Even though the error message is pointing to the annotations, the actual problem might be the size of the entire CRD. 
`CustomResourceDefinition "[inferenceservices.serving.kserve.io](http://inferenceservices.serving.kserve.io/)" is invalid: metadata.annotations: Too long: must have at most 262144 bytes`

**Comment by terrytangyuan** [comment]
https://github.com/kubernetes/kubernetes/issues/82292

**Comment by terrytangyuan** [comment]
Trying out an approach in https://github.com/kserve/kserve/pull/3492

**Comment by sivanantha321** [comment]
A temporary solution would be start using [server side apply](https://kubernetes.io/docs/reference/using-api/server-side-apply/), which does not use annotations to maintain previous state of a resource unlike the client side apply.

**Comment by yuzisun** [comment]
Also we have individual framework predictor  or explainer specs, each containing a PodSpec which contributed to the large crd size. @sivanantha321 has a PR starting deprecating those.

**Comment by yuzisun** [comment]
I do not think we should follow the Argo approach to keep all fields as known as in this way you lose the schema validation and dry-run.

**Comment by terrytangyuan** [comment]
> A temporary solution would be start using [server side apply](https://kubernetes.io/docs/reference/using-api/server-side-apply/), which does not use annotations to maintain previous state of a resource unlike the client side apply.

But even if it's doesn't use annotations, the CRD might still be too large.

> Also we have individual framework predictor or explainer specs, each containing a PodSpec which contributed to the large crd size. @sivanantha321 has a PR starting deprecating those.

That's long-term solution though and requires new CRD version after those are removed?

> I do not think we should follow the Argo approach to keep all fields as known as in this way you lose the schema validation and dry-run.

I think for Argo's case it's ok to drop validation since controller does validation anyways and we have a JsonSchema that can be used for validation in Argo Workflows UI's workflow editor or IDEs.

**Comment by terrytangyuan** [comment]
Discussed with Dan offline. Here are some things we can do:

**Short-term:**
1. Remove Seldon/Alibi specs https://github.com/kserve/kserve/pull/3443
2. Remove HuggingFace spec

**Long-term:**
1. Remove predictor/explainer specs https://github.com/kserve/kserve/pull/3144

**Nice-to-have:**

1. Provide minimal CRDs similar to what Argo is doing for users who do not need client-side validation. This is nice-to-have but not solving this particular issue though https://github.com/kserve/kserve/pull/3492. 
2. Add a separate helm-chart called "crd-minimal" https://github.com/kserve/kserve/pull/3492

**Comment by ram4444** [comment]
Hi,
I get the same error when I try to install the kubeflow.
Please let me know what should I do in order to apply this 20k line CRD to the cluster.

by running the hack/generate_install.sh v0.14.0
I still find the CRD remain the same length

**Comment by sivanantha321** [comment]
@ram4444 Use helm or server side apply with kubectl. https://kserve.github.io/website/master/admin/serverless/serverless/#4-install-kserve

**Comment by egvikosh** [comment]
Hi, facing same issue, when installing kserve-crd via ArgoCD - version v0.14.1. Not sure what is expected way of installing it, no any additional information provided here: https://kserve.github.io/website/0.14/admin/kubernetes_deployment/#3-install-kserve.
Use kserve-crd-minimal chart?
