### ISSUE TITLE
Sample model failing to launch,"No such file or directory: '/mnt/models'" inside the inference service pod.

### ISSUE THREAD

**Issue by wassimMsw** [kserve/kserve#3499]
/kind bug

**What steps did you take and what happened:**
I am following the exact steps of the "Getting Started" guide. Installed kserve on a minikube cluster and launched the first InferenceService but the pod is failing. This is what Im getting in the logs of the pod:

```
INFO:root:Copying contents of /mnt/models to local
ERROR:root:fail to locate model file for model sklearn-iris under dir /mnt/models,trying loading from model repository.
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/local/lib/python3.9/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/sklearnserver/sklearnserver/__main__.py", line 42, in <module>
    kserve.ModelServer(registered_models=SKLearnModelRepository(args.model_dir)).start(
  File "/sklearnserver/sklearnserver/sklearn_model_repository.py", line 24, in __init__
    self.load_models()
  File "/kserve/kserve/model_repository.py", line 37, in load_models
    for name in os.listdir(self.models_dir):
FileNotFoundError: [Errno 2] No such file or directory: '/mnt/models'
```

**What's the InferenceService yaml:**
```
apiVersion: "serving.kserve.io/v1beta1"
kind: "InferenceService"
metadata:
  name: "sklearn-iris"
spec:
  predictor:
    model:
      modelFormat:
        name: sklearn
      storageUri: "gs://kfserving-examples/models/sklearn/1.0/model"
```
**Anything else you would like to add:**
Tried with a `kind` cluster too but still didn't work.

**Environment:**

- Istio Version:
- Knative Version:
- KServe Version: 0.11.0
- Kubeflow version:
- Cloud Environment:[k8s_istio/istio_dex/gcp_basic_auth/gcp_iap/aws/aws_cognito/ibm]
- Minikube/Kind version: minikube version: v1.32.0
- Kubernetes version: (use `kubectl version`): 
```
Client Version: v1.29.1
Kustomize Version: v5.0.4-0.20230601165947-6ce0bf390ce3
Server Version: v1.28.3
```
- OS (e.g. from `/etc/os-release`):

**Comment by sivanantha321** [comment]
@wassimMsw Can you check if the init container successfully downloaded the model ? Unfortunately, I am unable to reproduce this.

**Comment by wassimMsw** [comment]
> @wassimMsw Can you check if the init container successfully downloaded the model ? Unfortunately, I am unable to reproduce this.

@sivanantha321 I tried to do this, but the init container is not launching. I can find only two containers at any time:
- queue-proxy
- kserve-container

**Comment by sivanantha321** [comment]
@wassimMsw Just to be clear, are you saying init container(storage-initializer) not injected ? Can you check the kserve controller logs for any potential errors ?

**Comment by dnesting** [comment]
I hit this today.  For me, the cause was re-using the `kserve` namespace for the InferenceService instead of following directions, as I did not expect that to matter.  The controller doesn't inject the storage-initializer container and doesn't give an error for this situation. It just "doesn't work".  It looks like others have stumbled into this as well.

**Comment by wassimMsw** [comment]
> @wassimMsw Just to be clear, are you saying init container(storage-initializer) not injected ? Can you check the kserve controller logs for any potential errors ?

@sivanantha321  yes not injected, couldn't find any lead in the controller manager logs

@dnesting I tried in a namespace different than `kserve` and still it didn't work.

**Comment by iciclespider** [comment]
I see the OP did not list Istio or KNative versions. Is this in a "Raw Deployment" environment? If so, it appears to me that RawDeploment does not do storage initialization.

See this discussion I started about RawDeployments: https://github.com/kserve/kserve/discussions/3505

**Comment by iciclespider** [comment]
I just reread the comments here and in my case I was also deploying the InferenceService to the `kserve` namespace. When I deployed it to a different namespace, storage was properly initialized. Mystery solved I believe. However, some documentation is needed clarifying this. Actually, IMO, I do not see a reason for not supporting InferenceServices in the kserve namespace.

**Comment by iciclespider** [comment]
On the other, other hand...

When deployed to the "kserve" namespace in RawDeployment mode, the kserve operator did create the Deployment and the Pod did get created. It was then the kserve mutating webhook that did not process the needed storage initialization. If deploying to the kserve namespace is not supported, the kserve operator should not be creating the Deployment and other resources. If it is supported, storage initialization is broken.

**Comment by sivanantha321** [comment]
@wassimMsw Is it possible that the namespace in isvc deployed contains a label called 'control-plane' ? Could you verify that ?

**Comment by wassimMsw** [comment]
> @wassimMsw Is it possible that the namespace in isvc deployed contains a label called 'control-plane' ? Could you verify that ?

@sivanantha321 I deleted the minikube cluster and started from scratch and tried creating the inference service in kserve-test, and now it worked, I can see the storage initializer. Idk why it didn't work the first time I tried that. The mystery is solved. But I think documentation should highlight the importance of not using the `kserve` namespace. Also, as @iciclespider said:
>  If deploying to the kserve namespace is not supported, the kserve operator should not be creating the Deployment and other resources. If it is supported, storage initialization is broken.

**Comment by sivanantha321** [comment]
A warning note is added to the website explaining the control plane namespaces as part of PR https://github.com/kserve/website/pull/354. Closing this issue based on the above comment.
