### ISSUE TITLE
Storage Initializer Azure IsADirectoryError 

### ISSUE THREAD

**Issue by tjandy98** [kserve/kserve#3501]
/kind bug

When an Azure storage url e.g `https://.....blob.core.windows.net/models/container/tfmodel/1/saved_model.pb`
pointing to a blob is used, the following error occurs:

```
Traceback (most recent call last):
  File "/app/scripts/initializer-entrypoint", line 15, in <module>
    kserve.Storage.download(src_uri, dest_path)
  File "/app/src/storage.py", line 91, in download
    Storage._download_blob(uri, out_dir)
  File "/app/src/storage.py", line 357, in _download_blob
    with open(dest_path, "wb+") as f:
         ^^^^^^^^^^^^^^^^^^^^^^
IsADirectoryError: [Errno 21] Is a directory: '/mnt/models/'
```

However if url to the dir e.g `https://.....blob.core.windows.net/models/container/tfmodel/1`is used instead, it downloads the content as expected.

**Comment by sivanantha321** [comment]
Fixed by #3502
