### ISSUE TITLE
What types of models does the Hugging Face runtime support?

### ISSUE THREAD

**Issue by yolk-pie-L** [kserve/kserve#3508]
Does the current HuggingFace runtime support text-to-image models on HuggingFace? Does it support diffuser? All kinds of NLP models?

**Comment by yolk-pie-L** [comment]
It seems only to support the following types of tasks (all related to language models):

- AutoModelForSequenceClassification
- AutoModelForQuestionAnswering
- AutoModelForTokenClassification
- AutoModelForMaskedLM
- AutoModelForCausalLM
- AutoModelForSeq2SeqLM

It does not support 'diffuser'.

**Comment by yuzisun** [comment]
We do not support text to image task yet.
