### ISSUE TITLE
Is it possible to inject custom initContainer into the InferenceService pod ?

### ISSUE THREAD

**Issue by bpradipt** [kserve/kserve#3522]
I'm looking at ways to integrate [confidential containers (CoCo)](https://github.com/confidential-containers/) with kserve. CoCo runs inside a hardware trusted execution environment (TEE), which provides runtime memory encryption. The benefit of runtime memory encryption is that even a privileged entity in the host cannot access plaintext inside the TEE. 
We rely on `runtimeClass` to deploy a K8s pod as a CoCo pod. This approach works fine when using knative-serving with the `runtimeclassname` feature enabled.

The recently introduced `modelCar` functionality also helps, as we can deploy and decrypt the encrypted model container images inside the TEE. This is taken care by the CoCo runtime.

Now, when using other model storage options (like S3), we need a way to decrypt the downloaded model. One option is to use a custom storage initializer that downloads the key and decrypts the model. 

However, I wanted to check if there is a standard mechanism in kserve for injecting a custom `initContainer` just before starting the main container to decrypt the model.

**Comment by israel-hdez** [comment]
The `ClusterStorageContainer` CRD is what you may be looking for: https://kserve.github.io/website/0.11/modelserving/storage/storagecontainers/
