### ISSUE TITLE
[Solution] Ray Serve version compatibility issue: cannot import name 'RayServeHandle' from 'ray.serve.handle'

### ISSUE THREAD

**Issue by cceyda** [kserve/kserve#3541]
/kind bug

**What steps did you take and what happened:**
Just  `import kserve`
Results in :

```
kserve_1  | Traceback (most recent call last):
kserve_1  |   File "/opt/program/serving.py", line 3, in <module>
kserve_1  |     import kserve
kserve_1  |   File "/opt/conda/lib/python3.10/site-packages/kserve/__init__.py", line 18, in <module>
kserve_1  |     from .model_server import ModelServer
kserve_1  |   File "/opt/conda/lib/python3.10/site-packages/kserve/model_server.py", line 27, in <module>
kserve_1  |     from ray.serve.handle import RayServeHandle
kserve_1  | ImportError: cannot import name 'RayServeHandle' from 'ray.serve.handle' (/opt/conda/lib/python3.10/site-packages/ray/serve/handle.py)
```

Judging by how my image builds broke overnight and latest [ray-2.10.0](https://github.com/ray-project/ray/releases/tag/ray-2.10.0) release was just ~13hours ago... seems to be breaking changes in new version.

**Anything else you would like to add:**

Current kserve version req for ray is:

> Collecting ray<3.0.0,>=2.9.2 (from ray[serve]<3.0.0,>=2.9.2->kserve)

**Issue is solved by** fixing the version requirement to be  `ray[serve]<=2.9.3,>=2.9.2`

- KServe Version: 0.12.0

**Comment by yang-ewx** [comment]
Are you using rayserve and kserve at the same time? Can you give more background on this question, where does it happen?

**Comment by cceyda** [comment]
kserve is using ray serve. it is a kserve dependency

**Comment by sivanantha321** [comment]
@yang-ewx You can use kserve with rayserve. Here is an [example from IBM blog](https://developer.ibm.com/articles/awb-parallel-inference-with-kserve-and-rayserve/).

**Comment by noelo** [comment]
Hitting the same issue but I found this in the ray code from release 2.9.3
@Deprecated(
    message="This API has been replaced by `ray.serve.handle.DeploymentHandle`."
)
class RayServeHandle(_DeploymentHandleBase):

**Comment by sivanantha321** [comment]
Fixed by #3556

**Comment by arshchimni** [comment]
Hey @sivanantha321  

Sorry for tagging on to a closed issue. I am trying to build a torchserve-kfs image using the docker files in the [serve](https://github.com/pytorch/serve.git ) and am facing this issue. Can you suggest a workaround or when the patch will be relased as maybe sdk version 0.12.1? 🙇🏻

**Comment by agunapal** [comment]
Hi @sivanantha321 Is there going to be a release soon. I'm not able to do a quick install with the master branch

```
Error from server (InternalError): error when creating "https://github.com/knative/net-istio/releases/download/knative-v1.13.1/release.yaml": Internal error occurred: failed calling webhook "webhook.serving.knative.dev": failed to call webhook: Post "https://webhook.knative-serving.svc:443/?timeout=10s": dial tcp 10.102.102.63:443: connect: connection refused
```

**Comment by sivanantha321** [comment]
@agunapal It seems like the knative's webhook is not ready. Re-running the script should fix it.
