### ISSUE TITLE
Closed

### ISSUE THREAD

**Issue by SNagappan** [kserve/kserve#3549]

**Comment by terrytangyuan** [comment]
Alibi will be removed in https://github.com/kserve/kserve/pull/3443

**Comment by SNagappan** [comment]
@terrytangyuan Thank you for the response. I understand that in a future version Alibi will be removed, but for current version, is there a fix for the issue that I am encountering?

**Comment by terrytangyuan** [comment]
That's an issue with Alibi so I don't think we can deliver any fix from KServe.

**Comment by terrytangyuan** [comment]
@sivanantha321 Any suggestions here given that you've updated it previously?

**Comment by sivanantha321** [comment]
@SNagappan The segmentation_func.dll and explainer.dll should be saved as a single dump file. The runtime only loads the explainer.dill file.

**Comment by SNagappan** [comment]
@sivanantha321 Do you have an example or guidance on how that can be done? The default save method in Alibi creates separate dill files.

**Comment by sivanantha321** [comment]
@SNagappan You can use dill library to dump the explainer.
```python
import dill

explainer = AnchorTabular(predict_fn, feature_names, categorical_names=category_map, seed=1)
explainer.fit(X_train, disc_perc=[25, 50, 75])

with open('explainer.dill', 'wb') as f:
    dill.dump(explainer, f)
```
By the way sorry for the late reply. I got sucked into my work schedule :sweat_smile: .
