### ISSUE TITLE
Unified log format in KServe runtime application

### ISSUE THREAD

**Issue by lizzzcai** [kserve/kserve#3560]
/kind feature

**Describe the solution you'd like**

Currently, KServe application logs are not unified.
1. some [places](https://github.com/kserve/kserve/blob/master/python/custom_tokenizer/transformer.py#L23) use `import logging` and some [places](https://github.com/kserve/kserve/blob/master/python/huggingfaceserver/huggingfaceserver/model.py#L24) use `from kserve.logging import logger`.
2. there is default [log config](https://github.com/kserve/kserve/blob/master/python/kserve/kserve/logging.py#L28) defined but not applied by default for the application logger.

example format for huggingface server:
```
python -m huggingfaceserver --model_id=bert-base-uncased --model_name=bert

INFO:kserve:successfully loaded tokenizer for task: 5
Some weights of the model checkpoint at bert-base-uncased were not used when initializing BertForMaskedLM: ['cls.seq_relationship.weight', 'bert.pooler.dense.bias', 'cls.seq_relationship.bias', 'bert.pooler.dense.weight']
- This IS expected if you are initializing BertForMaskedLM from the checkpoint of a model trained on another task or with another architecture (e.g. initializing a BertForSequenceClassification model from a BertForPreTraining model).
- This IS NOT expected if you are initializing BertForMaskedLM from the checkpoint of a model that you expect to be exactly identical (initializing a BertForSequenceClassification model from a BertForSequenceClassification model).
INFO:kserve:successfully loaded huggingface model from path bert-base-uncased
INFO:kserve:Registering model: model
INFO:kserve:Setting max asyncio worker threads as 16
INFO:kserve:Starting uvicorn with 1 workers
2024-01-08 06:32:08.801 uvicorn.error INFO:     Started server process [75012]
2024-01-08 06:32:08.801 uvicorn.error INFO:     Waiting for application startup.
2024-01-08 06:32:08.804 75012 kserve INFO [start():62] Starting gRPC server on [::]:8081
2024-01-08 06:32:08.804 uvicorn.error INFO:     Application startup complete.
2024-01-08 06:32:08.805 uvicorn.error INFO:     Uvicorn running on http://0.0.0.0:8080 (Press CTRL+C to quit)
```

I would expect:
1. KServe application logs have default format
2. Storage initializer logs have default format
3. [optional] The user can overwrite the default format if necessary.

Information like `timestamp` will be helpful to know how long it take for model being downloaded in storage initializer and how long it take to load the model.

**Anything else you would like to add:**

My naive approach is to add `logging.config.dictConfig(KSERVE_LOG_CONFIG)` in kserve.logging and use `kserve.logging import logger`.
Concern on whether it will overwrite the user's application log format mentioned [here](https://github.com/kserve/kserve/pull/2884#discussion_r1190296386). 

**Links to the design documents:**
[Optional, start with the short-form [RFC template](https://docs.google.com/document/d/1UcBeLfZ_JMGpVrPJmYtEIVH_9Y4U3AEKQdq_IKuOMrU) to outline your ideas and get early feedback.]
[Required, use the longer-form [design doc template](https://docs.google.com/document/d/1Mtoui_PP2a9N59NjYHnsvrdJ8t2iKFwIJAx1zRO_I1c) to specify and discuss your design in more detail]

**Comment by yuzisun** [comment]
Agreed on this! @sivanantha321 Can you help on this issue?
