### ISSUE TITLE
Go Coverage action is failing in CI

### ISSUE THREAD

**Issue by sivanantha321** [kserve/kserve#3563]
/kind bug

**What steps did you take and what happened:**
[A clear and concise description of what the bug is.]
https://github.com/kserve/kserve/actions/runs/8509936231/job/23306463027#step:8:12
Run schneegans/dynamic-badges-action@v1.7.0
Error: Failed to get gist: 401 Unauthorized

**What did you expect to happen:**

**What's the InferenceService yaml:**
[To help us debug please run `kubectl get isvc $name -n $namespace -oyaml` and paste the output]

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

**Environment:**

- Istio Version:
- Knative Version:
- KServe Version:
- Kubeflow version:
- Cloud Environment:[k8s_istio/istio_dex/gcp_basic_auth/gcp_iap/aws/aws_cognito/ibm]
- Minikube/Kind version:
- Kubernetes version: (use `kubectl version`):
- OS (e.g. from `/etc/os-release`):

**Comment by spolti** [comment]
Interesting, maybe the GIST_SECRET expired?

**Comment by sivanantha321** [comment]
> Interesting, maybe the GIST_SECRET expired?

Yep and fixed
