### ISSUE TITLE
Support text embedding task in huggingface server

### ISSUE THREAD

**Issue by kevinmingtarja** [kserve/kserve#3572]
/kind feature

**Describe the solution you'd like**

Support text embedding (I think huggingface calls it [Feature Extraction](https://huggingface.co/tasks/feature-extraction)) task in huggingface server. Some examples are [mixedbread-ai/mxbai-embed-large-v1](https://huggingface.co/mixedbread-ai/mxbai-embed-large-v1) and [BAAI/bge-base-en-v1.5](https://huggingface.co/BAAI/bge-base-en-v1.5).

This seems like a pretty common task that people use, mostly to later store these in vector databases, so that they can do nearest neighbor search, or compute similarity between different texts, etc, so I think it'd be a good addition to have.

I have implemented this myself in my fork of kserve, so I'd be happy to contribute a PR for this!

**Anything else you would like to add:**

For reference, here are the supported tasks as of now:
https://github.com/kserve/kserve/blob/f6782431cd0751b3dc504fd51d56da75e6e12027/python/huggingfaceserver/huggingfaceserver/task.py#L18-L30

**Links to the design documents:**
[Optional, start with the short-form [RFC template](https://docs.google.com/document/d/1UcBeLfZ_JMGpVrPJmYtEIVH_9Y4U3AEKQdq_IKuOMrU) to outline your ideas and get early feedback.]
[Required, use the longer-form [design doc template](https://docs.google.com/document/d/1Mtoui_PP2a9N59NjYHnsvrdJ8t2iKFwIJAx1zRO_I1c) to specify and discuss your design in more detail]

**Comment by sivanantha321** [comment]
@kevinmingtarja Your contribution is highly appreciated ! Please feel free to raise a PR.

**Comment by yuzisun** [comment]
@kevinmingtarja are you still on this ?

**Comment by kevinmingtarja** [comment]
> @kevinmingtarja are you still on this ?

sorry i've been postponing this, but i will do this this week.

**Comment by sivanantha321** [comment]
@kevinmingtarja Are you still working on this ?

**Comment by kevinmingtarja** [comment]
Hey @sivanantha321, yeah i just made the PR!

**Comment by bet0x** [comment]
You guys really should integrate @michaelfeil/infinity as yall did with vLLM.

**Comment by papagala** [comment]
Thanks for the awesome work @kevinmingtarja. I just realized this is not yet reflected in the documentation, and it would be great to do so 😄. Else I'm afraid the work will go unnoticed. Having at least one example would be very nice! Do you have time to add an example there? For obvious reasons I belive you are the best suited, if you don't have time I could try.
