### ISSUE TITLE
logger not surfacing the error when failed to send cloud event

### ISSUE THREAD

**Issue by yuzisun** [kserve/kserve#3637]
/kind bug

**What steps did you take and what happened:**
There is a regression for [this PR](https://github.com/kserve/kserve/commit/dffd91c493080b15f1dbc30c36e8e9a128c96f44) that it nuked the error from sending cloud event
https://github.com/kserve/kserve/blob/master/pkg/logger/worker.go#L104

**What did you expect to happen:**

**What's the InferenceService yaml:**
[To help us debug please run `kubectl get isvc $name -n $namespace -oyaml` and paste the output]

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

**Environment:**

- Istio Version:
- Knative Version:
- KServe Version:
- Kubeflow version:
- Cloud Environment:[k8s_istio/istio_dex/gcp_basic_auth/gcp_iap/aws/aws_cognito/ibm]
- Minikube/Kind version:
- Kubernetes version: (use `kubectl version`):
- OS (e.g. from `/etc/os-release`):

**Comment by sivanantha321** [comment]
Fixed in https://github.com/kserve/kserve/pull/3635/files#diff-0d6a3602c8fafb02befb2605603deed05066d158f90acde89cbe9368cdbabf42R114-R127
