### ISSUE TITLE
Release 0.13 Tracking

### ISSUE THREAD

**Issue by yuzisun** [kserve/kserve#3648]
# KServe 0.13.0 release tracking:

RC0 release Date: Will be released in the week of `April 29, 2024`
Release Date: Will be released in the week of `*May 13, 2024*`

## **TIMELINE**
| Week | Start                     | End                         | When | Event (Actual timelines)                                                                                |
| ---- |---------------------------| --------------------------- | ---- | ------------------------------------------------------------------------------------------------------- |
| 0-10  | **Week of  Feb 24, 2024**    | **Week of April 29, 2024**       |      | **Feature Freeze + RC0 Released + Documentation update starts**                                             |
| 12   | May 6, 2024       | May 11, 2024      |      | Testing   + End of documentation                                                                                               |
| 13   | **May 13 2024**  | **May 18, 2024**      |      | **Final release - 0.13.0 released**

**Comment by robertgshaw2-redhat** [comment]
Is the OpenAI completions API going to be included in the release?

**Comment by yuzisun** [comment]
> Is the OpenAI completions API going to be included in the release?

Yes!

**Comment by robertgshaw2-redhat** [comment]
> > Is the OpenAI completions API going to be included in the release?
> 
> Yes!

SGTM! Great for vllm deployments :)
