### ISSUE TITLE
Model Storage For Multi-Node Scaling of Large Models

### ISSUE THREAD

**Issue by robertgshaw2-redhat** [kserve/kserve#3663]
/kind feature

**Describe the solution you'd like**
I work on vLLM and I am making a reference architectures that demonstrate best practices for deploying vLLM within KServe. At the moment, I am focused on recommendations for `ModelStorage`.

Given the size of the models (e.g. 70B Llama is 140GB), download time is quite important for autoscaling scenarios. Additionally, in autoscaling scenarios, we often need to scale up to another GPU node, since the model typically uses an entire node (since we need at 4xA100-80GB just to serve the 70B model which will consume all the gpu resources of a node).

As a result, I am trying to design an architecture that enables me to download a model once and then mount the model to each pod as they pop up. 

I really like the OCI user flow (described at https://kserve.github.io/website/0.12/modelserving/storage/oci/), but I was unsure of whether the model assets can be shared across nodes or just within a single node, as it seems like the modelcar container needs to run on a specific node to be accessed by the `InferenceService`:

> As you can see, the Pod has now one additional container. This container is running the modelcar image and runs a ln -s /proc/$$/root/models /mnt/ command to create a symbolic link on a shared empty volume that is mounted on /mnt in the modelcar container and the serving runtime container. The magic here is the symbolic link over proc filesystem, which is shared among all containers. This is possible on Kubernetes for the container's of a Pod if the field .spec.shareProcessNamespace is set to true, which is the case for all storageUri that leverages the oci:// schema.

So, I was wondering:
- Does the OCI image use flow support caching the model weights across nodes?
- If not, is there any plan to expand this OCI image flow to support this?
- If both no, is the best pathway for something like I am describe to use PVCs with `ReadOnly` access method?

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

**Links to the design documents:**
[Optional, start with the short-form [RFC template](https://docs.google.com/document/d/1UcBeLfZ_JMGpVrPJmYtEIVH_9Y4U3AEKQdq_IKuOMrU) to outline your ideas and get early feedback.]
[Required, use the longer-form [design doc template](https://docs.google.com/document/d/1Mtoui_PP2a9N59NjYHnsvrdJ8t2iKFwIJAx1zRO_I1c) to specify and discuss your design in more detail]

**Comment by yuzisun** [comment]
@robertgshaw2-neuralmagic were you able to manage to load the 70b model using oci storage ?

**Comment by robertgshaw2-redhat** [comment]
@yuzisun i managed to get it working with a 7b model! 

Going to try it again in a multi node setup with this model scale then move onto the 70b

**Comment by robertgshaw2-redhat** [comment]
@yuzisun is oci is the recommended pathway moving forward?

**Comment by yuzisun** [comment]
> @yuzisun is oci is the recommended pathway moving forward?

Not sure if it is best practice to store 130g model in an OCI image, the other alternative solution is to store the model on local NVMe volumes and load the model with PVC.

**Comment by robertgshaw2-redhat** [comment]
That makes sense - I will try both

Just curious: is there a specific model size you recommend for the OCI images?

[The docs](https://kserve.github.io/website/latest/modelserving/storage/oci/) suggest that this OCI pathway was built specifically for the LLM serving use case

**Comment by pavanchhatpar** [comment]
Hey @robertgshaw2-neuralmagic - did you manage to run vLLM with kserve using GPUs spread over multiple nodes?

**Comment by spolti** [comment]
@pavanchhatpar the multi-node support work is under review: https://github.com/kserve/kserve/pull/3972
