### ISSUE TITLE
Update deprecated generate-groups.sh to kube_codegen

### ISSUE THREAD

**Issue by spolti** [kserve/kserve#3667]
/kind bug

```bash
$ make generate
test -s /Users/fspolti/data/dev/sources/kserve/bin/controller-gen || GOBIN=/Users/fspolti/data/dev/sources/kserve/bin go install sigs.k8s.io/controller-tools/cmd/controller-gen@v0.12.0                                                                ─╯
go env -w GOFLAGS=-mod=mod
warning: go env -w GOFLAGS=... does not override conflicting OS environment variable
hack/update-codegen.sh
WARNING: generate-groups.sh is deprecated.
WARNING: Please use k8s.io/code-generator/kube_codegen.sh instead.

WARNING: generate-internal-groups.sh is deprecated.
WARNING: Please use k8s.io/code-generator/kube_codegen.sh instead.

```

**What steps did you take and what happened:**
[A clear and concise description of what the bug is.]

**What did you expect to happen:**

**What's the InferenceService yaml:**
[To help us debug please run `kubectl get isvc $name -n $namespace -oyaml` and paste the output]

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

**Environment:**

- Istio Version:
- Knative Version:
- KServe Version:
- Kubeflow version:
- Cloud Environment:[k8s_istio/istio_dex/gcp_basic_auth/gcp_iap/aws/aws_cognito/ibm]
- Minikube/Kind version:
- Kubernetes version: (use `kubectl version`):
- OS (e.g. from `/etc/os-release`):

**Comment by skonto** [comment]
@spolti hi, I think this was fixed in https://github.com/kserve/kserve/pull/3912.
