### ISSUE TITLE
model with name <inference service name> does not exist.

### ISSUE THREAD

**Issue by VikasAbhishek** [kserve/kserve#3682]
/kind bug

**What steps did you take and what happened:**
I ran the inference service on custom xgboost model that I trained and saved in .joblib extension using the pvc storage option, followed the link 
https://kserve.github.io/website/master/modelserving/storage/pvc/pvc/

I have used the port forward and node port to get the ingress host and port.
Inference service and pods are running fine.
after running the curl command I am getting this error:
*   Trying 127.0.0.1:8080...
* TCP_NODELAY set
* Connected to localhost (127.0.0.1) port 8080 (#0)
> POST /v1/models/xgboost-pvc:predict HTTP/1.1
> Host: xgboost-pvc.default.example.com
> User-Agent: curl/7.68.0
> Accept: */*
> Content-Type: application/json
> Content-Length: 646
>
* upload completely sent off: 646 out of 646 bytes
* Mark bundle as not supporting multiuse
< HTTP/1.1 404 Not Found
< content-length: 55
< content-type: application/json
< date: Mon, 13 May 2024 06:02:43 GMT
< server: istio-envoy
< x-envoy-upstream-service-time: 16
<
* Connection #0 to host localhost left intact
{"error":"Model with name xgboost-pvc does not exist."}

**What did you expect to happen:**
I expected that the curl command will return the predictions.

**What's the InferenceService yaml:**
[To help us debug please run `kubectl get isvc $name -n $namespace -o yaml` and paste the output]

apiVersion: serving.kserve.io/v1beta1
kind: InferenceService
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"serving.kserve.io/v1beta1","kind":"InferenceService","metadata":{"annotations":{},"name":"xgboost-pvc","namespace":"default"},"spec":{"predictor":{"xgboost":{"storageUri":"pvc://task-pv-claim/model/S1-B2-C1_xgboost.joblib"}}}}
  creationTimestamp: "2024-05-10T11:16:48Z"
  finalizers:
  - inferenceservice.finalizers
  generation: 1
  name: xgboost-pvc
  namespace: default
  resourceVersion: "1804889"
  uid: efbe751b-9865-47a3-a84a-501f14bc9618
spec:
  predictor:
    model:
      modelFormat:
        name: xgboost
      name: ""
      resources: {}
      storageUri: pvc://task-pv-claim/model/S1-B2-C1_xgboost.joblib
status:
  address:
    url: http://xgboost-pvc.default.svc.cluster.local
  components:
    predictor:
      address:
        url: http://xgboost-pvc-predictor.default.svc.cluster.local
      latestCreatedRevision: xgboost-pvc-predictor-00001
      latestReadyRevision: xgboost-pvc-predictor-00001
      latestRolledoutRevision: xgboost-pvc-predictor-00001
      traffic:
      - latestRevision: true
        percent: 100
        revisionName: xgboost-pvc-predictor-00001
      url: http://xgboost-pvc-predictor.default.example.com
  conditions:
  - lastTransitionTime: "2024-05-10T11:17:11Z"
    status: "True"
    type: IngressReady
  - lastTransitionTime: "2024-05-10T11:17:11Z"
    severity: Info
    status: "True"
    type: LatestDeploymentReady
  - lastTransitionTime: "2024-05-10T11:17:11Z"
    severity: Info
    status: "True"
    type: PredictorConfigurationReady
  - lastTransitionTime: "2024-05-10T11:17:11Z"
    status: "True"
    type: PredictorReady
  - lastTransitionTime: "2024-05-10T11:17:11Z"
    severity: Info
    status: "True"
    type: PredictorRouteReady
  - lastTransitionTime: "2024-05-10T11:17:11Z"
    status: "True"
    type: Ready
  - lastTransitionTime: "2024-05-10T11:17:11Z"
    severity: Info
    status: "True"
    type: RoutesReady
  modelStatus:
    copies:
      failedCopies: 0
      totalCopies: 1
    states:
      activeModelState: Loaded
      targetModelState: Loaded
    transitionStatus: UpToDate
  observedGeneration: 1
  url: http://xgboost-pvc.default.example.com

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]
when I checked the logs of xgboost predictor pod after running the curl command I am getting this:
2024-05-13 05:16:25.231 1 kserve ERROR [model_not_found_handler():113] Exception:
Traceback (most recent call last):
  File "/prod_venv/lib/python3.9/site-packages/starlette/_exception_handler.py", line 53, in wrapped_app
    await app(scope, receive, sender)
  File "/prod_venv/lib/python3.9/site-packages/starlette/routing.py", line 74, in app
    response = await func(request)
  File "/prod_venv/lib/python3.9/site-packages/fastapi/routing.py", line 299, in app
    raise e
  File "/prod_venv/lib/python3.9/site-packages/fastapi/routing.py", line 294, in app
    raw_response = await run_endpoint_function(
  File "/prod_venv/lib/python3.9/site-packages/fastapi/routing.py", line 191, in run_endpoint_function
    return await dependant.call(**values)
  File "/kserve/kserve/protocol/rest/v1_endpoints.py", line 67, in predict
    model_ready = self.dataplane.model_ready(model_name)
  File "/kserve/kserve/protocol/dataplane.py", line 213, in model_ready
    raise ModelNotFound(model_name)
kserve.errors.ModelNotFound: Model with name xgboost-pvc does not exist.
2024-05-13 05:16:25.232 uvicorn.access INFO:     10.244.2.5:0 1 - "POST /v1/models/xgboost-pvc%3Apredict HTTP/1.1" 404 Not Found
2024-05-13 05:16:25.233 kserve.trace kserve.io.kserve.protocol.rest.v1_endpoints.predict: 0.0017123222351074219
2024-05-13 05:16:25.233 kserve.trace kserve.io.kserve.protocol.rest.v1_endpoints.predict: 0.0017050000001290755

**Environment:**

- Istio Version: 1.19.4
- Knative Version: 1.10.1
- KServe Version: 0.12.1
- Kubeflow version: not installed
- Cloud Environment:[k8s_istio/istio_dex/gcp_basic_auth/gcp_iap/aws/aws_cognito/ibm]
- Minikube/Kind version: kind version 0.22.0
- Kubernetes version: (use `kubectl version`) : Client Version: v1.30.0
Kustomize Version: v5.0.4-0.20230601165947-6ce0bf390ce3
Server Version: v1.29.2

- OS (e.g. from `/etc/os-release`): Distributor ID: Ubuntu
Description:    Ubuntu 20.04.6 LTS
Release:        20.04
Codename:       focal

**Comment by sivanantha321** [comment]
@VikasAbhishek Can you post the response of `http://${Host}:${Port}/v1/models`

**Comment by VikasAbhishek** [comment]
> @VikasAbhishek Can you post the response of `http://${Host}:${Port}/v1/models`

*   Trying 127.0.0.1:8080...
* TCP_NODELAY set
* Connected to localhost (127.0.0.1) port 8080 (#0)
> GET /v1/models HTTP/1.1
> Host: localhost:8080
> User-Agent: curl/7.68.0
> Accept: */*
>
* Mark bundle as not supporting multiuse
< HTTP/1.1 404 Not Found
< date: Mon, 13 May 2024 06:49:27 GMT
< server: istio-envoy
< content-length: 0
<
* Connection #0 to host localhost left intact

**Comment by VikasAbhishek** [comment]
> @VikasAbhishek Can you post the response of `http://${Host}:${Port}/v1/models`

*   Trying 127.0.0.1:8080...
* TCP_NODELAY set
* Connected to localhost (127.0.0.1) port 8080 (#0)
> GET /v1/models HTTP/1.1
> Host: localhost:8080
> User-Agent: curl/7.68.0
> Accept: */*
>
* Mark bundle as not supporting multiuse
< HTTP/1.1 404 Not Found
< date: Mon, 13 May 2024 06:49:27 GMT
< server: istio-envoy
< content-length: 0
<
* Connection #0 to host localhost left intact

**Comment by sivanantha321** [comment]
Have you added Host header ?

**Comment by VikasAbhishek** [comment]
Classification: Confidential
No I run the command curl -v http://${INGRESS_HOST}:${INGRESS_PORT}/v1/models<http://$%7bINGRESS_HOST%7d:$%7bINGRESS_PORT%7d/v1/models>.

**Comment by VikasAbhishek** [comment]
Classification: Confidential
After using host header :
curl -v -H "Host: ${SERVICE_HOSTNAME}" http://${INGRESS_HOST}:${INGRESS_PORT}/v1/models<http://$%7bINGRESS_HOST%7d:$%7bINGRESS_PORT%7d/v1/models>              *   Trying 127.0.0.1:8080...
* TCP_NODELAY set
* Connected to localhost (127.0.0.1) port 8080 (#0)
> GET /v1/models HTTP/1.1
> Host: xgboost-pvc.default.example.com
> User-Agent: curl/7.68.0
> Accept: */*
>
* Mark bundle as not supporting multiuse
< HTTP/1.1 200 OK
< content-length: 13
< content-type: application/json
< date: Mon, 13 May 2024 07:38:51 GMT
< server: istio-envoy
< x-envoy-upstream-service-time: 15
<
* Connection #0 to host localhost left intact

**Comment by sivanantha321** [comment]
@VikasAbhishek The response is not available in your comment, anyways you can verify if the model is ready, and can view the model name. Try using this as the model name for inference . If the response is empty, this may mean that the model is not loaded. In that case please, verify the model server logs.

**Comment by VikasAbhishek** [comment]
Classification: Confidential
I checked with the curl command that my model is not uploading to the models folder like the sklearn-iris example.
curl -v -H "Host: ${SERVICE_HOSTNAME}" -H "Content-Type: application/json" http://${INGRESS_HOST}:${INGRESS_PORT}/v1/models<http://$%7bINGRESS_HOST%7d:$%7bINGRESS_PORT%7d/v1/models>
*   Trying 172.18.0.2:30227...
* TCP_NODELAY set
* Connected to 172.18.0.2 (172.18.0.2) port 30227 (#0)
> GET /v1/models HTTP/1.1
> Host: sklearn-iris.kserve-test.example.com
> User-Agent: curl/7.68.0
> Accept: */*
> Content-Type: application/json
>
* Mark bundle as not supporting multiuse
< HTTP/1.1 200 OK
< content-length: 27
< content-type: application/json
< date: Mon, 13 May 2024 08:46:34 GMT
< server: istio-envoy
< x-envoy-upstream-service-time: 6
<
* Connection #0 to host 172.18.0.2 left intact
{"models":["sklearn-iris"]}
For sklearn-iris example

curl -v -H "Host: ${SERVICE_HOSTNAME}" -H "Content-Type: application/json" http://${INGRESS_HOST}:${INGRESS_PORT}/v1/models<http://$%7bINGRESS_HOST%7d:$%7bINGRESS_PORT%7d/v1/models>
*   Trying 172.18.0.2:30227...
* TCP_NODELAY set
* Connected to 172.18.0.2 (172.18.0.2) port 30227 (#0)
> GET /v1/models HTTP/1.1
> Host: xgboost-pvc.default.example.com
> User-Agent: curl/7.68.0
> Accept: */*
> Content-Type: application/json
>
* Mark bundle as not supporting multiuse
< HTTP/1.1 200 OK
< content-length: 13
< content-type: application/json
< date: Mon, 13 May 2024 08:47:58 GMT
< server: istio-envoy
< x-envoy-upstream-service-time: 9
<
* Connection #0 to host 172.18.0.2 left intact
{"models":[]}
For custom xgboost model v1/models is empty

Can you guide me how to upload my model in the v1/models for pvc storageUri method.

**Comment by sivanantha321** [comment]
@VikasAbhishek As mentioned earlier, the model is not loaded. Please, verify the model server logs and storage initializer logs.

**Comment by fschlz** [comment]
I have a similar issue using the InferenceService on Azure AKS with a MLflow tracked model.

This is the structure of my model directory:
```
└── model
    ├── MLmodel
    ├── conda.yaml
    ├── metadata
    │   ├── MLmodel
    │   ├── conda.yaml
    │   ├── python_env.yaml
    │   └── requirements.txt
    ├── model-settings.json
    ├── model.pkl
    ├── python_env.yaml
    └── requirements.txt
```

I followed the Azure guide [here](https://kserve.github.io/website/0.12/modelserving/storage/azure/azure/#attach-secret-to-a-service-account) and MLflow guide [here](https://kserve.github.io/website/0.10/modelserving/v1beta1/mlflow/v2/#start-the-model-server-locally) but cannot seem to get the InferenceService to deploy correctly.

This is my `model.yml`

```yaml
apiVersion: "serving.kserve.io/v1beta1"
kind: "InferenceService"
metadata:
  name: "wine-classifier"
  namespace: "mlflow-kserve-test"
spec:
  predictor:
    serviceAccountName: sa
    model:
      modelFormat:
        name: mlflow
      protocolVersion: v2
      storageUri: "https://{SA}.blob.core.windows.net/azureml/ExperimentRun/dcid.{RUNID}/model"
```

I tried using `storageUri: "https://{SA}.blob.core.windows.net/azureml/ExperimentRun/dcid.{RUNID}/model/model.pkl"`, but then the service doesn't start properly because it cannot build the environment.

Here are the log outputs from the `kserve-container`:

```logs
Environment tarball not found at '/mnt/models/environment.tar.gz'
Environment not found at './envs/environment'
2024-06-05 14:36:17,236 [mlserver.parallel] DEBUG - Starting response processing loop...
2024-06-05 14:36:17,238 [mlserver.rest] INFO - HTTP server running on http://0.0.0.0:8080
INFO:     Started server process [1]
INFO:     Waiting for application startup.
2024-06-05 14:36:17,267 [mlserver.metrics] INFO - Metrics server running on http://0.0.0.0:8082
2024-06-05 14:36:17,267 [mlserver.metrics] INFO - Prometheus scraping endpoint can be accessed on http://0.0.0.0:8082/metrics
INFO:     Started server process [1]
INFO:     Waiting for application startup.
INFO:     Application startup complete.
2024-06-05 14:36:18,568 [mlserver.grpc] INFO - gRPC server running on http://0.0.0.0:9000
INFO:     Application startup complete.
INFO:     Uvicorn running on http://0.0.0.0:8080 (Press CTRL+C to quit)
INFO:     Uvicorn running on http://0.0.0.0:8082 (Press CTRL+C to quit)
2024/06/05 14:36:19 WARNING mlflow.pyfunc: Detected one or more mismatches between the model's dependencies and the current Python environment:
- mlflow (current: 2.3.1, required: mlflow==2.12.2)
- cloudpickle (current: 2.2.1, required: cloudpickle==3.0.0)
- numpy (current: 1.23.5, required: numpy==1.24.4)
- packaging (current: 23.1, required: packaging==23.2)
- psutil (current: uninstalled, required: psutil==5.9.8)
- pyyaml (current: 6.0, required: pyyaml==6.0.1)
- scikit-learn (current: 1.2.2, required: scikit-learn==1.3.2)
- scipy (current: 1.9.1, required: scipy==1.10.1)
To fix the mismatches, call `mlflow.pyfunc.get_model_dependencies(model_uri)` to fetch the model's environment and install dependencies using the resulting environment file.
2024-06-05 14:36:19,791 [mlserver] INFO - Couldn't load model 'wine-classifier'. Model will be removed from registry.
2024-06-05 14:36:19,791 [mlserver.parallel] ERROR - An error occurred processing a model update of type 'Load'.
Traceback (most recent call last):
File "/opt/conda/lib/python3.8/site-packages/mlserver/parallel/worker.py", line 158, in _process_model_update
await self._model_registry.load(model_settings)
File "/opt/conda/lib/python3.8/site-packages/mlserver/registry.py", line 293, in load
return await self._models[model_settings.name].load(model_settings)
File "/opt/conda/lib/python3.8/site-packages/mlserver/registry.py", line 148, in load
await self._load_model(new_model)
File "/opt/conda/lib/python3.8/site-packages/mlserver/registry.py", line 165, in _load_model
model.ready = await model.load()
File "/opt/conda/lib/python3.8/site-packages/mlserver_mlflow/runtime.py", line 155, in load
self._model = mlflow.pyfunc.load_model(model_uri)
File "/opt/conda/lib/python3.8/site-packages/mlflow/pyfunc/__init__.py", line 582, in load_model
model_meta = Model.load(os.path.join(local_path, MLMODEL_FILE_NAME))
File "/opt/conda/lib/python3.8/site-packages/mlflow/models/model.py", line 468, in load
return cls.from_dict(yaml.safe_load(f.read()))
File "/opt/conda/lib/python3.8/site-packages/mlflow/models/model.py", line 478, in from_dict
model_dict["signature"] = ModelSignature.from_dict(model_dict["signature"])
File "/opt/conda/lib/python3.8/site-packages/mlflow/models/signature.py", line 83, in from_dict
inputs = Schema.from_json(signature_dict["inputs"])
File "/opt/conda/lib/python3.8/site-packages/mlflow/types/schema.py", line 360, in from_json
return cls([read_input(x) for x in json.loads(json_str)])
File "/opt/conda/lib/python3.8/site-packages/mlflow/types/schema.py", line 360, in <listcomp>
return cls([read_input(x) for x in json.loads(json_str)])
File "/opt/conda/lib/python3.8/site-packages/mlflow/types/schema.py", line 358, in read_input
return TensorSpec.from_json_dict(**x) if x["type"] == "tensor" else ColSpec(**x)
TypeError: __init__() got an unexpected keyword argument 'required'
2024-06-05 14:36:19,793 [mlserver] INFO - Couldn't load model 'wine-classifier'. Model will be removed from registry.
2024-06-05 14:36:19,795 [mlserver.parallel] ERROR - An error occurred processing a model update of type 'Unload'.
Traceback (most recent call last):
File "/opt/conda/lib/python3.8/site-packages/mlserver/parallel/worker.py", line 160, in _process_model_update
await self._model_registry.unload_version(
File "/opt/conda/lib/python3.8/site-packages/mlserver/registry.py", line 302, in unload_version
await model_registry.unload_version(version)
File "/opt/conda/lib/python3.8/site-packages/mlserver/registry.py", line 201, in unload_version
model = await self.get_model(version)
File "/opt/conda/lib/python3.8/site-packages/mlserver/registry.py", line 237, in get_model
raise ModelNotFound(self._name, version)
mlserver.errors.ModelNotFound: Model wine-classifier not found
2024-06-05 14:36:19,796 [mlserver] ERROR - Some of the models failed to load during startup!
Traceback (most recent call last):
File "/opt/conda/lib/python3.8/site-packages/mlserver/server.py", line 125, in start
await asyncio.gather(
File "/opt/conda/lib/python3.8/site-packages/mlserver/registry.py", line 293, in load
return await self._models[model_settings.name].load(model_settings)
File "/opt/conda/lib/python3.8/site-packages/mlserver/registry.py", line 148, in load
await self._load_model(new_model)
File "/opt/conda/lib/python3.8/site-packages/mlserver/registry.py", line 161, in _load_model
model = await callback(model)
File "/opt/conda/lib/python3.8/site-packages/mlserver/parallel/registry.py", line 152, in load_model
loaded = await pool.load_model(model)
File "/opt/conda/lib/python3.8/site-packages/mlserver/parallel/pool.py", line 74, in load_model
await self._dispatcher.dispatch_update(load_message)
File "/opt/conda/lib/python3.8/site-packages/mlserver/parallel/dispatcher.py", line 123, in dispatch_update
return await asyncio.gather(
File "/opt/conda/lib/python3.8/site-packages/mlserver/parallel/dispatcher.py", line 138, in _dispatch_update
return await self._dispatch(worker_update)
File "/opt/conda/lib/python3.8/site-packages/mlserver/parallel/dispatcher.py", line 146, in _dispatch
return await self._wait_response(internal_id)
File "/opt/conda/lib/python3.8/site-packages/mlserver/parallel/dispatcher.py", line 152, in _wait_response
inference_response = await async_response
mlserver.parallel.errors.WorkerError: builtins.TypeError: __init__() got an unexpected keyword argument 'required'
2024-06-05 14:36:19,796 [mlserver.parallel] INFO - Waiting for shutdown of default inference pool...
2024-06-05 14:36:19,997 [mlserver.parallel] INFO - Shutdown of default inference pool complete
2024-06-05 14:36:19,997 [mlserver.grpc] INFO - Waiting for gRPC server shutdown
2024-06-05 14:36:20,001 [mlserver.grpc] INFO - gRPC server shutdown complete
INFO:     Shutting down
INFO:     Shutting down
INFO:     Waiting for application shutdown.
INFO:     Waiting for application shutdown.
INFO:     Application shutdown complete.
INFO:     Finished server process [1]
INFO:     Application shutdown complete.
INFO:     Finished server process [1]
```

It manages to create the environment, but cannot load the model.

Calling `mlflow.pyfunc.load_model(model_uri)` locally, loads the model.
And testing with `mlserver start .` was also successful.

Deployments of real-time endpoints of the tracked model in Azure Machine Learning also work, but I need an alternative to deploy on prem.

Any help would be much appreciated.

**Comment by dr3s** [comment]
I have a similar issue.  pretty sure it's due to the dependencies not loading for the model but the error is less than helpful.  In my case, I'm using a private pypi so thinking that's not working.

**Comment by jagveers** [comment]
@fschlz I am also facing the same issue. Are you able to figure this out?

This is my log - 

```
Environment tarball not found at '/mnt/models/environment.tar.gz'
Environment not found at './envs/environment'
2024-09-11 20:21:03,209 [mlserver.parallel] DEBUG - Starting response processing loop...
2024-09-11 20:21:03,211 [mlserver.rest] INFO - HTTP server running on http://0.0.0.0:8080
INFO:     Started server process [1]
INFO:     Waiting for application startup.
2024-09-11 20:21:03,238 [mlserver.metrics] INFO - Metrics server running on http://0.0.0.0:8082
2024-09-11 20:21:03,291 [mlserver.metrics] INFO - Prometheus scraping endpoint can be accessed on http://0.0.0.0:8082/metrics
INFO:     Started server process [1]
INFO:     Waiting for application startup.
INFO:     Application startup complete.
2024-09-11 20:21:05,197 [mlserver.grpc] INFO - gRPC server running on http://0.0.0.0:9000
INFO:     Application startup complete.
INFO:     Uvicorn running on http://0.0.0.0:8080 (Press CTRL+C to quit)
INFO:     Uvicorn running on http://0.0.0.0:8082 (Press CTRL+C to quit)
2024/09/11 20:21:06 WARNING mlflow.pyfunc: Detected one or more mismatches between the model's dependencies and the current Python environment:
 - mlflow (current: 2.3.1, required: mlflow==2.14.2)
 - accelerate (current: uninstalled, required: accelerate==0.32.1)
 - autonomize-model-sdk (current: uninstalled, required: autonomize-model-sdk==0.1.1.dev3)
 - click (current: 8.1.3, required: click==8.1.7)
 - cloudpickle (current: 2.2.1, required: cloudpickle==3.0.0)
 - datasets (current: 2.12.0, required: datasets==2.20.0)
 - dateparser (current: uninstalled, required: dateparser==1.2.0)
 - httpx (current: uninstalled, required: httpx==0.27.2)
 - nlpreprocessing (current: uninstalled, required: nlpreprocessing==1.0.1)
 - numpy (current: 1.23.5, required: numpy==1.26.4)
 - packaging (current: 23.1, required: packaging==24.1)
 - pandas (current: 2.0.1, required: pandas==2.2.2)
 - protobuf (current: 3.20.3, required: protobuf==4.25.4)
 - pyarrow (current: 11.0.0, required: pyarrow==15.0.2)
 - python-dotenv (current: 1.0.0, required: python-dotenv==1.0.1)
 - pytz (current: 2023.3, required: pytz==2024.1)
 - pyyaml (current: 6.0, required: pyyaml==6.0.2)
 - requests (current: 2.28.2, required: requests==2.32.3)
 - scikit-learn (current: 1.2.2, required: scikit-learn==1.5.1)
 - scipy (current: 1.9.1, required: scipy==1.14.1)
 - transformers (current: 4.28.1, required: transformers==4.42.3)
To fix the mismatches, call `mlflow.pyfunc.get_model_dependencies(model_uri)` to fetch the model's environment and install dependencies using the resulting environment file.
2024/09/11 20:21:06 WARNING mlflow.pyfunc: The version of Python that the model was saved in, `Python 3.11.9`, differs from the version of Python that is currently running, `Python 3.8.16`, and may be incompatible
2024/09/11 20:21:06 WARNING mlflow.pyfunc: The version of CloudPickle that was used to save the model, `CloudPickle 3.0.0`, differs from the version of CloudPickle that is currently running, `CloudPickle 2.2.1`, and may be incompatible
2024-09-11 20:21:06,985 [mlserver] INFO - Couldn't load model 'cllm-v2'. Model will be removed from registry.
2024-09-11 20:21:06,985 [mlserver.parallel] ERROR - An error occurred processing a model update of type 'Load'. 
```

here is my inference - 

`apiVersion: "serving.kserve.io/v1beta1"
kind: "InferenceService"
metadata:
  name: "cllm"
  namespace: "modelhub"
  labels:
    azure.workload.identity/use: "true"
spec:
  predictor:
    model:
      modelFormat:
        name: mlflow
      protocolVersion: v2
      storageUri: "https://autonomizestorageaccount.blob.core.windows.net/mlflow/26/596c868bc1b94b2597750afb425dfbc4/artifacts/cllm_v2"
`

I am able to run this using - 

`mlflow.pyfunc.load_model(model_uri)`

**Comment by sivanantha321** [comment]
@jagveers @fschlz This is due the dependency mismatch with your environment and model. This is not related to KServe.

**Comment by dblane-digicatapult** [comment]
I have a similar issue, I was led to believe that Kserve would install the dependencies if we suppled the `conda.yaml`, `python_env.yaml` or `requirements.txt` @sivanantha321 are you saying this is not the case and the only way to do this with kserve is to either a) bundle the deps into an `environment.tar.gz` using mlflow/conda OR b) supply our own model serving container with the deps already bundled?

**Comment by sivanantha321** [comment]
@dblane-digicatapult KServe didn't install dependencies for you but the the underlying MLServer does. https://mlserver.readthedocs.io/en/stable/examples/conda/README.html. You have to verify if the runtime is using MLServer and if it recognises the environment or not.
