### ISSUE TITLE
Allow PVC Model Mount in ReadWrite Mode

### ISSUE THREAD

**Issue by supertetelman** [kserve/kserve#3687]
/kind feature

I would like to add an additional flag to specify a volume to be ReadWrite or ReadOnly.

Currently the implementation for PVC model stores [here](https://github.com/kserve/kserve/blob/master/pkg/webhook/admission/pod/storage_initializer_injector.go#L255) expects that a PV containing model files is always mounted to a `ServingRuntime` as `ReadOnly`. I have a use case where my server has some internal logic that I would like to dynamically download model components and cache them to the local PV.

As an alternative, this could be a use case for the new model-car, but my download logic is somewhat complex and I need to run the logic in many locations outside of KServe, so keeping the logic inside the container works best for me. This may also be a use case for a custom StorageContainer, but I think the change is small enough and common enough that other users might find this feature useful.

**Design proposal:**
Add a readonly flag under storageUri:
```
storageUri: "pvc://pvc-name/model-store/" 
  readonly: true # default true
```

See Slack for more details: https://cloud-native.slack.com/archives/C06AH2C3K8B/p1714883766854429

**Comment by lizzzcai** [comment]
do you think adding a configuration `readOnly` [here](https://github.com/kserve/kserve/blob/master/config/configmap/inferenceservice.yaml#L84-L87) will help here instead of adding a new parameter in the spec? so you can overwrite the value to `False`.

**Comment by lizzzcai** [comment]
In addition, current KServe using [emptyDir](https://github.com/kserve/kserve/blob/master/pkg/webhook/admission/pod/storage_initializer_injector.go#L318) as share volume between Storage initializer and main container, if we have option to configure a PVC to it (and storage initializer support skip the model download if model already exists), in this case model will be only downloaded once. Do you think it will be helpful as well?  what do you think? @yuzisun

**Comment by spolti** [comment]
> do you think adding a configuration readOnly [here](https://github.com/kserve/kserve/blob/master/config/configmap/inferenceservice.yaml#L84-L87) will help here instead of adding a new parameter in the spec? so you can overwrite the value to False.


this option sounds like you can provide your own PVC, in theory you can configure it as RWX, right? Or am I missing something?



> In addition, current KServe using [emptyDir](https://github.com/kserve/kserve/blob/master/pkg/webhook/admission/pod/storage_initializer_injector.go#L318) as share volume between Storage initializer and main container, if we have option to configure a PVC to it (and storage initializer support skip the model download if model already exists), in this case model will be only downloaded once. Do you think it will be helpful as well? what do you think? @yuzisun

Isn't it the purpose of the model-car as well?

**Comment by terrytangyuan** [comment]
>In addition, current KServe using [emptyDir](https://github.com/kserve/kserve/blob/master/pkg/webhook/admission/pod/storage_initializer_injector.go#L318) as share volume between Storage initializer and main container, if we have option to configure a PVC to it (and storage initializer support skip the model download if model already exists), in this case model will be only downloaded once. Do you think it will be helpful as well? what do you think?

I think this would be very useful to have. We recently just had OOM issue because of this.

**Comment by yuzisun** [comment]
> > In addition, current KServe using [emptyDir](https://github.com/kserve/kserve/blob/master/pkg/webhook/admission/pod/storage_initializer_injector.go#L318) as share volume between Storage initializer and main container, if we have option to configure a PVC to it (and storage initializer support skip the model download if model already exists), in this case model will be only downloaded once. Do you think it will be helpful as well? what do you think?
> 
> I think this would be very useful to have. We recently just had OOM issue because of this.

How did you get OOM ?

**Comment by terrytangyuan** [comment]
>How did you get OOM ?

When we start having more replicas, it creates disk pressure on the node and also the pods are killed due to OOM killed as finite amount of RAM is allocated to emptyDir volume.

**Comment by yuzisun** [comment]
> > How did you get OOM ?
> 
> When we start having more replicas, it creates disk pressure on the node and also the pods are killed due to OOM killed as finite amount of RAM is allocated to emptyDir volume.


EmptyDir should by default use ephemeral storage so if you do not set the resource limit then it can potentially create the disk pressure issue.

**Comment by yuzisun** [comment]
> In addition, current KServe using [emptyDir](https://github.com/kserve/kserve/blob/master/pkg/webhook/admission/pod/storage_initializer_injector.go#L318) as share volume between Storage initializer and main container, if we have option to configure a PVC to it (and storage initializer support skip the model download if model already exists), in this case model will be only downloaded once. Do you think it will be helpful as well? what do you think? @yuzisun

Interesting idea, sounds like you want to do lazy model caching on local PVC, if the model does not exist on the local PVC then you download from the cloud storage otherwise you directly load from PVC.

**Comment by supertetelman** [comment]
> > In addition, current KServe using [emptyDir](https://github.com/kserve/kserve/blob/master/pkg/webhook/admission/pod/storage_initializer_injector.go#L318) as share volume between Storage initializer and main container, if we have option to configure a PVC to it (and storage initializer support skip the model download if model already exists), in this case model will be only downloaded once. Do you think it will be helpful as well? what do you think? @yuzisun
> 
> Interesting idea, sounds like you want to do lazy model caching on local PVC, if the model does not exist on the local PVC then you download from the cloud storage otherwise you directly load from PVC.

That's exactly what I am trying to do.

And yes, I have encountered Disk Pressure issues as well when downloading larger models from an S3 bucket, having that download go directly to a PVC would help even if done out-of-scope from this local PVC caching functionality.

In many of the clusters I am deploying to, I have high-speed shared storage backing this PVC. So I am able to download from the Internet (or a local in-cluster object store) once, cache it onto the high-speed storage, and then mount that same PV to all similar pods launching the model or in the same auto-scaling group. Not having to download each time helps with the startup times and supports some of the air-gapped environments I am working in better.

In the workflow I imagine, I anticipate there may be use cases in a cluster where RW and where RO make sense. Having the setting make exist globally would be better for me, but having it in the spec makes the most sense in the workflows I have in mind. Essentially I expect that in some cases a user might expect the lazy local cache as described above and keep it RW, but in some cases they may be forced by security to only use what has been validated and must mount a RO volume.

**Comment by lizzzcai** [comment]
> do you think adding a configuration readOnly [here](https://github.com/kserve/kserve/blob/master/config/configmap/inferenceservice.yaml#L84-L87) will help here instead of adding a new parameter in the spec? so you can overwrite the value to False.
> 
> this option sounds like you can provide your own PVC, in theory you can configure it as RWX, right? Or am I missing something?

Hi @spolti , The PVC can be RWX but when it is mounted to main container, it is [ready-only](https://github.com/kserve/kserve/blob/master/pkg/webhook/admission/pod/storage_initializer_injector.go#L364), so application can only read data from `/mnt/models`.


> In addition, current KServe using [emptyDir](https://github.com/kserve/kserve/blob/master/pkg/webhook/admission/pod/storage_initializer_injector.go#L318) as share volume between Storage initializer and main container, if we have option to configure a PVC to it (and storage initializer support skip the model download if model already exists), in this case model will be only downloaded once. Do you think it will be helpful as well? what do you think? @yuzisun
> 
> Isn't it the purpose of the model-car as well?

from my understanding model-car is mainly for models in [oci image](https://kserve.github.io/website/master/modelserving/storage/oci/#using-modelcars), and it can be cached in the same node only. 
The idea here can utilize the feature in storage initializer to download models from different storage (s3, gcs, az, hdfs etc) and if the PVC is a NFS, the model can be shared in multiple nodes as well.

**Comment by lizzzcai** [comment]
> Interesting idea, sounds like you want to do lazy model caching on local PVC, if the model does not exist on the local PVC then you download from the cloud storage otherwise you directly load from PVC.

Yes, this is something I want to achieve. And we should provide this option out of the emptyDir, especially for large model.

If the option of using PVC as the share volume can solve the issue, I will prefer to keep the pattern of storage initializer to write the data to the volume and the main container only read the data, as it is a good pratice. However I have no objection to provide an option as well, instead of having it in spec, how about using annotation like `storage.kserve.io/readyOnly: false`?  @supertetelman

**Comment by supertetelman** [comment]
Having an annotation like that in the `InferenceService` would be perfect for me.

**Comment by terrytangyuan** [comment]
@yuzisun Our team would like to pick this up but we need to agree on an approach. What do you think about the following?

When `storage.kserve.io/readyonly: false`  appears in the ISVC annotation, we set the `readOnly`  field in the  `/mnt/models`  volumeMount to be `false`. Otherwise, if it's true or unset, we'll default to `readOnly` to be consistent with the current behavior (although this is the opposite of the default in `VolumeMount`).

**Comment by supertetelman** [comment]
That is the opposite of `VolumeMount`, but it retains backwards compatibility and enforces a more secured default option (`ReadOnly`). I'd be very happy with that design.

**Comment by yuzisun** [comment]
> That is the opposite of `VolumeMount`, but it retains backwards compatibility and enforces a more secured default option (`ReadOnly`). I'd be very happy with that design.

The flag is ok, but what happens when multiple pods scheduled to the same node and both try to write the model? You can set the PV access mode to ReadWriteOnce but does other pods wait for the writing pod to finish downloading the model? Just want to understand the behavior in this case.

**Comment by supertetelman** [comment]
In my case, there will be basic logic inside my inference application that creates a lockfile to prevent multiple pod replicas from writing at the same time. There will also be several workflows that will likely end up in `readonly: False` only being set for `isvc` that are intended to not scale or run while services are writing.

**Comment by terrytangyuan** [comment]
Yes, I think it's the user's responsibilities to provide additional logic to handle that.

**Comment by lizzzcai** [comment]
> but what happens when multiple pods scheduled to the same node and both try to write the model? 

If the user provides their own logic download model (custom container), then the user should handle it properly by additional logic.

What if the user is using storage initalizer and RWX PV? Maybe storage initializer should have additional logic to prevent multiple pod replicas from writing at the same time as well.

**Comment by supertetelman** [comment]
That makes sense, but wouldn't that logic be covered in a different feature request specific to the initializer or by the person writing the custom storage initializer?

**Comment by lizzzcai** [comment]
> That makes sense, but wouldn't that logic be covered in a different feature request specific to the initializer or by the person writing the custom storage initializer?

Yes, it should be covered in a different issue as a refinement, just to bring it up for future reference.
