### ISSUE TITLE
error setting up interface service

### ISSUE THREAD

**Issue by LOADBC** [kserve/kserve#3732]
i am new to kserve , i am following the guide from 
https://kserve.github.io/website/latest/get_started/first_isvc/  

kubectl apply -n kserve-test -f - <<EOF
apiVersion: "serving.kserve.io/v1beta1"
kind: "InferenceService"
metadata:
  name: "sklearn-iris"
spec:
  predictor:
    model:
      modelFormat:
        name: sklearn
      storageUri: "gs://kfserving-examples/models/sklearn/1.0/model"

and i am getting the error

error: resource mapping not found for name: "sklearn-iris" namespace: "" from "STDIN": no matches for kind "InferenceService" in version "serving.kserve.io/v1beta1"
ensure CRDs are installed first

**Comment by israel-hdez** [comment]
The CRD does not look installed. What steps did you follow to install KServe?

**Comment by LOADBC** [comment]
thanks you i installed the CRDs now its working
