### ISSUE TITLE
stop using `gcr.io/kubebuilder/kube-rbac-proxy` before `18 March 2025` (image being deleted)

### ISSUE THREAD

**Issue by thesuperzapper** [kserve/kserve#3734]
Currently, we make use of the `gcr.io/kubebuilder/kube-rbac-proxy` image which is __going to become unavailable__ on or after `18 March 2025`.

As this will break every KServe instance currently deployed, we MUST create a migration plan and help users become aware of what they must do.

You can see the notice about deprecation of all `gcr.io` repos in a few places:

- [Notice from Kubebuilder](https://book.kubebuilder.io/reference/metrics)
- [Notice on GCR Repo](https://console.cloud.google.com/gcr/images/kubebuilder/GLOBAL/kube-rbac-proxy)
- [Notice from Google](https://cloud.google.com/artifact-registry/docs/transition/prepare-gcr-shutdown)

To fix new versions of KServe, we either need to remove our dependency on `gcr.io/kubebuilder/kube-rbac-proxy` or migrate to the direct replacement [`brancz/kube-rbac-proxy`](https://github.com/brancz/kube-rbac-proxy), see [__this notice__](https://book.kubebuilder.io/reference/metrics) on the Kubebuilder docs for more info.

__NOTE:__ we should also probably ask Google to redirect some of the critical `gcr.io` images after that date, to avoid breaking legacy systems which fail to be updated in time.

**Comment by thesuperzapper** [comment]
@yuzisun @sivanantha321 @johnugeorge I just want to bring this critical issue to your attention, as it will break every KServe deployment on `18 March 2025`.

**Comment by philipp1992** [comment]
Hi,
i have successfully tested the kube-rbac-proxy from quay.io/brancz/kube-rbac-proxy. Can you please update the kserve deployment to use this image instead of the outdated kubebuilder version?
Thanks!

**Comment by sivanantha321** [comment]
Updated as part of #3867
