### ISSUE TITLE
Predict vs Predict Proba

### ISSUE THREAD

**Issue by csteegz** [kserve/kserve#374]
Have it been considered to support predict_proba for Sklearn and SGBoost in addition to predict? Will that be considered for the V2 API?

**Comment by ellis-bigelow** [comment]
We will definitely take this into consideration. Thank you!

**Comment by ellis-bigelow** [comment]
Hey Colin,
Following up on this. Could you outline your usecase for predict_proba vs predict? It this something you'd need to configure at request time (i.e., send both types to the same endpoint) or something we could configure at deploy time.
