### ISSUE TITLE
protobuf version conflict while trying to integrate with kfp

### ISSUE THREAD

**Issue by SaiKireeti2905** [kserve/kserve#3742]
/kind feature

**Describe the solution you'd like**
While trying to use KFP version 2.6.0 for parallel pipelines that includes a step for training a model and then a step that deploys the trained model using KServe version 0.13.0, a custom component or container step that interacts with KServe APIs to deploy or update an InferenceService. Facing issues with protobuf version, as kfp 2.6.0 depends on protobuf<5 and >=4.21.1 where as kserve 0.13.0 depends on protobuf<4.0.0 and >=3.19.0.

With next future stable release of kserve, expecting protobuf version to be upgraded to >=4.21.1 as this is most compactable version with most ML modules.

**Comment by sivanantha321** [comment]
duplicate #3730

**Comment by sivanantha321** [comment]
Will be resolved by #3751

**Comment by yuzisun** [comment]
@SaiKireeti2905 does kfp plan to support protobuf version 5 ?

**Comment by sivanantha321** [comment]
resolved by #3881
