### ISSUE TITLE
Client fails to list clusterservingruntimes

### ISSUE THREAD

**Issue by tylerhyang** [kserve/kserve#3744]
/kind bug

**What steps did you take and what happened:**
Using the v1alpha1 go client, I am using the ClusterServingruntime list functionality to retrieve the Clusterservingruntimes in the cluster.  When the function is called, the response that I am getting back is nil, while there are three existing clusterservingruntimes in my cluster.
go code being called:
```
availableRuntimes, err := clients.KServe.V1Alpha1.ClusterServingRuntimes("").List(ctx, v1.ListOptions{})
fmt.Println(map[string]interface{}{"available runtimes": availableRuntimes})
```
response being received:
```
{"available runtimes":{"metadata":{},"items":null}}
```
existing clusterservingruntimes in the cluster:
```
> kubectl get clusterservingruntimes
NAME                    DISABLED   MODELTYPE                CONTAINERS         AGE
runtime1                              type1                 kserve-container   16h
runtime2                              type2                 kserve-container   24h
runtime3                              type3                 kserve-container   24h
```

**What did you expect to happen:**
I am expecting to get a list of clusterservingruntimes items back from the go client

**Anything else you would like to add:**
Could it be related to namespacing? clusterservingruntimes are cluster scoped resources so I don't know if there should be a namespace when instantiating the getter

**Environment:**

- Istio Version: 1.19
- Knative Version: 1.11
- KServe Version: 0.11.2
- Kubeflow version: N/A
- Cloud Environment: Azure/AWS
- Kubernetes version: (use `kubectl version`): 1.28

**Comment by spolti** [comment]
You could take a look on how it is done on kserve, e.g.: https://github.com/kserve/kserve/blob/master/pkg/webhook/admission/servingruntime/servingruntime_webhook.go#L97

**Comment by tylerhyang** [comment]
Ahh found the issue.  Didn't handle the error properly and didn't add the clusterservingruntime to the Cluster Roles
