### ISSUE TITLE
Can't find version compatibility matrix for KServe

### ISSUE THREAD

**Issue by rosemorozenkova** [kserve/kserve#3763]
/kind bug

**What steps did you take and what happened:**
I am trying to find compatibility matrix for KServe + K8S + KNative.

There is this compatibility matrix: 
https://kserve.github.io/website/latest/admin/serverless/serverless/#recommended-version-matrix

But there is no information how to choose KServe version itself.

Please help!

**Comment by sivanantha321** [comment]
You are viewing `0.13` release docs. So it is meant for kserve 0.13.
![Screenshot from 2024-06-26 14-18-56](https://github.com/kserve/kserve/assets/90966311/45554782-3d46-4036-a1c2-73e81abe4f28)

**Comment by rosemorozenkova** [comment]
@sivanantha321 thank you!

So the minimum supported K8S version for current KServe version (0.13) is the one that specified on that matrix (1.27)?

**Comment by rosemorozenkova** [comment]
UPD: Ah, I see:
> Kubernetes 1.22 is the minimally required version and please check the following recommended Knative, Istio versions for the corresponding Kubernetes version.

**Comment by sivanantha321** [comment]
Closing this issue. Please feel free to open a new one.
