### ISSUE TITLE
Make inference to models using Istio and keycloak avoiding session cookies

### ISSUE THREAD

**Issue by acardoco** [kserve/kserve#3766]
/kind feature

Hi!

I recently read the documentation on making inference predictions using Istio-Dex from the official repository [here](https://github.com/kserve/kserve/tree/master/docs/samples/istio-dex).

As an external user of a platform (e.g., I've deployed a Kubeflow + KServe environment in my Kubernetes cluster), how can I make requests to my InferenceService (using VirtualService from Istio and IngressRoute from Traefik) and avoid scraping cookies? Are there any documents or tutorials on how to properly use Bearer tokens instead of cookies for authentication?

Thanks!

**Comment by sivanantha321** [comment]
There is already an example in the docs which uses kubernetes jwt tokens. Better approach would be using oauth2-proxy which is recently included in kubeflow 1.9

**Comment by acardoco** [comment]
I’ve checked it! I was verifying the kserve version for my Kubeflow v1.7.0 setup. 

EDIT: i found a solution for my problem with keycloak. This issue can be closed, thanks!
