### ISSUE TITLE
Failed to start model server: integer division or modulo by zero

### ISSUE THREAD

**Issue by hyder** [kserve/kserve#3769]
/kind bug

**What steps did you take and what happened:**
Deployed a model as documented in https://kserve.github.io/website/0.13/modelserving/v1beta1/llm/huggingface/text_generation/#serve-the-hugging-face-llm-model-using-vllm-backend

**What did you expect to happen:**
Model successfully deployed like the basic sklearn-iris model: https://kserve.github.io/website/0.13/get_started/first_isvc/#run-your-first-inferenceservice

**What's the InferenceService yaml:**
kubectl get isvc
NAME                 URL   READY     PREV   LATEST   PREVROLLEDOUTREVISION   LATESTREADYREVISION   AGE
huggingface-llama3         Unknown                                                                 7m14s

**Anything else you would like to add:**
sklearn-iris basic example works fine. 

pod log:

```
/prod_venv/lib/python3.10/site-packages/huggingface_hub/file_download.py:1132: FutureWarning: `resume_download` is deprecated and will be removed in version 1.0.0. Downloads always resume when possible. If you want to force a new download, use `force_download=True`.
  warnings.warn(
2024-07-01 07:28:04.488 1 kserve ERROR [__main__.py:<module>():254] Failed to start model server: integer division or modulo by zero
```

**Environment:**

- Istio Version: 1.21.1
- Knative Version: 1.14.0
- KServe Version: 0.13.0
- Kubeflow version:
- Cloud Environment: Oracle
- Minikube/Kind version:
- Kubernetes version: 1.29.1
- OS (e.g. from `/etc/os-release`): Oracle Linux 8.9

**Comment by sivanantha321** [comment]
@hyder Do you have a GPU ?

**Comment by hyder** [comment]
I do but I didn't use it here.

**Comment by hyder** [comment]
This is my isvc definition:

```
apiVersion: serving.kserve.io/v1beta1
kind: InferenceService
metadata:
  name: huggingface-llama3
  namespace: kserve-test
spec:
  predictor:
    model:
      modelFormat:
        name: huggingface
      args:
      - --model_name=llama3
      - --model_id=meta-llama/meta-llama-3-8b-instruct
      env:
      - name: HF_TOKEN
        value: "hf_******************************"
      resources:
        limits:
          cpu: "20"
          memory: 40Gi
        requests:
          cpu: "20"
          memory: 40Gi

**Comment by sivanantha321** [comment]
> I do but I didn't use it here.

By default generative LLMs are deployed with `vLLM` backend which requires GPU. If you do not have GPU, Please use `--backend=huggingface`

**Comment by hyder** [comment]
With huggingface backend, it works now. Thanks a lot.

I'll also try with a GPU and let you know how I go.

**Comment by hyder** [comment]
Hi, 

When using the vLLM backend, I ran into the following error:

```
(RayWorkerWrapper pid=762) ERROR 07-01 11:05:45 worker_base.py:145] Error executing method init_device. This might cause deadlock in distributed execution.
(RayWorkerWrapper pid=762) ERROR 07-01 11:05:45 worker_base.py:145] Traceback (most recent call last):
(RayWorkerWrapper pid=762) ERROR 07-01 11:05:45 worker_base.py:145]   File "/prod_venv/lib/python3.10/site-packages/vllm/worker/worker_base.py", line 137, in execute_method
(RayWorkerWrapper pid=762) ERROR 07-01 11:05:45 worker_base.py:145]     return executor(*args, **kwargs)
(RayWorkerWrapper pid=762) ERROR 07-01 11:05:45 worker_base.py:145]   File "/prod_venv/lib/python3.10/site-packages/vllm/worker/worker.py", line 111, in init_device
(RayWorkerWrapper pid=762) ERROR 07-01 11:05:45 worker_base.py:145]     init_worker_distributed_environment(self.parallel_config, self.rank,
(RayWorkerWrapper pid=762) ERROR 07-01 11:05:45 worker_base.py:145]   File "/prod_venv/lib/python3.10/site-packages/vllm/worker/worker.py", line 305, in init_worker_distributed_environment
(RayWorkerWrapper pid=762) ERROR 07-01 11:05:45 worker_base.py:145]     pynccl_utils.init_process_group(
(RayWorkerWrapper pid=762) ERROR 07-01 11:05:45 worker_base.py:145]   File "/prod_venv/lib/python3.10/site-packages/vllm/distributed/device_communicators/pynccl_utils.py", line 43, in init_process_group
(RayWorkerWrapper pid=762) ERROR 07-01 11:05:45 worker_base.py:145]     logger.info("vLLM is using nccl==%s", ncclGetVersion())
(RayWorkerWrapper pid=762) ERROR 07-01 11:05:45 worker_base.py:145] NameError: name 'ncclGetVersion' is not defined
```

As a workaround, I added the following environment variable to the manifest:

```
      - name: VLLM_NCCL_SO_PATH
        value: /prod_venv/lib/python3.10/site-packages/nvidia/nccl/lib/libnccl.so.2
```

Thanks again.

**Comment by sivanantha321** [comment]
> Hi,
> 
> When using the vLLM backend, I ran into the following error:
> 
> ```
> (RayWorkerWrapper pid=762) ERROR 07-01 11:05:45 worker_base.py:145] Error executing method init_device. This might cause deadlock in distributed execution.
> (RayWorkerWrapper pid=762) ERROR 07-01 11:05:45 worker_base.py:145] Traceback (most recent call last):
> (RayWorkerWrapper pid=762) ERROR 07-01 11:05:45 worker_base.py:145]   File "/prod_venv/lib/python3.10/site-packages/vllm/worker/worker_base.py", line 137, in execute_method
> (RayWorkerWrapper pid=762) ERROR 07-01 11:05:45 worker_base.py:145]     return executor(*args, **kwargs)
> (RayWorkerWrapper pid=762) ERROR 07-01 11:05:45 worker_base.py:145]   File "/prod_venv/lib/python3.10/site-packages/vllm/worker/worker.py", line 111, in init_device
> (RayWorkerWrapper pid=762) ERROR 07-01 11:05:45 worker_base.py:145]     init_worker_distributed_environment(self.parallel_config, self.rank,
> (RayWorkerWrapper pid=762) ERROR 07-01 11:05:45 worker_base.py:145]   File "/prod_venv/lib/python3.10/site-packages/vllm/worker/worker.py", line 305, in init_worker_distributed_environment
> (RayWorkerWrapper pid=762) ERROR 07-01 11:05:45 worker_base.py:145]     pynccl_utils.init_process_group(
> (RayWorkerWrapper pid=762) ERROR 07-01 11:05:45 worker_base.py:145]   File "/prod_venv/lib/python3.10/site-packages/vllm/distributed/device_communicators/pynccl_utils.py", line 43, in init_process_group
> (RayWorkerWrapper pid=762) ERROR 07-01 11:05:45 worker_base.py:145]     logger.info("vLLM is using nccl==%s", ncclGetVersion())
> (RayWorkerWrapper pid=762) ERROR 07-01 11:05:45 worker_base.py:145] NameError: name 'ncclGetVersion' is not defined
> ```
> 
> As a workaround, I added the following environment variable to the manifest:
> 
> ```
>       - name: VLLM_NCCL_SO_PATH
>         value: /prod_venv/lib/python3.10/site-packages/nvidia/nccl/lib/libnccl.so.2
> ```
> 
> Thanks again.

This is fixed in master
