### ISSUE TITLE
Remove ray dependency for the storage-initializer

### ISSUE THREAD

**Issue by mkumatag** [kserve/kserve#3794]
/kind bug

**What steps did you take and what happened:**

Rightnow storage-initializer installs ray as a prerequisite because the kserve module imports but just for the storage-initializer module we don't need ray package. Following patch proves that:

```
[root@mkumatag-x86-fedora python]# git diff kserve/kserve/__init__.py
diff --git a/python/kserve/kserve/__init__.py b/python/kserve/kserve/__init__.py
index 638bacbc..74658fa1 100644
--- a/python/kserve/kserve/__init__.py
+++ b/python/kserve/kserve/__init__.py
@@ -15,10 +15,10 @@
 from __future__ import absolute_import from .model import Model
-from .model_server import ModelServer
+#from .model_server import ModelServer
 from .inference_client import InferenceGRPCClient, InferenceRESTClient, RESTConfig
 from .protocol.infer_type import InferRequest, InferInput, InferResponse, InferOutput
-from .model_repository import ModelRepository
+#from .model_repository import ModelRepository
 from .constants import constants
 from .utils import utils[root@mkumatag-x86-fedora python]# git diff kserve/pyproject.toml
diff --git a/python/kserve/pyproject.toml b/python/kserve/pyproject.toml
index 406b42b5..1d592c09 100644
--- a/python/kserve/pyproject.toml
+++ b/python/kserve/pyproject.toml
@@ -42,7 +42,7 @@ kubernetes = ">=23.3.0"
 python-dateutil = "^2.8.0"
 numpy = "^1.23.5"
 psutil = "^5.9.0"
-ray = { version = "~2.10.0", extras = ["serve"] }
+#ray = { version = "~2.10.0", extras = ["serve"] }
 grpcio = "^1.49.1"
 protobuf = "^3.19.0"
 prometheus-client = "^0.20.0" 
```

We need to find a way to avoid this hard dependency, may be by some conditional import or some other way..

**What did you expect to happen:**

**What's the InferenceService yaml:**
[To help us debug please run `kubectl get isvc $name -n $namespace -oyaml` and paste the output]

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

**Environment:**

- Istio Version:
- Knative Version:
- KServe Version:
- Kubeflow version:
- Cloud Environment:[k8s_istio/istio_dex/gcp_basic_auth/gcp_iap/aws/aws_cognito/ibm]
- Minikube/Kind version:
- Kubernetes version: (use `kubectl version`):
- OS (e.g. from `/etc/os-release`):

**Comment by LOADBC** [comment]
@mkumatag you have to update the kserve module to conditionally import ModelServer and ModelRepository only if they are needed.The Modified kserve/__init__.py: will something look like this 
```
from __future__ import absolute_import
from .model import Model
from .model_server import ModelServer                    #use this only if you need it
from .inference_client import InferenceGRPCClient, InferenceRESTClient, RESTConfig
from .protocol.infer_type import InferRequest, InferInput, InferResponse, InferOutput
from .model_repository import ModelRepository        #use this only if you need it  
from .constants import constants
from .utils import utils
```

and Modified pyproject.toml:

```
kubernetes = ">=23.3.0"
python-dateutil = "^2.8.0"
numpy = "^1.23.5"
psutil = "^5.9.0" 
grpcio = "^1.49.1"
protobuf = "^3.19.0"
prometheus-client = "^0.20.0"

```

The storage-initializer module should no longer install Ray as a prerequisite and
the main kserve functionality that does not depend on ModelServer or ModelRepository should work as expected.


ensure that ModelServer and ModelRepository are imported only when necessary.

**Comment by sivanantha321** [comment]
Ray will be optional once this https://github.com/kserve/kserve/pull/3668 is merged

**Comment by mkumatag** [comment]
@sivanantha321 thanks for the information, this is wonderful news.. looking forward to see that PR merged soon.
