### ISSUE TITLE
 Target Model State:  Pending

### ISSUE THREAD

**Issue by yage11** [kserve/kserve#3798]
Model and Inferenceservice are deployed in GCP.
StorageUri is pointed to Cloud Storage in the same cluster as the service.
Here is as status of model with Pending for Target Model State.

Model Status:
 Copies:
   Failed Copies: 0
   Total Copies: 1
 States:
   Active Model State: Loaded
  Target Model State: Pending
Transition Status: InProgress

Could you point out possible reason for that status.
Is there some configuration for gc://... required?

**Comment by ageyuri** [comment]
Hi,
There was a lack of permission to access GCP baskets, after the access was updated the permission issue is solved. 
This issue is closed.

**Comment by spolti** [comment]
Thanks for the feedback.
