### ISSUE TITLE
Tensorflow model Could not find variable

### ISSUE THREAD

**Issue by yashprakashsharma** [kserve/kserve#3801]
/kind bug

**What steps did you take and what happened:**
[A clear and concise description of what the bug is.]
I ran a kubeflow pipeline and creted an endpoint(inferenceservice), it is in ready state, but when I curl it to get predictions i get attached issue, i already saved model inproper format and loaded model from storage uri to make predictions which worked, even tensorflow runtime version for training and kserve is same:                                                                                                                          curl -v -H "Host: ${SERVICE_HOSTNAME}" -H "Authorization: Bearer $TOKEN" -H "Content-Type: application/json" http://${INGRESS_HOST}:${INGRESS_PORT}/v1/models/digits-recognizer:predict -d @./input.json
*   Trying 127.0.0.1:8080...
* TCP_NODELAY set
* Connected to localhost (127.0.0.1) port 8080 (#0)
> POST /v1/models/digits-recognizer:predict HTTP/1.1
> Host: [digits-recognizer.kubeflow-user-example-com.example.com](http://digits-recognizer.kubeflow-user-example-com.example.com/)
> User-Agent: curl/7.68.0
> Accept: */*
> Authorization: Bearer eyJhbGciOiJSUzI1NiIsImtpZCI6IlVYRGNjcE03U3VLcGV4S2MxT2Z1cU9RQW92NHMtVjJGcnJOWW9FUWpfekEifQ.eyJhdWQiOlsiaXN0aW8taW5ncmVzc2dhdGV3YXkuaXN0aW8tc3lzdGVtLnN2Yy5jbHVzdGVyLmxvY2FsIl0sImV4cCI6MTcyMDU4OTg0MiwiaWF0IjoxNzIwNTAzNDQyLCJpc3MiOiJodHRwczovL2t1YmVybmV0ZXMuZGVmYXVsdC5zdmMuY2x1c3Rlci5sb2NhbCIsImt1YmVybmV0ZXMuaW8iOnsibmFtZXNwYWNlIjoia3ViZWZsb3ctdXNlci1leGFtcGxlLWNvbSIsInNlcnZpY2VhY2NvdW50Ijp7Im5hbWUiOiJkZWZhdWx0LWVkaXRvciIsInVpZCI6ImRlNmIwNDQzLTMwNTYtNDgwMi04ODVhLTgxMWY4YWY3YTk5ZCJ9fSwibmJmIjoxNzIwNTAzNDQyLCJzdWIiOiJzeXN0ZW06c2VydmljZWFjY291bnQ6a3ViZWZsb3ctdXNlci1leGFtcGxlLWNvbTpkZWZhdWx0LWVkaXRvciJ9.4LTNQA-AUUB9-2rgJYxzPB8P0q6AbAnlQrIb3XbPpnKm3HAqPFrKi0ajwbEybn_WXcol-5IfCe7oIMR_26-UMw27GZ544HUDvorwt_MEc0izzJgwCvcXakH0O8P7IZoIJyJEiSXSb610_L37SCy89Gq0B6bkavFK0NnGRJos8Wx9r60ATt_32qpXiclt7b-_lF4ePLs8sScg3BsXT-KTTOiy9MtHEfUrHb0tpmHB9dpPD4MHgQvXDay4k__ijDa2RHo37AzNb7GNN2GiX6K_7nrEwcaxHByVIoi9U5YFM_XB5KB8OrTtCSwlCcaazuH_LvI-EFZypkKnqwVbtJyHog
> Content-Type: application/json
> Content-Length: 2924
> Expect: 100-continue
>
Handling connection for 8080
* Mark bundle as not supporting multiuse
< HTTP/1.1 100 Continue
* We are completely uploaded and fine
* Mark bundle as not supporting multiuse
< HTTP/1.1 400 Bad Request
< content-length: 346
< content-type: application/json
< date: Tue, 09 Jul 2024 05:46:59 GMT
< server: istio-envoy
< x-envoy-upstream-service-time: 7
<
{
    "error": "Could not find variable dense_1/kernel. This could mean that the variable has been deleted. In TF1, it can also mean the variable is uninitialized. Debug info: container=localhost, status=Not found: Resource localhost/dense_1/kernel/N10tensorflow3VarE does not exist.\n\t [[{{node sequential_1/dense_1_2/Cast/ReadVariableOp}}]]"
* Connection #0 to host localhost left intact

**What did you expect to happen:**
i expected it to give me prediction but it gave variable missing issue, although inference service is in ready state

**What's the InferenceService yaml:**
[To help us debug please run `kubectl get isvc $name -n $namespace -oyaml` and paste the output]
apiVersion: "serving.kserve.io/v1beta1"
kind: "InferenceService"
metadata:
  name: "digits-recognizer"
  annotations:
    sidecar.istio.io/inject: "false"
spec:
  predictor:
    serviceAccountName: sa-minio-kserve
    model:
      modelFormat:
        name: tensorflow
      runtimeVersion: "2.16.2"
      storageUri: "s3://mlpipeline/v2/artifacts/mnist-classifier-dev/2e3a2119-2db4-42e3-be6e-b7683e0f2f70/model-training"

**Anything else you would like to add:**
I have added the saved tensorflow model(used tf:2.16.1 to train and serve) used by kserve to create inference service, the service is created successfully but we get Could not find variable dense_1/kernel, Could not find variable dense_2/kernel etc error. Please help in resolving it
[Miscellaneous information that will assist in solving the issue.]
The zip contain saved model in /1 dir
[mlpipeline-v2_artifacts_mnist-classifier-dev_66302705-7389-43c3-b5b4-2f707f8929af_model-training.zip](https://github.com/user-attachments/files/16278292/mlpipeline-v2_artifacts_mnist-classifier-dev_66302705-7389-43c3-b5b4-2f707f8929af_model-training.zip)

**Environment:**

- Istio Version: [1.17.3](https://github.com/istio/istio/releases/tag/1.17.3)
- Knative Version: [1.10.2](https://github.com/knative/serving/releases/tag/knative-v1.10.2)
- KServe Version: [v0.11.2](https://github.com/kserve/kserve/tree/v0.11.2/install/v0.11.2)
- Kubeflow version: v1.8.1
- Cloud Environment:[k8s_istio/istio_dex/gcp_basic_auth/gcp_iap/aws/aws_cognito/ibm]
- Minikube/Kind version: v1.33.0
- Kubernetes version: (use `kubectl version`): v1.26
- OS (e.g. from `/etc/os-release`): ubuntu

**Comment by sivanantha321** [comment]
Closing this issue. This is more related to tensorflow, than KServe. KServe uses the tensorflow server to deploy model. You should raise this issue in [tensorflow/serving](https://github.com/tensorflow/serving)
