### ISSUE TITLE
Bump install manifests to v0.13.0

### ISSUE THREAD

**Issue by rimolive** [kserve/kserve#3805]
/kind bug

**What steps did you take and what happened:**
While updating KServe installation docs in Kubeflow to install 0.13.0, I realized there's no `v0.13.0` release under `/installs` folder. There's only `v0.13.0-rc0`.

**What did you expect to happen:**
There should be a `/install/v0.13.0` folder to install 0.13.0 in Kubeflow

**What's the InferenceService yaml:**
N/A

**Anything else you would like to add:**
cc @yuzliu @terrytangyuan 

**Environment:**

- Istio Version: N/A
- Knative Version: N/A
- KServe Version: 0.13.0
- Kubeflow version: 1.9 (future)
- Cloud Environment: N/A
- Minikube/Kind version: N/A
- Kubernetes version: (use `kubectl version`): N/A
- OS (e.g. from `/etc/os-release`): N/A

**Comment by sivanantha321** [comment]
After discussing with @yuzisun We decided release artifacts is enough. But currently, this process is manual. The maintainer has to upload the artifacts. Once it is automated, we will deprecate /install path. The release artifact upload automation is tracked here. https://github.com/kserve/kserve/issues/3714
