### ISSUE TITLE
Need to upgrade vLLM version to support Llama3.1 

### ISSUE THREAD

**Issue by vdabravolski** [kserve/kserve#3826]
/kind feature

**Describe the solution you'd like**
Latest Llama3.1 architecture requires update of vLLM to [v0.5.3.post1](https://github.com/vllm-project/vllm/releases/tag/v0.5.3.post1)

See more details on prerequisites in vLLM issue thread: https://github.com/vllm-project/vllm/issues/6689#issue-2425483231

**Links to the design documents:**
vLLM Llama3.1 [launch announcement](https://blog.vllm.ai/2024/07/23/llama31.html)

**Comment by romanwozniak** [comment]
Seems like [vllm-project/vllm](https://github.com/vllm-project/vllm) introduced breaking changes to OpenAI endpoint implementation in v0.5.3, which makes impossible to simply patch `kserve/huggingfaceserver:0.13.1` image with the newer version of vllm package (i.e. `>=0.5.3`). 

I also tried to use the latest compatible version of vllm (0.5.2) and additionally patch required by Llama3.1 version of `transformers` package (i.e. `transformers>=4.43.2`), but it doesn't work either with Llama3.1 models and throws the following exception 
```
Failed to start model server: 'type'
```

Such a patched serving image still works fine with Lllama3 models tho.
