### ISSUE TITLE
Support for TLS enabled logger endpoints

### ISSUE THREAD

**Issue by ruivieira** [kserve/kserve#3837]
/kind feature

**Describe the solution you'd like**
KServe's Inference Logger producer does not support TLS-enabled endpoints, as the [logger handler](https://github.com/kserve/kserve/blob/master/pkg/logger/handler.go) does not implement TLS-related parameters and implementing the necessary logic to establish secure connections.

Althought this feature proposal does not include the mechanism to pass certificates to the agent, we can assume that if those certificates are available, then the logger could properly configure the transport according to the protocol (ie. either `http` or `https`).

cc @terrytangyuan @danielezonca

**Comment by terrytangyuan** [comment]
From the meeting, the community is interested in this. We need to discuss how to mount the CA certificate, KServe has done this in storage initializer (cc @Jooho).
