### ISSUE TITLE
Too many deployment after kubectl appfy yaml

### ISSUE THREAD

**Issue by deniyes** [kserve/kserve#3846]
/kind bug

**What steps did you take and what happened:**
[A clear and concise description of what the bug is.]

After following the serverless [guide[]](https://kserve.github.io/website/master/admin/serverless/serverless/) and installing everything, I tried to deploy a Hugging Face model[https://kserve.github.io/website/latest/modelserving/v1beta1/llm/huggingface/text_generation/]. 
However, after submitting the kubectl apply, I noticed that there were many Deployments created. 
What could be the reason for this?

**What did you expect to happen:**

**What's the InferenceService yaml:**
[To help us debug please run `kubectl get isvc $name -n $namespace -oyaml` and paste the output]

apiVersion: serving.kserve.io/v1beta1
kind: InferenceService
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"serving.kserve.io/v1beta1","kind":"InferenceService","metadata":{"annotations":{},"name":"huggingface-llama3","namespace":"kserve"},"spec":{"predictor":{"model":{"args":["--model_name=llama3","--model_id=meta-llama/meta-llama-3-8b-instruct"],"modelFormat":{"name":"huggingface"},"resources":{"limits":{"cpu":"6","memory":"16Gi","nvidia.com/gpu":"1"},"requests":{"cpu":"6","memory":"16Gi","nvidia.com/gpu":"1"}}}}}}
  creationTimestamp: "2024-08-08T03:46:13Z"
  finalizers:
  - inferenceservice.finalizers
  generation: 1
  name: huggingface-llama3
  namespace: kserve
  resourceVersion: "1202601"
  uid: 3c3539a0-e864-4aba-a50e-a77274ddc6ea
spec:
  predictor:
    model:
      args:
      - --model_name=llama3
      - --model_id=meta-llama/meta-llama-3-8b-instruct
      modelFormat:
        name: huggingface
      name: ""
      resources:
        limits:
          cpu: "6"
          memory: 16Gi
          nvidia.com/gpu: "1"
        requests:
          cpu: "6"
          memory: 16Gi
          nvidia.com/gpu: "1"
status:
  components:
    predictor:
      latestCreatedRevision: huggingface-llama3-predictor-default-01094
  conditions:
  - lastTransitionTime: "2024-08-08T03:46:15Z"
    reason: PredictorConfigurationReady not ready
    severity: Info
    status: Unknown
    type: LatestDeploymentReady
  - lastTransitionTime: "2024-08-08T03:51:11Z"
    severity: Info
    status: Unknown
    type: PredictorConfigurationReady
  - lastTransitionTime: "2024-08-08T03:51:10Z"
    message: Configuration "huggingface-llama3-predictor-default" is waiting for a
      Revision to become ready.
    reason: RevisionMissing
    status: Unknown
    type: PredictorReady
  - lastTransitionTime: "2024-08-08T03:46:14Z"
    message: Configuration "huggingface-llama3-predictor-default" is waiting for a
      Revision to become ready.
    reason: RevisionMissing
    severity: Info
    status: Unknown
    type: PredictorRouteReady
  - lastTransitionTime: "2024-08-08T03:51:10Z"
    message: Configuration "huggingface-llama3-predictor-default" is waiting for a
      Revision to become ready.
    reason: RevisionMissing
    status: Unknown
    type: Ready
  - lastTransitionTime: "2024-08-08T03:46:15Z"
    reason: PredictorRouteReady not ready
    severity: Info
    status: Unknown
    type: RoutesReady
  modelStatus:
    states:
      activeModelState: ""
      targetModelState: Pending
    transitionStatus: InProgress
  observedGeneration: 1442

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

**Environment:**

- Istio Version:v1.22.3
- Knative Version:v1.15.2
- KServe Version: 0.13.0
- Kubeflow version:
- Cloud Environment:[k8s_istio/istio_dex/gcp_basic_auth/gcp_iap/aws/aws_cognito/ibm]  k8s_istio
- Minikube/Kind version:  I use kubeadm, v1.30.3
- Kubernetes version: (use `kubectl version`): v1.30.3
- OS (e.g. from `/etc/os-release`):  Ubuntu 20.04.6 LTS

**Comment by deniyes** [comment]
I've noticed that revisions are being continuously created. What could be causing this?
<img width="1729" alt="1723108535487" src="https://github.com/user-attachments/assets/a5a7c225-6bb0-4153-b7fa-b626f8687815">


and log in kserve-controller-manager-86879549d8-tn7zc shows:
{"level":"error","ts":"2024-08-08T06:51:57Z","logger":"v1beta1Controllers.InferenceService","msg":"Failed to update InferenceService status","InferenceService":"huggingface-llama3","error":"Operation cannot be fulfilled on inferenceservices.serving.kserve.io \"huggingface-llama3\": the object has been modified; please apply your changes to the latest version and try again","stacktrace":"github.com/kserve/kserve/pkg/controller/v1beta1/inferenceservice.(*InferenceServiceReconciler).updateStatus\n\t/go/src/github.com/kserve/kserve/pkg/controller/v1beta1/inferenceservice/controller.go:282\ngithub.com/kserve/kserve/pkg/controller/v1beta1/inferenceservice.(*InferenceServiceReconciler).Reconcile\n\t/go/src/github.com/kserve/kserve/pkg/controller/v1beta1/inferenceservice/controller.go:261\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Reconcile\n\t/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.16.3/pkg/internal/controller/controller.go:119\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).reconcileHandler\n\t/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.16.3/pkg/internal/controller/controller.go:316\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem\n\t/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.16.3/pkg/internal/controller/controller.go:266\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func2.2\n\t/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.16.3/pkg/internal/controller/controller.go:227"}

**Comment by sivanantha321** [comment]
@deniyes Is there anything that is trying to modify the deployment or Knative service ? This may trigger the reconciliation and going in endless loop

**Comment by deniyes** [comment]
> @deniyes Is there anything that is trying to modify the deployment or Knative service ? This may trigger the reconciliation and going in endless loop

Thx.
 I had reinstall the knative, istio and kserve, and the issue was fixed.  Maybe I made some mistake in the first install.

**Comment by sivanantha321** [comment]
Closing the issue based on the above comment.
