### ISSUE TITLE
KServe controller missing SecurityContext in helm chart installation

### ISSUE THREAD

**Issue by yuzisun** [kserve/kserve#3862]
/kind bug

**What steps did you take and what happened:**
The kserve controller manifest from helm chart is missing SecurityContext as defined in kustomize resources
https://github.com/kserve/kserve/blob/master/charts/kserve-resources/templates/deployment.yaml

https://github.com/kserve/kserve/blob/f9c73c2bd1518b470d2ee45c168ec723fe3868a6/config/manager/manager.yaml#L23

**What did you expect to happen:**

**What's the InferenceService yaml:**
[To help us debug please run `kubectl get isvc $name -n $namespace -oyaml` and paste the output]

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

**Environment:**

- Istio Version:
- Knative Version:
- KServe Version:
- Kubeflow version:
- Cloud Environment:[k8s_istio/istio_dex/gcp_basic_auth/gcp_iap/aws/aws_cognito/ibm]
- Minikube/Kind version:
- Kubernetes version: (use `kubectl version`):
- OS (e.g. from `/etc/os-release`):

**Comment by LOADBC** [comment]
i looked it up, the `deployment.yaml` and the `manager.yaml`, its true that the `securitycontext` is not configured in `deployment.yaml`, i am trying to understand what will this result if not configured @sivanantha321
