### ISSUE TITLE
Release 0.14 Tracking

### ISSUE THREAD

**Issue by yuzisun** [kserve/kserve#3872]
# KServe 0.14.0 release tracking:

RC0 release Date: Will be released in the week of `August 26, 2024`
Release Date: Will be released in the week of `Sep 23, 2024`

## **TIMELINE**
| Week | Start                     | End                         | When | Event (Actual timelines)                                                                                |
| ---- |---------------------------| --------------------------- | ---- | ------------------------------------------------------------------------------------------------------- |
| 0-10  | **Week of  June 3, 2024**    | **August 23, 2024**       |      | **Feature Freeze + RC0 Released + Documentation update starts**                                             |
| 11-13   | **Week of August 26, 2024**       | **Sep 20, 2024**      |      | Testing   + End of documentation                                                                                               |
| 14   | **Sep 23 2024**  | **Sep 27, 2024**      |      | **Final release - 0.14.0 released**

**Comment by lizzzcai** [comment]
this [issue](https://github.com/kserve/kserve/pull/3495) needs to be merged if it is all good, and doc needs to be updated as well once it is merged.
