### ISSUE TITLE
Storage initializer missing

### ISSUE THREAD

**Issue by Zeashh** [kserve/kserve#3873]
/kind bug

**What steps did you take and what happened:**
[A clear and concise description of what the bug is.]

I've been following these guides to try and deploy gemma-2b in our test k8s cluster:
- https://kserve.github.io/website/latest/modelserving/v1beta1/torchserve/
- https://kserve.github.io/website/latest/modelserving/v1beta1/llm/torchserve/accelerate/

I've prepared the storage. However, upon creating the InferenceService, I've noticed that no storage initializer init container is created. Is this a bug or have I missed something in my configuration?

**What did you expect to happen:**

**What's the InferenceService yaml:**
[To help us debug please run `kubectl get isvc $name -n $namespace -oyaml` and paste the output]

``` yaml
apiVersion: v1
items:
- apiVersion: serving.kserve.io/v1beta1
  kind: InferenceService
  metadata:
    annotations:
      kubectl.kubernetes.io/last-applied-configuration: |
        {"apiVersion":"serving.kserve.io/v1beta1","kind":"InferenceService","metadata":{"annotations":{},"name":"gemma-2b-torchserve","namespace":"kserve"},"spec":{"predictor":{"model":{"modelFormat":{"name":"pytorch"},"protocolVersion":"v2","resources":{"limits":{"cpu":"8","memory":"12Gi"},"requests":{"cpu":"2","memory":"12Gi"}},"storageUri":"kserve-lab/kserve-lab/torchserve-gemma-2b"}}}}
      serving.kserve.io/deploymentMode: RawDeployment
    creationTimestamp: "2024-08-19T13:21:11Z"
    finalizers:
    - inferenceservice.finalizers
    generation: 3
    name: gemma-2b-torchserve
    namespace: kserve
    resourceVersion: "650332587"
    uid: 16aafe3a-b82d-4d4f-aea4-332c0193ffd2
  spec:
    predictor:
      model:
        modelFormat:
          name: pytorch
        name: ""
        protocolVersion: v2
        resources:
          limits:
            cpu: "8"
            memory: 12Gi
          requests:
            cpu: "2"
            memory: 12Gi
        storageUri: kserve-lab/kserve-lab/torchserve-gemma-2b
  status:
    components:
      predictor:
        latestCreatedRevision: "3"
    conditions:
    - lastTransitionTime: "2024-08-19T13:21:11Z"
      reason: Predictor ingress not created
      status: "False"
      type: IngressReady
    - lastTransitionTime: "2024-08-19T13:21:11Z"
      message: Deployment does not have minimum availability.
      reason: MinimumReplicasUnavailable
      status: "False"
      type: PredictorReady
    - lastTransitionTime: "2024-08-19T13:42:00Z"
      reason: Predictor ingress not created
      status: "False"
      type: Ready
    modelStatus:
      lastFailureInfo:
        exitCode: 1
        reason: ModelLoadFailed
      states:
        activeModelState: ""
        targetModelState: FailedToLoad
      transitionStatus: BlockedByFailedLoad
    observedGeneration: 3
kind: List
metadata:
  resourceVersion: ""
```

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

**Environment:**

- Istio Version: 1.22
- Knative Version:
- KServe Version: 0.13
- Kubeflow version:
- Cloud Environment: k8s_istio
- Minikube/Kind version:
- Kubernetes version: (use `kubectl version`): v1.25.14
- OS (e.g. from `/etc/os-release`): Ubuntu 20.04.3 LTS (Focal Fossa)

**Comment by spolti** [comment]
Hi, what is the protocol of your storage?
It should be something like `storageUri: gs://kfserving-examples/models/torchserve/image_classifier/v1`

It seems that you are using `Raw Deployments`, if I am not mistaken, this method does not initialize the `storage-initializer`.
@israel-hdez @terrytangyuan can you please confirm?

**Comment by sivanantha321** [comment]
@Zeashh Do not deploy inference services in control plane namespaces like Kserve namespace. The storage initializer will not be injected.

**Comment by sivanantha321** [comment]
@Zeashh Read the warning here https://kserve.github.io/website/latest/get_started/first_isvc/#2-create-an-inferenceservice

**Comment by sivanantha321** [comment]
> Hi, what is the protocol of your storage?
> 
> It should be something like `storageUri: gs://kfserving-examples/models/torchserve/image_classifier/v1`
> 
> 
> 
> It seems that you are using `Raw Deployments`, if I am not mistaken, this method does not initialize the `storage-initializer`.
> 
> @israel-hdez @terrytangyuan can you please confirm?

No, storage initializer can be used with raw deployment.

**Comment by Zeashh** [comment]
> @Zeashh Read the warning here https://kserve.github.io/website/latest/get_started/first_isvc/#2-create-an-inferenceservice

Thank you, such a dumb oversight on my part since I went through that tutorial earlier.

Now I'm getting a "No model found" error, even though I set up the directory structure according to [this](https://kserve.github.io/website/latest/modelserving/v1beta1/torchserve/#create-model-storage-with-a-model-archive-file-and-config).

``` bash
$ mc ls kserve-lab/kserve-lab/torchserve-gemma-2b
[2024-08-20 08:33:27 UTC]     0B config/  # contains config.properties
[2024-08-20 08:33:27 UTC]     0B model-store/ # contains MAR file
```

Looking at the source code, this happens when the storage initializer finds no files on the specified storage.

New InferenceService manifest:

``` yaml
apiVersion: serving.kserve.io/v1beta1
kind: InferenceService
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"serving.kserve.io/v1beta1","kind":"InferenceService","metadata":{"annotations":{},"name":"gemma-2b-torchserve","namespace":"gemma"},"spec":{"predictor":{"model":{"modelFormat":{"name":"pytorch"},"protocolVersion":"v2","resources":{"limits":{"cpu":"8","memory":"12Gi"},"requests":{"cpu":"2","memory":"12Gi"}},"storageUri":"s3://kserve-lab/kserve-lab/torchserve-gemma-2b/"},"serviceAccountName":"sa"}}}
    serving.kserve.io/deploymentMode: RawDeployment
  creationTimestamp: "2024-08-20T08:22:31Z"
  finalizers:
  - inferenceservice.finalizers
  generation: 2
  name: gemma-2b-torchserve
  namespace: gemma
  resourceVersion: "650912910"
  uid: 4b7fceb4-6cf2-4a3c-bc8a-c05c7ccfb4c2
spec:
  predictor:
    model:
      modelFormat:
        name: pytorch
      name: ""
      protocolVersion: v2
      resources:
        limits:
          cpu: "8"
          memory: 12Gi
        requests:
          cpu: "2"
          memory: 12Gi
      storageUri: s3://kserve-lab/kserve-lab/torchserve-gemma-2b/
    serviceAccountName: sa
status:
  components:
    predictor:
      latestCreatedRevision: "2"
  conditions:
  - lastTransitionTime: "2024-08-20T08:22:32Z"
    reason: Predictor ingress not created
    status: "False"
    type: IngressReady
  - lastTransitionTime: "2024-08-20T08:22:32Z"
    message: Deployment does not have minimum availability.
    reason: MinimumReplicasUnavailable
    status: "False"
    type: PredictorReady
  - lastTransitionTime: "2024-08-20T08:33:12Z"
    reason: Predictor ingress not created
    status: "False"
    type: Ready
  modelStatus:
    lastFailureInfo:
      exitCode: 1
      message: |
        2024-08-20 08:30:06.005 1 kserve INFO [initializer-entrypoint:<module>():16] Initializing, args: src_uri [s3://kserve-lab/kserve-lab/torchserve-gemma-2b/] dest_path[ [/mnt/models]
        2024-08-20 08:30:06.005 1 kserve INFO [storage.py:download():66] Copying contents of s3://kserve-lab/kserve-lab/torchserve-gemma-2b/ to local
        Traceback (most recent call last):
          File "/storage-initializer/scripts/initializer-entrypoint", line 17, in <module>
            Storage.download(src_uri, dest_path)
          File "/kserve/kserve/storage/storage.py", line 86, in download
            Storage._download_s3(uri, out_dir)
          File "/kserve/kserve/storage/storage.py", line 269, in _download_s3
            raise RuntimeError(
        RuntimeError: Failed to fetch model. No model found in kserve-lab/torchserve-gemma-2b/.
      reason: ModelLoadFailed
    states:
      activeModelState: ""
      targetModelState: FailedToLoad
    transitionStatus: BlockedByFailedLoad
  observedGeneration: 2
```

I attached a service account and to it a secret with storage credentials as documented [here](https://kserve.github.io/website/latest/modelserving/storage/s3/s3/#deploy-the-model-on-s3-with-inferenceservice).

EDIT: Dumb oversight again, the storageUri doesn't need the first "kserve-lab", since there are no aliases involved. Marking as solved, thanks for the help
