### ISSUE TITLE
RBAC permission for secret is too broad

### ISSUE THREAD

**Issue by wqlparallel** [kserve/kserve#3897]
/kind bug

**What steps did you take and what happened:**
[A clear and concise description of what the bug is.]

I found that the RBAC permission for secret under the chart directory is too broad, it includes more operations than necessary.
`- apiGroups:
  - ""
  resources:
  - secrets
  verbs:
  - create
  - delete
  - get
  - patch
  - update`

**What did you expect to happen:**
I expected the RBAC permission for secret to only include 'get' operation.

**What's the InferenceService yaml:**
[To help us debug please run `kubectl get isvc $name -n $namespace -oyaml` and paste the output]

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

**Environment:**

- Istio Version:
- Knative Version:
- KServe Version:
- Kubeflow version:
- Cloud Environment:[k8s_istio/istio_dex/gcp_basic_auth/gcp_iap/aws/aws_cognito/ibm]
- Minikube/Kind version:
- Kubernetes version: (use `kubectl version`):
- OS (e.g. from `/etc/os-release`):

**Comment by spolti** [comment]
Hi @wqlparallel , @sivanantha321 has pushed a PR to limit it, see: https://github.com/kserve/kserve/pull/3893

**Comment by wqlparallel** [comment]
This good,  thank you !
