### ISSUE TITLE
Fail to execute make generate on local

### ISSUE THREAD

**Issue by Jooho** [kserve/kserve#3923]
/kind bug

**What steps did you take and what happened:**
[A clear and concise description of what the bug is.]
To execute `make generate` locally, the directory has to be `$(go env GOPATH)/src/kserve/kserve`
If the directory is different, it will fail with the following error msg:
```
ERROR: 
	 API rule check failed. Reported violations in file hack/current_violation_exceptions.list differ from known violations in file hack/violation_exceptions.list
```
The main reason why it shows is because the path is different.

Expected output:
```
API rule violation: names_match,github.com/kserve/kserve/pkg/apis/serving/v1beta1,PredictorSpec,XGBoost
```

Actual output:
```
 API rule violation: names_match,./pkg/apis/serving/v1beta1,PredictorSpec,XGBoost
```

**What did you expect to happen:**
This command should succeed no matter where it is run.

**Comment by spolti** [comment]
I had this issue before as well, and it seems that when this generate part was made, it was using the old way to clone and organize go projects, under `$GOPATH/src`.

With go modules it is not necessary anymore.

So, to overcome this small issue locally, I've symlinked my `kserve` repo to `$GOPATH/src/github.com` and run `make generate` from there, by doing this it will keep the exception violation file as it is.

But, at this point, it might be a good idea to change this.
