### ISSUE TITLE
Orphan cluster role kserve-addressable-resolver deployed

### ISSUE THREAD

**Issue by zhangyue110026** [kserve/kserve#3929]
/kind bug

**What steps did you take and what happened:**
We have noticed three instances of an orphan resource in some of your Kubernetes configuration files. Deploying Kubernetes resources that are not being actively used or referenced by any other resources in the cluster can lead to orphan resources. These orphan resources consume unnecessary resources and can potentially cause confusion or clutter within the cluster. Additionally, we provide anecdotal evidence from [topolvm-topolvm#484](https://github.com/topolvm/topolvm/issues/484) regarding the orphan resource defect.

cluster role kserve-addressable-resolver does not have a role binding:

https://github.com/kserve/kserve/blob/29731befb0a1721d42e642f09f5ec62f1eafd522/charts/kserve-resources/templates/clusterrole.yaml#L320C9-L320C36

**What did you expect to happen:**
cluster role kserve-addressable-resolver should have a role binding, otherwise it is a orphan resource. Or delete kserve-addressable-resolver to avoid deploy orphan resource.

**What's the InferenceService yaml:**
[To help us debug please run `kubectl get isvc $name -n $namespace -oyaml` and paste the output]

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

**Environment:**

- Istio Version:
- Knative Version:
- KServe Version:
- Kubeflow version:
- Cloud Environment:[k8s_istio/istio_dex/gcp_basic_auth/gcp_iap/aws/aws_cognito/ibm]
- Minikube/Kind version:
- Kubernetes version: (use `kubectl version`):
- OS (e.g. from `/etc/os-release`):

**Comment by sivanantha321** [comment]
This is taken care here with a flag https://github.com/kserve/kserve/blob/master/charts/kserve-resources/templates/addressable_resolver_role.yaml.

The addressable role is used along side with Knative, the role binding is defined in knative as it is selecting these external roles by label duck.knative.dev/addressable.

https://github.com/knative/serving/blob/edb073ce7c2d158d2e46ea3610d1b72c5f002d92/config/core/200-serviceaccount.yaml#L68

https://github.com/knative/serving/blob/edb073ce7c2d158d2e46ea3610d1b72c5f002d92/config/core/200-roles/addressable-resolvers-clusterrole.yaml#L25
