### ISSUE TITLE
Even if inferenceservice's related components ready, inferenceservice argo health is inprogressing

### ISSUE THREAD

**Issue by haksuuu** [kserve/kserve#3973]
/kind bug

**What steps did you take and what happened:**
[A clear and concise description of what the bug is.]

I deployed rawDeployment type Inferenceservice using ArgoCD.
Even if all resources (ingress, HPA, Deployment) are healthy, Inferenceservice's status still Inprogressing. 
![스크린샷 2024-10-07 오전 9 38 41](https://github.com/user-attachments/assets/1ce534c7-f5eb-4f68-ad5e-e494a4b9f57a)

**What did you expect to happen:**
Inferenceservice and argoCD app status healthy.

**What's the InferenceService yaml:**
[To help us debug please run `kubectl get isvc $name -n $namespace -oyaml` and paste the output]
apiVersion: v1
items:
- apiVersion: serving.kserve.io/v1beta1
  kind: InferenceService
  metadata:
    annotations:
      serving.kserve.io/deploymentMode: RawDeployment
    creationTimestamp: "2024-10-07T00:26:41Z"
    finalizers:
    - inferenceservice.finalizers
    generation: 1
    labels:
      app.kubernetes.io/instance: dev-kan-data-ocean-koelectra-base
    name: dev-koelectra-base
    namespace: ocean
    resourceVersion: "87649010"
    uid: 9dcb6a77-6059-4054-b914-d4df34142bc1
  spec:
    predictor:
      minReplicas: 1
      model:
        image:harbor.example.com/platform/nvidia/tritonserver:24.07-py3
        imagePullPolicy: IfNotPresent
        modelFormat:
          name: triton
        name: ""
        protocolVersion: v2
        resources:
          limits:
            memory: 2Gi
          requests:
            cpu: 500m
            memory: 2Gi
        runtimeVersion: 24.07-py3
        storageUri: s3://sandbox-example-registry/koelectra-base/koelectra-base-develop-08f5ace
      nodeSelector:
        kubernetes.io/arch: amd64
       /dev: "true"
       /ingress: "false"
       /node-group: app
       /zone: app
      securityContext:
        fsGroup: 1000
        runAsUser: 1000
      serviceAccountName: kserve-sa
      terminationGracePeriodSeconds: 60
  status:
    address:
      url: http://dev-koelectra-base-predictor.ocean.svc.cluster.local
    components:
      predictor:
        latestCreatedRevision: "1"
        url: http://dev-koelectra-base-predictor-ocean.example.com
    conditions:
    - lastTransitionTime: "2024-10-07T00:26:59Z"
      status: "True"
      type: IngressReady
    - lastTransitionTime: "2024-10-07T00:26:59Z"
      status: "True"
      type: PredictorReady
    - lastTransitionTime: "2024-10-07T00:26:59Z"
      status: "True"
      type: Ready
    modelStatus:
      copies:
        failedCopies: 0
        totalCopies: 1
      states:
        activeModelState: Loaded
        targetModelState: Loaded
      transitionStatus: UpToDate
    observedGeneration: 1
    url: http://dev-koelectra-base-ocean.example.com
kind: List
metadata:
  resourceVersion: ""
**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

**Environment:**

- Istio Version:
- Knative Version:
- KServe Version:
- Kubeflow version:
- Cloud Environment:[k8s_istio/istio_dex/gcp_basic_auth/gcp_iap/aws/aws_cognito/ibm]
- Minikube/Kind version:
- Kubernetes version: (use `kubectl version`):
- OS (e.g. from `/etc/os-release`):

**Comment by noymmm** [comment]
Hey @haksuuu , 
I am also experiencing this issue. Did you mark it as completed because you found a workaround?

**Comment by haksuuu** [comment]
@noymmm yes, you can check below document.
in argocd custom resource, there is about kserve.

https://argo-cd.readthedocs.io/en/stable/operator-manual/health/#way-2-contribute-a-custom-health-check
