### ISSUE TITLE
KServe VLLM cpu image 

### ISSUE THREAD

**Issue by twtheisen** [kserve/kserve#3997]
/kind feature

**Describe the solution you'd like**
Currently, the image: `kserve/vllmserver:latest` only supports GPU workloads. I'd like an image that supports running VLLM via KServe using CPU. 

**Anything else you would like to add:**

The VLLM dockerfile for CPU is here: https://github.com/vllm-project/vllm/blob/main/Dockerfile.cpu

**Comment by jyono** [comment]
Coincidentally, I am having the same problem.  Is anybody currently working on this? 

Some immediate avenues to explore: 

1. Bake CPU support into the docker image and pass an arg at runtime specify. Of course, at this point, we don't need CUDA so we are taking on a lot of bloat there. This may require require huggingface server be capable of processing the arg, too.  
2. We could do something similar to torchserve and default to a `-cpu` image if no GPU is provided.

**Comment by yuzisun** [comment]
@johnugeorge Are you guys planning to work on this?

**Comment by gavrissh** [comment]
> @johnugeorge Are you guys planning to work on this?

Yes @yuzisun, we have started on this task. Will have the PR open shortly

**Comment by jyono** [comment]
@yuzisun @gavrissh @johnugeorge 

awesome. excitedly awaiting the PR. 

can you point to where in the code the kserve images are built/published?

**Comment by hustxiayang** [comment]
> awesome. excitedly awaiting the PR.

@gavrissh I am also waiting for the PR. I feel it's really difficult to write the mock tests for vLLM, and would be more and more difficult.

**Comment by gavrissh** [comment]
> can you point to where in the code the kserve images are built/published?

@jyono The Fix PR changes would show the workflow for the above query #4049

**Comment by jyono** [comment]
@gavrissh huge! thanks :)
