### ISSUE TITLE
kserve from is failing on k8s 1.31

### ISSUE THREAD

**Issue by padrian2s** [kserve/kserve#4002]
/kind bug

**What steps did you take and what happened:**

While installing KF 1.7 on Kubernetes version 1.31, I encountered the following error:

"""

The CustomResourceDefinition "[inferenceservices.serving.kserve.io](http://inferenceservices.serving.kserve.io/)" is invalid: spec.conversion.webhookClientConfig.caBundle: Invalid value: []byte{0xa}: unable to load root certificates: unable to parse bytes as PEM block

"""

I understand that Kubernetes 1.31 is not officially supported, but I'm not sure what specifically is causing this issue. When running Kubernetes version 1.30, everything works fine without this error.

There are no issues with the pods or events, but the error only occurs when installing Kubeflow 1.7 manifests. 
KServe from FP 1.7/ Is hard to debug, I inspected all certs resources (crds), none are with errors.

**What did you expect to happen:**
The manifests should run successfully without encountering any certificate or CRD-related errors.

**What's the InferenceService yaml:**
[To help us debug please run `kubectl get isvc $name -n $namespace -oyaml` and paste the output]

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

**Environment:**
kind, k8s 1.30 (ok) and 1.31 (error)

- Istio Version:
- Knative Version:
- KServe Version:
- Kubeflow version:
- Cloud Environment:[k8s_istio/istio_dex/]
- Minikube/Kind version:  latest
- Kubernetes version: (use `kubectl version`): latest
- OS (e.g. from `/etc/os-release`): linux ubuntu

**Comment by spolti** [comment]
I didn't find anything related to certificates in the 1.,31 release notes.

Is there a chance of the cabundle be corrupted in your cluster?


Also, could you confirm if installing KServe 0.13 without KF works?
And, did you try to use the latest KF version? (1.9)

**Comment by padrian2s** [comment]
tested on k8s 1.31 with kserve main trunck = no issues
tested on k8s 1.31 with Kubeflow main trunck = no issues

please close the issue

Thank you all for your incredible support! I truly appreciate it!
