### ISSUE TITLE
Storage Initializer GCS no model found with single file

### ISSUE THREAD

**Issue by bentohset** [kserve/kserve#4013]
/kind bug

**What steps did you take and what happened:**
When GCS storage url points to single file directly (eg. `gs://REDACTED/model/test-folder/model.pb`), following error occurs:

```
Traceback (most recent call last):
  File "/storage-initializer/scripts/initializer-entrypoint", line 17, in <module>
    Storage.download(src_uri, dest_path)
  File "/kserve/kserve/storage/storage.py", line 89, in download
    model_dir = Storage._download_gcs(uri, out_dir)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/kserve/kserve/storage/storage.py", line 353, in _download_gcs
    raise RuntimeError("Failed to fetch model. No model found in %s." % uri)
RuntimeError: Failed to fetch model. No model found in gs://REDACTED/model/test-folder/model.pb.
```

**What did you expect to happen:**
It should download the single file directly

**What's the InferenceService yaml:**
```
apiVersion: "serving.kserve.io/v1beta1"
kind: "InferenceService"
metadata:
  name: "flower-gcs"
  annotations:
    serving.kserve.io/enable-metric-aggregation:  "true"
    serving.kserve.io/enable-prometheus-scraping: "true"
spec:
  predictor:
    tensorflow:
      storageUri: "gs://REDACTED/model/test-folder/model.pb"
```

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

**Environment:**

- Istio Version:
- Knative Version:
- KServe Version:
- Kubeflow version:
- Cloud Environment:[k8s_istio/istio_dex/gcp_basic_auth/gcp_iap/aws/aws_cognito/ibm]
- Minikube/Kind version:
- Kubernetes version: (use `kubectl version`):
- OS (e.g. from `/etc/os-release`):

**Comment by spolti** [comment]
While it isn't fixed, you can use the directory.


to test locally:
```bash
podman run -it kserve/storage-initializer:latest gs://REDACTED/model/test-folder /tmp/
```


I've create this little patch: https://github.com/kserve/kserve/pull/4015
