### ISSUE TITLE
How is the router image used?

### ISSUE THREAD

**Issue by EyeCantCU** [kserve/kserve#4016]
/kind bug

**What steps did you take and what happened:**
On deploying KServe, the router image is set as part of the deployment. However, the image never actually appears to be used by a container

**What did you expect to happen:**
For the image to be used by a container

**Anything else you would like to add:**
Is there any documentation on how the router is used?

**Comment by sivanantha321** [comment]
@EyeCantCU It is used for Inferencegraph resources. https://kserve.github.io/website/latest/modelserving/inference_graph/

**Comment by EyeCantCU** [comment]
Thank you so much for the reference!
