### ISSUE TITLE
KServe Agent OOMKilled When Allocated Memory is Insufficient

### ISSUE THREAD

**Issue by ops-jaeha** [kserve/kserve#4017]
/kind bug

**What steps did you take and what happened:**
I attempted to load a model using the KServe Agent with the `StorageURI` pointing to **Google Cloud Storage**. However, when the memory allocated to the KServe Agent was smaller than the memory required by the model, the agent was OOMKilled and subsequently restarted.

**What did you expect to happen:**
I expected the KServe Agent to attempt downloading the model using minimal memory resources, regardless of the model's size. This approach would allow models of varying sizes to be loaded without being restricted by the initially allocated memory, enhancing flexibility and reliability in different deployment scenarios.

**What's the InferenceService yaml:**
KServe/agent OOMKilled

**Anything else you would like to add**
I plan to address this issue and will be submitting a Pull Request (PR) to fix it. I would appreciate it if the maintainers could review my PR once it's submitted.

**Environment:**

Same Kubeflow Manifest
- Istio Version: 1.22.1
- Knative Version: 1.12.4
- KServe Version: 0.13.1
- Kubeflow version: 1.9.0
- Cloud Environment: On-prem, GKE
- Kubernetes version: v1.30.3
- OS: Ubuntu 20.04

**Comment by spolti** [comment]
Hi, btw, isn't affecting other storages as well than just gcs?

**Comment by ops-jaeha** [comment]
Hello, thank you for pointing that out. Except for GCS at the moment, the only other feature that handles storage in a similar approach seems to be https.go. However, I haven't seen an example of downloading a model using the https.go file in particular.

If i find any future cases or use cases, we will add additional appointments to resolve this issue.
Would it be okay if I first modify and commit the https.go file and then validate it through the CI pipeline?
If that’s acceptable, it seems best to proceed by merging the gcs.go file first. I believe the gcs.go file has a critical issue affecting functionality.
