### ISSUE TITLE
How to modify the model volumes type?

### ISSUE THREAD

**Issue by qzheng527** [kserve/kserve#4040]
/kind bug

**What steps did you take and what happened:**
I am trying to use kserve on top of confidential containers ([CoCo](https://github.com/confidential-containers)) for security.
While in current CoCo pod env (guest confidential VM, similar to kata guest), the Ephemeral volumes such as **emptyDir** is not supported unless mark it as **medium: Memory**.
In kserve, the model storage volumes use below settings in default which is not supported in CoCo.
```
  - emptyDir: {}
    name: kserve-provision-location
```

My question is, how to modify above settings? Such as using memory backend emptyDir as below.
```
  - name: kserve-provision-location
    emptyDir:
      medium: Memory
```

**What did you expect to happen:**
There is some elegant way to customize the model storage volumes.

**Environment:**

- Istio Version: 
- Knative Version: v1.13.1
- KServe Version: v0.13.0
- Kubeflow version:
- Cloud Environment:[k8s_istio]
- Minikube/Kind version:
- Kubernetes version: (use `kubectl version`):  v1.31.2
- OS (e.g. from `/etc/os-release`): ubuntu 24.04

**Comment by rhuss** [comment]
I have no answer to your question, but just wanted mention that ppl were able to run KServe successfully with modelcar (`oci://` storage scheme) on CoCo. See e.g. this KubeCon presentation --> https://www.youtube.com/watch?v=Ko0o5_hpmxI

**Comment by lizzzcai** [comment]
Hi @qzheng527 , regarding on customizing it, I think adding a field in the [configmap](https://github.com/kserve/kserve/blob/master/config/configmap/inferenceservice.yaml#L47) or having an annotation to set it per inference service will be a good option.

**Comment by qzheng527** [comment]
Thanks, guys. @lizzzcai @rhuss 
After digging it, the failure may not come from the **emptyDir**.
It was probably due to the limitation of large container image pulling inside CoCo CVM.
I close this issue for now.
