### ISSUE TITLE
Where is the most up to date vllmserver image?

### ISSUE THREAD

**Issue by geodavic** [kserve/kserve#4088]
I see this image: https://hub.docker.com/r/kserve/vllmserver/tags

which is about a year old. Where can I get the most up-to-date vllmserver image? vLLM updates frequently with support for new models, and I would like to have the most recent version of vLLM on my kserve. Or can I build one myself? I don't see a dockerfile however.

**Comment by sivanantha321** [comment]
@geodavic KServe is using vLLM 0.6.3post1. https://github.com/kserve/kserve/blob/5bbb1369a429f84303b71b9e512a09a63f9d68f3/python/huggingface_server.Dockerfile#L12.The image you linked is not used by KServe. This is the image used by KServe for serving LLM models using vLLM/Huggingface as backend. https://hub.docker.com/r/kserve/huggingfaceserver

**Comment by geodavic** [comment]
Thank you for the clarification!
