### ISSUE TITLE
Add prometheus annotation to scrape metrics from queue-proxy

### ISSUE THREAD

**Issue by yuzisun** [kserve/kserve#485]
/kind feature

**Describe the solution you'd like**
Need following annotations on InferenceService so that prometheus can scrape metrics from  revision pods.

```
prometheus.io/scape: true
prometheus.io/port: 9091
```

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

**Comment by Iamlovingit** [comment]
I want to collect inferenceservice metrics from kfserving for monitoring. I notice that, there is a yaml [promethues-patch](https://github.com/kubeflow/kfserving/blob/master/config/default/manager_prometheus_metrics_patch.yaml). Now I have known the promethus' address, how to config kfserving can make me collect these metrics? BTW, is there haved a list file for definition the metircs' name?

**Comment by sivanantha321** [comment]
Completed via
-  #2459
