### ISSUE TITLE
enable grpc or rest api

### ISSUE THREAD

**Issue by hougangliu** [kserve/kserve#533]
/kind feature

**Describe the solution you'd like**
[A clear and concise description of what you want to happen.]
for now, all kinds of  kfserving model frameworks enable both grpc port and rest port, and knative  serving can only apply one user port (8080 by default, or the first port in user container), since inferenceservice doesn't specify any port, knative serving will always use 8080 port (8080 port is rest port of kfserving)
Since each model serving also enables grpc port (for now user cannot access it), we should allow user to expose grpc or rest port by a flag.

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

**Comment by pugangxa** [comment]
Take a look at the code, except for tensorflow serving it's built in supported,  we did not really implement grpc logic to support it. 
So the story is not only just expose a flag to select the port, but also add the grpc serving ability to kfserver. 
Not sure do we have a protocol for the data, now I see it's all of format like
{
instances: []
}
We need clear proto to define the message if we want to do it for kfserver. @ellis-bigelow

**Comment by ellis-bigelow** [comment]
Let's discuss in one of the weeklies. This is a big upcoming topic (i.e. performance). Let's get it right. Hopefully OpenVino, Nvidia, and Tensorflow Serving can help us out here.

**Comment by andyi2it** [comment]
/close
We can specify grpc or rest port in the spec now and this can be closed.
