### ISSUE TITLE
Default nthread for xgbserver

### ISSUE THREAD

**Issue by pradithya** [kserve/kserve#584]
/kind feature
Related to #549 and #548 

**Describe the solution you'd like**
A fancier default for configuring nthread in xgbserver.
Currently it default to CPU request if user doesn't specify in XGBoostSpec

**Anything else you would like to add:**
Optimal nthread value depends from workload to workload. 
For simple case where there is only 1-row inference per request, setting nthread=1 usually achieve the best performance (https://github.com/dmlc/xgboost/issues/3042). However, for batch inference, nthread > 1 might be better.

**Comment by ellis-bigelow** [comment]
Interesting point about inference per request. Do you think it makes more sense to set it based on the # instances the server receives?

**Comment by andyi2it** [comment]
/close
This is fixed as part of #549
