### ISSUE TITLE
Enhance the logger to support predictor listening on customized port

### ISSUE THREAD

**Issue by pugangxa** [kserve/kserve#594]
/kind feature

**Describe the solution you'd like**
[A clear and concise description of what you want to happen.]
Now for logger we need call predictor service which is hard coded to be 0.0.0.0:8080. That's fine for most of the cases, but it's in fact a limitation:
- If user use custom spec and defined another container port for predictor/transformer/explainer, the call service will fail
- If later we support GRPC in another port, we need support the GRPC port in addition to the GRPC protocol.

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]
In fact we already have option of component-port, we can add an annotation of the customized port and specify it when doing injection.

**Comment by cliveseldon** [comment]
If the protocol is gRPC would we still use 8080 or should we change to another as 8080 is assumed to be REST?

**Comment by pugangxa** [comment]
> If the protocol is gRPC would we still use 8080 or should we change to another as 8080 is assumed to be REST?

Threre's no technical blocker and in fact the interface from user point of view would be all the same because knative just wrap it and no port need be sepicified to access the ksvc. But I prefer to using another port, and the kfserver.py implementation also used another port to be the default grpc port.

**Comment by andyi2it** [comment]
/close

This should be working now with changes done to handle loggers with custom port, grpc.
