### ISSUE TITLE
Create KFServing's Stable Requirements using the Kubeflow Community's process as defined  in the Application Requirement's template

### ISSUE THREAD

**Issue by jbottum** [kserve/kserve#737]
/kind feature

**Describe the solution you'd like**
[A clear and concise description of what you want to happen.]

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

**Comment by jbottum** [comment]
@ellis-bigelow @animeshsingh @cliveseldon KFServing should define its "stable" requirements per the Kubeflow Community's define process of using the Applications Requirements template.   https://github.com/kubeflow/community/blob/master/guidelines/application_requirements.md

**Comment by ahakanbaba** [comment]
Hi all. May I bring some more attention to the requirements and timing before becoming stable ? 

From enterprise user's point of view, knowing those would help significantly while making decisions about to adopt kfserving or not. 
Thanks!

**Comment by yuzisun** [comment]
> Hi all. May I bring some more attention to the requirements and timing before becoming stable ?
> 
> From enterprise user's point of view, knowing those would help significantly while making decisions about to adopt kfserving or not.
> Thanks!

@ahakanbaba good timing! Stable API is our current priority, I just send v1beta1 API PR up here https://github.com/kubeflow/kfserving/pull/991.
