### ISSUE TITLE
Error Response Logging 

### ISSUE THREAD

**Issue by orezahc** [kserve/kserve#778]
/kind feature

**Describe the solution you'd like**
[A clear and concise description of what you want to happen.]

Logger should also log error responses with `LogRequest()` instead of only STDOUT.
https://github.com/kubeflow/kfserving/blob/master/pkg/logger/server.go#L124-L142

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

**Comment by pugangxa** [comment]
In my opinion, the logger here is to provide retrospective record for the predicted result so we only need the successful result. If there's something wrong, then user should go to the program log to check what's going on(which is already recorded and can be configured by debug level for http service too). If we are going to add this, we must provide a switch and make it by default off. 
What's your opinion? @cliveseldon

**Comment by cliveseldon** [comment]
@pugangxa  Yes I think I would agree. Some use cases for the logger are to store the core request, responses and allow them to be further analyzed for outlier detection, drift detection, adversarial detection etc. If we allow error payloads then this creates a different and unexpected payloads and is a different use case I think. 
We could add error_response as a new type and it would need to be given a different cloud event type so downstream processes like above could ignore them.

**Comment by andyi2it** [comment]
/close
I think this can be safely closed as #1533 would address this.
