### ISSUE TITLE
Kfserving does not set knative default readiness probe

### ISSUE THREAD

**Issue by yuzliu** [kserve/kserve#804]
/kind bug

**What steps did you take and what happened:**

Kfserving depends on Knative serving and knative serving's validating webhook does not allow users to set port for readiness probe. According to [Knative's runtime contract](https://github.com/knative/serving/blob/master/docs/runtime-contract.md#meta-requests) , it's readiness probe MUST probe the inbound container port. Knative serving has a validating webhook to ensure that users can only set host, path, scheme, httpheaders for httpGet readiness probe or  host for tcpSocket readiness probe. See allowed fields for [httpGet](https://github.com/knative/serving/blob/release-0.13/pkg/apis/serving/fieldmask.go#L301) and [tcp](https://github.com/knative/serving/blob/release-0.13/pkg/apis/serving/fieldmask.go#L334)

I tried to add tcp readiness probe to a custom kfserving predictor.
If I set tcp readiness check with a port as below example, I get error:
> Custom container validation error: must not set the field(s): readinessProbe.tcpSocket.port: 

If I do not set the port, I get error:
> Custom container validation error: expected exactly one, got neither: readinessProbe.exec, readinessProbe.httpGet

```apiVersion: "serving.kubeflow.org/v1alpha2"
kind: "InferenceService"
metadata:
  name: readiness-probe-test
spec:
  default:
    predictor:
      minReplicas: 1
      maxReplicas: 1
      parallelism: 1
      custom:
        container:
          name: kfserving-container
          image: <my image>
          command:
          - python
          - -m
          - <my model>
          args:
          - --model_name
          - readiness-probe-test
          - --workers
          - "1"
          livenessProbe:
            httpGet:
              path: /
            timeoutSeconds: 1
            initialDelaySeconds: 5
            failureThreshold: 1
            periodSeconds: 20
          readinessProbe:
            successThreshold: 2
            initialDelaySeconds: 5
            periodSeconds: 10
            timeoutSeconds: 1
            failureThreshold: 1
            tcpSocket:
              port: 8080
          resources:
            requests:
              cpu: "1"
              memory: "1Gi"
            limits:
              cpu: "1"
              memory: "1Gi"
          env:
          - name: TIER
            value: dev
          - name: OVERRIDE_DBNAME
            value: strerout
          - name: OVERRIDE_DBTIER
            value: dev`
```

I found two workarounds for this issue:
The first is setting the port to 0:
```
tcpSocket:
  port: 0
```
The second is setting the host which also makes Kubernetes to parse the tcpSocket's port number to 0:
```         
tcpSocket:
  host: test
```
Both workarounds give the port an empty value so it can pass knative serving' validating webhook.

**What did you expect to happen:**
Kfserving should apply the Knative [default probes]( https://github.com/knative/serving/blob/6194d05b83f8a97fa4ab6d09573efe8cf3bab943/pkg/apis/serving/v1/revision_defaults.go#L109) before [validating the container]( https://github.com/kubeflow/kfserving/blob/master/pkg/apis/serving/v1alpha2/framework_custom.go#L53)

**Environment:**

- Istio Version: 1.1.7
- Knative Version: 0.13
- KFServing Version: 0.3.0
- Kubernetes version: (use `kubectl version`):1.15.5

**Comment by nlarusstone** [comment]
I'm also encountering this when trying to set this for the `liveness_probe`. If I set the port I get:
```
HTTP response body: {"kind":"Status","apiVersion":"v1","metadata":{},"status":"Failure","message":"admission webhook \"inferenceservice.kfserving-webhook-server.validator\" denied the request: Custom container validation error: must not set the field(s): livenessProbe.httpGet.port","code":400}
```
and if I don't I get:
```
     File "/Users/nlarusstone/.virtualenvs/bml/lib/python3.7/site-packages/kubernetes/client/models/v1_http_get_action.py", line 161, in port
        raise ValueError("Invalid value for `port`, must not be `None`")
    ValueError: Invalid value for `port`, must not be `None`
```

**Comment by sivanantha321** [comment]
No longer valid.
