### ISSUE TITLE
Virtual Services won't let you return HTTPS for the endpoint

### ISSUE THREAD

**Issue by nlarusstone** [kserve/kserve#815]
/kind bug

**What steps did you take and what happened:**
I've set up KFServing/Knative to use TLS, but the virtualService still returns a URL that has `http` at the front of it instead of `https`.

**What did you expect to happen:**
I expected KFServing to have an option to configuration `https` endpoints.

**Anything else you would like to add:**
Looking at https://github.com/kubeflow/kfserving/blob/master/pkg/controller/inferenceservice/resources/istio/virtualservice.go#L275 it looks like http is hardcoded:
```
    serviceURL := fmt.Sprintf("%s://%s%s", "http", serviceHostname, constants.InferenceServicePrefix(isvc.Name))
```

**Environment:**
- Knative Version: 0.14.0
- KFServing Version: 0.3.0

**Comment by yuzisun** [comment]
fixed with #2202
