### ISSUE TITLE
SKLearn example needs to document a step for installing locally the kfserving python sdk

### ISSUE THREAD

**Issue by jpatanooga** [kserve/kserve#840]
/kind bug

**What steps did you take and what happened:**

https://github.com/kubeflow/kfserving/tree/master/docs/samples/sklearn

the example talks about running SKLearnServer locally, but fails to mention that the reader needs the kfserving sdk dependency installed via (conda/pip) first.

**What did you expect to happen:**

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

**Environment:**

- Istio Version:
- Knative Version:
- KFServing Version:
- Kubeflow version:
- Kfdef:[k8s_istio/istio_dex/gcp_basic_auth/gcp_iap/aws/aws_cognito/ibm]
- Minikube version:
- Kubernetes version: (use `kubectl version`):
- OS (e.g. from `/etc/os-release`):

**Comment by jinchihe** [comment]
@jpatanooga I'm confused, the example should not need kfserving SDK, that's created by kubectl from YAML file. Would you please show details? Thanks.

**Comment by sivanantha321** [comment]
Already documented https://kserve.github.io/website/0.11/modelserving/v1beta1/sklearn/v2/#test-the-model-locally.
