### ISSUE TITLE
Multi stage model inference pipelines

### ISSUE THREAD

**Issue by Iamlovingit** [kserve/kserve#846]
/kind feature
In many situations, inferenceservice is contained many small services. If we want to deploy this big servcie by KFServing, we should create a server to connect these small services together, and use `custom` model to deploy this big service. If we want to change the connection, we should recode the server and rebuild the image. If KFServing can handle this by edit the deploy yaml, it'll save much developer time.
**Describe the solution you'd like**
[A clear and concise description of what you want to happen.]
```
                                                            +-----------------+
                                                            |   big-service   |
                                                            |                 |
                                                        +--->                 +-----+
          +---------------+        +----------------+   |   |    step 3-1/4   |     |      +-----------------+
          |  big-service  |        | big-service    |   |   |                 |     |      |    big-service  |
          |               |        |                |   |   +-----------------+     |      |                 |
          |               +------->+                +---+                           +----->+                 |
          |   step 1/4    |        |    step 2/4    |   |   +-----------------+     |      |                 |
          |               |        |                |   |   |   big-service   |     |      |    step 4/4     |
          +---------------+        +----------------+   |   |                 |     |      |                 |
                                                        +--->                 +-----+      +-----------------+
                                                            |   step 3-2/4    |
                                                            |                 |
                                                            +-----------------+
```
**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

**Comment by Iamlovingit** [comment]
It looks like inference service mesh.

**Comment by yuzisun** [comment]
@Iamlovingit what are those services ? Can you give a more concrete example?

**Comment by Iamlovingit** [comment]
Some pattern recognition methods is splited some steps. For example, the face recognition:
 1.  find the face area 
 2.  compute the features of these face
 3.  match the result from face database
Usually, **1,2**  are two different models. **1** output is **2** input.

**Comment by cliveseldon** [comment]
Having a full inference graph as a component of KFServing is part of the roadmap but the work has not yet been started.

**Comment by Iamlovingit** [comment]
> Having a full inference graph as a component of KFServing is part of the roadmap but the work has not yet been started.

Could you show me the roadmap?

**Comment by cliveseldon** [comment]
https://github.com/kubeflow/kfserving/blob/master/ROADMAP.md#unscheduled-work
Which has a link to https://github.com/SeldonIO/mlgraph an early proposal for full DAG.

**Comment by Iamlovingit** [comment]
> https://github.com/kubeflow/kfserving/blob/master/ROADMAP.md#unscheduled-work
> Which has a link to https://github.com/SeldonIO/mlgraph an early proposal for full DAG.

Thanks for roadmap. Is there have any design about this feature or some feasible idea? Hope for your reply.

**Comment by cliveseldon** [comment]
We want to kickoff items including AB testing, ensembles, and multi-armed bandits leading up to a dull DAG in coming weeks. Can I suggest you attend the community WG call (weds - biweekly) see https://www.kubeflow.org/docs/about/community/ and add an agenda item.

**Comment by gabrielecastellano** [comment]
Is there any alternative that can be used on top of kfserving for implementing this behavior at the moment? I would just need a chain of models, instead of an arbitrarily complex graph.

**Comment by yuzisun** [comment]
@gabrielecastellano For now you could create an inference service for each model and then write a python client to chain the HTTP calls. 

```
        score = await call_model_one(data=data)
        if score > 0.5:
            result = await call_model_two(data=data)
            result = {"model_used": 2, "score": score}
        else:
            result = {"model_used": 1, "score": score}
```

**Comment by gabrielecastellano** [comment]
Hi @yuzisun, thanks for your reply.
unfortunately, this solution would make the intermediate data go back to the client at every step, introducing unnecessary network latency.

**Comment by yuzisun** [comment]
> Hi @yuzisun, thanks for your reply.
> unfortunately, this solution would make the intermediate data go back to the client at every step, introducing unnecessary network latency.

If you are looking all doing this on server side, you can take a look at triton's [ensemble](https://github.com/triton-inference-server/server/blob/master/docs/architecture.md#ensemble-models) solution if your models can fit on a single node.

**Comment by yuzisun** [comment]
> > https://github.com/kubeflow/kfserving/blob/master/ROADMAP.md#unscheduled-work
> > Which has a link to https://github.com/SeldonIO/mlgraph an early proposal for full DAG.
> 
> I'm curious if anyone has looked at leveraging https://serverlessworkflow.io/ for pipelines/dags via an extension?

@seancarroll We have looked into this, this is definitely relevant but I think we want a more ML inference specific yaml schema. I have open a [draft PR](https://github.com/kubeflow/kfserving/pull/1728), feel free to comment on it.

**Comment by Nagarajj** [comment]
@yuzisun @cliveseldon what is the plan for Inference Graph, it is on roadmap but don't see anything concrete. Would be good to get some clarity. Thanks.
