### ISSUE TITLE
Authentication setup interfering with kfserving

### ISSUE THREAD

**Issue by abdulsalama** [kserve/kserve#848]
/kind bug

How authentication is supposed to interact with kfserving?

I followed this article to setup istio/dex authentication here:
https://journal.arrikto.com/kubeflow-authentication-with-istio-dex-5eafdfac4782

And it has been working great. However, we are trying to get kfserving to work and now the envoy filter below is interfering with it.

apiVersion: networking.istio.io/v1alpha3
kind: EnvoyFilter
metadata:
  name: authn-filter
spec:
  workloadLabels:
    istio: ingressgateway
  filters:
  - filterConfig:
      httpService:
        serverUri:
          uri: http://authservice.istio-system.svc.cluster.local
          cluster: outbound|8080||authservice.istio-system.svc.cluster.local
        authorizationRequest: 
          allowedHeaders:
            patterns:
            - exact: "cookie"
    filterName: envoy.ext_authz
    filterType: HTTP
    listenerMatch:
      portNumber: 443
      listenerType: GATEWAY

We are trying to simply make serving api calls pass this filter all together, so I'm trying to see how I can scope down when this filter applies.

For example the call below (making a backend prediction api call) shouldn't go through this filter:
curl -v -H "Host: sklearn-iris.foo.example.com" http://localhost:8080/v1/models/sklearn-iris:predict -d @https://raw.githubusercontent.com/kubeflow/kfserving/master/docs/samples/sklearn/iris-input.json

Ideally we want a mechanism to say if the host header is "sklearn-iris.foo.example.com", then pass the authentication filter...

Looks to me kfserving is using the same kubeflow-gateway and thus the filter will apply no matter what, which seems wrong.

So just in general, how is this kfserving configuration supposed to be compatible with the recommended UI authentication setup/filter indicated above?

**Comment by yuzisun** [comment]
@yanniszark  @krishnadurai Any thoughts on this?

**Comment by josete89** [comment]
@yuzisun any update on this one? I'm falling in the same error!

**Comment by nallagangus** [comment]
Is there an  update or recommendation on this? I was wondering if there are sample envoyfilter that overrides authentication for kfserving - sudhir

**Comment by marcinkosztolowicz** [comment]
Hi, is there any update on this one?

**Comment by nallagangus** [comment]
What I found as a workaround or probably the right way is -
Have separate ingress-gateways and loadbalancer/IP addresses with each own entry point. One for main kubeflow pipelines /training and another ingress-gateway for kfserving with no authentication. So we do not have to be constrained using the same envoyfilter for both. 

That is what I did and made it work

Sudhir

**Comment by jai** [comment]
> What I found as a workaround or probably the right way is -
> Have separate ingress-gateways and loadbalancer/IP addresses with each own entry point. One for main kubeflow pipelines /training and another ingress-gateway for kfserving with no authentication. So we do not have to be constrained using the same envoyfilter for both.
> 
> That is what I did and made it work
> 
> Sudhir

@nallagangus can you share how you configured the separate ingress?

**Comment by Rstar1998** [comment]
Any update on this ?
