### ISSUE TITLE
Adding user profiles from UI

### ISSUE THREAD

**Issue by Hmr-ramzi** [kserve/kserve#910]
/kind feature

**Describe the solution you'd like**
Adding user profiles from the UI (maybe for the admin users only!)

**Anything else you would like to add:**
Also, be able to upload secrets to be attached to the default-editor service account in order to pull images from private registries

**Comment by yuzisun** [comment]
@Hmr-ramzi Can you elaborate what is this for?

**Comment by Hmr-ramzi** [comment]
Hi @yuzisun Thank you for your reply. I think i should have submitted this feature request in another repo as it is not related much to the kfserving component. But the problem i am facing is the following. Each time i want to create a new profile, i have to apply post usage steps (After the user login for the first time and decide the namespace name) then i have to add image pull secrets to the name space and also patch it to the default editor sa. I was thinking if this could be possible within the ui of kubeflow (central dashboard)

**Comment by yuzisun** [comment]
> Hi @yuzisun Thank you for your reply. I think i should have submitted this feature request in another repo as it is not related much to the kfserving component. But the problem i am facing is the following. Each time i want to create a new profile, i have to apply post usage steps (After the user login for the first time and decide the namespace name) then i have to add image pull secrets to the name space and also patch it to the default editor sa. I was thinking if this could be possible within the ui of kubeflow (central dashboard)

Got it, I think kubeflow or kubeflow/manifests repo might be the better place to raise this.
