### ISSUE TITLE
azure-storage-blob package update to 12.x

### ISSUE THREAD

**Issue by nyejon** [kserve/kserve#923]
/kind feature

**Update to the current azure blob service to 12.x**
Update the current package from the legacy 2.1 version to the current 12.x series.

Hi, what would need to be done to do the upgrade? Is it only the files in the python kfserving package?

**Comment by yuzisun** [comment]
@nyejon I think all we need to upgrade is here https://github.com/kubeflow/kfserving/blob/87b45e037ca279a7791e0b2a7da6d38898385a2b/python/kfserving/requirements.txt#L14, would you like to give a try and test out ?

**Comment by maganaluis** [comment]
We are using a custom SDK which requires Azure Storage Blob ```12.1.0``` within a custom Transformer. I don't see a workaround this. Is there a reason why not to upgrade it? Otherwise we can create a PR?

**Comment by yuzisun** [comment]
@maganaluis yes please!

**Comment by maganaluis** [comment]
@yuzisun I was waiting for approval from my org, I initiated PR https://github.com/pwc-labs/kfserving/tree/azure-blob-upgrade
