### ISSUE TITLE
imagePullSecret for custom inferenceservice-config predictor

### ISSUE THREAD

**Issue by aka-toxa** [kserve/kserve#965]
/kind feature

**Describe the solution you'd like**
[A clear and concise description of what you want to happen.]

Hi there is this config map [/config/overlays/test/configmap/inferenceservice.yaml](https://github.com/kubeflow/kfserving/blob/6a678c29a7b70e44ab057e204e8d5c53a256aacd/config/overlays/test/configmap/inferenceservice.yaml)

our company using their own custom predictors and we have our own custom kfserving predictors images that we need to put here. All our registries are private so we need to have a way to provide imagePullSecret for the custom image we have

I think it would be neatly enough if we just could put imagePullSecret reference just after image field

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

**Comment by yuzisun** [comment]
@aka-toxa image pull secret is supported on KFServing v1beta1 API as we expose pod spec for predictor,  so you can directly specify on the inference service yaml, stay tuned we are actively working on it towards 0.5 release.

**Comment by aka-toxa** [comment]
is there any bit of documentation or code that i can check to understand what exactly i should do to apply service yaml? 

or I understood you incorrect and you say that this will be at the next releases?

**Comment by yuzisun** [comment]
> is there any bit of documentation or code that i can check to understand what exactly i should do to apply service yaml?
> 
> or I understood you incorrect and you say that this will be at the next releases?

@aka-toxa yes v1beta1 API will be in next release :)
